### ISSUE TITLE
大批量图片数据管理

### ISSUE THREAD

**Issue by qianlinjun** [vearch/vearch#100]
感谢作者的工作。
想问一下在vearch这个框架下面，如何对大批量图片数据进行管理，看到plugin\images\image_retrieval路径下面的download_image.sh脚本是直接下载解压，如果数据量很大，可能需要储存在多台机器上，这时候应该怎么管理数据？vearch里面好像没看到相关的接口

**Comment by ljeagle** [comment]
大规模图片存储属于非结构化文件存储了。vearch只是可以提供端到端一键式图片检索及向量检索的解决方案。大规模图片存储有一些开源分布式文件系统可以用来存储图片和管理，比如ceph，chubaofs等等。

**Comment by qianlinjun** [comment]
好的。
还有个疑问，plugin里提供的vgg以及resnet提取的都是全局特征，即一张图片只有一个n维特征向量，如果使用图片的局部特征，即一张图片可能有若干个n维特征向量，vearch还支持吗？
另外，faiss里面会把所有的特征向量生成一个index文件，vearch也是这样吗？如果是这样的话是把index文件放到不同ps上去了？
