### ISSUE TITLE
编译gamma报错，找不到faiss

### ISSUE THREAD

**Issue by TTian-vivo** [vearch/vearch#101]
使用conda安装faiss，安装地址为/home/app/anaconda/lib/python3.7/site-packages/faiss，然后设置FAISS_HOME=“/home/app/anaconda/lib/python3.7/site-packages/faiss”，
使用 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/app/vearch/ps/engine/gammacb/lib ..   编译gamma，
报错：cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/app/vearch/ps/engine/gammacb/lib ..
-- Could not find Faiss include. Turning Faiss_FOUND off
-- Could not find Faiss lib. Turning Faiss_FOUND off
CMake Error at cmake/Modules/FindFaiss.cmake:45 (MESSAGE):
  Could not find Faiss, please install faiss or set $FAISS_HOME
Call Stack (most recent call first):
  CMakeLists.txt:9 (FIND_PACKAGE)
请问faiss是要用源码安装才有效吗？

**Comment by wxingda** [comment]
先执行`export FAISS_HOME=/home/app/anaconda/lib/python3.7/site-packages/faiss`

**Comment by TTian-vivo** [comment]
是的，已经执行了export FAISS_HOME=/home/app/anaconda/lib/python3.7/site-packages/faiss，不知道为什么在我的情况下，还是提示找不到，后来就改为了源码安装，
export FAISS_HOME=/home/app/faiss 就成功了！
