### ISSUE TITLE
go build -o vearch报错：ps/engine/gammacb/reader.go:34:2: cannot find package "github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api"

### ISSUE THREAD

**Issue by TTian-vivo** [vearch/vearch#102]
我在执行go build -o vearch的时候，报错：
ps/engine/gammacb/reader.go:34:2: cannot find package "github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api" in any of:
	/home/app/go/src/github.com/vearch/vearch/vendor/github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api (vendor tree)
	/usr/local/go/src/github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api (from $GOROOT)

具体环境：
设置export GOROOT="/usr/local/go"
export GOBIN="$GOROOT/bin"
export PATH="$PATH:$GOBIN"
export GOPATH="/home/app/go"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$vearch/ps/engine/gammacb/lib/lib
export FAISS_HOME=/home/app/faiss

并且gamma编译成功

**Comment by ansjsun** [comment]
/home/app/go/src/github.com/vearch/vearch/



把程序 vearch 里面所有的文件copy到这个目录下。 




在2020年02月15日 18:40，TTian-vivo 写道：

我在执行go build -o vearch的时候，报错：
ps/engine/gammacb/reader.go:34:2: cannot find package "github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api" in any of:
/home/app/go/src/github.com/vearch/vearch/vendor/github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api (vendor tree)
/usr/local/go/src/github.com/vearch/vearch/engine/gamma/idl/fbs-gen/go/gamma_api (from $GOROOT)

具体环境：
设置export GOROOT="/usr/local/go"
export GOBIN="$GOROOT/bin"
export PATH="$PATH:$GOBIN"
export GOPATH="/home/app/go"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$vearch/ps/engine/gammacb/lib/lib
export FAISS_HOME=/home/app/faiss

并且gamma编译成功

**Comment by TTian-vivo** [comment]
您好，非常抱歉没有搞懂，vearch的文件本来就在这个/home/app/go/src/github.com/vearch/vearch/目录下的呀？

**Comment by TTian-vivo** [comment]
![image](https://user-images.githubusercontent.com/51990690/74631349-b366ed00-5197-11ea-9e0a-ee91c3ce61de.png)

**Comment by ansjsun** [comment]
有个 build.sh 试试。




在2020年02月17日 15:11，TTian-vivo 写道：

**Comment by TTian-vivo** [comment]
使用sh build.sh执行到这边的时候，还是出现了相同的错误
![image](https://user-images.githubusercontent.com/51990690/74717888-22157a80-526c-11ea-9aaa-7b144a214f7e.png)

**Comment by ansjsun** [comment]
1.确定源码 完整最好先pull下
2. 确定源码再 /home/app/go/src/github.com/vearch/vearch

同时你的gopath 是   /home/app/go  , 通过echo $GOPATH 获取到的.

**Comment by TTian-vivo** [comment]
感谢回复，该问题已经解决，之前的错误是在公司电脑环境下，升级了gcc版本所致。在还原机器的gcc版本后，之前的错误不存在了。
