### ISSUE TITLE
支持 一张图片多个n维特征 增删改查吗？

### ISSUE THREAD

**Issue by qianlinjun** [vearch/vearch#103]
我看到plugin里提供的vgg以及resnet提取的都是全局特征，即一张图片只有一个n维特征向量，如果使用图片的局部特征，即一张图片可能有若干个n维特征向量，vearch还支持吗？
另外，faiss里面会把所有的特征向量生成一个index文件，vearch也是这样吗？如果是这样的话是把index文件放到不同ps上去了？

**Comment by ljeagle** [comment]
1、vearch支持一个document存储多个向量，并在多个向量中做联合检索。
2、vearch是类似es的，用户不需要关注index文件，数据按API格式插入存储检索引擎中后即可直接查询，并能持续将数据，索引持久化。

**Comment by qianlinjun** [comment]
谢谢！
