### ISSUE TITLE
docker example query score not between 0-1

### ISSUE THREAD

**Issue by cocodee** [vearch/vearch#104]
Use the docker example and query,but the result _score field is not between 0-1

> '  http://127.0.0.1:9001/test_vector_db/dk_space/_search
{"took":16,"timed_out":false,"_shards":{"total":1,"failed":0,"successful":1},"hits":{"total":1,"max_score":35.57204055786133,"hits":[{"_index":"test_vector_db","_type":"dk_space","_id":"1","_score":35.57204055786133,"_extra":{"vector_result":[{"field":"vector","source":"14AW1mK_j19FyJvn5NR4Ep","score":35.572040557861328}]},"_version":0,"_source":{"float":3.7416573867739413,"float_tags":-0.45059848,"int":14,"int_tags":15,"string":"14AW1mK_j19FyJvn5NR4Ep","string_tags":["14","10","15"],"vector":{"feature":[0.1273058,0.14176957,0.09854962,-0.016467767,-0.06470184,0.07697855,0.13272406,0.020516276,0.13473997,0.025109291,0.05585007,0.13164522,0.094729684,0.0759687,0.078858286,-0.035476357,0.040982492,0.12597392,-0.027098512,0.040228426,0.021289311,0.10363742,0.095288254,0.12057113,0.041661736,-0.10486522,0.045641936,0.10928743,0.055150945,0.0006760127,0.039769117,0.08715404,0.074879,0.049445946,0.08135012,0.13894968,0.1352023,-0.13641186,-0.106850386,0.046629444,0.035061963,0.059076097,-0.022484459,0.13738745,0.13131227,0.11545417,0.10583011,0.058933355,-0.01825732,0.105464056,0.13711017,0.09696539,0.11356345,0.039980292,0.10905001,0.13876207,0.030662585,0.021061495,0.07569206,0.05715398,0.018757932,-0.037392873,0.030408913,0.0127675,0.101090245,0.13188165,0.04771765,0.01565357,0.10414231,0.12337897,0.09870874,0.1319348,0.06414346,0.09382706,0.09740277,0.057858966,0.110031694,0.1038056,0.035999946,0.12483695,0.015069707,0.08195667,0.12828799,0.12782839,0.009486352,0.066573665,0.12688972,0.1208528,0.061980054,-0.008543415,0.036007512,0.13155061,0.030737014,0.010686528,0.12059156,-0.0744157,0.064294234,0.07858972,0.056289047,0.04307529,0.031884197,0.12996691,0.10397864,0.12993847,0.07021576,0.01714761,0.06483403,0.13376908,0.025699263,0.10908673,0.036605444,0.13785964,0.036885638,0.0850846,0.04407154,0.13170001,0.06746153,0.02090268,0.12779723,0.12138812,0.080531076,0.09921498,0.11158334,0.09557812,0.08673281,0.11190124,0.08492593,0.017957624],"source":"14AW1mK_j19FyJvn5NR4Ep"}}}]}}MacBook-Pro-2:cloud kdi$

**Comment by qiutianme** [comment]
@cocodee  The value of cache_size is too big，which meanings 500000000M bytes，maybe you want set it to be 500

**Comment by cocodee** [comment]
I've changed the topic.Could you please see to the new issue?
