### ISSUE TITLE
raft occupies too much storage

### ISSUE THREAD

**Issue by cocodee** [vearch/vearch#106]
I tried to insert 4,000,000 items to vearch. Each item contains a vector value with 512 dimension.
The go structure looks like below.
map[string]interface{}{
				"string":      id,
				"int":         15,
				"float":       3.7416573867739413,
				"string_tags": []string{"14", "10", "15"},
				"int_tags":    []int64{14, 10, 15},
				"float_tags":  []float64{0.88658684, 0.9873159, 0.68632215, -0.114685304, -0.45059848},
				"vector": map[string]interface{}{
					"feature": features[i],
				},
			}
After 4000000 items are inserted. I've found that the data folder took too much storage. Specifically, the raft sub folder took about 33G disk space.How could I reduce the disk storage taken by raft?
 33G	./datas1/raft/1
 33G	./datas1/raft
9.3G	./datas1/data/1
9.3G	./datas1/data
 42G	./datas1
 42G	.

**Comment by ansjsun** [comment]
the raft 10 million logs are saved by default. you can set   `raft_truncate_count` to store .  it start job 
 for truncate every 5 minute 
![image](https://user-images.githubusercontent.com/1221947/74932843-b541e200-541d-11ea-8307-c2fdcb74e16d.png)
