### ISSUE TITLE
What happens when new ps server is added or removed after cluster deployment?

### ISSUE THREAD

**Issue by cocodee** [vearch/vearch#108]
It seems that there is few document about the working theory of ps server and partition. Could you please comment on this?

**Comment by ljeagle** [comment]
Thanks for your advice!  We will write some technical documents describing about Master, PartitionServer, Router and Gamma Engine in the Wiki of this project as soon as possible.

**Comment by ljeagle** [comment]
New PartitionServer can be automatically added into the cluster through API, since Master is similar to Zookeeper which can be used for service discovery.
