### ISSUE TITLE
使用term Filter比不使用term Filter要慢很多，这是为什么？

### ISSUE THREAD

**Issue by dingjun606** [vearch/vearch#111]
有两个使用方面的问题需咨询下：
180w条数据，1024维度，内存配置是默认的。使用term Filter （200个值，or），加上向量检索top20，单路平均耗时在260ms。不使用term Filter时单路平均耗时50ms，但是我需要的场景就是需要加Filter的，请问有优化空间吗？
另外，term Filter中使用_id时会报错，是不支持在termFilter中使用_id吗？

**Comment by dingjun606** [comment]
附上我的建表语句：
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "candidate_ht",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 10000000,
        "nprobe": 10,
        "metric_type": "InnerProduct",
        "ncentroids": 256,
        "nsubvector": 32
    },
    "properties": {
        "user_id": {
            "type": "keyword",
            "index": true
        },
        "grade": {
            "type": "keyword",
            "index": true
        },
        "YYMM": {
          "type": "keyword",
            "index": true
        },
        "ht":{
            "type": "vector",
            "dimension": 1024
        }
    }
}
' http://172.31.100.143:8817/space/candidate_user_ht_0205/_create

**Comment by wxingda** [comment]
1. term Filter目前采用顺序过滤，也就是200个依次过滤，这里可以优化成并行的，后续我们会改进
2. _id是内置字段，无法使用term Filter
