### ISSUE TITLE
插入操作会阻塞查询吗？

### ISSUE THREAD

**Issue by zzypeak** [vearch/vearch#112]
我的在3台机器上部署了vearch，每台都是启动all module[master, ps, router]。space的配置参数为
{
    "name":  doc01,
    "partition_num": 3,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 400000,
        "max_size": 8000000,
        "nprobe": 8,
        "metric_type": "InnerProduct",
        "ncentroids": 2828,
        "nsubvector": 32
    },
    "properties": {
        "enddate": {
            "type": "keyword", "index": True
        },
        "feature": {
            "type": "vector",
            "dimension": 200,
            "store_type": "Mmap"
        }
    }
}
，新来一条记录，我会调用search接口判断是否有相似的，如果没有再调用insert接口把新纪录插入到vearch中，插入调用比较多。我看日志查询时间变化比较大，看代码插入时候有加锁，加锁会影响search吗？
![image](https://user-images.githubusercontent.com/6071020/75434645-dc079780-598c-11ea-8486-453b33a37f7c.png)
如图，通常搜索在几毫秒完成，但有时会到100多毫秒。

**Comment by zzypeak** [comment]
经试验，调用_forcemerge接口进行index后查询时间稳定了。

**Comment by ljeagle** [comment]
@zzypeak vearch的gamma引擎实时索引为高效无锁实现，插入不会阻塞查询的。io特别大或者索引和数据的增量频繁dump可能会影响到查询，您说的情况，我们正准备复现中。

**Comment by qiutianme** [comment]
> 经试验，调用_forcemerge接口进行index后查询时间稳定了。

@zzypeak 跟你确认下，你发现search耗时变化比较大的时候，是不是某些parttion上的doc数据还没到index size：400000，导致没建索引，然后调用_forcemerge强制建索引后就好了

**Comment by zzypeak** [comment]
@qiutianme 我打印了下日志，是没建索引，调用的是GammaIVFPQIndex::SearchDirectly()，下面是我加的部分日志:
INFO 2020-03-14 15:56:56,909 raw_vector.cc:336 flusher waiting......, expected num=1540, flushed num=1539
search-directly: 100.95 ms
vec_manager search: 101.077 ms
I0314 15:56:57.010864    8498 doc_http.go:707] [INFO] search use time :[102] . max partition:[27] use time:[101]
search-directly: 2.51294 ms
vec_manager search: 2.64502 ms
I0314 15:56:57.135830    8498 doc_http.go:707] [INFO] search use time :[103] . max partition:[28] use time:[101]
search-directly: 0.906006 ms
vec_manager search: 1.00903 ms
I0314 15:56:57.353878    8498 doc_http.go:707] [INFO] search use time :[102] . max partition:[26] use time:[101]
search-directly: 0.85498 ms
vec_manager search: 0.976807 ms

**Comment by zzypeak** [comment]
目前定位到是GammaIVFPQIndex::SearchDirectly()搜索时间不稳定

**Comment by zzypeak** [comment]
@ljeagle 找到原因了，在GammaIVFPQIndex::SearchDirectly()中，
715行 raw_vec_->GetVectorHeader(0, 0 + num_vectors, scope_vec) 里面不是memory_only_时flusher完sleep100ms。备注，我用的Mmap。
