### ISSUE TITLE
java api

### ISSUE THREAD

**Issue by zyjlx123456** [vearch/vearch#113]
vearch目前有java api的支持吗？用于解析和封装restful的request和response的转换

**Comment by ljeagle** [comment]
http返回协议是restful的，任何语言都可以解析。
对于高性能场景的grpc接口后续会提供java api，感兴趣请关注，谢谢！

**Comment by xuechongliu** [comment]
@ljeagle 请问grpc接口的定义在哪里，找了一下没有找到。

**Comment by xuechongliu** [comment]
> 定义在哪里，找了一下没有

只看到Search的接口，没有找到database, space, document等接口

**Comment by git4wht** [comment]
提供的proto是syntax = "proto3";
运行时显示 “io.grpc.StatusRuntimeException: INTERNAL: http2 exception”
server端提供的协议是Http2的吗？
