### ISSUE TITLE
Binary Index

### ISSUE THREAD

**Issue by Dr1rD** [vearch/vearch#114]
Hello,
我看了你们实现实时IVFPQ索引的代码，你们是自己实现了InvertIndex、vector buffer、mapper
我想请问，这一套也适用BinaryIndex吧？（除了float->uint8_t以及不需要PQ编码）

**Comment by ljeagle** [comment]
是的，同样也适用BinaryIndex，不用PQ相对更简单些。这两天我们会开源支持BinaryIndex相关的代码。

**Comment by Dr1rD** [comment]
好的，关注ing
