### ISSUE TITLE
数据设置过期时间

### ISSUE THREAD

**Issue by TTian-vivo** [vearch/vearch#116]
在插入数据的时候，发现插入数据比较慢。3G左右的数据，一条条插入完毕可能需要60min。这种情况在全量构建索引的时候时间有点过长。是否可以给插入的数据设置过期时间呢？

**Comment by ansjsun** [comment]
用多线程插入啊




在2020年03月05日 17:38，TTian-vivo 写道：

在插入数据的时候，发现插入数据比较慢。3G左右的数据，一条条插入完毕可能需要60min。这种情况在全量构建索引的时候时间有点过长。是否可以给插入的数据设置国企时间呢？

**Comment by TTian-vivo** [comment]
是的，多线程插入会快很多，然后关闭该issue
