### ISSUE TITLE
vearch通过vector查询score的计算

### ISSUE THREAD

**Issue by zyjlx123456** [vearch/vearch#118]
请问vearch通过vector查询score的计算逻辑是什么样子的，我插入二维数据[0.1,0.1],[0.2,0.2],[0.3,0.3] 通过[0.2,0.2]查询，发现返回的三个数据的score分数是一样的，这个是因为？

**Comment by qiutianme** [comment]
@zyjlx123456 发一下你返回的结果和你创建space的json语句吧

**Comment by qiutianme** [comment]
@zyjlx123456  我们用你说的数据验证了一下，搜索结果分数都是正确，其中test1=[0.1,0.1]，test2=[0.2,0.2]，test3=[0.3,0.3]，用[0.2,0.2]进行搜索的，你可以进一步确认下

```JSON
{
    "took": 4,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "failed": 0,
        "successful": 1
    },
    "hits": {
        "total": 3,
        "max_score": 0.12000000476837158,
        "hits": [
            {
                "_index": "vector_db",
                "_type": "vector_space",
                "_id": "test3",
                "_score": 0.12000000476837158,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "feature",
                            "source": "",
                            "score": 0.12000000476837158
                        }
                    ]
                },
                "_version": 1,
                "_source": {}
            },
            {
                "_index": "vector_db",
                "_type": "vector_space",
                "_id": "test2",
                "_score": 0.08000000566244125,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "feature",
                            "source": "",
                            "score": 0.08000000566244125
                        }
                    ]
                },
                "_version": 1,
                "_source": {}
            },
            {
                "_index": "vector_db",
                "_type": "vector_space",
                "_id": "test1",
                "_score": 0.04000000283122063,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "feature",
                            "source": "",
                            "score": 0.04000000283122063
                        }
                    ]
                },
                "_version": 1,
                "_source": {}
            }
        ]
    }
}
```

**Comment by zyjlx123456** [comment]
@qiutianme 不好意思，这两天在忙其他的事情，刚刚看到回复
space为：
`[
  {
    "db_id": "36",
    "engine": {
      "index_size": 100000,
      "max_size": 100000,
      "metric_type": "L2",
      "name": "gamma",
      "ncentroids": -1,
      "nprobe": -1,
      "nsubvector": -1
    },
    "id": 16,
    "name": "doc",
    "partition_num": 1,
    "properties": {
      "vector": {
        "type": "vector",
        "dimension": "2"
      },
      "integer": {
        "index": "true",
        "type": "integer"
      },
      "keyword": {
        "array": "true",
        "index": "true",
        "type": "keyword"
      }
    },
    "replica_num": 1,
    "vearchFieldType": {
      "vector": {
        "dimension": 2,
        "type": "vector"
      },
      "integer": {
        "index": "true",
        "type": "integer"
      },
      "keyword": {
        "array": true,
        "index": "true",
        "type": "keyword"
      }
    },
    "version": 2
  }
]`
查询的语句：
`{"direct_search_type":0,"query":{"sum":[{"feature":[0.2,0.2],"field":"vector"}]},"quick":false,"size":10,"vector_value":false}
`
结果为：其中，1对应的是[0.1,0.1],2对应的[0.2,0.2],3对应的是[0.3,0.3]
`{
  "hits": {
    "hits": [
      {
        "extra": {
          "vector_result": [
            {
              "score": 0.080000005662441254,
              "field": "vector",
              "source": ""
            }
          ]
        },
        "id": "2",
        "index": "zyj",
        "score": 0.08000000566244125,
        "source": {
          "integer": 2,
          "keyword": [
            "2"
          ]
        },
        "type": "doc",
        "version": 1
      },
      {
        "extra": {
          "vector_result": [
            {
              "score": 0.080000005662441254,
              "field": "vector",
              "source": ""
            }
          ]
        },
        "id": "3",
        "index": "zyj",
        "score": 0.08000000566244125,
        "source": {
          "integer": 3,
          "keyword": [
            "3"
          ]
        },
        "type": "doc",
        "version": 1
      },
      {
        "extra": {
          "vector_result": [
            {
              "score": 0.2800000011920929,
              "field": "vector",
              "source": ""
            }
          ]
        },
        "id": "1",
        "index": "zyj",
        "score": 0.2800000011920929,
        "source": {
          "integer": 1,
          "keyword": [
            "1"
          ]
        },
        "type": "doc",
        "version": 1
      }
    ],
    "max_score": 0.2800000011920929,
    "total": 3
  },
  "shards": {
    "failed": 0,
    "successful": 1,
    "total": 1
  },
  "timed_out": false,
  "took": 1
}`

**Comment by zyjlx123456** [comment]
@qiutianme 帮忙看一下
