### ISSUE TITLE
how to extract valid feature vector data from pictures?

### ISSUE THREAD

**Issue by yzy888** [vearch/vearch#119]
Hello,I want to know how to recognize face basing on vearch. If I want to recognize face with vearch, should I refer to APIVisualSearch.md or APILowLevel.md?
I have tried it with ten groups of random pictures as APIVisualSearch.md said, but the accuracy rate result is not high.
When I did it as APILowLevel.md said, I created db and created space with a field of vector type, then I donot know how to extract feature vector from my pictures to help to recognize face. Is there vearch API that can help to convert a picture to valid feature vector data to help to recognize face?
Is there anyone who can help me?

**Comment by gDreamcatcher** [comment]
Hello, if you want to recognize face with vearch, you can execute this command `python main.py --model_name=face_retrieval` at this path `vearch/plugin/src/`  .  I hope this can help you.

**Comment by yzy888** [comment]
Thank you very much. I will have a try.

**Comment by yzy888** [comment]
@gDreamcatcher I have done it as you said and I really have got a better result. Thanks again.

**Comment by gDreamcatcher** [comment]
You're welcome!
