### ISSUE TITLE
启动图[片插件后，为什么不能通过4101访问。不返回任何结果

### ISSUE THREAD

**Issue by lxx1220** [vearch/vearch#120]
curl -XPOST -H "content-type:application/json" -d '{
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' http://127.0.0.1:4101/testDb/testSpace/_create

**Comment by ansjsun** [comment]
用router的端口 看你配置文件 你这个是master端口




在2020年03月08日 12:11，lxx1220 写道：

curl -XPOST -H "content-type:application/json" -d '{
"db": true,
"method": 0,
"columns": {
"imageurl": {
"type": "keyword"
},
"boundingbox": {
"type": "keyword"
},
"label": {
"type": "keyword"
}
},
"feature": {
"type": "vector",
"filed": "imageurl",
"model_id": "vgg16",
"dimension": 512
}
}' http://127.0.0.1:4101/testDb/testSpace/_create

**Comment by gDreamcatcher** [comment]
@lxx1220  你好，我有两个问题需要确认一下：

1. 你的代码是否是最新的，如果不是请在github上拉取最新的代码
2. 请问你vearch后台服务是否已经部署，如果没有部署请参考[Quickstart.md](https://github.com/vearch/vearch/blob/master/docs/Quickstart.md)，

**Comment by lxx1220** [comment]
是最新版的。
为什么创建库表之后
 curl -XPOST -H "content-type:application/json" -d '{
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' http://127.0.0.1:9001/test/test/_create
显示的是：
{"_index":"test","_type":"test","_id":"_create","status":550,"error":{"index":"","index_uuid":"","shard":"0","type":"","reason":"db:[test] space:[test] err:[space not exists]"}} @ansjsun

**Comment by gDreamcatcher** [comment]
@lxx1220 使用新版的代码建表语句应该是下面的的格式：
# create a db which name test
curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' http://127.0.0.1:4101/db/_create

# create a space in test db which name test too.
curl -XPUT -H "content-type: application/json" -d' { "name": "test", "dynamic_schema": "strict", "partition_num": 2, "replica_num": 1, "engine": {"name":"gamma","metric_type": "InnerProduct"}, "properties": { "url": { "type": "keyword", "index":"true"}, "feature1": { "type": "vector", "dimension":512, "format": "normalization" }}} ' http://127.0.0.1:4101/space/test/_create

**Comment by lxx1220** [comment]
在没启动图片插件之前，表库都可以正常建。
启动图像插件后，就这样：
 curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' http://127.0.0.1:9001/db/_create
{"error":"Incorrect HTTP method for uri [/db/_create] and method [PUT], allowed: [POST]","status":405}
路由端口 就是127.0.0.1:9001。

**Comment by gDreamcatcher** [comment]
9001默认的是router的端口号 你创建库和表的时候应该使用master的端口号，默认的是8817，如果你没有修改这些默认的端口号 可以试试把上面的语句改成
 `curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' http://127.0.0.1:8817/db/_create`

**Comment by lxx1220** [comment]
谢谢您，但是我还有疑问。
能正常创建库testDb。
在创建表的时候：
curl -XPUT -H "content-type: application/jsoame": "testSpace", "dynamic_schema": "strict", "partition_num": 2, "replica_num": 1, "engine": {"name":"gamma","metric_type": "InnerProduct"}, "properties": { "url": { "type": "keyword", "index":"true"}, "feature1": { "type": "vector", "dimension":512, "format": "normalization" }}} ' http://127.0.0.1:8817/space/testDb/_create
又遇到了这个问题
{"code":550,"msg":"json: cannot unmarshal string into Go struct field .index of type bool"}

**Comment by gDreamcatcher** [comment]
这个应该是我们文档没有及时更新造成的， 你可以把建表语句中的“true”换成true试一下。如果还有什么问题的话可以参考最新的操作文档[vearch中文文档](https://vearch.readthedocs.io/zh_CN/latest/use_op/op_space.html#id2)

**Comment by lxx1220** [comment]
您好，我按文档里最新的和按您说的替换了后，出现的问题{"code":550,"msg":"create partition err: create gamma table has err:[4294967294]

**Comment by ansjsun** [comment]
你可以清空数据。data 和 log 还有master 的数据 再试试




在2020年03月08日 16:47，lxx1220 写道：

您好，我按文档里最新的和按您说的替换了后，出现的问题{"code":550,"msg":"create partition err: create gamma table has err:[4294967294]
