### ISSUE TITLE
How to install PythonSDK

### ISSUE THREAD

**Issue by aelous** [vearch/vearch#121]
when I try to run `python setup.py build_ext --inplace `, it return 
```
running build_ext
building '_swigvearch' extension
swigging swigvearch.i to swigvearch_wrap.c
swig -python -o swigvearch_wrap.c swigvearch.i
/usr/local/share/swig/4.0.1/python/std_common.i:73: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
```
how to solve it ?

**Comment by duyongan** [comment]
我尝试pip install vearch
这个可以使用,可以创建表空间,但却无法正常查询

**Comment by duyongan** [comment]
> 我尝试pip install vearch
> 这个可以使用,可以创建表空间,但却无法正常查询

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by zcdb** [comment]
详细的代码可以贴一下吗，比如如何插入数据以及查询的？

> 我尝试pip install vearch
> 这个可以使用,可以创建表空间,但却无法正常查询
> 
> Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by zcdb** [comment]
you can just install PythonSDK by pip install vearch, or you want to build it from source, you can follow the steps in [https://github.com/vearch/vearch/blob/master/docs/Deploy.md](url) or use [https://github.com/vearch/vearch/blob/master/build/build.sh](url) to build it by set PYTHON_FLAG=ON in build.sh, then you can get vearch***.whl

> when I try to run python setup.py build_ext --inplace , it return
> running build_ext
> building '_swigvearch' extension
> swigging swigvearch.i to swigvearch_wrap.c
> swig -python -o swigvearch_wrap.c swigvearch.i
> /usr/local/share/swig/4.0.1/python/std_common.i:73: Error: Syntax error in input(1).
> error: command 'swig' failed with exit status 1
> 
> how to solve it ?

**Comment by duyongan** [comment]
> 详细的代码可以贴一下吗，比如如何插入数据以及查询的？
> 
> > 我尝试pip install vearch
> > 这个可以使用,可以创建表空间,但却无法正常查询
> > Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

我已解决无法查询的问题,我认为此项目的python API 不是很python,我将参与python API 的构建.
另外,我觉得缺少一个客户端,不知道是否有前端工程师愿意构建.或者现在已经有了?

**Comment by duyongan** [comment]
> 详细的代码可以贴一下吗，比如如何插入数据以及查询的？
> 
> > 我尝试pip install vearch
> > 这个可以使用,可以创建表空间,但却无法正常查询
> > Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
我的测试代码如下:
`import vearch
import numpy as np



#create a engine
engine_path = "files"
max_doc_size = 100000
path = 'data'
engine = vearch.Engine(path, max_doc_size)
log_path = "logs"
engine.init_log_dir(log_path)



#create a table
table = {
    "name": "test_table",
    "model": {
        "name": "IVFPQ",
        "nprobe": -1,
        "metric_type": "L2",
        "ncentroids": -1,
        "nsubvector": -1
    },
    "properties": {
        "key": {
            "type": "integer"
        },
        "feature": {
            "type": "vector",
            "dimension": 128,
            "store_param": {
                "cache_size": 2000
            }
        },
    },
}
engine.create_table(table)


#insert some data
add_num = 10000
features = np.random.rand(add_num, 128)
doc_items = []
for i in range(add_num):
    profiles = {}
    profiles["key"] = i
    profiles["feature"] = features[i, :].tolist()
    doc_items.append(profiles)
engine.add(doc_items)



#query one data
query = {
    "vector": [{
        "field": "feature",
        "feature": features[0, :].tolist(),

    }], "topn": 3
}
result = engine.search(query)
print(result)`

**Comment by duyongan** [comment]
import vearch
import numpy as np



#create a engine
engine_path = "files"
max_doc_size = 100000
path = 'data'
engine = vearch.Engine(path, max_doc_size)
log_path = "logs"
engine.init_log_dir(log_path)



#create a table
table = {
    "name": "test_table",
    "model": {
        "name": "IVFPQ",
        "nprobe": -1,
        "metric_type": "L2",
        "ncentroids": -1,
        "nsubvector": -1
    },
    "properties": {
        "key": {
            "type": "integer"
        },
        "feature": {
            "type": "vector",
            "dimension": 128,
            "store_param": {
                "cache_size": 2000
            }
        },
    },
}
engine.create_table(table)


#insert some data
add_num = 10000
features = np.random.rand(add_num, 128)
doc_items = []
for i in range(add_num):
    profiles = {}
    profiles["key"] = i
    profiles["feature"] = features[i, :].tolist()
    doc_items.append(profiles)
engine.add(doc_items)



#query one data
query = {
    "vector": [{
        "field": "feature",
        "feature": features[0, :].tolist(),

    }], "topn": 3
}
result = engine.search(query)
print(result)

**Comment by zcdb** [comment]
features = np.random.rand(add_num, 128) 这里生成的数据是float64的，目前vearch仅支持float32，使用tolist()之后 vearch python sdk 会使用float32来解析list,，实际上是可以直接使用numpy数组的，后续这块我们会优化一下，另外也非常欢迎加入vearch python api的构建

> import vearch
> import numpy as np
> #create a engine
> engine_path = "files"
> max_doc_size = 100000
> path = 'data'
> engine = vearch.Engine(path, max_doc_size)
> log_path = "logs"
> engine.init_log_dir(log_path)
> #create a table
> table = {
> "name": "test_table",
> "model": {
> "name": "IVFPQ",
> "nprobe": -1,
> "metric_type": "L2",
> "ncentroids": -1,
> "nsubvector": -1
> },
> "properties": {
> "key": {
> "type": "integer"
> },
> "feature": {
> "type": "vector",
> "dimension": 128,
> "store_param": {
> "cache_size": 2000
> }
> },
> },
> }
> engine.create_table(table)
> #insert some data
> add_num = 10000
> features = np.random.rand(add_num, 128)
> doc_items = []
> for i in range(add_num):
> profiles = {}
> profiles["key"] = i
> profiles["feature"] = features[i, :].tolist()
> doc_items.append(profiles)
> engine.add(doc_items)
> #query one data
> query = {
> "vector": [{
> "field": "feature",
> "feature": features[0, :].tolist(),
> }], "topn": 3
> 
> }
> result = engine.search(query)
> print(result)

**Comment by aelous** [comment]
Thanks for answer.
Whether PythonSDK is an independent client which has nothing to do with the cluster deployed via http?

**Comment by zcdb** [comment]
Yes. PythonSDK only encapsulates the core engine of the storage and calculation part of vearch so that vearch can be used locally by PythonSDK.

**Comment by rrjia** [comment]
pip无法下载vearch
pip install vearch
Collecting vearch
  Could not find a version that satisfies the requirement vearch (from versions: )
No matching distribution found for vearch

**Comment by zcdb** [comment]
@rrjia 请问你是在什么平台上安装的？目前pip 安装的方式仅支持linux平台

**Comment by rrjia** [comment]
> @rrjia 请问你是在什么平台上安装的？目前pip 安装的方式仅支持linux平台

是在linux平台下下载的，但是pypi源配置的阿里云的源，另外我的python版本是3.0从pypi网站上手动下载vearch-0.3.0.6-cp36-cp36m-manylinux2010_x86_64.whl，pip install 后显示：
vearch-0.3.0.6-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform.

**Comment by zcdb** [comment]
你可以试试import pip._internal.pep425tags; print(pip._internal.pep425tags.get_supported()) 查看一下cp36-cp36m-manylinux2010_x86_64是你现在的pip支持的吗？

**Comment by rrjia** [comment]
> import pip._internal.pep425tags; print(pip._internal.pep425tags.get_supported())

ModuleNotFoundError: No module named 'pip._internal'

**Comment by rrjia** [comment]
请问怎么样通过源码编译生成的engine库：libgamma.so.0.1，再编译生成pythonSDK？

**Comment by rrjia** [comment]
API for Vearch Python SDK中如何控制使用CPU还是GPU？

**Comment by zcdb** [comment]
请问你通过pip还是安装不了吗？建议你通过pip安装，直接通过源码编译生成engine库再编译生成pythonsdk,目前engine库更新了代码，但是新的python_sdk接口还未更新。现在的python sdk仅仅支持cpu.

**Comment by rrjia** [comment]
> 请问你通过pip还是安装不了吗？建议你通过pip安装，直接通过源码编译生成engine库再编译生成pythonsdk,目前engine库更新了代码，但是新的python_sdk接口还未更新。现在的python sdk仅仅支持cpu.

但是我想通过C++接口来实现GPU检索的效果时，发现gamma_api.h中好像也没有控制使用CPU还是GPU的接口参数

**Comment by zcdb** [comment]
你可以参照https://github.com/vearch/vearch/blob/master/docs/APILowLevelOnGPU.md来使用gpu进行检索，这个是直接使用vearch的

**Comment by wxingda** [comment]
MakeTable的时候设置retrieval_type为GPU就可以了

**Comment by rrjia** [comment]
请问有计划后续提供C++ API文档么？仅看gamma_api.h实在不太了解如何使用gamma引擎，
例如：
ByteArray *retrieval_param;  // retrieval parameters, json format
实在不知道retrieval_param应该输入什么内容

**Comment by wxingda** [comment]
下一版我们会重构API，届时接口会简化很多

**Comment by wxingda** [comment]
现在的版本的用法可以参考test_files.cc
