### ISSUE TITLE
vearch在重启后服务报错

### ISSUE THREAD

**Issue by zej0709** [vearch/vearch#122]
经常出现以下情况，请问能怎么解决呢？
![image](https://user-images.githubusercontent.com/58759236/76197781-c4030400-6227-11ea-8ed4-06d3d90e4b8b.png)
```
INFO 2020-03-09 08:46:36,688 realtime_mem_data.cc:68 ===init total_mem_bytes is 5898338304===
ERROR 2020-03-09 08:52:16,529 realtime_mem_data.cc:425 the file /datas/data/1/dump/2020-02-07-17:01:55/feature.index missing some vectors after the file /datas/data/1/dump/2020-02-07-16:59:06/vector.idx
```

**Comment by qiutianme** [comment]
@zej0709 首先你确认下，重启之后每个partition是不是只有一条这个错误信息。如果只有一条，那是没问题的（我们打印的日志不准确，需要完善一下）。如果有多条错误，麻烦提供下更多的错误信息。
其次，验证数据是否丢失，应该通过get或者search接口验证，不应该通过日志判断。

**Comment by zej0709** [comment]
目前partition只有一个。一开始我是查看了数据库的健康状态，发现无法连接space，所以去看了一下日志是什么原因，最后发现在日志中有如上错误。
因此认为是数据丢失导致无法连接，我又将数据重新录入了一边，一般情况下是么有问题的，但是查看健康状态又出现了以下信息：
![image](https://user-images.githubusercontent.com/58759236/76274552-f2322380-62bb-11ea-88bd-6716fb0caffe.png)

**Comment by qiutianme** [comment]
@zej0709 你这个错误应该有ps服务启动成功，或者网络连接不上。你确认下服务和网络吧

**Comment by qiutianme** [comment]
@zej0709 你这个错误应该是ps服务没有启动成功，或者网络不通，你确定下服务和网络

**Comment by iou2much** [comment]
INFO 2020-03-17 08:39:39,746 profile.cc:126 Profile load successed!
D0317 08:39:45.496521       1 startup.go:111] [DEBUG] mem.Alloc:14392328 mem.TotalAlloc:16219992 mem.HeapAlloc:14392328 mem.HeapSys:64847872 routing :113
I0317 08:39:46.099242       1 rpc_client.go:35] [INFO] instance client by rpc 127.0.0.1:8081
I0317 08:39:46.099286       1 rpc_client.go:49] [INFO] to instance client for server:[[127.0.0.1:8081]]
2020/03/17 08:39:46 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
2020/03/17 08:39:46 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
2020/03/17 08:39:46 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
2020/03/17 08:39:46 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
E0317 08:39:46.109342       1 monitor.go:71] [ERROR] monitor has err:[runtime error: invalid memory address or nil pointer dereference]
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
D0317 08:39:55.497057       1 startup.go:111] [DEBUG] mem.Alloc:14660648 mem.TotalAlloc:16488312 mem.HeapAlloc:14660648 mem.HeapSys:64847872 routing :113
D0317 08:40:05.497601       1 startup.go:111] [DEBUG] mem.Alloc:14869552 mem.TotalAlloc:16697216 mem.HeapAlloc:14869552 mem.HeapSys:64847872 routing :113
D0317 08:40:15.498054       1 startup.go:111] [DEBUG] mem.Alloc:15048824 mem.TotalAlloc:16876488 mem.HeapAlloc:15048824 mem.HeapSys:64847872 routing :113
D0317 08:40:25.498574       1 startup.go:111] [DEBUG] mem.Alloc:15225736 mem.TotalAlloc:17053400 mem.HeapAlloc:15225736 mem.HeapSys:64847872 routing :113
D0317 08:40:31.098432       1 schedule_job.go:133] [DEBUG] Start clean task
I0317 08:40:31.099151       1 schedule_job.go:36] [INFO] Start Walking Partitions!
I0317 08:40:31.099830       1 schedule_job.go:58] [INFO] Complete Walking Partitions!
I0317 08:40:31.100502       1 schedule_job.go:63] [INFO] Start Walking Spaces!
D0317 08:40:31.587717       1 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!
I0317 08:40:34.616616       1 schedule_job.go:104] [INFO] Receive keepalive, leaseId: 7354783806693611535, ttl:188
D0317 08:40:35.499058       1 startup.go:111] [DEBUG] mem.Alloc:15542808 mem.TotalAlloc:17370472 mem.HeapAlloc:15542808 mem.HeapSys:64847872 routing :113
D0317 08:40:45.499497       1 startup.go:111] [DEBUG] mem.Alloc:15719496 mem.TotalAlloc:17547160 mem.HeapAlloc:15719496 mem.HeapSys:64847872 routing :113
D0317 08:40:55.499952       1 startup.go:111] [DEBUG] mem.Alloc:15899168 mem.TotalAlloc:17726832 mem.HeapAlloc:15899168 mem.HeapSys:64847872 routing :113
D0317 08:41:05.500393       1 startup.go:111] [DEBUG] mem.Alloc:16107928 mem.TotalAlloc:17935592 mem.HeapAlloc:16107928 mem.HeapSys:64847872 routing :110
D0317 08:41:15.500784       1 startup.go:111] [DEBUG] mem.Alloc:16286384 mem.TotalAlloc:18114048 mem.HeapAlloc:16286384 mem.HeapSys:64847872 routing :110
D0317 08:41:25.501253       1 startup.go:111] [DEBUG] mem.Alloc:16462192 mem.TotalAlloc:18289856 mem.HeapAlloc:16462192 mem.HeapSys:64847872 routing :110
I0317 08:41:26.980732       1 rpc_client.go:35] [INFO] instance client by rpc 127.0.0.1:8081
I0317 08:41:26.980772       1 rpc_client.go:49] [INFO] to instance client for server:[[127.0.0.1:8081]]
2020/03/17 08:41:26 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
2020/03/17 08:41:26 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
2020/03/17 08:41:26 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
2020/03/17 08:41:26 connection.go:91: WARN : failed to dial server: dial tcp 127.0.0.1:8081: connect: connection refused
[GIN] 2020/03/17 - 08:41:27 | 200 |   23.248312ms |     192.168.5.1 | GET      /_cluster/stats
D0317 08:41:31.588204       1 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!
D0317 08:41:35.501732       1 startup.go:111] [DEBUG] mem.Alloc:11521992 mem.TotalAlloc:18824104 mem.HeapAlloc:11521992 mem.HeapSys:64815104 routing :110
I0317 08:41:37.647278       1 schedule_job.go:104] [INFO] Receive keepalive, leaseId: 7354783806693611535, ttl:188

@qiutianme 你好，我也遇到类似的情况。我是单机（单容器）运行，重启容器后就报dial tcp 127.0.0.1:8081: connect: connection refused了。所有服务都在同一容器中，应该不存在网络问题。请问ps服务的日志应该怎么看？我想定位一下是什么原因导致它没起来

**Comment by qiutianme** [comment]
@iou2much 这个错误看起来确实优点问题，我们会尽快确认并修复

**Comment by iou2much** [comment]
感谢！和这个是同样的问题：https://github.com/vearch/vearch/issues/52 ，这有另一part日志
