### ISSUE TITLE
关于特征加属性过滤检索的一些问题

### ISSUE THREAD

**Issue by paradoxtown** [vearch/vearch#127]
1000万512维特征，每个特征带有如下属性：

名称 | camera_id | img_id | captured_time | created_time | age | gender | mean_age | mean_gender | profile_id | cluster_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
类型 | integer | string | integer | integer | integer | integer | float | float | string | string

取同样的特征和属性，构造如下query：
```
{
    "query": {
        "filter": [{
            "range": {
                "gender": {
                    "gte": 0,
                    "lte": 0
                },
                "mean_gender": {
                    "gte": 0,
                    "lte": 0.5
                },
                "age": {
                    "gte": 40,
                    "lte": 55
                },
                "mean_age": {
                    "gte": 50,
                    "lte": 55
                }
            }
        }],
        "sum": [{
            "field": "feature",
            "feature": feature,
            "format": "normalization"
        }]
    },
    "direct_search_type": mode,
    "size": k
}
```
用这个query进行了**暴力检索和索引检索**各10次。
**相同的query**，返回的结果不稳定。大部分情况下返回的是正确的经过属性过滤的结果。
但是其中某些**暴力检索**后的到的结果和**索引检索**后得到的结果出现了属性过滤失败的情况。此时**索引检索**和**暴力检索**的到结果的重合率就非常低。
我想问一下vearch的属性过滤检索机制，以及可能会是什么原因导致上述问题的发生？

**Comment by wxingda** [comment]
你好，目前属性过滤多个条件求交功能有bug，最近会提交修复后代码

**Comment by paradoxtown** [comment]
谢谢！

**Comment by dingjun606** [comment]
> 你好，目前属性过滤多个条件求交功能有bug，最近会提交修复后代码

请问这个问题修复了吗，我们使用遇到了类似的问题，range filter过滤失效：返回结果和过滤的范围不匹配

**Comment by ljeagle** [comment]
我们check一下，这个bug我们尽快修复。

**Comment by wxingda** [comment]
请问使用的是哪个版本

**Comment by dingjun606** [comment]
> 请问使用的是哪个版本

使用的是docker镜像：
vearch/vearch             0.3.1
"Id": "sha256:2211951ac503fec4102a4d224b0b05a7a401074a33ac6cbc8dd32884d4e8eba8"
"Created": "2020-07-31T04:08:01.306188052Z"

不确定是否是我们使用方式的问题，我们使用同等过滤条件，测试vearch-hnsw检索相比暴力（自己实现的）检索的召回，共验证10个case，每个case召回top10结果，有8条召回是100%一致的，但是有两条结果完全不一致（vearch-hnsw召回的向量甚至不在过滤条件范围内），稍后我提供下建表语句与查询语句

**Comment by wxingda** [comment]
@dingjun606 麻烦提供下建表语句与查询语句

**Comment by rosickyyu** [comment]
@wxingda 
建表语句
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "candidate_ht",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 1000000,
        "id_type": "String",
		"retrieval_type": "HNSW",
        "retrieval_param": {
            "metric_type": "InnerProduct","nlinks":32,"efConstruction":40,"efSearch":64
        }
    },
    "properties": {
        "user_id": {
            "type": "keyword",
                "index": true
        },
        "month": {
            "type": "keyword"
        },"subject": {
            "type": "keyword",
                "index": true
        },"grade": {
            "type": "keyword",
                "index": true
        },
        "avg_score": {
            "type": "float",
                "index": true
        },
        "ht": {
            "type": "vector",
            "dimension": 1024,
            "store_type": "Mmap"
        }
    }
}
' http://172.31.96.173:8817/space/user_ht_test/_create

查询语句
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {"sum": [{"field": "ht", "feature": [1024维向量],"boost": 1.0}], "filter": [{"range": {"avg_score": {"gte": 0.20729166666666668, "lte": 0.4072916666666667}}}]}
    ,
    "fields": ["uesr_id"],
    "direct_search_type": 0,
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "size": 10
}
' http://172.31.96.173:9001/user_ht_test/candidate_ht/_search

**Comment by wxingda** [comment]
先把数字截短下试试，0.20729166666666668变成0.207

**Comment by rosickyyu** [comment]
@wxingda 试过的 检索出来的结果有avg_score=0.83的结果

**Comment by rosickyyu** [comment]
@wxingda 另外我现在试的是IVFPQ 51万条数据 第一次top10的召回率和暴力的差距很小接近于无 
但是过了一段时间 比如1-2个小时以后再检索 差距就很大了基本10个里面只能召回4-6个 我是放到内存里的 这个问题我试了几次 都是这样 就刚插入进去 第一次查的时候 结果和暴力检索的结果差不多 过一段时间再查结果就不一样了 好奇怪

**Comment by wxingda** [comment]
刚插入完成时vearch还没有建完索引，搜索时使用的是暴力搜索，所以结果跟暴力搜一样，等建完索引，就会使用索引搜索，结果就会和暴力搜不一样

**Comment by rosickyyu** [comment]
@wxingda 但是我这是设置direct_search_type=1查询出来的结果 也不是暴力检索的结果 跟direct_search_type=0召回率基本一致 我的建表语句中  "ht": {
            "type": "vector",
            "dimension": 1024,
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 40000
            }
        }没有设置 "index": true 然后属性描述中direct_search_type 指定查询类型，0代表若特征已经创建索引则使用索引，若没有创建则暴力搜索； -1 代表只使用索引进行搜索， 1代表不使用索引只进行暴力搜索。默认值是0。是默认对向量字段就建立索引吗？但是为什么我设置0 和 1返回结果都是一样呢。

**Comment by wxingda** [comment]
direct_search_type应该放在query里面去，也就是和sum同级，现在的文档有错误

**Comment by rosickyyu** [comment]
@wxingda 你好
我按下面的查询语句尝试了 仍然不是暴力检索的查询结果 不知道问题出在哪里
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
		"sum": [{
			"field": "ht",
			"feature": [1024向量],
			"boost": 1.0
		}],
		"direct_search_type": 1,
		"filter": [{
			"range": {
				"avg_score": {
					"gte": 0.2072, 
					"lte": 0.407
				}
			}
		}]
	},
    "fields": ["uesr_id"],
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "size": 20
}
' http://172.31.96.173:9001/user_ht_test/candidate_ht/_search

这个向量我建表时没建索引，需要加 "index": true吗
但是如果是这个原因，既然我没建索引 刚插入查询的和后面查询的应该都是一样的结果呢。不吝赐教

**Comment by zcdb** [comment]
你好，向量不指定是否建索引的话会默认建索引的。我看你上面建表里面指定的是HNSW，但是中间你又提到了IVFPQ，麻烦问一下现在指定暴力搜不生效是对于建表时使用HNSW的场景吗？这个我们暂时只在IVFPQ里面实现了通过direct_search_type来使用暴力搜，其它的索引还未实现通过direct_search_type来控制是否暴力搜

**Comment by rosickyyu** [comment]
@zcdb 我和同事先实验了HNSW模型 但是发现在检索过程中，我们用学科等于02、年级在（07,08,09）、平均分字段在0.2-0.4过滤条件后在排出检索值 但是实际出来的结果还有平均分字段等于0.8的结果出现。上面看到目前属性过滤多个条件求交功能有bug后，我们换了IVFPQ模型。以下是新的建表语句：
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "candidate_ht",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 1000000,
        "id_type": "String",
		"retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 256,
            "nsubvector": 64,
			"nbits_per_idx":8
        }
    },
    "properties": {
        "user_id": {
            "type": "keyword",
                "index": true
        },
        "month": {
            "type": "keyword"
        },"subject": {
            "type": "keyword",
                "index": true
        },"grade": {
            "type": "keyword",
                "index": true
        },
        "avg_score": {
            "type": "float",
                "index": true
        },
        "ht": {
            "type": "vector",
            "dimension": 1024,
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 40000
            }
        }
    }
}
' http://172.31.96.173:8817/space/user_ht_test/_create
但是direct_search_type没有起效果，我在刚把数据全部插入的时候，第一次检索出来的结果是暴力的结果，上面你们已经解释了这个时候在建索引，所以查询都是暴力检索。但是之后我把direct_search_type设为0继续查询，查询结果召回率就改变了，可以判断索引已经建立了，但是在我把direct_search_type设为1以后查询，查询结果召回率没有变化，和使用索引的查询结果几乎一样。

curl -H "content-type: application/json" -XPOST -d'
{
"query": {
"sum": [{
"field": "ht",
"feature": [1024向量],
"boost": 1.0
}],
"direct_search_type": 1,
"filter": [{
"range": {
"avg_score": {
"gte": 0.2072,
"lte": 0.407
}
}
}]
},
"fields": ["uesr_id"],
"online_log_level": "debug",
"quick": false,
"vector_value": false,
"client_type": "leader",
"size": 20
}
' http://172.31.96.173:9001/user_ht_test/candidate_ht/_search
这是查询语句 ，我根据你们的提醒，已经把direct_search_type放到了query里面

**Comment by zcdb** [comment]
好的，direct_search_type没有生效的问题我们再排查一下。还有一个问题我再确认一下，你们使用IVFPQ的时候range 过滤是正常的吗，即不会出现"avg_score": {"gte": 0.2072,"lte": 0.407}之外的值吗？

**Comment by wxingda** [comment]
最新版本的range index是异步创建的，插入数据后需要等几秒后才能正常使用，下个版本会修复这个问题

**Comment by rosickyyu** [comment]
@zcdb 这个结果我统计下，等下回复你。之前是10个查询，返回结果没有出来range异常的，我现在在大批量统计一次。HNSW是10个查询就出现了2个查询结果返回range异常的情况，即使我只有一个range没有其他term也会必现。

**Comment by rosickyyu** [comment]
@wxingda 我用的0.3.1版本的镜像，在数据插入后多次测试HNSW都必现上面那个问题

**Comment by wxingda** [comment]
创建表后，有重启的操作吗？

**Comment by rosickyyu** [comment]
@wxingda 没有

**Comment by rosickyyu** [comment]
> 好的，direct_search_type没有生效的问题我们再排查一下。还有一个问题我再确认一下，你们使用IVFPQ的时候range 过滤是正常的吗，即不会出现"avg_score": {"gte": 0.2072,"lte": 0.407}之外的值吗？

我重新做了实验，IVFPQ的这个range过滤不会超范围，检索出来的结果都在这个区间内
另外还有一个问题。HNSW模型的hits.total值和暴力检索的值对应不上，我没有设置min_score和max_score。但是每次查询返回的total都只几百到1000多不等，但是实际满足过滤条件的记录都是3万以上的记录。

**Comment by zcdb** [comment]
好的，hnsw的total是每次查询在hnsw图中访问的节点个数，因为hnsw会根据你设置的efSearch来决定在hnsw图中能够遍历有多远，数据量不大的时候它查询的时候很有可能只会遍历几百个到1000个点就完成了查询

**Comment by rosickyyu** [comment]
@zcdb 这个HNSW的暴力检索参数direct_search_type是不是还是不起作用？我理解efSearch来决定在hnsw图中能够遍历有多远
那ivfpq模型的ncentroids应该也是影响遍历个数的吧？为什么这个模型检索的total值比较正常呢。

**Comment by rosickyyu** [comment]
@zcdb 错了 是nprobe的个数

**Comment by zcdb** [comment]
ivfpq的total是满足过滤条件的总数，而不是ivfpq在搜索中遍历的节点个数，这里跟hnsw含义有一点不一样，在接下来的新版本我们将total都统一成了如果有数值过滤，那就是满足过滤条件的总数，如果没有数值过滤，那么就是表中的文档总数

**Comment by zcdb** [comment]
另外对于hnsw，direct_search_type现在是不起作用的，暂时还没有实现

**Comment by rosickyyu** [comment]
@zcdb direct_search_type这个参数对于ivfpq如何使用？我目前的查询语句如下
curl -H "content-type: application/json" -XPOST -d'
{
"query": {
"sum": [{
"field": "ht",
"feature": [1024向量],
"boost": 1.0
}],
"direct_search_type": 1,
"filter": [{
"range": {
"avg_score": {
"gte": 0.2072,
"lte": 0.407
}
}
}]
},
"fields": ["uesr_id"],
"online_log_level": "debug",
"quick": false,
"vector_value": false,
"client_type": "leader",
"nprobe": 200
"size": 20
}
' http://172.31.96.173:9001/user_ht_test/candidate_ht/_search

但是没有起作用，返回的结果感觉还是索引查询的结果

**Comment by zcdb** [comment]
@rosickyyu 我们查看了一下版本，发现docker镜像0.3.1版本暴力搜的字段已经修改了，即从direct_search_type变成了is_brute_search，查询的时候设置的位置和使用方式没变，还是跟sum字段一个级别

**Comment by rosickyyu** [comment]
@zcdb 经测，确实可以暴力检索了。感谢

**Comment by zcdb** [comment]
好的，不用谢~

**Comment by zcdb** [comment]
@rosickyyu hnsw数值过滤的确有bug，我们会马上提交修复的代码

**Comment by rosickyyu** [comment]
@zcdb 由于检索召回率不高 我准备调试ncentroids、nsubvector、nbits_per_idx  3个建表时的数据来尝试提高召回，但是我发现nbits_per_idx  这个值设置除8以外的数都会报错

curl -XPUT -H "content-type: application/json" -d'
> {
>     "name": "candidate_ht",
>     "partition_num": 1,
>     "replica_num": 1,
>     "engine": {
>         "name": "gamma",
>         "index_size": 70000,
>         "max_size": 1000000,
>         "id_type": "String",
> "retrieval_type": "IVFPQ",
>         "retrieval_param": {
>             "metric_type": "InnerProduct",
>             "ncentroids": 64,
>             "nsubvector": 32, 
> "nbits_per_idx":6
>         }
>     },
>     "properties": {
>         "user_id": {
>             "type": "keyword",
>                 "index": true
>         },
>         "month": {
>             "type": "keyword"
>         },"subject": {
>             "type": "keyword",
>                 "index": true
>         },"grade": {
>             "type": "keyword",
>                 "index": true
>         },
>         "avg_score": {
>             "type": "float",
>                 "index": true
>         },
>         "ht": {
>             "type": "vector",
>             "dimension": 1024,
>             "store_type": "Mmap",
>             "store_param": {
>                 "cache_size": 40000
>             }
>         }
>     }
> }
> ' http://172.31.96.173:8817/space/user_ht_test/_create
{"code":550,"msg":"create partition err: create gamma table has err:[4294967294] "}
这是啥原因呢？

**Comment by zcdb** [comment]
@rosickyyu  ivfpq限定了nbits_per_idx只能为8，另外如果要提高召回的话，按照我们之前的经验512维的向量需要设置到64，1028维向量的情况下nsubvector可以设置的更大，nprobe的话也可以进行适当的调整
