### ISSUE TITLE
集群部署的一些问题

### ISSUE THREAD

**Issue by zej0709** [vearch/vearch#129]
1、用docker是不是也可以集群部署？具体的命令应该是什么。
2、如果我有2000万的特征，我需要两台机器各存储1000万，最后在两台机器上检索，这是否可行？如果可行，是不是按照1 master，1 router 和 2 ps部署？

**Comment by nizyun** [comment]
1、建议使用k8s集群部署。
2、2000万特征两台机器各存储1000万进行检索可行。数据拆分是根据创建表时分片参数partition_num指定的, 数据会均匀分布在指定数量的分片上。

**Comment by zej0709** [comment]
谢谢倪兄，最后还是放弃了docker，orz
