### ISSUE TITLE
vearch动态增删节点对数据的影响

### ISSUE THREAD

**Issue by TTian-vivo** [vearch/vearch#130]
你好，想请教一下关于vearch动态增删节点的问题
vearch可以动态增删节点是吗？在其他同事的issue中看到了相同问题，此处想再确认下。如果我动态增加节点的话，以前构建的数据是否会自动分布到新的节点呢？如果我删除节点的话，以前在该节点下的数据也会被删除，此时数据又是如何管理的呢？

**Comment by ljeagle** [comment]
vearch可以支持动态增删副本。对于一个ps可以配置对应多个partition，并且通过master命令可以调整ps服务上配置的partition数目。现在版本对于一个partition上的数据总量设定了，不能扩容。数据上的扩容建议通过调整ps上的partition数目来达到扩容数据的目的。比如一个ps包含了4个partition， 可以调整为一个ps包含2个partition。

**Comment by TTian-vivo** [comment]
那我动态加入一个节点后，如果我自己不手动重新构建表空间并且添加数据，理论上这台机器就没有数据？那添加节点后还是解决不了现有数据问题。只能自己手动解决。
