### ISSUE TITLE
有没有vearch的交流群啊，有太多问题想问了

### ISSUE THREAD

**Issue by zej0709** [vearch/vearch#131]

**Comment by ljeagle** [comment]
@zej0709  微信交流群临时二维码https://github.com/vearch/vearch/blob/master/docs/img/tmp_communication.jpg

**Comment by zej0709** [comment]
谢谢！

**Comment by qianlinjun** [comment]
上面微信二维码过期了，谁可以重新分享一下微信群二维码吗？谢谢

**Comment by liruixue** [comment]
有最新的二维码么，挺好的一个项目，希望可以有地方互相交流真正地用好它

**Comment by Missqinxiaoer** [comment]
> 有最新的二维码么，挺好的一个项目，希望可以有地方互相交流真正地用好它

![微信图片_20200416190431](https://user-images.githubusercontent.com/39689026/79449893-a0955b00-8016-11ea-8c11-593627291056.jpg)
