### ISSUE TITLE
删除数据后，会定期在索引库里物理删除数据吗？

### ISSUE THREAD

**Issue by renyuxiang** [vearch/vearch#133]
1.现在更新是按照add+del的方式进行，del是记录在文档里，比如果断时间，del的数据很多，会重新更新索引吗？ 在faiss物理库里删除掉被del的数据。   
2.相同的数据，我先增加后删除，相当于删除，没有数据。 如果我先增加后删除又增加，相当于增加，使用上是这样的吗？

**Comment by qiutianme** [comment]
> 1.现在更新是按照add+del的方式进行，del是记录在文档里，比如果断时间，del的数据很多，会重新更新索引吗？ 在faiss物理库里删除掉被del的数据。
> 2.相同的数据，我先增加后删除，相当于删除，没有数据。 如果我先增加后删除又增加，相当于增加，使用上是这样的吗？

问题1: 我们已经开发了索引的compaction，测试没问题后就会更新到github
问题2: 是这样的，理解是对的
