### ISSUE TITLE
Server stuck when start vearch version 0.3 after index data 

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#134]
Hi team 

When I restart vearch v0.3 after index 34 million items with PS  : RocksDB . 
It show log error : 

> terminate called after throwing an instance of 'std::system_error'
>   what():  Resource temporarily unavailable
>

And my server show stuck error :  kernel:NMI watchdog: BUG: soft lockup - CPU#20 stuck for 22s! [xinetd:22883]

What is going on ?

**Comment by qiutianme** [comment]
@phamthanhtri Please show us the gamma.log which is in the log path configured in conf.toml and the ps running nohup log

**Comment by phamthanhtri** [comment]
Hi @qiutianme 
I run all services ( router,master, ps)  on the same server. I use  "store_type": "RocksDB" . 

- **nohup.log** 

> INFO 2020-03-20 09:21:06,922 profile.cc:106 Load profile doc_num [34207530]
> INFO 2020-03-20 09:21:15,496 profile.cc:126 Profile load successed!
> D0320 09:21:18.453192   56010 startup.go:111] [DEBUG] mem.Alloc:13746512 mem.TotalAlloc:17327384 mem.HeapAlloc:13746512 mem.HeapSys:64815104 routing :110
> D0320 09:21:28.453479   56010 startup.go:111] [DEBUG] mem.Alloc:14768688 mem.TotalAlloc:18349560 mem.HeapAlloc:14768688 mem.HeapSys:64815104 routing :110
> terminat
> 

- **gamma.log**

> INFO 2020-03-20 09:21:06,922 profile.cc:106 Load profile doc_num [34207530]
> INFO 2020-03-20 09:21:15,496 profile.cc:126 Profile load successed!
> 
> 

- **Master.ERROR.log**

> E0320 09:20:58.443843   56010 server.go:192] [ERROR] to register master error, nodeId:[1440], err : master server all down
> E0320 09:21:00.445028   56010 server.go:192] [ERROR] to register master error, nodeId:[1440], err : master server all down
> 

**

**- Master.DEBUG.log**

**

> D0320 09:20:58.441846   56010 master_api.go:242] [DEBUG] master api Register url: http://xxxx:8917/register?clusterName=cbdb_v3&nodeId=1440
> D0320 09:20:58.443773   56010 master_api.go:244] [DEBUG] master api Register response: 
> D0320 09:20:58.443807   56010 master_api.go:248] [DEBUG] master api Register err: Post http://xxxx:8917/register?clusterName=cbdb_v3&nodeId=1440: dial tcp xxxx:8917: connect: connection refused
> D0320 09:21:00.444539   56010 master_api.go:242] [DEBUG] master api Register url: http://xxxx:8917/register?clusterName=cbdb_v3&nodeId=1440
> D0320 09:21:00.444942   56010 master_api.go:244] [DEBUG] master api Register response: 
> D0320 09:21:00.445002   56010 master_api.go:248] [DEBUG] master api Register err: Post http://xxxx:8917/register?clusterName=cbdb_v3&nodeId=1440: dial tcp xxxx:8917: connect: connection refused
> D0320 09:21:02.165086   56010 master_cache.go:602] [DEBUG] start watcher routine
> D0320 09:21:02.445371   56010 master_api.go:242] [DEBUG] master api Register url: http://xxxx:8917/register?clusterName=cbdb_v3&nodeId=1440
> D0320 09:21:02.446215   56010 cluster_api.go:139] [DEBUG] register from: xxxx
> D0320 09:21:02.448182   56010 master_api.go:244] [DEBUG] master api Register response: {"code":200,"msg":"success","data":{"rpc_port":0,"raft_heartbeat_port":0,"raft_replicate_port":0,"ip":"xxxx","p_ids":[3],"private":false,"version":null}}
> D0320 09:21:02.448766   56010 partition_service.go:253] [DEBUG] starting recover partition[3]...
> D0320 09:21:02.451576   56010 server.go:101] [DEBUG] RaftResolver AddNode(), nodeId: [1440], nodeRef:[&{0 xxxx:8998 xxxx:8999 xxxx:8181}], obj:[&{0 xxxx:8998 xxxx:8999 xxxx:8181}]
> D0320 09:21:02.451635   56010 server.go:103] [DEBUG] r.nodes, key: [1440], value: [&{0 xxxx:8998 xxxx:8999 xxxx:8181}]
> D0320 09:21:08.451542   56010 startup.go:111] [DEBUG] mem.Alloc:12721992 mem.TotalAlloc:16302864 mem.HeapAlloc:12721992 mem.HeapSys:64815104 routing :110
> D0320 09:21:18.453192   56010 startup.go:111] [DEBUG] mem.Alloc:13746512 mem.TotalAlloc:17327384 mem.HeapAlloc:13746512 mem.HeapSys:64815104 routing :110
> D0320 09:21:28.453479   56010 startup.go:111] [DEBUG] mem.Alloc:14768688 mem.TotalAlloc:18349560 mem.HeapAlloc:14768688 mem.HeapSys:64815104 routing :110
> 
>

**Comment by qiutianme** [comment]
@phamthanhtri  This does look like a problem, we will fix it as soon as possible.
