### ISSUE TITLE
系统支持建立索引后，将原始vector删掉吗？

### ISSUE THREAD

**Issue by qianlinjun** [vearch/vearch#135]
比如我每张图片产生200个40维的vector，系统可以在自动建立索引后将这200个vector删掉吗？

**Comment by ljeagle** [comment]
目前不支持删除原始向量。

**Comment by qianlinjun** [comment]
好的。另外我看到作者分享过微信交流群的二维码，但是过期了，请问能不能重新更新一下?谢谢!
