### ISSUE TITLE
节点个数对批量查询性能的影响

### ISSUE THREAD

**Issue by TTian-vivo** [vearch/vearch#136]
你好，我现在在使用vearch做向量检索，数据量约53万128维向量，想通过vearch服务，批量查询20条数据，时延在30ms以内；我最先开启两个节点做测试，使用wrk压测，平均时延约280ms；然后开启四个节点，发现平均时延基本没变，请问这个是什么原因呢？我该怎样配置去达到这个性能？

**Comment by ljeagle** [comment]
向量检索比较吃cpu，所以压力情况下，时延会大一些。不知道你测试压力多大。另外，目前版本对于性能确实不是最好，我们已经优化完一版，您这样的数据规模情况下，批量访问情况下QPS8-900,tp99 36ms左右，最近会发布，可以关注一下。追求性能，当然更推荐用tcp接口，我们正在添加中。

**Comment by TTian-vivo** [comment]
感谢回复；关于测试压力，我个人认为不大，我只开了一个线程，4个并发。还想请问一下：
1. 批量查询的原理是什么？我在测试的时候发现批量查询的时间跟单条查询的叠加时间差不多，是不是目前的批量查询机制就是单挑查询多次呢？
2.关于分区数量和查询性能的关系；在有些数据集下，增加分区数压测性能会变好；有些数据集增加分区数，性能反而变差。不知道这个该如何解释。

**Comment by TTian-vivo** [comment]
咱们网页上的微信讨论群，我扫描过期了，可不可以加一下呢？微信号：tian103041
