### ISSUE TITLE
图像量大时上传时是否有批量接口呢？

### ISSUE THREAD

**Issue by liruixue** [vearch/vearch#138]
初步试用该系统，识别率还是很不错的，感谢Vearch团队的付出。当前项目中的图像要插入的数据会比较多，想知道图像量大时上传时是否有批量接口呢？

**Comment by gDreamcatcher** [comment]
你好， 如果你没有使用插件服务的话，可以使用批量插入接口，具体参考[API](https://vearch.readthedocs.io/zh_CN/latest/use_op/op_doc.html#id3)。

插件服务暂时不支持批量插入和批量搜索, 后期我们会考虑添加这个功能。

最后，感谢您的关注和认同！

**Comment by liruixue** [comment]
嗯，vearch的图像识别是比较实用的，但是要一张一张传确实比较耗时（看了下，4K大小的图片，大概2-3张就耗时一秒钟），对于大图片量的数据处理，比如我们现存的2000万张这种图片，项目即使不停歇地上传，这样算下来得3个多月才能上传完毕，可能就没办法使用Vearch来做了，希望厉害的Vearch团队能尽早推出批量插入功能帮助到我们呀，感谢~

**Comment by liruixue** [comment]
嗯，vearch的图像识别是比较实用的，但是要一张一张传确实比较耗时（看了下，4KB大小的图片，大概2-3张就耗时一秒钟），对于大图片量的数据处理，比如我们现存的2000万张这种图片，项目即使不停歇地上传，这样算下来得3个多月才能上传完毕，可能就没办法使用Vearch来做了，希望厉害的Vearch团队能尽早推出批量插入功能帮助到我们呀，感谢~

**Comment by gDreamcatcher** [comment]
插件服务需要提取完特征再存入系统中的，如果条件允许的话你可以在多台gpu机器部署插件服务，然后并发调用插入接口，相信速度会有很大的提升。
如果只有一台gpu机器的话也可以使用多进程的方式加快插入的速度。
修改这个地方为你的gpu卡，-1使用的cpu，假如你有4块GPU显卡的话你就可以修改为“1，2，3，4”，当然如果只有1块卡而且显存支持的话也可以这样写“1，1，1，1”
https://github.com/vearch/vearch/blob/94cd19cf2da0e95744ac5aeab145243600835903/plugin/src/config.py#L19

**Comment by liruixue** [comment]
当前启用的图片插件，应该是用yolov3模型自动提取特征后存入系统中的.
你提到的多进程方式是只支持GPU机器吗，cpu机器可以玩起来不？

**Comment by gDreamcatcher** [comment]
cpu也可以使用多进程，不过单机cpu多进程效果不会有明显提高

**Comment by liruixue** [comment]
好的，感谢，稍后试下在GPU机器上速度的提升情况.

**Comment by liruixue** [comment]
> 插件服务需要提取完特征再存入系统中的，如果条件允许的话你可以在多台gpu机器部署插件服务，然后并发调用插入接口，相信速度会有很大的提升。
> 如果只有一台gpu机器的话也可以使用多进程的方式加快插入的速度。
> 修改这个地方为你的gpu卡，-1使用的cpu，假如你有4块GPU显卡的话你就可以修改为“1，2，3，4”，当然如果只有1块卡而且显存支持的话也可以这样写“1，1，1，1”
> https://github.com/vearch/vearch/blob/94cd19cf2da0e95744ac5aeab145243600835903/plugin/src/config.py#L19



> 插件服务需要提取完特征再存入系统中的，如果条件允许的话你可以在多台gpu机器部署插件服务，然后并发调用插入接口，相信速度会有很大的提升。
> 如果只有一台gpu机器的话也可以使用多进程的方式加快插入的速度。
> 修改这个地方为你的gpu卡，-1使用的cpu，假如你有4块GPU显卡的话你就可以修改为“1，2，3，4”，当然如果只有1块卡而且显存支持的话也可以这样写“1，1，1，1”
> https://github.com/vearch/vearch/blob/94cd19cf2da0e95744ac5aeab145243600835903/plugin/src/config.py#L19

Hi gDreamcatcher ， 我根据你的建议去尝试GPU多进程的方案，试着把图像插件以docker（根据plugin目录的Dockerfile来build完成）的方式启动了起来，同时这个docker容器里config.py中的GPU支持项改为 gpus =“1，1，1，1”。 

不过插件启动之后，插入图片数据时，似乎仍然使用的是CPU运算，因为可以看到cpu的占用率比较高，而在使用nvidia-smi命令查看GPU的使用情况时（见下面打印的结果），却看不到有任何GPU进程在其中出现，请教下Docker这种运行方式，能有办法让机器的GPU跑起来吗？
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.63       Driver Version: 430.63       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID T4-4Q          On   | 00000000:00:07.0 Off |                  N/A |
| N/A   N/A    P0    N/A /  N/A |    272MiB /  4064MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by liruixue** [comment]
@gDreamcatcher  图片插件要使用GPU能力，请问还需要注意其他什么事项或配置没呢，在线等呀，谢谢

**Comment by gDreamcatcher** [comment]
不好意思刚看到，没有其他注意事项了 @liruixue

**Comment by liruixue** [comment]
好的，后来我尝试把gpus参数改成gpus =“0,0,0,0”反而看到GPU有启动起来了
