### ISSUE TITLE
Insert image error:gamma create doc err code, how to fix it?

### ISSUE THREAD

**Issue by liruixue** [vearch/vearch#139]
I can create the db and db-space for image plugin, it works fine. After insert some images(about 200,000 items), I can't insert more items, and I can find the error info from 'run-image-log.file' in Vearch Plugin path,   the error saying  "reason":"gamma create doc err code:[4294967295]",  I have no idea about it, would you please help give some suggestion to fix it? Many thanks.

**Comment by gDreamcatcher** [comment]
You can set max_size when you create db_space, the max num you can insert is equal to max_size*partition_num, refer to [vearch API](https://vearch.readthedocs.io/zh_CN/latest/use_op/op_space.html) for more detail.

**Comment by liruixue** [comment]
Ok, I will try it and let you know if it works.

**Comment by liruixue** [comment]
Tested, your solution works well, many thanks.
