### ISSUE TITLE
向量存储中的source字段

### ISSUE THREAD

**Issue by Dr1rD** [vearch/vearch#140]
请问, gamma中向量存储带的source字段作为什么用途？

[这里](https://github.com/vearch/vearch/blob/master/engine/gamma/vector/raw_vector.cc#L161)显示每个source分配100字节，如果未使用，是不是空间就浪费了？

**Comment by ljeagle** [comment]
这个是存储一些字符串用的，比如一个文档，可以对应多个图片url，每个图片都有自己的url标识要存，另外都有自己的特征向量。这块目前是占用空间比较多，我们也正考虑做优化。

**Comment by Dr1rD** [comment]
哦哦，有道理。了解了，谢谢！
