### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by Dr1rD** [vearch/vearch#147]
想请问下 ，在创建好space后，gamma的内存使用是不是也就确定下来了？

随着index或者search进行，内存使用不会增加？

**Comment by ljeagle** [comment]
实时索引是动态扩展的，但索引内存涨幅非常小。正排及向量数据在内存版中初始化好了，但在实际操作系统中，不会一次性malloc出来，所以实际运行中看到有一些内存涨幅
