### ISSUE TITLE
是否能够支持到分页查询呢

### ISSUE THREAD

**Issue by liruixue** [vearch/vearch#148]
当前的近似度查询如果想改变返回的条目数，是通过size参数来动态调整的，似乎并不支持from这种分页的查询方式，如果我想每次返回一定条目的数据进行分页查询，请问有办法支持到吗？

**Comment by ljeagle** [comment]
这个功能感觉外层使用方去支持可能更合适。

**Comment by liruixue** [comment]
外层使用方支持，是指调用方一口气查出大量结果，并临时保存这个查询结果，然后再分页是吗？比如我的系统可以看为外层使用方来对外开放查询接口，我的客户传图像来分页查近似结果，客户是要一页显示20条，不过我却必须先查500条，临时保存起来，别人要翻页，我根据自己保存的临时结果来做翻页功能是吧?  呵呵，这个分页功能要是能作为个插件放到vearch里支持应该也很实用

**Comment by ansjsun** [comment]
我记得query 里面有个start +size 可以试试




在2020年04月05日 16:41，liruixue 写道：

外层使用方支持，是指调用方一口气查出大量结果，并临时保存这个查询结果，然后再分页是吗？比如我的系统可以看为外层使用方来对外开放查询接口，我的客户传图像来分页查近似结果，客户是要一页显示20条，不过我却必须先查500条，临时保存起来，别人要翻页，我根据自己保存的临时结果来做翻页功能是吧? 呵呵，这个分页功能要是能作为个插件放到vearch里支持应该也很实用

**Comment by liruixue** [comment]
我试过from或者start与size的组合，只有size能起到作用，from和start带进查询条件里并不会让搜索的结果列表发生偏移哦

**Comment by ansjsun** [comment]
那应该就是bug了 用这个功能的比较少 所以没怎么测试
