### ISSUE TITLE
想问下支持的faiss版本是什么范围

### ISSUE THREAD

**Issue by simon666888** [vearch/vearch#151]
我这边下载了1.6.0版本的faiss，gamma编译是成功的, 但是最后启动 vearch的时候报错：
ps/engine/gammacb/lib/lib/libgamma.so：对‘faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)’未定义的引用
感觉是faiss版本没有对齐导致的，想问下具体支持的版本范围

**Comment by wxingda** [comment]
你是在Linux下编译的吗？

**Comment by simon666888** [comment]
是的呀， centos 7.4 , gcc 6.5, go 1.11

**Comment by wxingda** [comment]
你可以试下1.6.1版本，1.6.0版本比较旧了
