### ISSUE TITLE
profile dump error

### ISSUE THREAD

**Issue by Dr1rD** [vearch/vearch#152]
profile dump 字符串时，生成的 .str.prf 文件数据有缺失：**最后一个doc的字符串字段不全**。

这导致机器重启后，load进str_mem_的数据就乱套了，检索时返回的字符串字段很多错误。

原因应该是，str_mem_中字符串排列顺序与mem_(attr_idx_map_)中各字段的顺序不一样，str_mem_中的顺序是Add时决定的，而dump是按照attr_idx_map_来确定last_str_idx的，所以会导致last_str_idx并不是真正的最后一个字符的位置。

我在每次Add时，把fields按照attr_idx_map_中的顺序排序，dump就没问题了
```
  std::vector<Field *> sorted_fields(field_num_, nullptr);
  for (size_t i = 0; i < fields.size(); ++i) {
    const auto field_value = fields[i];
    const string &name =
        std::string(field_value->name->value, field_value->name->len);
    auto it = attr_idx_map_.find(name);
    sorted_fields[it->second] = field_value;
  }
```
我用的是f756e05372，不是最新的，不知道你们后面更新了没，抑或是我哪搞错了？

**Comment by wxingda** [comment]
你好，在f756e05372版本确实存在这个问题，最新版本已修复这个bug，建议将版本更新到最新，需要注意的是，最新版本为了支持对dump文件的update，安装gamma的时候需要使用RocksDB，`export ROCKSDB_HOME=the installed path of RocksDB`，具体可以参考文档https://github.com/vearch/vearch/blob/master/docs/Deploy.md
