### ISSUE TITLE
表参数cache_size设置问题

### ISSUE THREAD

**Issue by qianlinjun** [vearch/vearch#153]
想问一下　示例中说所有特征字段cache_size总大小建议不超过机器内存的70%，那么是否略大于index_size得到的cache_size就行了?

**Comment by qiutianme** [comment]
@qianlinjun “不超过机器内存的70%”是一个内存保护建议，因为系统和其它进程还会占用内存。

至于“ cache_size”具体设置多大，这个得看你想如何存储原始向量，下面分别说明：
1. 如果想用全内存模式（前提是内存足够大），cache_size可以不设置（默认是全内存模式）或者略大于max_size个特征向量计算的值；
2.  如果想用磁盘模式，cache只是作为临时的写缓冲，不用太大，cache_size设置成1024或者2048即可，单位是M bytes

**Comment by qianlinjun** [comment]
好的，谢谢
