### ISSUE TITLE
关于索引类型

### ISSUE THREAD

**Issue by aleczhangj** [vearch/vearch#154]
1、目前vearch支持faiss的哪些索引类型
2、如何手动指定建立索引时候的索引类型

**Comment by ljeagle** [comment]
目前只支持IVFPQ索引，马上会支持HNSW索引。

**Comment by aleczhangj** [comment]
有支持暴力搜索的计划吗

**Comment by ljeagle** [comment]
index_size=0，不会建索引，直接暴力搜索
