### ISSUE TITLE
搜索结果排序的问题

### ISSUE THREAD

**Issue by zyjlx123456** [vearch/vearch#155]
space：
`{
    "code": 200,
    "msg": "success",
    "data": [
        {
            "id": 20,
            "name": "spaceName",
            "version": 2,
            "db_id": 41,
            "enabled": true,
            "partitions": [
                {
                    "id": 21,
                    "space_id": 20,
                    "db_id": 41,
                    "partition_slot": 0,
                    "replicas": [
                        180
                    ]
                }
            ],
            "partition_num": 1,
            "replica_num": 1,
            "properties": {
                "id": {
                    "index": "true",
                    "type": "integer"
                },
                "project_name": {
                    "array": false,
                    "index": "true",
                    "type": "keyword"
                },
                "project_desc": {
                    "dimension": 2,
                    "type": "vector"
                }
            },
            "engine": {
                "name": "gamma",
                "index_size": 100000,
                "max_size": 100000,
                "nprobe": -1,
                "metric_type": "L2",
                "ncentroids": -1,
                "nsubvector": -1,
                "nbits_per_idx": -1
            }
        }
    ]
}`
插入数据之后的查询如下所示：
`{
  "hits": {
    "hits": [
      {
        "extra": {
          "vector_result": [
            {
              "score": 0.020000001415610313,
              "field": "project_desc",
              "source": ""
            }
          ]
        },
        "id": "",
        "index": "tb_yx_project_b",
        "score": 0.020000001415610313,
        "source": {
          "id": 2,
          "project_name": "name2",
          "project_desc": {
            "feature": [
              0.3,
              0.3
            ],
            "source": ""
          }
        },
        "type": "spaceName",
        "version": 0
      },
      {
        "extra": {
          "vector_result": [
            {
              "score": 0.020000001415610313,
              "field": "project_desc",
              "source": ""
            }
          ]
        },
        "id": "",
        "index": "tb_yx_project_b",
        "score": 0.020000001415610313,
        "source": {
          "id": 3,
          "project_name": "name3",
          "project_desc": {
            "feature": [
              0.5,
              0.5
            ],
            "source": ""
          }
        },
        "type": "spaceName",
        "version": 0
      },
      {
        "extra": {
          "vector_result": [
            {
              "score": 0.68000000715255737,
              "field": "project_desc",
              "source": ""
            }
          ]
        },
        "id": "",
        "index": "tb_yx_project_b",
        "score": 0.6800000071525574,
        "source": {
          "id": 1,
          "project_name": "name",
          "project_desc": {
            "feature": [
              0.1,
              0.1
            ],
            "source": ""
          }
        },
        "type": "spaceName",
        "version": 0
      }
    ],
    "max_score": 0.6800000071525574,
    "total": 3
  },
  "shards": {
    "failed": 0,
    "successful": 1,
    "total": 1
  },
  "timed_out": false,
  "took": 1
}`
两个问题：
1、查询结果之后的排序分数怎么以分数高的排在前面？
2、以[0.1,0.1]的向量查询，发现[0.3,0.3]和[0.5,0.5]的分数为什么是一样的？

**Comment by qiutianme** [comment]
@zyjlx123456 问题1: 看你的space信息中用的是L2距离，对于L2距离，分数（距离）越小表示向量越相似，所以是按照从小到大的分数排序的。
问题2: 我们查一下分数不对的问题
