### ISSUE TITLE
docid数据未dump

### ISSUE THREAD

**Issue by qianlinjun** [vearch/vearch#156]
我插入了两万条数据，但是重启容器时提示我 ERROR invalid docid file size=0,报错定位到engine/raw_vector.cc的　RawVectorIO::Load函数。然后把数据输出来看.docid文件大小为0

之后重开一个容器，在client/ps_partition_service.go　needRefresh函数中添加打印日志调试，发现
err := this.flush(LEADER)
这句代码一直没有调用，想问一下可能是什么原因?以及flush什么情况下会调用？

**Comment by qiutianme** [comment]
@qianlinjun  容器是无状态的，写到文件中的数据在容器重启后就没了，所以，如果你想使用dump/load功能，可以参考如下的操作
1. 通过docker的mount功能，将物理机的目录挂载到容器，然后用该目录作为ps的data目录（config.toml中配置）
2. 如果是k8s，可以看看它提供的有状态服务

**Comment by qianlinjun** [comment]
好的，谢谢
