### ISSUE TITLE
docker 容器重启，特征会重新保存一遍

### ISSUE THREAD

**Issue by qianlinjun** [vearch/vearch#157]
将容器关闭，然后docker start aontainer id, 重启容器，最开始插入的特征会通过engine AddOrUpdateDoc接口重新加载一遍,然后特征文件size会增加,增加量为最开始插入的特征size

**Comment by qiutianme** [comment]
@qianlinjun 为了保证数据一致性，服务重启后，vearch会重放最后一次dump之后插入的数据（如果没有触发dump，就是所有数据），所以这是正常的。

**Comment by qianlinjun** [comment]
好的，谢谢
