### ISSUE TITLE
最新的vearch和gamma是编译不过的

### ISSUE THREAD

**Issue by codingwangfeng** [vearch/vearch#158]
使用最新的vearch和gamma是编译不过的

**Comment by wxingda** [comment]
具体报什么错误呢？

**Comment by codingwangfeng** [comment]
> 具体报什么错误呢？

gamma的时候xxxgamma/c_api/gamma_api.cc:15:33: fatal error: gamma_api_generated.h: No such file or directory

**Comment by wxingda** [comment]
gamma_api_generated.h是在执行cmake时自动生成的，你可以把third_party下面的flatbuffers-1.11.0文件夹删除掉，然后重新cmake一下

**Comment by codingwangfeng** [comment]
> gamma_api_generated.h是在执行cmake时自动生成的，你可以把third_party下面的flatbuffers-1.11.0文件夹删除掉，然后重新cmake一下
cmake之后汇报如下错误，看起来是flatbuffers这个编译有点问题，我继续看看
build.sh: line 13: /home/op_dev/faiss/gamma/idl/../third_party/flatbuffers-1.11.0/flatc: No such file or directory

**Comment by codingwangfeng** [comment]
是因为没有flatc这个binary，需要编译出来
cd gamma/third_party/flatbuffers-1.11.0
cmake3 -G "Unix Makefiles" && make

**Comment by codingwangfeng** [comment]
cd "/deploy/vearch/gamma/idl" && sh build.sh flatbuffers-1.11.0 /deploy/vearch/gamma/idl/fbs-gen  2>&1
