### ISSUE TITLE
求个交流群呗

### ISSUE THREAD

**Issue by kongjiellx** [vearch/vearch#159]
求个交流群呗

**Comment by Missqinxiaoer** [comment]
> 求个交流群呗

![Uploading image.png…]()

**Comment by Missqinxiaoer** [comment]
> 求个交流群呗

![微信图片_20200416190431](https://user-images.githubusercontent.com/39689026/79449082-26b0a200-8015-11ea-8324-077a0ff1d3d1.jpg)

**Comment by rosickyyu** [comment]
@Missqinxiaoer 请重新发下群的二维码

**Comment by cuisonghui** [comment]
@Missqinxiaoer @ljeagle @qiutianme 能否在分享下交流群呢，想进一步进行技术交流。

**Comment by ljeagle** [comment]
![760342135](https://user-images.githubusercontent.com/15918167/91633402-9fd7f100-ea1a-11ea-9635-8cbc948439a8.jpg)

**Comment by zhouyongxiu** [comment]
可以再发一下吗，过期了

**Comment by wxingda** [comment]
![1](https://user-images.githubusercontent.com/12606514/92361509-0a76e400-f121-11ea-82da-7bf5aed951f5.png)

**Comment by hrb-apachexiong** [comment]
求重新发下

**Comment by wxingda** [comment]
![image](https://user-images.githubusercontent.com/12606514/93072146-96ee4d00-f6b3-11ea-9e59-846c6ef5cf78.png)

**Comment by njlkj** [comment]
求重新发下

**Comment by matadorhong** [comment]
求重新发一下。

**Comment by matadorhong** [comment]
@wxingda 求重新发一下。

**Comment by ljeagle** [comment]
![Uploading 1856809713.jpg…]()

**Comment by matadorhong** [comment]
@ljeagle 貌似图片看不出来。麻烦重新上传下。

**Comment by ljeagle** [comment]
![1856809713](https://user-images.githubusercontent.com/15918167/94024881-7b3d2200-fdea-11ea-93d8-24a5b23dd62d.jpg)

**Comment by pallashadow** [comment]
求更新

**Comment by wxingda** [comment]
> 求更新

![image](https://user-images.githubusercontent.com/12606514/95566260-e83ff100-0a53-11eb-9b1c-b56c92f872d8.png)

**Comment by rosaline1995** [comment]
求更新，谢谢～

**Comment by wxingda** [comment]
![image](https://user-images.githubusercontent.com/12606514/98633303-161e9b00-235c-11eb-91ed-e3aaa2178cd7.png)

**Comment by kousyaku** [comment]
麻烦再更新一下，谢谢

**Comment by wxingda** [comment]
![image](https://user-images.githubusercontent.com/12606514/102055597-1102af00-3e26-11eb-9f58-5b153e23193f.png)

**Comment by qihaoxiansheng** [comment]
求更新

**Comment by wxingda** [comment]
> 求更新

上面那个二维码还有效呢

**Comment by qihaoxiansheng** [comment]
打不开呀

**Comment by wxingda** [comment]
> 打不开呀

![image](https://user-images.githubusercontent.com/12606514/102297077-9a7ec200-3f89-11eb-8512-1aa5836dfa34.png)

**Comment by qihaoxiansheng** [comment]
网页打不开啊

**Comment by qihaoxiansheng** [comment]
可以截个屏，直接发在这上面吗
