### ISSUE TITLE
GPU上运行Image plugin时，报出max_pool2d_with_indices_out_cuda_frame failed with error code 0错误

### ISSUE THREAD

**Issue by liruixue** [vearch/vearch#163]
想使用GPU来跑Image plugin，正常启动后，通过`nvidia-smi`能够看到GPU状态中有正在运行的进程，然后创建DB与Space都能成功，不过在上传图片时，遇到错误`max_pool2d_with_indices_out_cuda_frame failed with error code 0`，请问可以有什么解决方案么？
`环境说明`cuda-toolkit版本为10.1`，

**Comment by wxingda** [comment]
这个日志是在哪里打印的呢？GPU是什么型号？

**Comment by liruixue** [comment]
是curl指令执行后直接返回的，4101及8817都没有见到这个日志的相关信息，GPU是NVIDIA的T4

**Comment by gDreamcatcher** [comment]
这是提取特征的时候失败了，所以接口直接把错误信息返回，这个问题具体的解决方案还需要测试一下。

**Comment by liruixue** [comment]
等你们的方案回复哈
