### ISSUE TITLE
I encounter the following errors when I "make && make install". 

### ISSUE THREAD

**Issue by Jupanlee** [vearch/vearch#164]
CMakeFiles/gamma.dir/build.make:166: recipe for target 'CMakeFiles/gamma.dir/index/gamma_index_ivfpq.cc.o' failed
make[2]: *** [CMakeFiles/gamma.dir/index/gamma_index_ivfpq.cc.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/gamma.dir/all' failed
make[1]: *** [CMakeFiles/gamma.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhaoshoucheng** [comment]
Has it been solved? How to solve the problem
