### ISSUE TITLE
请问如何将表空间的数据文件进行拷贝(迁移)呢

### ISSUE THREAD

**Issue by liruixue** [vearch/vearch#165]
因为原来的磁盘随着数据的插入增长，空间已经不太够用，我根据config.toml的数据路径配置，拷贝走了原vearch目录下的datas,datas1这两个文件夹下的所有文件，并放到新机器安装的vearch目录下，启动vearch后，使用curl -XGET http://127.0.0.1:4101/imageDB/tmImgSpace/_search来访问tmImgSpace空间里的文件数，会返回'partition not exsit '，不知道自己的数据拷贝迁移方法有什么，还请帮忙解答?

**Comment by vincentLk** [comment]
https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md#change-member

可以试试这个吧

**Comment by xqtbox** [comment]
同问，特别是docker模式。  直接把 容器 打包成新的镜像，然后拷贝到新的机器。这种方式科学吗？？

**Comment by xqtbox** [comment]
应该是 版本不一致造成的，为0.3版本的datas和datas1拷贝到0.5.1版本运行，报错。  0.5.1的数据互相拷贝 不报错
