### ISSUE TITLE
编译gamma时报错，‘const struct faiss::IndexIVF’没有名为‘maintain_direct_map’的成员，是哪版本代码有更新吗？

### ISSUE THREAD

**Issue by allensky708** [vearch/vearch#167]
[ 38%] Building CXX object CMakeFiles/gamma.dir/index/field_range_index.cc.o
[ 42%] Building CXX object CMakeFiles/gamma.dir/index/gamma_index_ivfpq.cc.o
In file included from /home/vearch/go/src/github/vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:20:0:
/home/vearch/go/src/github/vearch/vearch/engine/gamma/index/gamma_index_ivfpq.h: 在函数‘void tig_gamma::write_ivf_header(const faiss::IndexIVF*, faiss::IOWriter*)’中:
/home/vearch/go/src/github/vearch/vearch/engine/gamma/index/gamma_index_ivfpq.h:903:15: 错误：‘const struct faiss::IndexIVF’没有名为‘maintain_direct_map’的成员
   WRITE1(ivf->maintain_direct_map);
               ^
/home/vearch/go/src/github/vearch/vearch/engine/gamma/index/gamma_index_ivfpq.h:853:23: 附注：in definition of macro ‘WRITEANDCHECK’
     size_t ret = (*f)(ptr, sizeof(*(ptr)), n);                                \
                       ^
/home/vearch/go/src/github/vearch/vearch/engine/gamma/index/gamma_index_ivfpq.h:903:3: 附注：in expansion of macro ‘WRITE1’
......

**Comment by wxingda** [comment]
vearch暂不支持最新版本的faiss，请使用faiss v1.6.1
