### ISSUE TITLE
dump问题：日志显示dump成功，但没有生成dump.done文件

### ISSUE THREAD

**Issue by 1990hjp** [vearch/vearch#171]
单节点写入dump后能生成dump.done文件，并发写入时dump后只有dumping文件。
![单节点写入](https://user-images.githubusercontent.com/10457787/84001994-47a0ce00-a99a-11ea-8330-aa7ca1f72f16.jpg)
![多节点写入](https://user-images.githubusercontent.com/10457787/84001997-496a9180-a99a-11ea-9544-b5b65cbf0c39.jpg)

**Comment by qiutianme** [comment]
该问题已经修复过，建议升级新版本
