### ISSUE TITLE
支持仅更新文档单个字段吗

### ISSUE THREAD

**Issue by comeonfox** [vearch/vearch#172]
我的space中定义了5个字段，其中一个是向量字段，剩下为标量字段。我只想更新其中的一个标量（增加1），但是似乎需要在这里传入完成的5个字段的值，并且修改想更新的字段的值才可以，只传入待更新字段就会报错。

但这个更新成本就会变的很高，因为需要重新计算向量字段的值。

VEARCH版本：https://hub.docker.com/layers/ansj/vearch/0.3.2/images/sha256-9f28cccbd7f0e5262bcd172e38d291a3a960f11b5689fe65d1342d3639f16ad8?context=explore

更新命令：
```
curl -XPOST -H "content-type: application/json" http://${router_server}/${db_name}/${space_name}/${id}/_update -d '{
    "doc": {
            "field1": 2
    }
}'
```
返回
```
{"_index":"sentence_topk","_type":"sentences","_id":"text1","status":550,"error":{"index":"","index_uuid":"","shard":"0","type":"","reason":"field num:[1] not same by schema:[5]"}}
```

**Comment by wxingda** [comment]
暂时不支持单标量字段更新，后续会加入该功能
