### ISSUE TITLE
是否有去除重复结果的功能？

### ISSUE THREAD

**Issue by AnniWan** [vearch/vearch#173]
如果重复将数据插入的话，查询结果会存在重复结果，是否有去除重复结果的功能？

**Comment by wxingda** [comment]
插入时指定id，这样插入相同id的数据就会变成修改，结果就不会重复了

**Comment by AnniWan** [comment]
> 
> 
> 插入时指定id，这样插入相同id的数据就会变成修改，结果就不会重复了

不能直接根据数据去除重复结果吗？

**Comment by wxingda** [comment]
> > 插入时指定id，这样插入相同id的数据就会变成修改，结果就不会重复了
> 
> 不能直接根据数据去除重复结果吗？

怎么认定数据是否重复呢？

**Comment by AnniWan** [comment]
> 
> 
> > > 插入时指定id，这样插入相同id的数据就会变成修改，结果就不会重复了
> > 
> > 
> > 不能直接根据数据去除重复结果吗？
> 
> 怎么认定数据是否重复呢？

如果是插入n维特征数据，用相似性度量的方法应该是可以进行计算的，如果只能根据id来去除重复的话，那么只能在插入前就做一个去重。
