### ISSUE TITLE
Error when load vearch partition server

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#175]
Dear team 

I used vearch v.03 with rocksdb . After index approximate 40 million items . I restart vearch  partition server but It's not load partition data on server and show error :

File gamma.log:
ERROR 2020-06-19 10:30:35,137 field_range_index.cc:600 Cannot find field [Y��]
ERROR 2020-06-19 10:30:35,137 field_range_index.cc:600 Cannot find field [`�]
ERROR 2020-06-19 11:14:58,110 gamma_index_ivfpq.cc:243 add index from docid 26253000 error!
WARNING 2020-06-19 11:14:58,142 realtime_invert_index.cc:79 exceed the max bucket keys [1280000], not extend memory any more! keys_size [218] bucket_no [55] _cur_ptr->_cur_invert_ptr->_cur_bucket_keys[bucket_no] [640000]

**Comment by qiutianme** [comment]
@phamthanhtri Please use the latest version v3.1.0, and compile it with rocksdb, we have increase the bucket limit to 12800000 in v3.1.0

> Dear team
> 
> I used vearch v.03 with rocksdb . After index approximate 40 million items . I restart vearch partition server but It's not load partition data on server and show error :
> 
> File gamma.log:
> ERROR 2020-06-19 10:30:35,137 field_range_index.cc:600 Cannot find field [Y��]
> ERROR 2020-06-19 10:30:35,137 field_range_index.cc:600 Cannot find field [`�]
> ERROR 2020-06-19 11:14:58,110 gamma_index_ivfpq.cc:243 add index from docid 26253000 error!
> WARNING 2020-06-19 11:14:58,142 realtime_invert_index.cc:79 exceed the max bucket keys [1280000], not extend memory any more! keys_size [218] bucket_no [55] _cur_ptr->_cur_invert_ptr->_cur_bucket_keys[bucket_no] [640000]

**Comment by phamthanhtri** [comment]
Hi @qiutianme  

I build  gamma engine version v0.3.1 with  faiss v1.6.1 , gcc-7.3 , rocksdb-6.2 .  These dependencies build successfully  the version v0.3.0 but  with v0.3.1 , it show error :

> vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1121:36: error: ‘DirectMap’ in namespace ‘faiss’ does not name a type
 static void write_direct_map(const faiss::DirectMap *dm, faiss::IOWriter *f) {
                                    ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1121:54: error: ISO C++ forbids declaration of ‘dm’ with no type [-fpermissive]
 static void write_direct_map(const faiss::DirectMap *dm, faiss::IOWriter *f) {
                                                      ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc: In function ‘void tig_gamma::write_direct_map(const int*, faiss::IOWriter*)’:
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1123:17: error: request for member ‘type’ in ‘* dm’, which is of non-class type ‘const int’
       (char)dm->type;  // for backwards compatibility with bool
                 ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1125:19: error: request for member ‘array’ in ‘* dm’, which is of non-class type ‘const int’
   WRITEVECTOR(dm->array);
                   ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1093:20: note: in definition of macro ‘WRITEVECTOR’
     size_t size = (vec).size();        \
                    ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1125:19: error: request for member ‘array’ in ‘* dm’, which is of non-class type ‘const int’
   WRITEVECTOR(dm->array);
                   ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1076:23: note: in definition of macro ‘WRITEANDCHECK’
     size_t ret = (*f)(ptr, sizeof(*(ptr)), n);                                \
                       ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1125:3: note: in expansion of macro ‘WRITEVECTOR’
   WRITEVECTOR(dm->array);
   ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1125:19: error: request for member ‘array’ in ‘* dm’, which is of non-class type ‘const int’
   WRITEVECTOR(dm->array);
                   ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1076:37: note: in definition of macro ‘WRITEANDCHECK’
     size_t ret = (*f)(ptr, sizeof(*(ptr)), n);                                \
                                     ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1125:3: note: in expansion of macro ‘WRITEVECTOR’
   WRITEVECTOR(dm->array);
   ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1126:11: error: request for member ‘type’ in ‘* dm’, which is of non-class type ‘const int’
   if (dm->type == faiss::DirectMap::Hashtable) {
           ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1126:26: error: ‘faiss::DirectMap’ has not been declared
   if (dm->type == faiss::DirectMap::Hashtable) {
                          ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1129:55: error: request for member ‘hashtable’ in ‘* dm’, which is of non-class type ‘const int’
     const std::unordered_map<idx_t, idx_t> &map = dm->hashtable;
                                                       ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc: In function ‘void tig_gamma::write_ivf_header(const faiss::IndexIVF*, faiss::IOWriter*)’:
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1141:39: error: cannot convert ‘const std::vector<long int>*’ to ‘const int*’ for argument ‘1’ to ‘void tig_gamma::write_direct_map(const int*, faiss::IOWriter*)’
   write_direct_map(&ivf->direct_map, f);
                                       ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc: At global scope:
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1155:36: error: variable or field ‘read_direct_map’ declared void
 static void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f) {
                                    ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1155:29: error: ‘DirectMap’ is not a member of ‘faiss’
 static void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f) {
                             ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1155:47: error: ‘dm’ was not declared in this scope
 static void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f) {
                                               ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1155:67: error: expected primary-expression before ‘*’ token
 static void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f) {
                                                                   ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1155:68: error: ‘f’ was not declared in this scope
 static void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f) {
                                                                    ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1355:1: error: expected ‘}’ at end of input
 }  // namespace tig_gamma
 ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1136:13: warning: ‘void tig_gamma::write_ivf_header(const faiss::IndexIVF*, faiss::IOWriter*)’ defined but not used [-Wunused-function]
 static void write_ivf_header(const faiss::IndexIVF *ivf, faiss::IOWriter *f) {
             ^
vearch/vearch/engine/gamma/index/gamma_index_ivfpq.cc:1144:13: warning: ‘void tig_gamma::read_index_header(faiss::Index*, faiss::IOReader*)’ defined but not used [-Wunused-function]
 static void read_index_header(faiss::Index *idx, faiss::IOReader *f) {
             ^
make[2]: *** [CMakeFiles/gamma.dir/index/gamma_index_ivfpq.cc.o] Error 1
make[1]: *** [CMakeFiles/gamma.dir/all] Error 2
make: *** [all] Error 2

**Comment by phamthanhtri** [comment]
@qiutianme  I used lastest faiss v1.6.3 , gcc-7.3 , rocksdb-6.2  build vearch v3.1.0 successfully . But  I load indexed data , it show many error 

gamma.log 

> INFO 2020-06-22 10:58:08,949 gamma_api.cc:297 Engine init successed!
> ERROR 2020-06-22 10:58:08,956 vector_manager.cc:75 NO support for retrieval type 
> INFO 2020-06-22 10:58:08,956 profile.cc:170 Add field name [_id], type [4], index [0]
> INFO 2020-06-22 10:58:08,956 profile.cc:170 Add field name [uid], type [0], index [1]
> INFO 2020-06-22 10:58:08,956 profile.cc:170 Add field name [imageurl], type [4], index [1]
> INFO 2020-06-22 10:58:08,956 profile.cc:170 Add field name [boundingbox], type [4], index [1]
> INFO 2020-06-22 10:58:09,161 profile.cc:237 Create table 4 success!
> ERROR 2020-06-22 10:58:09,161 gamma_engine.cc:642 Cannot create table!
> INFO 2020-06-22 10:58:09,167 profile.cc:237 Create table 6 success!
> ERROR 2020-06-22 10:58:09,167 gamma_engine.cc:642 Cannot create table!
>

**Comment by qiutianme** [comment]
@phamthanhtri  Maybe v3.1.0's data format is not compatible to v0.3.0. You can try to recreate space and insert document

**Comment by phamthanhtri** [comment]
Hi @qiutianme  

I used new version v0.3.1 and reindex with my data . After indexed ~260 million item vectors ( 130 million items vector per partition) . Vearch can't load this spaces . What's wrong with me ? 

![image](https://user-images.githubusercontent.com/37447023/87409991-f23a8b00-c5ef-11ea-9923-6bc3ed824ce3.png)
