### ISSUE TITLE
插入数据的时候报404

### ISSUE THREAD

**Issue by xiesibo** [vearch/vearch#176]
表情况如下：
{
  "code": 200,
  "msg": "success",
  "data": {
    "id": 2,
    "name": "img_car",
    "version": 2,
    "db_id": 3,
    "enabled": true,
    "partitions": [
      {
        "id": 2,
        "space_id": 2,
        "db_id": 3,
        "partition_slot": 0,
        "replicas": [
          180
        ]
      }
    ],
    "partition_num": 1,
    "replica_num": 1,
    "properties": {
      "imageId": {
        "type": "keyword",
        "index": true
      },
      "imgsrc": {
        "type": "string",
        "array": true,
        "index": true
      },
      "feature": {
        "type": "vector",
        "store_type": "Mmap",
        "dimension": 512,
        "store_param": {
          "cache_size": 2000
        }
      }
    },
    "engine": {
      "name": "gamma",
      "index_size": 9999,
      "max_size": 100000,
      "nprobe": 10,
      "metric_type": "InnerProduct",
      "ncentroids": -1,
      "nsubvector": -1,
      "nbits_per_idx": -1
    }
  }
}
插入数据如下：
{"imgsrc": "/data1/traffic/0425_pic", "imageId": "00003224-9be3-11ea-b1d5-0492264f1e08", "feature": {"feature": [0.0, 0.0, 0.0, 0.0, 0.0, 0.016205, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.002067, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.021071, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08622, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.046341, 0.0, 0.007883, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.075046, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.023893, 0.0, 0.0, 0.0, 0.065234, 0.014035, 0.0, 0.095783, 0.0, 0.0, 0.0, 0.038396, 0.0, 0.0, 0.0, 0.0, 0.106313, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.019111, 0.0, 0.0, 0.185372, 0.0, 0.0, 0.0, 0.0, 0.0, 0.070567, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004475, 0.0, 0.0, 0.074806, 0.014223, 0.0, 0.0, 0.0, 0.0, 0.0, 0.006738, 0.0, 0.0, 0.0, 0.01979, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.032305, 0.0, 0.0, 0.0, 0.0, 0.2184, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.020428, 0.0, 0.0, 0.00504, 0.414054, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.014823, 0.0, 0.072475, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.224022, 0.0, 0.016695, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007194, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.096316, 0.028719, 0.0, 0.004647, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.012247, 0.0, 0.0, 0.0, 0.083938, 0.0, 0.0, 0.0, 0.0, 0.028113, 0.0, 0.051044, 0.0, 0.006844, 0.0, 0.0, 0.000948, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.058377, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.024933, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007905, 0.0, 0.000349, 0.0, 0.0, 0.104814, 0.0, 0.0, 0.004939, 0.0, 0.0, 0.0, 0.059985, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.006856, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.018515, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04153, 0.0, 0.001281, 0.0, 0.055003, 0.0, 0.0, 0.003607, 0.0, 0.0, 0.0, 0.0, 0.010409, 0.172098, 0.0, 0.0, 0.029619, 0.009107, 0.0, 0.0, 0.0, 0.0, 0.0, 0.015914, 0.002346, 0.150722, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.039983, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.022898, 0.108362, 0.0, 0.0, 0.141118, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02288, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007157, 0.0, 0.0, 0.0, 0.225198, 0.007068, 0.073482, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.007498, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010917, 0.0, 0.327062, 0.0, 0.014921, 0.0, 0.0, 0.0, 0.0, 0.190784, 0.0, 0.0, 0.0, 0.0, 0.003426, 0.0, 0.0, 0.0, 0.007892, 0.0, 0.0, 0.0, 0.0, 0.001068, 0.0, 0.013646, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}}
返回数据：
404 page not found

**Comment by kevintony001** [comment]
请求插入数据请求URL错误，麻烦查看：https://vearch.readthedocs.io/zh_CN/latest/use_op/op_doc.html#id2

**Comment by xiaojuan8** [comment]
请问解决了嘛？按照文档把insert数据格式改成和field的定义格式一样还是404 page not found
