### ISSUE TITLE
Text search index

### ISSUE THREAD

**Issue by DenisNovac** [vearch/vearch#186]
Hi everyone. In docs there are examples for images:

``` 
"properties": {
		"vector": {
			"type": "vector",
			"model_id": "img",
			"dimension": 128,
			"format": "normalization"
		},
...
}

"retrieval_type": "IVFPQ",

"models": [{
		"model_id": "vgg16",
		"fields": ["string"],
		"out": "feature"
	}]
```

Which model_ids are available? For example, can i use this setup?

```
"properties": {
		"vector": {
			"type": "vector",
			"model_id": "text",
			"dimension": 128,
			"format": "normalization"
		},
...
}

"retrieval_type": "HNSW",

"models": [{
		"model_id": "SVD",
		"fields": ["vector"],
		"out": "feature"
	}]
```

Seems like the `retrieval_type` parameter is the only one which is checked before creation. Does `model_id` parameters even do anything? I also found this comment in gamma: https://github.com/vearch/gamma/blob/4866970006d8ebc1ef85fb62086998ec3f3d8868/c_api/gamma_api.h#L101

**Comment by qiutianme** [comment]
@DenisNovac  model_id is unused now. retrieval_type="HNSW" is supported!

> "retrieval_type": "HNSW",

**Comment by DenisNovac** [comment]
@qiutianme Thank you for answer. But there are two "model_id" fields. They are both unused?

**Comment by qiutianme** [comment]
@DenisNovac  Yes,  they are both unused. And the "models" is unused too.
> "models": [{
>		"model_id": "SVD",
>		"fields": ["vector"],
>		"out": "feature"
>	}]

**Comment by DenisNovac** [comment]
@qiutianme Thank you for answer.
