### ISSUE TITLE
特征数据存储在哪里

### ISSUE THREAD

**Issue by aleczhangj** [vearch/vearch#187]
特征数据存储在哪里？本地磁盘还是数据库？在服务重启或者重新部署的时候，是不是需要停服。
比如1000w特征，加载耗时10分钟，这10分钟是不是停服状态

**Comment by qiutianme** [comment]
> 特征数据存储在哪里？本地磁盘还是数据库？在服务重启或者重新部署的时候，是不是需要停服。
> 比如1000w特征，加载耗时10分钟，这10分钟是不是停服状态

1. 特征数据是本地磁盘
2.服务重启加载特征阶段确实不能对外提供服务，但是1000w特征加载一般都是秒级，不会是10分钟这么久
