### ISSUE TITLE
Query result slowly after index data

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#191]
Hi everyone 

I used vearch v0.3.1 build with :

-  faiss v1.6.1 

-  gcc-7.3 

-  rocksdb-6.2

I indexed 60 million items successfully . But when search on system ,it's quite slow compared to the old version (v0.2) .  It spends ~230 ms (40ms - old v0.2 ) 

> [INFO] search use time :[236] . max partition:[5] use time:[234]

Please advise me what problem ?

**Comment by ljeagle** [comment]
Could you give the usage of creating table and searching in detail?

**Comment by phamthanhtri** [comment]
@ljeagle  

1. This is  the info of partition server 
![image](https://user-images.githubusercontent.com/37447023/88142494-c9357e00-cc1f-11ea-986b-346e4cb764d7.png)


2. This is meta for create table :

> {"id":4,"name":"test","version":1,"db_id":1,"enabled":false,"partitions":[{"id":4,"space_id":4,"db_id":1,"partition_slot":0,"replicas":[180]},{"id":5,"space_id":4,"db_id":1,"partition_slot":2147483647,"replicas":[360]}],"partition_num":2,"replica_num":1,"properties":{"imageurl": {"type": "keyword", "index": true}, "uid": {"type": "integer", "index": true}, "boundingbox": {"type": "keyword", "index": true}, "feature": {"type": "vector", "filed": "imageurl", "model_id": "vgg16", "dimension": 512, "store_type": "RocksDB", "format": "normalization"}},"engine":{"name":"gamma","index_size":10000,"max_size":700000000,"metric_type":"InnerProduct","retrieval_type":"IVFPQ","retrieval_param":{"metric_type": "InnerProduct", "ncentroids": -1, "nsubvector": -1}}}

**Comment by ljeagle** [comment]
Please confirm the parameters for the both versions are the same.

**Comment by phamthanhtri** [comment]
Yes ,  the parameters are the same.  Old version build with faiss v1.5.3 , gcc 4.8 and rocksdb 6.2

This is meta  table of old version 

> {"id":2,"name":"test","version":1,"db_id":2,"enabled":false,"partitions":[{"id":3,"space_id":2,"db_id":2,"partition_slot":0,"replicas":[180]},{"id":4,"space_id":2,"db_id":2,"partition_slot":2147483647,"replicas":[360]}],"partition_num":2,"replica_num":1,"properties":{"imageurl": {"type": "keyword", "index": true}, "uid": {"type": "integer", "index": true}, "boundingbox": {"type": "keyword", "index": true}, "feature": {"type": "vector", "filed": "imageurl", "model_id": "vgg16", "dimension": 512, "store_type": "RocksDB", "format": "normalization"}},"engine":{"name":"gamma","index_size":100000,"max_size":70000000,"nprobe":-1,"metric_type":"InnerProduct","ncentroids":-1,"nsubvector":-1,"nbits_per_idx":-1}}

**Comment by qiutianme** [comment]
@phamthanhtri  Maybe the default value of some parameters is changed in v0.3.1. Please paste the contents of gamma.log  when you created the space on v0.2 and v0.3.1

**Comment by qiutianme** [comment]
@phamthanhtri  And please paste the search request too.

**Comment by phamthanhtri** [comment]
Dear @qiutianme  
This is gamma.log when create space on v0.3.1 

> INFO 2020-07-23 11:04:48,401 gamma_engine.cc:346 GammaEngine setup successed!
> INFO 2020-07-23 11:04:48,401 gamma_api.cc:297 Engine init successed!
> INFO 2020-07-23 11:04:48,401 raw_vector_factory.h:35 store parameters={cache size=2048000000}
> INFO 2020-07-23 11:04:48,413 rocksdb_raw_vector.cc:66 rocks raw vector init success! name=feature, block cache size=2048000000Bytes
> INFO 2020-07-23 11:04:48,413 raw_vector.cc:204 raw vector init success! name=feature, has source=0, multi_vids=0
> INFO 2020-07-23 11:04:48,413 gamma_index_factory.h:36 Create index model [0]
> INFO 2020-07-23 11:04:48,413 gamma_index_factory.h:46 metric_type = 0, ncentroids =256, nsubvector =64, nbits_per_idx =8
> INFO 2020-07-23 11:04:48,452 realtime_mem_data.cc:88 ===init total_mem_bytes is 1843203072===
> INFO 2020-07-23 11:04:48,452 profile.cc:170 Add field name [_id], type [4], index [0]
> INFO 2020-07-23 11:04:48,452 profile.cc:170 Add field name [uid], type [0], index [1]
> INFO 2020-07-23 11:04:48,452 profile.cc:170 Add field name [imageurl], type [4], index [1]
> INFO 2020-07-23 11:04:48,452 profile.cc:170 Add field name [boundingbox], type [4], index [1]
> INFO 2020-07-23 11:04:48,468 profile.cc:237 Create table 11 success!
> INFO 2020-07-23 11:04:48,468 gamma_engine.cc:1234 Add range field [boundingbox]
> INFO 2020-07-23 11:04:48,469 gamma_engine.cc:1234 Add range field [imageurl]
> INFO 2020-07-23 11:04:48,469 gamma_engine.cc:1234 Add range field [uid]
> INFO 2020-07-23 11:04:48,471 gamma_engine.cc:664 create table [11] success!


This is gamma.log when create space on v0.2

> INFO 2020-05-11 17:46:27,111 gamma_engine.cc:308 GammaEngine setup successed!
> INFO 2020-05-11 17:46:27,111 gamma_api.cc:312 Engine init successed!
> INFO 2020-05-11 17:46:27,111 vector_manager.cc:53 ivfpq parameters: metric_type=0, nprobe=20, ncentroids=256, nsubvector=64, nbits_per_idx=8
> INFO 2020-05-11 17:46:27,111 raw_vector_factory.h:34 store parameters={cache size=122880000000}
> INFO 2020-05-11 17:46:27,112 profile.cc:42 Profile created success!
> INFO 2020-05-11 17:46:27,112 gamma_engine.cc:308 GammaEngine setup successed!
> INFO 2020-05-11 17:46:27,112 gamma_api.cc:312 Engine init successed!
>NFO 2020-05-11 17:46:28,000 rocksdb_raw_vector.cc:63 rocks raw vector init success! name=feature, block cache size=122880000000Bytes
INFO 2020-05-11 17:46:28,024 rocksdb_raw_vector.cc:63 rocks raw vector init success! name=feature, block cache size=122880000000Bytes
INFO 2020-05-11 17:46:28,354 profile.cc:140 Add field name [_id], type [4], index [0]
INFO 2020-05-11 17:46:28,354 profile.cc:140 Add field name [_version], type [1], index [0]
INFO 2020-05-11 17:46:28,354 profile.cc:140 Add field name [_slot], type [0], index [0]
INFO 2020-05-11 17:46:28,354 profile.cc:140 Add field name [uid], type [1], index [1]
INFO 2020-05-11 17:46:28,354 profile.cc:140 Add field name [imageurl], type [4], index [1]
INFO 2020-05-11 17:46:28,354 profile.cc:140 Add field name [boundingbox], type [4], index [1]
INFO 2020-05-11 17:46:28,355 profile.cc:164 Create table 6 success!


This is search function by python 

```
def test_api(dummy):
    min_score = 0
    filters = None
    _HEADERS = {"content-type": "application/json"}
    feat = (emb/np.linalg.norm(emb)).tolist()
    data = {"query": {"sum": [{"feature": feat, "field": "feature","min_score": min_score}],"filter":filters}}
    url = f"{router_address}/{video['db']}/{video['space']}/_search?size=10"
    res =  requests.post(url, headers=_HEADERS, data=json.dumps(data))
    res = res.json()
    return res
```

**Comment by qiutianme** [comment]
@phamthanhtri  As I see, only the cache size is different. So you can increase the cache size in v0.3.1 according to your total memory size of machine.

v0.3.1  cache size is 2G
> INFO 2020-07-23 11:04:48,413 rocksdb_raw_vector.cc:66 rocks raw vector init success! name=feature, block cache size=2048000000Bytes

v0.2 cache size is about 120G
> NFO 2020-05-11 17:46:28,000 rocksdb_raw_vector.cc:63 rocks raw vector init success! name=feature, block cache size=122880000000Bytes

**Comment by phamthanhtri** [comment]
Thanks @qiutianme  , How do I change the cache size ?

**Comment by qiutianme** [comment]
@phamthanhtri  When you create space, you can set the "cache_size" parameter is in "store_param" of vector field. Just like this, I set cache size=10240M bytes which means 10G bytes.

```JSON
{
    "properties": {
           "vector_field": {
            "type": "vector",
            "dimension": 256,
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 10240
            }
        }
    }
}
```

And you can also refer to the document https://vearch.readthedocs.io/en/latest/use_op/op_space.html#create-space

**Comment by phamthanhtri** [comment]
I create many test case with v0.3.1 for search benchmarks on 2 partition servers . Each server will contain half of the items: 

+ 50 thousands items (each partition server 25 thousands items) :  tooks 10ms  
+ 20 million items:  tooks 120ms 
+ 70 million items:  tooks 200ms  (v0.2 tooks 60ms) 
+ 230 million items:  tooks 700ms 

It increases linear time . 
I add log for check excute time search in ps/engine/gammacb/reader.go 
```
	arr := C.SearchV2(ri.engine.gamma, req)
	defer C.DestroyByteArray(arr)
	resp := gamma_api.GetRootAsResponse(CbArr2ByteArray(arr), 0)
	idType := ri.engine.space.Engine.IdType
	result := ri.singleSearchResult(resp, 0, idType)
	result.MaxTook = int64(time.Now().Sub(start) / time.Millisecond)
	result.MaxTookID = ri.engine.partitionID
	t3 := time.Now()
	log.Debug("Search_end :[%d]", (t3.Sub(t1) / time.Millisecond))
```
It took most of the time here . I would like to confirm that I'm using faiss v1.6.3

**Comment by qiutianme** [comment]
@phamthanhtri This is weird！Different versions of faiss will not have such a big impact on performance. 

You can do another experiment. Set the quick=true in search request, to exclude the impact of reading raw vectors from rocksdb on performance. Refer to https://vearch.readthedocs.io/en/latest/use_op/op_doc.html#search

```JSON
{
    "query": {
    },
    "quick": false
}
```

**Comment by qiutianme** [comment]
Sorry! It is

```JSON
{
    "query": {
    },
    "quick": true
}
```

**Comment by phamthanhtri** [comment]
Thanks @qiutianme 
I  test with new experiment with your search config `{
    "query": {
    },
    "quick": true
}`
But the processing time has not changed :(

**Comment by zcdb** [comment]
@phamthanhtri Is each query a single query? Not batch? Now the default value of the query parallel mode has been changed. The previous one was parallel on the inverted linked list (v0.2), and now it is changed to parallel between queries (v3.1.0). You can try to query like this { "query": { }, "parallel": false }

**Comment by qiutianme** [comment]
Yes, I forget it! The default parallel mode of v0.3.1 is changed to parallel_on_query from parrallel_on_inverted_list. @phamthanhtri you can try it with zcdb 's advice, set *"parallel": false* in search request

**Comment by phamthanhtri** [comment]
I set param  parallel and quick but it's not effective
        `data = {"query": {"sum": [{"feature": feat, "field": "feature"}], "parallel": False,"quick": True}}

I think the reason is maybe from faiss ( 1.5.3 -> 16.3) . I am currently reviewing it. 
`

**Comment by phamthanhtri** [comment]
Hi everyone 
I review code  in engine/gamma . Most of the process time of search request  in function scan_one_list  (gamma_index_ivfpq.cc) 

  ```
for (size_t ik = 0; ik < nprobe; ik++) {
          nscan += scan_one_list (
              scanner, keys [i * nprobe + ik], coarse_dis[i * nprobe + ik], 
              simi, idxi, k, this->nlist, this->invlists, store_pairs, 
              condition->ivf_flat, raw_vec_head);
  
          if (max_codes && nscan >= max_codes) {
            break;
          }
        }
```

> [scan_one_list] sys: 219ms


It used method scan_list_with_table (gamma_index_ivfpq.h).

**Comment by qiutianme** [comment]
> Hi everyone
> I review code in engine/gamma . Most of the process time of search request in function scan_one_list (gamma_index_ivfpq.cc)
> 
> ```
> for (size_t ik = 0; ik < nprobe; ik++) {
>         nscan += scan_one_list (
>             scanner, keys [i * nprobe + ik], coarse_dis[i * nprobe + ik], 
>             simi, idxi, k, this->nlist, this->invlists, store_pairs, 
>             condition->ivf_flat, raw_vec_head);
> 
>         if (max_codes && nscan >= max_codes) {
>           break;
>         }
>       }
> ```
> 
> > [scan_one_list] sys: 219ms
> 
> It used method scan_list_with_table (gamma_index_ivfpq.h).

@phamthanhtri  This is the problem. If you set parallel=false, it should enter this line("parallelize over inverted lists") https://github.com/vearch/gamma/blob/f0def6f43117766a2fcf08765a970d4e12d5a666/index/gamma_index_ivfpq.cc#L888, not https://github.com/vearch/gamma/blob/f0def6f43117766a2fcf08765a970d4e12d5a666/index/gamma_index_ivfpq.cc#L863.

Please confirm it !

**Comment by qiutianme** [comment]
@phamthanhtri  Just for test,  you can force set condition->parallel_mode=1 in this line https://github.com/vearch/gamma/blob/f0def6f43117766a2fcf08765a970d4e12d5a666/index/gamma_index_ivfpq.cc#L714

**Comment by phamthanhtri** [comment]
Hi @qiutianme  
I test 2 case with parallel=false and parallel=true. It process same the time . 

I think the problem comes from the code  . 
 ```
 nscan += scan_one_list (
            scanner, keys [i * nprobe + ik], coarse_dis[i * nprobe + ik], 
            simi, idxi, k, this->nlist, this->invlists, store_pairs, 
            condition->ivf_flat, raw_vec_head);
```

 >timer.h:65 [scan_codes] sys: 14ms, cpu: 0s.
> timer.h:65 [scan_one_list] sys: 219ms, cpu: 0s.


I measured the time of function  **scan_one_list ,  scan_codes** and I think it was not running in parallel (openMP is not effective?) . Probably the reason I built faiss and vearch with gcc7.3 but blas in system centOS  has install a version of gcc4.8 . I am looking into this problem ?

**Comment by qiutianme** [comment]
@phamthanhtri  You can use "top" command to look at the cpu usage of v3.1.0. if cpu usage is low, then openMP is most likely the problem.

**Comment by phamthanhtri** [comment]
Hi everyone 

I resolved this problem. There are some things to share
1: As zcdb 's advice  , vearch v3.0.1 search base parallelize over queries . But when I change param "parallel" =  (False or True)  on request search , it not change value of **condition->parallel_based_on_query** . It always has value  =1  . 
This is search param request 
```
       data = {"query": {"sum": [{"feature": feat, "field": "feature"}], "parallel": False}}
       res = requests.post(query_internal_url, headers=header, data=json.dumps(data))

```
I changed value  condition->parallel_mode=1 for enter this line("parallelize over inverted lists")  

2:  It not start flag -fopenmp in cmake file configure , I must add it for build source with openmp.  And with line code  when enter 
https://github.com/vearch/gamma/blob/f0def6f43117766a2fcf08765a970d4e12d5a666/index/gamma_index_ivfpq.cc#L838  . It crash PS server  

> Error in `./vearch': malloc(): memory corruption (fast): 0x00007ed5b4000b00 ***
> *** Error in `./vearch': free(): invalid next size (fast): 0x00007ed5b4000a40 ***

I fix it by add #pragma omp parallel before this line https://github.com/vearch/gamma/blob/f0def6f43117766a2fcf08765a970d4e12d5a666/index/gamma_index_ivfpq.cc#L837 

3.  I show result benchmark after change and run successfully:

- 70 million items: 40ms  (v0.3.1 no opemp - 200ms)  (v0.2 - 60ms) 

- 230 million items: 120ms (v0.3.1  no opemp - 700ms)

**Comment by zcdb** [comment]
@phamthanhtri I experimented on v3.1.0 to change the parallel mode by setting parallel, and found that it can take effect. So I rechecked your query statement. It should be like this {"query":{}, "parallel":false} to set parallel mode. 
here is yours:
data = {"query": {"sum": [{"feature": feat, "field": "feature"}], "parallel": False}}
it should be:
data = {"query": {"sum": [{"feature": feat, "field": "feature"}]}, "parallel": False}

Sorry for it, we should check it more carefully.
