### ISSUE TITLE
在vearch主目录中找不到plugin文件夹啊

### ISSUE THREAD

**Issue by hongchenxu01** [vearch/vearch#195]

**Comment by gDreamcatcher** [comment]
你好， 我们目前把plugin移出到一个单独的仓库了 [plugin](https://github.com/vearch/python-algorithm-plugin)

**Comment by hongchenxu01** [comment]
怎么引入呢，直接在vearch主目录里gitclone吗

**Comment by hongchenxu01** [comment]
> 你好， 我们目前把plugin移出到一个单独的仓库了 [plugin](https://github.com/vearch/python-algorithm-plugin)

怎么引入呢，直接在vearch主目录里gitclone吗

**Comment by gDreamcatcher** [comment]
你好， 可以在任何地方clone这个仓库，plugin和vearch之间是通过网络交互的，具体使用方法可以参考[README](https://github.com/vearch/python-algorithm-plugin/blob/master/README.md)

**Comment by hongchenxu01** [comment]
> 你好， 可以在任何地方clone这个仓库，plugin和vearch之间是通过网络交互的，具体使用方法可以参考[README](https://github.com/vearch/python-algorithm-plugin/blob/master/README.md)

有没有对文本进行处理的案例呢？能不能帮忙写一个案例

**Comment by gDreamcatcher** [comment]
你好，文本处理方式和图像是一样的，启动的时候指定启动方式为text就可以了，例如readme中写的`./bin/run.sh text`, 然后在插入数据的时候将存放特征的字段的值换成文本，具体可以参考readme中提供的插入图片的例子。我们提供的文本提取特征的方法只是一个Demo，建议您在正式使用前更改插件中默认的模型。
