### ISSUE TITLE
插入文本时，返回的状态时201

### ISSUE THREAD

**Issue by hongchenxu01** [vearch/vearch#198]
创建表的参数是：
{ "name": "test",
"dynamic_schema": "strict", "partition_num": 2, "replica_num": 1, "engine":
{"name":"gamma","index_size":10000,	"retrieval_type": "IVFPQ", "retrieval_param": {"metric_type": "InnerProduct","ncentroids": -1,"nsubvector": -1}}, "properties": { "content": { "type": "keyword", "index":true}, "feature1": { "type": "vector", "dimension":768, "format": "normalization"}}}
插入文本的参数是：
{ "content": "你好嘛", "feature1":{"feature":"你好嘛"}}

执行插入文本后返回：
{"_index":"text_test","_type":"test","_id":"001test","status":201,"_shards":{"total":0,"successful":1,"failed":0},"result":"created","_seq_no":1,"_primary_term":1}

在plugin的model里用的是这个模型：
chinese_L-12_H-768_A-12

**Comment by gDreamcatcher** [comment]
你好， 201是插入成功的返回码

**Comment by hongchenxu01** [comment]
> 你好， 201是插入成功的返回码

可是查询到数据啊
http://121.36.42.3:4101/text_test/test/001test
查不到数据

**Comment by gDreamcatcher** [comment]
你好， 为方便排查问题，麻烦提供一下查询的语句和返回的结果以及程序的日志。 程序如果是后台运行的话，输出会打印在nohup.out文件里

**Comment by hongchenxu01** [comment]
> 你好， 为方便排查问题，麻烦提供一下查询的语句和返回的结果以及程序的日志。 程序如果是后台运行的话，输出会打印在nohup.out文件里

好了，谢谢

**Comment by allforyou2016** [comment]
您好，我也遇到了这个问题，请问您是怎么解决的呢？
