### ISSUE TITLE
api有安全认证嘛

### ISSUE THREAD

**Issue by hongchenxu01** [vearch/vearch#199]

**Comment by gDreamcatcher** [comment]
你好，可以通过配置文件中 [skip_auth](https://github.com/vearch/vearch/blob/ffa651cd884b58e82421a0c13b6ce3702083d559/config/config.toml.example#L13)参数配置是否在创建和删除库表的使用权限认证, 认证时的账号是root，密码在配置文件中设置[signkey = "secret"](https://github.com/vearch/vearch/blob/ffa651cd884b58e82421a0c13b6ce3702083d559/config/config.toml.example#L11) , space中数据的增删改查目前是没有权限认证的。

**Comment by rosickyyu** [comment]
@gDreamcatcher 你好能给例子吗？
[global]
    name = "cbdb"
    data = ["datas/"]
    log = "logs/"
    level = "info"
    signkey = "secret"
    skip_auth = true

# if you are master, you'd better set all config for router、ps and router, ps use default config it so cool
[[masters]]
    name = "m3"
    address = "172.31.96.173"
    api_port = 18818
    etcd_port = 12379
    etcd_peer_port = 12391
    etcd_client_port = 12371
[[masters]]
    name = "m4"
    address = "172.31.98.11"
    api_port = 18818
    etcd_port = 12379
    etcd_peer_port = 12391
    etcd_client_port = 12371
[router]
    port = 19002
    skip_auth = true
[ps]
    rpc_port = 18082
    raft_heartbeat_port = 18899
    raft_replicate_port = 18900
    heartbeat-interval = 200 #ms
    raft_retain_logs = 10000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1
这样设置没有作用啊 我创建库表的时候没有提示需要账户密码

**Comment by NLPOR** [comment]
skip_auth改为false后在哪里进行认证啊，请求的时候直接返回error code 585
