### ISSUE TITLE
正排数据存储问题

### ISSUE THREAD

**Issue by macworld** [vearch/vearch#213]
我从  [Profile详细设计](https://github.com/vearch/vearch/wiki/Profile%E8%AF%A6%E7%BB%86%E8%AE%BE%E8%AE%A1) 了解到了vearch 正排存储设计，有些疑问想请教一下：

1. 我理解的vearch正排是放在内存中的，只有 update/dump 时会 更新/转存 到rocksdb里，不知道这块理解是否有误？
2. 一些应用场景下正排数据量较大,比如一个 doc 占用10KB，1亿doc大约900GB空间，这种情况把正排全部放入内存成本太高，请问该如何解决呢？

谢谢！

**Comment by wxingda** [comment]
1. 你的理解是正确的，现在的版本在add的时候没有同步到rocksdb里，下个版本会修复该问题
2. 下个版本会对变长字段进行压缩，在一定程度上能缓解内存占用太高的问题

**Comment by macworld** [comment]
感谢解答！还有个问题想请教：如果直接把正排放入 rocksdb 进行读取是否可行呢？

**Comment by wxingda** [comment]
可行，不过读取正排的速度会慢，取决于rocksdb配置的缓存大小和硬盘的速度

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by ljeagle** [comment]
rocksdb本身是kv，不是table结构，当然也可以用rocksdb存了。测试过，在压力大情况下，性能有一倍的损耗，所以这块实现没有用rocksdb。正排持久化的开发在计划中。

**Comment by macworld** [comment]
明白了，非常感谢！ @wxingda @ljeagle
