### ISSUE TITLE
我在使用IVFPQ模型时发现一个奇怪的问题，就是数据刚全部插入后，马上第一次检索，top10召回率非常高，但是过1-2小时后再次检索结果确变了

### ISSUE THREAD

**Issue by rosickyyu** [vearch/vearch#214]
我试了10几次 每次都是数据插入后 马上检索 这一次的结果召回率很高 近乎99%以上
但是间隔一段时间后，即使任何操作都没有，不管多少次检索，结果跟第一次结果相差很大，很多结果不能召回

curl -XPUT -H "content-type: application/json" -d'
{
    "name": "candidate_ht",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 1000000,
        "id_type": "String","retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 256,
            "nsubvector": 32,"nbits_per_idx":8
        }
    },
    "properties": {
        "user_id": {
            "type": "keyword",
                "index": true
        },
        "month": {
            "type": "keyword"
        },"subject": {
            "type": "keyword",
                "index": true
        },"grade": {
            "type": "keyword",
                "index": true
        },
        "avg_score": {
            "type": "float",
                "index": true
        },
        "ht": {
            "type": "vector",
            "dimension": 1024,
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 40000
            }
        }
    }
}
' http://172.31.96.173:8817/space/user_ht_test/_create

查询语句
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {"sum": [{"field": "ht", "feature": [0.005695, 0.007545, 0.014753, 0.011556, 0.059812, 0.009849, 0.036239, 0.025397, 0.012537, 0.029483, 0.015654, 0.04039, 0.060255, 0.051842, 0.015053, 0.013754, 0.027751, 0.003993, 0.038234, 0.011636, 0.030062, 0.018987, 0.047035, 0.036421, 0.021923, 0.009723, 0.006801, 0.032957, 0.046675, 0.02386, 0.020044, 0.027349, 0.026236, 0.024781, 0.007265, 0.009398, 0.006274, 0.004923, 0.009969, 0.03624, 0.023251, 0.055774, 0.015617, 0.040569, 0.058042, 0.005501, 0.053822, 0.05523, 0.031714, 0.044624, 0.02675, 0.055584, 0.01329, 0.027132, 0.017665, 0.015137, 0.060937, 0.00921, 0.008177, 0.016307, 0.052015, 0.031085, 0.003711, 0.050667, 0.044234, 0.031014, 0.032205, 0.001619, 0.024656, 0.017455, 0.031962, 0.032256, 0.023196, 0.010532, 0.021313, 0.008369, 0.021526, 0.010008, 0.019038, 0.008912, 0.026107, 0.025883, 0.044869, 0.034549, 0.037257, 0.038125, 0.043579, 0.014367, 0.019902, 0.039704, 0.034443, 0.053643, 0.037544, 0.031891, 0.004814, 0.033637, 0.017461, 0.0132, 0.027677, 0.007365, 0.013362, 0.008288, 0.035098, 0.031763, 0.040664, 0.024382, 0.023692, 0.061558, 0.050059, 0.037931, 0.015768, 0.007667, 0.05156, 0.034404, 0.029345, 0.010002, 0.028699, 0.006289, 0.044921, 0.016467, 0.020061, 0.021707, 0.00343, 0.00956, 0.043202, 0.031309, 0.04015, 0.018983, 0.031258, 0.018029, 0.056245, 0.025494, 0.019163, 0.042545, 0.011664, 0.02368, 0.040106, 0.010507, 0.028222, 0.03698, 0.019058, 0.00494, 0.013169, 0.002655, 0.049752, 0.031008, 0.015906, 0.019936, 0.028052, 0.048563, 0.01762, 0.043668, 0.050341, 0.053263, 0.052801, 0.011399, 0.007618, 0.038065, 0.039361, 0.017811, 0.020587, 0.045792, 0.000246, 0.03969, 0.022157, 0.010607, 0.044891, 0.033146, 0.010422, 0.042361, 0.016319, 0.007214, 0.038495, 0.043812, 0.037416, 0.019671, 0.020922, 0.013119, 0.039403, 0.036557, 0.019111, 0.043654, 0.025816, 0.025253, 0.048276, 0.023537, 0.024833, 0.00831, 0.009625, 0.029218, 0.00433, 0.058412, 0.014628, 0.037646, 0.043124, 0.008244, 0.013254, 0.04909, 0.050345, 0.019404, 0.004262, 0.037335, 0.017938, 0.0177, 0.011801, 0.008699, 0.049594, 0.02522, 0.024422, 0.03321, 0.019968, 0.051814, 0.052751, 0.035689, 0.035577, 0.030092, 0.025843, 0.015166, 0.043122, 0.019814, 0.037192, 0.002252, 0.025243, 0.041429, 0.00905, 0.022749, 0.046958, 0.035691, 0.008346, 0.048877, 0.00851, 0.04671, 0.012356, 0.019911, 0.022221, 0.026062, 0.011905, 0.038109, 0.006994, 0.034277, 0.019698, 0.00605, 0.01106, 0.028958, 0.052416, 0.029394, 0.020612, 0.059414, 0.002254, 0.01326, 0.023801, 0.012812, 0.012581, 0.004806, 0.031772, 0.032371, 0.05433, 0.030669, 0.057399, 0.014106, 0.03726, 0.008253, 0.039497, 0.019336, 0.002023, 0.046188, 0.01408, 0.006269, 0.031573, 0.041172, 0.002939, 0.013285, 0.019145, 0.03785, 0.036148, 0.048532, 0.006026, 0.034788, 0.040997, 0.038526, 0.020036, 0.011347, 0.02614, 0.054597, 0.020014, 0.059464, 0.01954, 0.042936, 0.046847, 0.031301, 0.021532, 0.04259, 0.043047, 0.017428, 0.017107, 0.052896, 0.054048, 0.042453, 0.011771, 0.029046, 0.02807, 0.029082, 0.056331, 0.029374, 0.017423, 0.041271, 0.003546, 0.008304, 0.057772, 0.046855, 0.003477, 0.009534, 0.003554, 0.026461, 0.023646, 0.014045, 0.011348, 0.023312, 0.018722, 0.006303, 0.049281, 0.046662, 0.020745, 0.053473, 0.015469, 0.046038, 0.040072, 0.038612, 0.009366, 0.01171, 0.037393, 0.01984, 0.010495, 0.011538, 0.007247, 0.039535, 0.048602, 0.052827, 0.026712, 0.019728, 0.030729, 0.017717, 0.007709, 0.016185, 0.003237, 0.009428, 0.029303, 0.02438, 0.02779, 0.033281, 0.036936, 0.009235, 0.003616, 0.040566, 0.043827, 0.028828, 0.016575, 0.005144, 0.013621, 0.013353, 0.023013, 0.011976, 0.03937, 0.041821, 0.014752, 0.004684, 0.047054, 0.057519, 0.011935, 0.019485, 0.00727, 0.039819, 0.017393, 0.022493, 0.016878, 0.031649, 0.026728, 0.004796, 0.052093, 0.026058, 0.014318, 0.010263, 0.046961, 0.011333, 0.044549, 0.023978, 0.051309, 0.047969, 0.042393, 0.019666, 0.013174, 0.029822, 0.028661, 0.021828, 0.050583, 0.016121, 0.022453, 0.024921, 0.016127, 0.054848, 0.006168, 0.043219, 0.022257, 0.043798, 0.025826, 0.013941, 0.024776, 0.027278, 0.013492, 0.020252, 0.012495, 0.027409, 0.05706, 0.043438, 0.028612, 0.032181, 0.017483, 0.050281, 0.015254, 0.003954, 0.041343, 0.017977, 0.041876, 0.029194, 0.030931, 0.025208, 0.010896, 0.013755, 0.015769, 0.021438, 0.007618, 0.013613, 0.011033, 0.008978, 0.008547, 0.059675, 0.01293, 0.012124, 0.008408, 0.028999, 0.018101, 0.023517, 0.020669, 0.02127, 0.009587, 0.052847, 0.018171, 0.03166, 0.041052, 0.023157, 0.053603, 0.011103, 0.026078, 0.008099, 0.027761, 0.009203, 0.005266, 0.047103, 0.04784, 0.04431, 0.006754, 0.036568, 0.011671, 0.048165, 0.036355, 0.051691, 0.028124, 0.042517, 0.035442, 0.018435, 0.041009, 0.003693, 0.031331, 0.005187, 0.023557, 0.04918, 0.011609, 0.045205, 0.00859, 0.045885, 0.004811, 0.011644, 0.013595, 0.01097, 0.021266, 0.027649, 0.030015, 0.014471, 0.008839, 0.011653, 0.028158, 0.009778, 0.005531, 0.04226, 0.02713, 0.028483, 0.030396, 0.022629, 0.009616, 0.014957, 0.055137, 0.026787, 0.040423, 0.002938, 0.038982, 0.039816, 0.047454, 0.029563, 0.046604, 0.020038, 0.05753, 0.025755, 0.009471, 0.007266, 0.049493, 0.008145, 0.044803, 0.045242, 0.043809, 0.011414, 0.005972, 0.01049, 0.032311, 0.024985, 0.028946, 0.046719, 0.01475, 0.037021, 0.017278, 0.042981, 0.019695, 0.019087, 0.042954, 0.025387, 0.054906, 0.020968, 0.028222, 0.035297, 0.050692, 0.012959, 0.006938, 0.021421, 0.019078, 0.037671, 0.036673, 0.045961, 0.06091, 0.015887, 0.049505, 0.040852, 0.039047, 0.039431, 0.034837, 0.031985, 0.035335, 0.024259, 0.01986, 0.026317, 0.015927, 0.027445, 0.004885, 0.043266, 0.022937, 0.051839, 0.007956, 0.054995, 0.015688, 0.011978, 0.048852, 0.010414, 0.027599, 0.048092, 0.039084, 0.010194, 0.048238, 0.017784, 0.019867, 0.061238, 0.007663, 0.041644, 0.008581, 0.051236, 0.02347, 0.052213, 0.023137, 0.013655, 0.033964, 0.017607, 0.021029, 0.022501, 0.012336, 0.042633, 0.060373, 0.046421, 0.037832, 0.003471, 0.017569, 0.019038, 0.021477, 0.016665, 0.018141, 0.012823, 0.017116, 0.031892, 0.042693, 0.005957, 0.046498, 0.024226, 0.025981, 0.036732, 0.050299, 0.014497, 0.048452, 0.053194, 0.010414, 0.014991, 0.039607, 0.003195, 0.038714, 0.029584, 0.038945, 0.039646, 0.026417, 0.033829, 0.029325, 0.051369, 0.020702, 0.03049, 0.017844, 0.039933, 0.018965, 0.039905, 0.024209, 0.002426, 0.00718, 0.036703, 0.029602, 0.02131, 0.059696, 0.009943, 0.032782, 0.010553, 0.037652, 0.035174, 0.038632, 0.010084, 0.00414, 0.002732, 0.003238, 0.036317, 0.062098, 0.035678, 0.017406, 0.003401, 0.012737, 0.010844, 0.003503, 0.017642, 0.037109, 0.021591, 0.040095, 0.014673, 0.014084, 0.017768, 0.052172, 0.024001, 0.033822, 0.026299, 0.026851, 0.019811, 0.050449, 0.045505, 0.046865, 0.048519, 0.014503, 0.021242, 0.008501, 0.002547, 0.022742, 0.01819, 0.012425, 0.042455, 0.023105, 0.043869, 0.056639, 0.009899, 0.038014, 0.021466, 0.031296, 0.061368, 0.03231, 0.011319, 0.023501, 0.001348, 0.042209, 0.009108, 0.015607, 0.027092, 0.014663, 0.020149, 0.039259, 0.011781, 0.037437, 0.044676, 0.01778, 0.019526, 0.01091, 0.057009, 0.026008, 0.057816, 0.023072, 0.024789, 0.016371, 0.034091, 0.030614, 0.011318, 0.017858, 0.018263, 0.021978, 0.018651, 0.047082, 0.029085, 0.048878, 0.056207, 0.038729, 0.005852, 0.017821, 0.020158, 0.02412, 0.013976, 0.008628, 0.033364, 0.0399, 0.008617, 0.042503, 0.022659, 0.032011, 0.050874, 0.046712, 0.052391, 0.040425, 0.031483, 0.028298, 0.006644, 0.045414, 0.00279, 0.044775, 0.018566, 0.040312, 0.020779, 0.029995, 0.033708, 0.018236, 0.057892, 0.005146, 0.023753, 0.05894, 0.016568, 0.019597, 0.055399, 0.015997, 0.028935, 0.025307, 0.029606, 0.013524, 0.041199, 0.052055, 0.020648, 0.017021, 0.032407, 0.023549, 0.030547, 0.031385, 0.051855, 0.018429, 0.006268, 0.053746, 0.030606, 0.04862, 0.051415, 0.0254, 0.030967, 0.051641, 0.053074, 0.047249, 0.02381, 0.007901, 0.018679, 0.00831, 0.020829, 0.049363, 0.023024, 0.025031, 0.017422, 0.007988, 0.030514, 0.008402, 0.023738, 0.00531, 0.03996, 0.027418, 0.020066, 0.033137, 0.060621, 0.025612, 0.047574, 0.049665, 0.0285, 0.019493, 0.024101, 0.018674, 0.033961, 0.036698, 0.030711, 0.005977, 0.011715, 0.006062, 0.01834, 0.012739, 0.037757, 0.035129, 0.060685, 0.030818, 0.018312, 0.050398, 0.024916, 0.01878, 0.006376, 0.041164, 0.001704, 0.031492, 0.059717, 0.019719, 0.03501, 0.029608, 0.019701, 0.035316, 0.041146, 0.013796, 0.005103, 0.008252, 0.030263, 0.052646, 0.017726, 0.028547, 0.050783, 0.013713, 0.047583, 0.008479, 0.013227, 0.026452, 0.032811, 0.002684, 0.004335, 0.019108, 0.052668, 0.032629, 0.039431, 0.037944, 0.018277, 0.002666, 0.023014, 0.032378, 0.040545, 0.011864, 0.039572, 0.042617, 0.029825, 0.059698, 0.015406, 0.027059, 0.042285, 0.043578, 0.028976, 0.019449, 0.022288, 0.012532, 0.023323, 0.026378, 0.021028, 0.058902, 0.005867, 0.013396, 0.012752, 0.023125, 0.010596, 0.042836, 0.030768, 0.019376, 0.030914, 0.005981, 0.026947, 0.035539, 0.053521, 0.021654, 0.023304, 0.03844, 0.01095, 0.02615, 0.005363, 0.022266, 0.052305, 0.008408, 0.046502, 0.053007, 0.011104, 0.00351, 0.002279, 0.007026, 0.01852, 0.011345, 0.044493, 0.049836, 0.003011, 0.045682, 0.015452, 0.03114, 0.012667, 0.051417, 0.030724, 0.020256, 0.044014, 0.051425, 0.056076, 0.025066, 0.020095, 0.021515, 0.045839, 0.010045, 0.051481, 0.020494, 0.010742, 0.025908, 0.018031, 0.016683, 0.049008, 0.034923, 0.01604, 0.020477, 0.012828, 0.01999, 0.015266, 0.053978, 0.01806, 0.013055, 0.020448, 0.011182, 0.003963, 0.009797, 0.046994, 0.012641, 0.025851, 0.015036, 0.056358, 0.017283, 0.027102, 0.008064, 0.045705, 0.056172, 0.01185, 0.006504, 0.019274, 0.003722, 0.009508, 0.033647, 0.056187, 0.034626, 0.04214, 0.047283, 0.004791, 0.024263, 0.009785, 0.022145, 0.038925, 0.021845, 0.00564, 0.044776, 0.014058, 0.041117, 0.037333, 0.020704, 0.021727, 0.044858, 0.028649, 0.012758, 0.018613, 0.047379, 0.018428, 0.022058, 0.022944, 0.051805, 0.041054, 0.038515, 0.011328, 0.016828, 0.046404, 0.005173, 0.006709, 0.003431, 0.039816, 0.023735, 0.007995, 0.013098, 0.021658, 0.018931, 0.025383, 0.030139, 0.030254, 0.037753, 0.038734, 0.043797, 0.008139, 0.014139, 0.032287, 0.026245, 0.050884, 0.037475, 0.028908, 0.009499, 0.051371, 0.023596, 0.01135, 0.021878, 0.055496],"boost": 1.0}], "filter": [{"range": {"avg_score": {"gte": 0.207, "lte": 0.407}}}]}
    ,
    "direct_search_type": 0,
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "size": 10
}
' http://172.31.96.173:9001/user_ht_test/candidate_ht/_search

**Comment by pallashadow** [comment]
我猜是插入后faiss会自动建立index，比如IVFPQ，是异步的。在faiss建立index之前会brute force search。所以结果不一样。
