### ISSUE TITLE
在大数据集上相较于hnsw召回率的提升

### ISSUE THREAD

**Issue by WaterElapse** [vearch/vearch#215]
我看到了介绍的ppt,在1M数据集上，基本持平，在10M上提升很明显，能好奇问下到底是什么优化带来的提升么？
不应该是分片这种，在通过提升到topk * n召回数量带来的提升吧？
非常好奇，独门绝技是什么，论文阅读中

**Comment by zcdb** [comment]
你好，召回率的提升，我们是在使用索引搜索出来的粗排结果后，会利用原始向量重新计算一下粗排的结果并重新排序来提升召回率。在Vearch的实际使用中，是可以通过参数来控制是否精排，如果需要速度更快就可以不进行精排，如果为了更高的召回就可以进行精排

**Comment by WaterElapse** [comment]
> 你好，召回率的提升，我们是在使用索引搜索出来的粗排结果后，会利用原始向量重新计算一下粗排的结果并重新排序来提升召回率。在Vearch的实际使用中，是可以通过参数来控制是否精排，如果需要速度更快就可以不进行精排，如果为了更高的召回就可以进行精排

那大概明白了，索引数据有压缩，例如pq，然后召回时扩召回，然后对召回数据还原进行排序？
看下了论文，你们好像用的kmeans做聚类，类似IMI或者IVF?

**Comment by zcdb** [comment]
召回的时候如果用户需要的返回topk条记录，会对这topK条结果利用原始数据重新排序。另外我们现在也集成了hnsw，现在ivfpq和hnsw都可以使用，分别针对不同的数据量场景，如果数据量较大可以使用ivfpq，单机数据量1000万级别的话可以使用hnsw
