### ISSUE TITLE
{"code":550,"msg":"create partition err: create gamma table has err:[4294967294] "}

### ISSUE THREAD

**Issue by DragonDriver** [vearch/vearch#216]
hello, i have problem when i'm trying to create space.

below shows how i create space:

```shell
curl -XPUT -H "content-type: application/json" -d'
{
"name": "test",
"partition_num": 1,
"replica_num": 1,
"engine": {
"name": "gamma",
"nprobe":200,
"ncentroids":512,
"metric_type":"L2",
"nsubvector":64
}
,
"properties": {
"field1":{
"type":"vector",
"index":true,
"dimension":128}
}
}
' http://172.16.0.251:443/space/test/_create
```

but i got the error response below:

```json
{"code":550,"msg":"create partition err: create gamma table has err:[4294967294] "}
```

**Comment by DragonDriver** [comment]
i noticed `max_size` was mentioned in [issue 34](https://github.com/vearch/vearch/issues/34)

so i changed the `max_size` to `10000` and even smaller, this error was still there

**Comment by DragonDriver** [comment]
below is the gamma.log:

INFO 2020-08-25 19:51:51,669 gamma_api.cc:285 Version []
INFO 2020-08-25 19:51:51,678 profile.cc:48 Profile created success!
INFO 2020-08-25 19:51:51,678 gamma_engine.cc:346 GammaEngine setup successed!
INFO 2020-08-25 19:51:51,678 gamma_api.cc:297 Engine init successed!
ERROR 2020-08-25 19:51:51,678 vector_manager.cc:75 NO support for retrieval type
INFO 2020-08-25 19:51:51,678 profile.cc:170 Add field name [_id], type [4], index [0]
INFO 2020-08-25 19:51:51,691 profile.cc:237 Create table 1 success!
ERROR 2020-08-25 19:51:51,691 gamma_engine.cc:642 Cannot create table!

**Comment by kevintony001** [comment]
lost of retrieval_type , such as :
{
"name": "test",
"partition_num": 1,
"replica_num": 1,
"engine": {
"name": "gamma",
"retrieval_type":"IVFPQ",
"retrieval_param": {"nprobe" : 200, "metric_type" : "L2", "ncentroids" : 512,"nsubvector" : 64}
}
,
"properties": {
"field1":{
"type":"vector",
"index":true,
"dimension":128}
}
}

Please refer to the doc:
https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md

**Comment by DragonDriver** [comment]
thank you very much, i notice i use the vearch 3.1.0 but refer to the https://www.bookstack.cn/read/vearch-zh/755979bdad55f339.md, i will have a try using the corresponding api.

by the way, https://www.bookstack.cn/books/vearch-zh is your official doc?

**Comment by DragonDriver** [comment]
after i insert data to space, should i explicitly use the `curl -XPOST {{ROUTER}}/test_vector_db/vector_space/_forcemerge` to create index?
