### ISSUE TITLE
数据存储因为NAN报错，无法重启

### ISSUE THREAD

**Issue by allensky708** [vearch/vearch#218]
因为数据写入向量时存在：NAN导致数据解析错误
1.数据解析错误会导致服务进程中断
2.服务无法重启，必须删除数据文件，服务重启报错:master server all down
现在使用版本0.3

**Comment by qiutianme** [comment]
提供下具体的错误日志吧，包括你说的NAN错误，数据解析错误。
另外可以用最新版试试，看还存在这个问题不
