### ISSUE TITLE
L2 metric_type score incorrect?

### ISSUE THREAD

**Issue by miner-realm** [vearch/vearch#240]
curl -H "Content-Type:application/json" -X POST http://xx.xx.xx.xx/vrouter-3-2/vearchDB/vearchSpace_20200914/_search -d '{"quick": false,"vector_value": true,"size": 80,"retrieval_param":{"nprobe":20, "metric_type": "L2"},"is_brute_search": 0, "query": {"sum": [{"symbol": ">=","field": "value","feature": [13.3089552, 4.68511629, 4.64321089, 0.0, 0.0, 2.18795, 4.85803509, 3.03833389, 3.23964047, 0.0, 4.54940557, 0.0, 0.0, 5.01291561, 0.0, 0.0, 0.0, 4.74395704, 9.0893116, 0.0, 0.0, 0.0, 2.12878156, 0.0, 13.0333548, 1.79197538, 0.0, 0.0, 6.23481941, 0.0, 0.0, 1.04360437, 0.0, 1.44835818, 7.46952, 2.1407938, 0.0, 10.6977396, 0.0,0.0, 0.0, 2.25952959, 5.57894897, 2.98033285, 0.0, 0.0, 0.0, 2.62263846, 0.0, 4.73520041, 11.7127171, 0.0, 0.55297327, 1.38830614, 0.0, 0.0, 0.0, 0.0, 7.867,0.0, 5.86622667, 0.0, 0.0, 0.0, 11.801981, 0.0, 0.0, 0.0, 1.00659823, 5.70555, 7.35319757, 0.0, 8.69684, 0.0, 0.0, 0.0, 5.84924698, 0.0, 0.0, 0.0, 0.466738343, 0.0, 2.57717371, 0.0, 0.0, 3.90497804, 0.0, 8.71214294, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.78698587, 2.7257185, 0.0, 2.69314265, 10.8274336, 0.0, 0.0, 0.0, 1.28584969, 5.02681828, 0.0, 0.0, 0.0, 0.0, 0.0, 7.77245331, 4.722579, 18.9409962, 0.0, 4.49876, 5.29604816, 0.0, 0.0, 2.88821888, 0.0, 1.11648035, 0.0, 5.54676342, 17.5859585, 1.00313616, 0.917058766, 0.0, 12.138648, 0.109771073, 4.03205585, 3.13251352, 0.0, 0.0, 1.74776936, 0.54055512, 0.869920254, 2.90018606,2.64420295, 0.0503847, 0.566327095, 0.0, 4.9374876, 0.315920413, 0.081443727, 0.360850066, 3.61562467, 0.0833658054, 2.22531295, 0.0, 2.43415451, 1.21502304,3.59983397, 0.0, 0.0, 7.20529318, 0.0, 5.37365341, 1.25034404, 3.73405933, 3.48362827, 0.0, 0.0251131058, 0.0, 0.0, 0.0, 3.22075629, 0.242929593, 2.08323717,0.0, 0.0, 1.85157669, 8.29734325, 0.0, 0.264032453, 3.68477225, 0.0, 1.34498632, 0.0, 0.0, 0.0, 0.0, 0.916933298, 2.79470944, 0.0, 3.93892598, 5.6294384, 0.0, 4.5852108, 0.15473032, 4.88345242, 0.0, 2.83953738, 3.00517559, 0.0, 3.50484872, 0.0, 0.0, 0.117293268, 0.0, 0.0675120875, 0.0, 0.835135341, 4.63764572, 0.0, 0.771308839, 0.0, 0.0, 0.0, 3.24916458, 1.87975574, 0.0, 2.19305849, 3.95279789, 0.196582869, 4.38463736, 0.0, 1.14921093, 3.60075951, 0.357498497, 0.0, 0.0, 5.96832037, 6.73957348, 1.60516262, 0.0, 0.548777103, 0.0, 6.28097057, 0.0, 0.0, 0.0, 0.0, 6.14882755, 0.0, 0.887346804, 0.62883693, 0.0, 5.20071, 0.0, 0.0,0.0, 0.787085176, 0.0, 0.0, 0.0, 0.0, 0.0, 1.51359224, 1.88065302, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.36320496, 1.372666, 0.0, 0.0, 2.40758038, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0437884033, 2.53042197, 0.0, 0.0, 0.94157207, 0.0, 1.87413621, 0.0, 3.1734724, 0.182574287, 2.49245048, 0.0, 5.06110382, 0.0, 0.0, 0.0, 0.0, 5.08087206, 1.7596612, 2.53151107, 0.0, 0.0, 0.0, 2.79349113, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.709453106, 1.21582437, 0.0, 0.104570538, 0.0, 0.0, 0.0, 0.0, 0.0774701834, 0.0, 0.883249044, 0.0, 0.403793424, 0.0, 7.04765034, 6.80505371, 0.0, 0.0, 0.0, 0.0, 1.24907184, 0.0, 0.0, 0.685068071, 0.0, 4.07068872, 0.0, 0.140663296, 0.0, 0.0, 0.0, 1.01264799, 2.88486457, 2.35475063, 0.0601108074, 4.53587866, 0.0, 3.2301209, 3.02423549, 0.0, 0.0, 0.902865231, 0.0, 3.37237215, 0.00956255198, 1.0]}]}}'

返回结果：
{"took":21,"timed_out":false,"_shards":{"total":9,"successful":9},"hits":{"total":80,"max_score":2.149703025817871,"hits":[{"_index":"vearchDB","_type":"vearchSpace_20200914","_id":"1916606302",**"_score":1.8286088705062866**,"_extra":{"vector_result":[{"field":"value","source":"","score":1.828609}]},"_source":{"key":"1916606302","time":20200917,"value":{"feature":[0.04402951,0.0024996544,0.011972291,0.0043093185,0.0055275178,-0.0036644114,0.0008044664,0.00067226484,0.03579772,0.0664212,0.012069554,-0.016872434,-0.015667502,0.018566497,0.014692974,0.05053289,-0.004444707,-0.00022801833,0.017530605,0.093725495,0.021966137,-0.01897207,0.007769068,0.015918903,0.023893235,0.026115643,0.01159388,-0.00012395969,-0.017753482,-0.01982661,0.040943444,0.011484807,0.025254492,0.0044446276,0.04038853,-0.014407198,0.0017247144,0.0031326413,0.03936617,0.020474307,0.019837676,0.020084472,0.021428367,0.00433792,-0.0029326314,-0.007425117,-0.007513746,0.0069598947,-0.005633957,0.023254998,0.010313465,0.05319093,0.022256078,0.028973754,-0.009402951,0.044703472,0.02721414,0.01994474,0.017459257,0.011406979,-0.008493322,0.0013410536,-0.004995383,0.004541787,0.029265303,0.12036488,0.023876974,0.00041987302,0.009167278,0.025175225,0.022113226,0.025375072,0.016474258,0.036409236,0.05319412,0.007874699,0.017301977,0.006787362,0.009273373,0.03382374,0.014103902,0.045802012,0.04726051,0.019105487,-0.00559458,0.020615807,0.06925309,-0.0005352561,0.028179029,0.04691978,-0.016799832,0.0054949545,-0.012480695,0.06386778,0.022104083,0.012457918,-0.019781856,-0.012907499,0.0033191668,0.0057673478,0.00979282,0.037263796,0.01496912,0.0048747896,-0.005404679,0.04592267,0.014873307,-0.005536714,0.016407665,0.011090697,0.015478288,0.020787068,-0.010650714,0.115562335,0.025348412,0.017347718,0.011629603,0.028390579,-0.00004737844,0.029757293,-0.014867341,0.02883718,0.0029848465,0.033443056,-0.022291478,0.018000016,0.023272954,0.018038288,0.097810544,-0.0706664,0.35695225,0.15651782,-0.21915613,0.2063783,0.12089966,0.1770721,0.03805487,0.013078186,-0.06144517,-0.102767214,0.12332418,-0.10272873,-0.19213228,0.08684709,0.039916065,0.020284757,-0.0003821301,-0.02452944,0.000030143103,-0.015452311,-0.00023284084,0.05990545,-0.008034722,0.030624878,-0.0034194002,0.008587714,-0.015299848,0.012388477,0.041807976,-0.01629944,-0.010631999,0.018201951,0.013132574,-0.01995874,0.056070887,-0.00048848067,-0.021222336,0.012212439,0.015050841,-0.0044016233,0.017794082,0.008932396,0.050782382,-0.009085986,0.029959025,0.006846087,0.048543736,0.032306492,0.040037923,-0.01175004,-0.05114195,0.003970274,-0.008103876,-0.008986408,0.007634539,-0.0063617127,-0.017520072,0.0045547853,0.020788092,-0.0038032567,0.033000752,-0.005552937,0.015179396,0.025835764,-0.0055888197,0.008834307,0.009925076,0.05864393,-0.03665801,0.024826076,0.0059355116,0.0023931328,-0.021694975,-0.020056194,0.0008565417,0.00032769408,-0.021716902,0.027228821,0.017042855,0.015815565,0.04903786,-0.017449714,-0.0035831353,0.013432476,-0.0031230303,0.024436777,0.010123783,0.009980083,-0.017958311,0.051297616,0.050011937,0.06959698,-0.05345516,-0.01832098,0.0035671284,-0.01388824,0.0020027207,-0.017471265,0.019391583,0.0067781727,0.0063669467,-0.020907503,-0.0021759719,-0.009548326,0.0029976412,-0.013577179,-0.011551666,-0.009450754,-0.0032166666,0.0021313655,-0.028351614,0.08116493,-0.02450527,0.020879254,0.024768487,-0.029045487,-0.002349968,-0.08246203,0.09518333,-0.030662052,-0.10585889,0.054591767,0.041595966,0.03925761,-0.01192498,-0.009840893,-0.037413284,0.02960263,0.08987041,-0.00079317385,0.043220133,0.07766542,0.15777598,-0.018914282,0.013618014,-0.046069384,0.1136793,-0.054533586,0.013596031,0.016905705,0.008103211,-0.016635878,-0.00090809085,-0.003884352,0.025966482,-0.030059073,0.02540139,-0.032503784,0.10073865,-0.024603859,0.020805258,-0.013793889,-0.027398929,0.057594754,-0.00009161688,-0.0012816589,0.025924591,-0.056208268,-0.01779488,-0.06392974,0.028793855,0.045733936,-0.30702585,0.020489674,0.035016634,0.043502364,-0.029785,-0.026353847,-0.02268989,0.0012587693,-0.001261158,-0.053226843,0.05593786,-0.035220932,0.05005868,0.056561545,-0.0030655,-0.18836695,-0.028603999,-0.023816397,-0.05668098,0.0026642936,-0.08837203,-0.018601986,0.018192206,-0.005364527,-0.01740704,-0.016034143,0.00673648,-0.045131188,0.033134952,0.028930204,-0.3135352,0.06062068,-0.0103152245,0.04035727,0.079246655,0.003600454,-0.08282391,0.008621351,0.032434314,-0.028382557,0.03279581,0.046835013,-0.031865247,-0.028599832,0.026710462,-0.007458312,-0.110370815,0.06651456,0.0073569533,0.032429926],"source":""}}}

**Comment by miner-realm** [comment]
create space json:
{"name": "vearchSpace_20200914", "replica_num": 3, "partition_num": 9, "dynamic_schema": "strict", "engine": {"name": "gamma", "max_size": 1024000, "retrieval_type": "IVFPQ", "index_size": 50000}, "properties": {"key": {"type": "keyword", "index": true}, "time": {"type": "integer", "index": true}, "value": {"type": "vector", "dimension": 384, "format": "normalization"}}}

vearch version: 3.2.0

**Comment by zcdb** [comment]
I found that the features you searched for are not normalized, so it is normal for the score to exceed 1. You can set to normalize when searching just like this:
