### ISSUE TITLE
【混合索引】IVF+HNSW+PQ

### ISSUE THREAD

**Issue by matadorhong** [vearch/vearch#245]
请问下，是否有计划支持如下的混合索引：IVF+HNSW+PQ

**Comment by zcdb** [comment]
这个已经在开发中了，包括OPQ+IVF_HNSW+PQ也在开发计划中

**Comment by xiaming9880** [comment]
预计什么时候特性可以上线发布，可以使用？

**Comment by matadorhong** [comment]
在哪个版本上线？啥时候的版本？@zcdb

**Comment by zcdb** [comment]
在接下来要发布的新版本中会包含此特性，新版本暂时还未确定发布日期，如果确认了我会告知的

**Comment by zcdb** [comment]
@matadorhong @xiaming9880 新版本已经发布，此功能可以参考 https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md 中ivfpq部分来使用
