### ISSUE TITLE
Questions about gpu support

### ISSUE THREAD

**Issue by ABNER-1** [vearch/vearch#252]
Hello. Thanks for the great project.
I'm building the gpu version vearch 3.2.0 with faiss commit_id 2a36d4d and 33d417db1. I built vearch successfully. 

However, I got errors when I use gpu index which is "gpu index not indexed!" after creating index manually.

I built binary with cuda 10.0 and 10.2, but both failed. My gpu is 1660.
How can I do for using gpu ivfpq?

Looking forward for your advice.

**Comment by wxingda** [comment]
Could you give me the gamma.log and vearch-startup.log ?

**Comment by ABNER-1** [comment]
Thanks for your reply.

I was debuging the gamma. I found that this error caused by creating index not completed when I got response success=1.

So, I wait for the index process going on.
However, I got another error.

These two logs are below:

[gamma.log](https://github.com/vearch/vearch/files/5291475/gamma.log)
[startup.log](https://github.com/vearch/vearch/files/5291482/startup.log)

**Comment by wxingda** [comment]
Please provide hardware information

**Comment by ABNER-1** [comment]
gpu : | NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
cpu: 12  Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
32G memory

**Comment by ABNER-1** [comment]
Maybe these simple logs are better for you to debug than before.

[startup.log](https://github.com/vearch/vearch/files/5291847/startup.log)
[gamma.log](https://github.com/vearch/vearch/files/5291849/gamma.log)

**Comment by wxingda** [comment]
How many doc are inserted？

**Comment by ABNER-1** [comment]
10000 vectors

**Comment by wxingda** [comment]
I'm very sorry for the trouble. There's a bug in `gamma_engine.cc`, please change line `gamma_engine.cc:965` from
```
int field_num = table_->FieldsNum();
for (int i = 0; i < max_docid_; ++i) {
    for (int j = 0; j < field_num; ++j) {
      field_range_index_->Add(i, j);
    }
  }
```
to
```
#ifndef BUILD_GPU
int field_num = table_->FieldsNum();
for (int i = 0; i < max_docid_; ++i) {
    for (int j = 0; j < field_num; ++j) {
      field_range_index_->Add(i, j);
    }
  }
#endif
```
and rebuild gamma

**Comment by ABNER-1** [comment]
Thank you very much. 
I think not only this error occurs. 
I fix this bug, rebuild and rerun my code. However, the same error occurs.

With my log info, I found that the gamma crashed before this code.


[startup.log](https://github.com/vearch/vearch/files/5296045/startup.log)
[gamma.log](https://github.com/vearch/vearch/files/5296046/gamma.log)

PS: Do you have some tricks about debuging with c code in cgo? My debug method is so ineffiective.

**Comment by wxingda** [comment]
You can rebuild gamma with `cmake -DCMAKE_BUILD_TYPE=Debug`, then startup vearch by `gdb vearch`.
Input `(gdb) set args -conf <config path>/config.toml <start type>` and `(gdb) run`.
