### ISSUE TITLE
Question about async create index interface

### ISSUE THREAD

**Issue by ABNER-1** [vearch/vearch#254]
Thanks for the great project.

I noticed that vearch need to be indexed after insert data using '_forcemerge' interface.
However, I found that is an async interface. So, when I get success code from this url, I get low recall result with HNSW and empty result with gpu IVF-PQ / cpu IVF-Flat.

I try to look for something about this in documents, but I failed.
How can I do to know when the indexing is successfully done?

**Comment by pallashadow** [comment]
Agree. I spend a day to figure out the '_forcemerge' is async. 
I am using vearch v3.1.0. This might work: 
```
response = requests.get("http://" + ip_db + "/_cluster/stats")
index_status = json.loads(response.text)[0]["spaces"][0]["partitions"][0]["index_status"]
```
when indexing is over. index_status==2.

**Comment by ABNER-1** [comment]
Thank you. I will have a try.

However, I think an interface about that maybe better.
