### ISSUE TITLE
how to insert document after IVFPQ build index?

### ISSUE THREAD

**Issue by pallashadow** [vearch/vearch#255]
How to insert documents after IVFPQ index has been built?
When using faiss, I can insert additional features, even they are not trained by IVFPQ index. 

`index = faiss.index_factory(d, "IVF{}, PQ{}x8".format(nlist, m))`
`index.train(feature1)`
`index.add(feature1)`
`index.add(feature2) # additional feature not trained`

But how can I do it in vearch? It seems new documents inserted after "_forcemerge" is called, would be ignored.

**Comment by pallashadow** [comment]
When "_forcemerge" the 2nd time. gamma.log shows: 

INFO 2020-10-06 20:15:25,233 gamma_index_ivfpq.cc:149 gamma ivfpq index is already trained, skip indexing

**Comment by pallashadow** [comment]
Sorry, it is my fault. Before I call "_search", I should wait for the insertion operation to synchronize.

**Comment by pallashadow** [comment]
It still not work on "GPU" mode. I cannot search the features which is inserted after "_forcemerge" is called, on GPU mode.

**Comment by wxingda** [comment]
I'm sorry there is a bug in "_forcemerge", it will be fixed in next version.
