### ISSUE TITLE
Question about different query param leads to same recall

### ISSUE THREAD

**Issue by ABNER-1** [vearch/vearch#256]
I have trained data with ivfflat mode. 
However, I got the same recall with different search param 'nprobe'.

For example, I trained the mode with 'ncentroids' 8196. The result recalls of 'nprobe' value 1\100\1024\4096 are the same answer.

This is amazing and confusing.
My payload is below.
```python
    payload = {
            "query": {
                "sum": [{
                    "field": self._field,
                    "feature": features,
                }]
            },
            "size": n,
            "sort": [{
                "_score": {"order": "asc"}
            }],
            "retrieval_params": {
                "parallel_on_queries": 0,
                "nprobe": self._nprobe,
                "metric_type": "L2"
            }
        }
```

**Comment by Missqinxiaoer** [comment]
"retrieval_params" should be "retrieval_param", you can see https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md

**Comment by ABNER-1** [comment]
Thanks for your help. It helps.
