### ISSUE TITLE
How to search on properties?

### ISSUE THREAD

**Issue by pallashadow** [vearch/vearch#258]
If I would like to remove the features whose "string_tags" is ["0","0","1"], how can I get the "id_" without querying it with a filter?

**Comment by pallashadow** [comment]
Is it possible to search rocksdb directly?

**Comment by wxingda** [comment]
> If I would like to remove the features whose "string_tags" is ["0","0","1"], how can I get the "id_" without querying it with a filter?

你的意思是如何通过string_tags查找到符合条件的doc的_id吧？

**Comment by pallashadow** [comment]
是的呀

**Comment by wxingda** [comment]
暂时还没有这个功能，主要是返回的结果数可能很大

**Comment by pallashadow** [comment]
好的，谢谢
