### ISSUE TITLE
Question about index size

### ISSUE THREAD

**Issue by ABNER-1** [vearch/vearch#259]
Can I know my index size when I have built index in vearch?

**Comment by gyd2019** [comment]
Does  "index size" refer to the memory occupied by the index, or the number of indexes that have been constructed?

**Comment by ABNER-1** [comment]
I want to know the previous one.

**Comment by zcdb** [comment]
This function is not fully implemented, only some indexes have realized the statistics of memory usage。
You can check for details 
 https://github.com/vearch/gamma/blob/d56163b77dff553a2fe2795cfee21b0a8e75c1b9/search/gamma_engine.cc at line 915
