### ISSUE TITLE
ps服务进程异常退出

### ISSUE THREAD

**Issue by miner-realm** [vearch/vearch#267]
vearch 版本，3.2.0
现象：在查询时，新建space并插入， ps进程退出

**Comment by miner-realm** [comment]
2020/11/04 02:00:33 server.go:358: INFO : client has closed this connection: 10.19.28.91:40002
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f7a87fdd000 pc=0x7f7d8b792a20]

runtime stack:
runtime.throw(0x1601286, 0x2a)
        /env/app/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /env/app/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 3985337 [syscall]:
runtime.cgocall(0x127f0d0, 0xc000a33378, 0x40e600)
        /env/app/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000a33348 sp=0xc000a33310 pc=0x40536b
github.com/vearch/vearch/ps/engine/gamma._Cfunc_Search(0x7f493483bd20, 0xc0002bc1b8, 0x648, 0xc0009d2018, 0xc0001925d0, 0xc000000000)
        _cgo_gotypes.go:218 +0x4d fp=0xc000a33378 sp=0xc000a33348 pc=0x10988ed
github.com/vearch/vearch/ps/engine/gamma.Search.func1(0x7f493483bd20, 0xc0002bc1b8, 0x648, 0x8c8, 0xc0009d2018, 0xc0001925d0, 0x4bcf36)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gamma/gamma.go:120 +0xba fp=0xc000a333b8 sp=0xc000a33378 pc=0x1099a5a
github.com/vearch/vearch/ps/engine/gamma.Search(0x7f493483bd20, 0xc0002bc1b8, 0x648, 0x8c8, 0x0, 0x0, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gamma/gamma.go:120 +0xb3 fp=0xc000a33418 sp=0xc000a333b8 pc=0x1099053
github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search(0xc007e6c480, 0x1865fe0, 0xc000ae3f40, 0xc0002a4000, 0xc000aa6280, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:147 +0x1af fp=0xc000a33590 sp=0xc000a33418 pc=0x123f52f
github.com/vearch/vearch/ps/storage/raftstore.(*Store).Search(0xc0054c06c0, 0x1865fe0, 0xc000ae3f40, 0xc0002a4000, 0xc000aa6280, 0x40e7e8, 0x80)
        /env/app/go/src/github.com/vearch/vearch/ps/storage/raftstore/store_read.go:82 +0xfe fp=0xc000a335e8 sp=0xc000a33590 pc=0x123571e
github.com/vearch/vearch/ps.search(0x1865fe0, 0xc000ae3f40, 0x188d160, 0xc0054c06c0, 0xc0002a4000, 0xc000aa6280)
        /env/app/go/src/github.com/vearch/vearch/ps/handler_document.go:233 +0x63 fp=0xc000a33648 sp=0xc000a335e8 pc=0x1247963
github.com/vearch/vearch/ps.(*UnaryHandler).Execute(0xc00018a0f8, 0x1865fe0, 0xc000ae3f40, 0xc000b64000, 0xc000b64240, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/handler_document.go:134 +0xad2 fp=0xc000a33760 sp=0xc000a33648 pc=0x1246d52
github.com/vearch/vearch/util/server/rpc/handler.(*Chain).Execute(0xc000364e00, 0x1865fe0, 0xc000ae3f40, 0xc000b64000, 0xc000b64240, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/util/server/rpc/handler/chain.go:63 +0xe2 fp=0xc000a337b8 sp=0xc000a33760 pc=0x117cff2
runtime.call64(0xc000aca750, 0xc00018a118, 0xc000365280, 0x2800000038)
        /env/app/go/src/runtime/asm_amd64.s:520 +0x3b fp=0xc000a33808 sp=0xc000a337b8 pc=0x45d77b
reflect.Value.call(0xc000aa6080, 0xc00018a118, 0x13, 0x15ca178, 0x4, 0xc000a33ae8, 0x4, 0x4, 0xc000a33aa0, 0x28, ...)
        /env/app/go/src/reflect/value.go:447 +0x461 fp=0xc000a33a28 sp=0xc000a33808 pc=0x48c131
reflect.Value.Call(0xc000aa6080, 0xc00018a118, 0x13, 0xc000a33ae8, 0x4, 0x4, 0xc000a33ba8, 0x115dfd4, 0x1537340)
        /env/app/go/src/reflect/value.go:308 +0xa4 fp=0xc000a33a90 sp=0xc000a33a28 pc=0x48bbb4
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*service).call(0xc0069c2230, 0x1865fe0, 0xc000ae3f40, 0xc000aa6100, 0x1537340, 0xc000b64000, 0x16, 0x1537340, 0xc000b64240, 0x16, ...)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/service.go:361 +0x215 fp=0xc000a33b58 sp=0xc000a33a90 pc=0x115db25
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc0000300e0, 0x1865fe0, 0xc000ae3f40, 0xc000a0e9c0, 0x0, 0x0, 0xc00ea34e60)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:529 +0x98c fp=0xc000a33d80 sp=0xc000a33b58 pc=0x1157d5c
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc0000300e0, 0xc000a0e9c0, 0x187e640, 0xc0001b4460, 0xc000ae3f40)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:414 +0x1e8 fp=0xc000a33fb8 sp=0xc000a33d80 pc=0x115ea48
runtime.goexit()
        /env/app/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000a33fc0 sp=0xc000a33fb8 pc=0x45f411
created by github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:396 +0x713

**Comment by miner-realm** [comment]
`2020/11/04 02:00:33 server.go:358: INFO : client has closed this connection: 10.19.28.91:40002
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f7a87fdd000 pc=0x7f7d8b792a20]

runtime stack:
runtime.throw(0x1601286, 0x2a)
        /env/app/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /env/app/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 3985337 [syscall]:
runtime.cgocall(0x127f0d0, 0xc000a33378, 0x40e600)
        /env/app/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000a33348 sp=0xc000a33310 pc=0x40536b
github.com/vearch/vearch/ps/engine/gamma._Cfunc_Search(0x7f493483bd20, 0xc0002bc1b8, 0x648, 0xc0009d2018, 0xc0001925d0, 0xc000000000)
        _cgo_gotypes.go:218 +0x4d fp=0xc000a33378 sp=0xc000a33348 pc=0x10988ed
github.com/vearch/vearch/ps/engine/gamma.Search.func1(0x7f493483bd20, 0xc0002bc1b8, 0x648, 0x8c8, 0xc0009d2018, 0xc0001925d0, 0x4bcf36)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gamma/gamma.go:120 +0xba fp=0xc000a333b8 sp=0xc000a33378 pc=0x1099a5a
github.com/vearch/vearch/ps/engine/gamma.Search(0x7f493483bd20, 0xc0002bc1b8, 0x648, 0x8c8, 0x0, 0x0, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gamma/gamma.go:120 +0xb3 fp=0xc000a33418 sp=0xc000a333b8 pc=0x1099053
github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search(0xc007e6c480, 0x1865fe0, 0xc000ae3f40, 0xc0002a4000, 0xc000aa6280, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:147 +0x1af fp=0xc000a33590 sp=0xc000a33418 pc=0x123f52f
github.com/vearch/vearch/ps/storage/raftstore.(*Store).Search(0xc0054c06c0, 0x1865fe0, 0xc000ae3f40, 0xc0002a4000, 0xc000aa6280, 0x40e7e8, 0x80)
        /env/app/go/src/github.com/vearch/vearch/ps/storage/raftstore/store_read.go:82 +0xfe fp=0xc000a335e8 sp=0xc000a33590 pc=0x123571e
github.com/vearch/vearch/ps.search(0x1865fe0, 0xc000ae3f40, 0x188d160, 0xc0054c06c0, 0xc0002a4000, 0xc000aa6280)
        /env/app/go/src/github.com/vearch/vearch/ps/handler_document.go:233 +0x63 fp=0xc000a33648 sp=0xc000a335e8 pc=0x1247963
github.com/vearch/vearch/ps.(*UnaryHandler).Execute(0xc00018a0f8, 0x1865fe0, 0xc000ae3f40, 0xc000b64000, 0xc000b64240, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/ps/handler_document.go:134 +0xad2 fp=0xc000a33760 sp=0xc000a33648 pc=0x1246d52
github.com/vearch/vearch/util/server/rpc/handler.(*Chain).Execute(0xc000364e00, 0x1865fe0, 0xc000ae3f40, 0xc000b64000, 0xc000b64240, 0x0, 0x0)
        /env/app/go/src/github.com/vearch/vearch/util/server/rpc/handler/chain.go:63 +0xe2 fp=0xc000a337b8 sp=0xc000a33760 pc=0x117cff2
runtime.call64(0xc000aca750, 0xc00018a118, 0xc000365280, 0x2800000038)
        /env/app/go/src/runtime/asm_amd64.s:520 +0x3b fp=0xc000a33808 sp=0xc000a337b8 pc=0x45d77b
reflect.Value.call(0xc000aa6080, 0xc00018a118, 0x13, 0x15ca178, 0x4, 0xc000a33ae8, 0x4, 0x4, 0xc000a33aa0, 0x28, ...)
        /env/app/go/src/reflect/value.go:447 +0x461 fp=0xc000a33a28 sp=0xc000a33808 pc=0x48c131
reflect.Value.Call(0xc000aa6080, 0xc00018a118, 0x13, 0xc000a33ae8, 0x4, 0x4, 0xc000a33ba8, 0x115dfd4, 0x1537340)
        /env/app/go/src/reflect/value.go:308 +0xa4 fp=0xc000a33a90 sp=0xc000a33a28 pc=0x48bbb4
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*service).call(0xc0069c2230, 0x1865fe0, 0xc000ae3f40, 0xc000aa6100, 0x1537340, 0xc000b64000, 0x16, 0x1537340, 0xc000b64240, 0x16, ...)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/service.go:361 +0x215 fp=0xc000a33b58 sp=0xc000a33a90 pc=0x115db25
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc0000300e0, 0x1865fe0, 0xc000ae3f40, 0xc000a0e9c0, 0x0, 0x0, 0xc00ea34e60)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:529 +0x98c fp=0xc000a33d80 sp=0xc000a33b58 pc=0x1157d5c
github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc0000300e0, 0xc000a0e9c0, 0x187e640, 0xc0001b4460, 0xc000ae3f40)
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:414 +0x1e8 fp=0xc000a33fb8 sp=0xc000a33d80 pc=0x115ea48
runtime.goexit()
        /env/app/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000a33fc0 sp=0xc000a33fb8 pc=0x45f411
created by github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn
        /env/app/go/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:396 +0x713`

**Comment by jrvin** [comment]
关闭原因是啥呢？哪个版本解决了？
