### ISSUE TITLE
compile gamma 出错

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#270]
able_data.cc: In member function 'int tig_gamma::table::TableData::GetStr(tig_gamma::table::str_offset_t, tig_gamma::table::str_len_t, std::__cxx11::string&, tig_gamma::table::DecompressStr&)':
gopath/src/github.com/vearch/vearch/engine/table/table_data.cc:296:72: error: 'ZSTD_getDecompressedSize' was not declared in this scope
       auto de_size = ZSTD_getDecompressedSize(base_str, compressed_size);
已经配置好ZSTD仍然出错

**Comment by gyd2019** [comment]
https://github.com/facebook/rocksdb/blob/master/INSTALL.md可以参考RocksDB里面的zstd安装方式，添加环境变量。
