### ISSUE TITLE
关于文档“Deploy your own plugin service”部分

### ISSUE THREAD

**Issue by Valandilich** [vearch/vearch#273]
Modify parameters in src/config.py;
Execution script: For image, bash ./bin/run.sh image ; For video, bash ./bin/run.sh video; For text, bash ./bin/run.sh text ;

上述两个脚本的路径在哪里，服务节点和源码中都没有找到。

**Comment by gDreamcatcher** [comment]
https://github.com/vearch/python-algorithm-plugin
