### ISSUE TITLE
gamma编译失败

### ISSUE THREAD

**Issue by cml26** [vearch/vearch#275]
/usr/local/go/src/github.com/vearch_new/vearch/engine/table/table_data.cc:18:10: fatal error: zstd.h: No such file or directory
 #include <zstd.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gamma.dir/table/table_data.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....

/usr/local/go/src/github.com/vearch_new/vearch/engine/index/gamma_index_io.h:64:36: error: ‘DirectMap’ in namespace ‘faiss’ does not name a type
 void write_direct_map(const faiss::DirectMap *dm, faiss::IOWriter *f);
                                    ^~~~~~~~~
/usr/local/go/src/github.com/vearch_new/vearch/engine/index/gamma_index_io.h:67:29: error: variable or field ‘read_direct_map’ declared void
 void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f);
                             ^~~~~~~~~

/usr/local/go/src/github.com/vearch_new/vearch/engine/index/gamma_index_io.h:67:60: error: expected primary-expression before ‘*’ token
 void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f);
                                                            ^
/usr/local/go/src/github.com/vearch_new/vearch/engine/index/gamma_index_io.h:67:61: error: ‘f’ was not declared in this scope
 void read_direct_map(faiss::DirectMap *dm, faiss::IOReader *f);
                                                             ^
大概就是这三类问题，其中gcc:7.3.1-5， go:1.14.2，faiss：1.6.1 ， rocksdb：6.2.2，且都是源码编译的。
不知道这个报错原因是什么？

**Comment by wxingda** [comment]
需要安装zstd库

**Comment by cml26** [comment]
我用yum install zstd安装了zstd库为什么还是报一样的错误呀

**Comment by cml26** [comment]
> 需要安装zstd库

我用yum install zstd安装了zstd库为什么还是报一样的错误呀

**Comment by wxingda** [comment]
可能是环境变量的问题，将zstd的动态库路径加到`LD_LIBRARY_PATH`里面，把头文件路径加到`CPLUS_INCLUDE_PATH`里面

**Comment by ChenCongZhu2017** [comment]
我这边也碰到了，我这边配置CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:跟上你的zstd.h头文件路径    解决的
