### ISSUE TITLE
机器足够的话，单表数据量最大是多少，按天分表是否可以提高查询性能？

### ISSUE THREAD

**Issue by NLPOR** [vearch/vearch#277]
我们每天有2048维的feature 1亿个，以后想按时间段做range 的feature查询，是一年数据放一个表好，还是每天1个表快，应该怎么设计，担心是1个表装不下几百亿数据，和查询性能问题.

**Comment by ljeagle** [comment]
每天一个表快。一个表存放几百亿也可以，看你们的机器配置和规模了。
