### ISSUE TITLE
检索的问题

### ISSUE THREAD

**Issue by cml26** [vearch/vearch#278]
创建一个表：
curl -XPUT -H "content-type: application/json" -d'
{
     "name": "space2",
     "partition_num": 1,
     "replica_num": 1,
     "engine": {
         "name": "gamma",
         "index_size": 70000,
         "id_type": "String",
         "retrieval_type": "IVFFLAT",
         "retrieval_param": {
             "metric_type": "InnerProduct",
             "ncentroids": 2048
         }
     },
     "properties": {
         "field1": {
             "type": "vector",
             "dimension": 2,
             "format": "normalization",
             "store_type": "RocksDB",
             "store_param": {
                 "cache_size": 2048,
                 "compress": false
             }
         }
     }
 }
 ' http://ip:port/space/db_name/_create

插入一个数据：
curl -H "content-type: application/json" -XPOST -d'
> {"index": {"_id": "11"}}
> {"field1": {"feature": [0.11, 0.11]}}
> {"index": {"_id": "12"}}
> {"field1": {"feature": [0.12, 0.12]}}
> ' http://ip:port/db_name/space2/_bulk

检索：
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        "sum": [{
            "field": "field1”,
            "feature": [0.11, 0.11],
            "min_score”: 0,
            "boost": 1.0
        }]
    },
    "retrieval_param": {
    "parallel_on_queries": 1,
    "nprobe": 80,
    "metric_type": "L2"
     }, 
    "is_brute_search": 0,
    "online_log_level": "debug",
    "quick": true,
    "vector_value": true,
    "client_type": "leader",
    "size": 10
}' http://ip:port/db_name/space2/_search
结果是这样：{"took":1,"timed_out":false,"_shards":{},"hits":{"total":0,"max_score":-1}
为什么会是没有匹配的特征向量
此时的检索的时候报错信息是：
gamma_engine.cc:217 req_num should not less than 0

**Comment by cml26** [comment]
批量插入：
curl -H "content-type: application/json" -XPOST -d '{"index": {"_id": "11"}}\n  {"field1": {"feature": [0.98, 0.7, 0.34, 0.06, 0.07, 0.8, 0.74, 0.52, 0.47, 0.93, 0.44, 0.83, 0.07, 0.39, 0.51, 0.4, 0.47, 0.63, 0.67, 0.84, 0.75, 0.99, 0.05, 0.74, 0.5, 0.03, 0.51, 0.73, 0.35, 0.25, 0.48, 0.24, 0.29, 0.46, 0.49, 0.22, 0.16, 0.74, 0.28, 0.73, 0.69, 0.47, 0.08, 0.47, 0.83, 0.14, 0.31, 0.93, 0.67, 0.25, 0.21, 0.85, 0.79, 0.97, 0.12, 0.11, 0.02, 0.76, 0.32, 0.35, 0.88, 0.15, 0.47, 0.0, 0.0, 0.11, 0.78, 0.72, 0.05, 0.57, 0.99, 0.77, 0.2, 0.55, 0.58, 0.14, 0.73, 0.04, 0.78, 0.36, 0.55, 0.8, 0.96, 0.39, 0.66, 0.67, 0.68, 0.64, 0.97, 0.68, 0.22, 0.96, 0.57, 0.65, 0.08, 0.72, 0.23, 0.94, 0.27, 0.09, 0.59, 0.24, 0.16, 0.27, 0.87, 0.08, 0.37, 0.47, 0.64, 0.57, 0.08, 0.78, 0.59, 0.46, 0.65, 0.55, 0.8, 0.88, 0.37, 0.19, 0.55, 0.79, 0.8, 0.29, 0.66, 0.29, 0.18, 0.8]}}\n  {"index": {"_id": "12"}}\n  {"field1": {"feature": [0.34, 0.46, 0.12, 0.05, 0.19, 0.29, 0.41, 0.67, 0.59, 0.06, 0.27, 0.57, 0.46, 0.19, 0.34, 0.27, 0.43, 0.91, 0.54, 0.85, 0.93, 0.93, 1.0, 0.77, 0.19, 0.45, 0.84, 0.67, 0.93, 0.59, 0.59, 0.52, 0.69, 1.0, 0.08, 0.51, 0.21, 0.81, 0.0, 0.72, 0.47, 0.09, 0.87, 0.61, 0.62, 0.37, 0.03, 0.43, 0.47, 0.08, 0.34, 0.19, 0.62, 0.74, 0.97, 0.35, 0.39, 0.23, 0.36, 0.73, 0.13, 0.68, 0.76, 0.31, 0.59, 0.57, 0.8, 0.42, 0.87, 0.99, 0.28, 0.6, 0.34, 0.27, 0.97, 0.6, 0.28, 0.58, 0.32, 0.79, 0.54, 0.29, 0.23, 0.9, 0.13, 0.07, 0.59, 0.55, 0.16, 0.67, 0.63, 0.31, 0.12, 0.2, 0.46, 0.31, 0.28, 0.59, 0.17, 0.45, 0.58, 0.44, 0.03, 0.87, 0.67, 0.0, 0.39, 0.88, 0.27, 0.23, 0.39, 0.8, 0.4, 0.05, 0.32, 0.5, 0.39, 0.81, 0.8, 0.07, 0.91, 0.25, 0.87, 0.67, 0.28, 0.56, 0.84, 0.02]}}\n' http://ip:port/db_name/space1/_bulk
报错就是这样的：{"error":{"root_cause":[{"type":"","reason":"Unmarshal: there are bytes left after unmarshal, error found in #10 byte of ...|\": \"11\"}}\\n  {\"field|..., bigger context ...|{\"index\": {\"_id\": \"11\"}}\\n  {\"field1\": {\"feature\": [0.98, 0.7, 0.34, 0.06, |..."}],"type":"","reason":"Unmarshal: there are bytes left after unmarshal, error found in #10 byte of ...|\": \"11\"}}\\n  {\"field|..., bigger context ...|{\"index\": {\"_id\": \"11\"}}\\n  {\"field1\": {\"feature\": [0.98, 0.7, 0.34, 0.06, |..."},"status":400}
在ALL.ERROR.log日志中都没有相关的信息显示。

**Comment by cml26** [comment]
检索的时候报错信息是：
gamma_engine.cc:217 req_num should not less than 0

**Comment by cml26** [comment]
还有一个问题，我是用vearch/vearch:3.2.0来启动单机vearch的，但是总是隔不了多久master就会挂掉。
报错信息是：server.go:187 to register master error, nodeId:[1], err : master server all down

**Comment by zcdb** [comment]
查询语句用json格式化的工具查看一下吧，里面有好几个引号不对。另外master挂掉的情况可以提供下chubao-master-startup.log吗？
