### ISSUE TITLE
Compile Question

### ISSUE THREAD

**Issue by winself** [vearch/vearch#28]
when I "go build -o vearch" 

I meets "ps/engine/gammacb/util.go:94:26: too many arguments in call to _Cfunc_MakeVectorInfo
	have (*_Ctype_struct_ByteArray, uint32, _Ctype_int, *_Ctype_struct_ByteArray, *_Ctype_struct_ByteArray, *_Ctype_struct_ByteArray, *_Ctype_struct_ByteArray)
	want (*_Ctype_struct_ByteArray, uint32, _Ctype_int, *_Ctype_struct_ByteArray, *_Ctype_struct_ByteArray, *_Ctype_struct_ByteArray)
" 

Look forward to your reply.

**Comment by ansjsun** [comment]
how did you compile vearch?

recommend use docker like this: https://github.com/vearch/vearch/blob/master/docs/Deploy.md#docker-example

or 

````
go to $vearch/cloud dir
you can run ./run_docker.sh
````

**Comment by winself** [comment]
I compile it using the Deploy.md step by step .
when  "go build -o vearch when vearch file generated, it is ok."  meets the problems.  Not use docker yet.
 
Thank you .
I try it again using  https://my.oschina.net/ansj/blog/3117596.  
If I meet some questions. I will leave you a message on your blog.  Thank you again~

**Comment by ljeagle** [comment]
you can try it again according to the Deploy.md, we have fixed it. @winself

**Comment by winself** [comment]
thanks @ljeagle @ansjsun
