### ISSUE TITLE
编译gamma总找不到faiss的头文件

### ISSUE THREAD

**Issue by lintong0402** [vearch/vearch#280]
![image](https://user-images.githubusercontent.com/40934962/101657752-363a9a80-3a7f-11eb-8c68-be5ce6f8b899.png)

![image](https://user-images.githubusercontent.com/40934962/101658801-5585f780-3a80-11eb-9b81-ac6233b76c88.png)

我在执行命令时 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$vearch/ps/engine/gammacb/lib ..  然后再执行 make -j && make install 总报找不到faiss的头文件，但是通过打印信息看，faiss也打印出来了(Found Faiss libraries,Found Faiss include)，faiss我是安装好的，环境变量也设置了，路径设置的也没有问题，非常奇怪，master和v3.2.0_1、v3.2.0版本我都试过了，是我哪个地方设置的有问题吗？

**Comment by wxingda** [comment]
到faiss安装路径下看看InveredLists.h文件是否存在

**Comment by lintong0402** [comment]
> 到faiss安装路径下看看InveredLists.h文件是否存在

![image](https://user-images.githubusercontent.com/40934962/101853142-1946ba00-3b9a-11eb-9a25-27e689f7930d.png)

文件都是在的，这个检查过了

**Comment by lintong0402** [comment]
找到问题了，可能是之前我编译过faiss的版本，但不是指定的commit的版本，在/usr/local/include和/usr/local/lib64 生成了头文件和库文件等信息，但是里面是没有InvertedLists.h这个文件的，我把 /usr/local中相应的faiss相关的都删除了，再次编译gamma成功。如果编译过程中能把faiss的目录信息打印出来，会更容易定位此问题。
