### ISSUE TITLE
创建维度大于1024的MemoryOnly类型表空间报错

### ISSUE THREAD

**Issue by richxnh** [vearch/vearch#282]
返回结果：{"code":550,"msg":"create partition err: create gamma table has err:[-2] "}
请求信息：
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "space",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 100000,
        "id_type": "Long",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 64
        }
    },
    "properties": {
        "camId": {
            "type": "integer"
        },
        "shotTime": {
            "type": "long"
        },
        "vde": {
            "type": "vector",
            "dimension": 2048,
            "format": "normalization",
            "store_type": "MemoryOnly",
            "store_param": {
                "cache_size": 4096,
                "compress": true
            }
        }
    }
}
' http://master:8817/space/test/_create

**Comment by wxingda** [comment]
请发下gamma.log

**Comment by qihaoxiansheng** [comment]
MemoryOnly类型，是不是不支持维度大于1024的特征向量？
