### ISSUE TITLE
v3.2.0_1版本，单机部署创建space失败，没有partition

### ISSUE THREAD

**Issue by lintong0402** [vearch/vearch#285]
创建的时候经常系统服务崩溃，有时创建不成功，即使创建了，通过master health查看，没有partition,信息如下：
[
    {
        "db_name": "lintongdb",
        "space_num": 1,
        "doc_num": 0,
        "size": 0,
        "spaces": [
            {
                "name": "spacetest",
                "partition_num": 0,
                "replica_num": 0,
                "doc_num": 0,
                "size": 0,
                "partitions": [],
                "status": "green"
            }
        ],
        "status": "green",
        "errors": [
            "partition:[2] not found in space: [spacetest]"
        ]
    }
]
查看表空间显示如下：
{
    "code": 200,
    "msg": "success",
    "data": {
        "id": 2,
        "name": "spacetest",
        "version": 1,
        "db_id": 2,
        "enabled": false,
        "partitions": [
            {
                "id": 2,
                "space_id": 2,
                "db_id": 2,
                "partition_slot": 0
            }
        ],
        "partition_num": 1,
        "replica_num": 1,
        "properties": {
            "url": {
                "type": "keyword"
            },
            "facevec": {
                "type": "vector",
                "dimension": 256,
                "format": "normalization",
                "store_type": "RocksDB",
                "store_param": {
                    "cache_size": 2048,
                    "compress": false
                }
            }
        },
        "engine": {
            "name": "gamma",
            "index_size": 10000,
            "retrieval_type": "IVFFLAT",
            "retrieval_param": {
                "metric_type": "InnerProduct",
                "ncentroids": 2048
            },
            "id_type": "Long"
        },
        "space_properties": {
            "facevec": {
                "field_type": 7,
                "type": "vector",
                "format": "normalization",
                "dimension": 256,
                "store_type": "RocksDB",
                "store_param": {
                    "cache_size": 2048,
                    "compress": false
                },
                "option": 1
            },
            "url": {
                "field_type": 1,
                "type": "keyword"
            }
        }
    }
}

其中enabled=false, 这种状态也插入不了数据，这是什么原因？我反复核对了每次请求参数，也试过多次，没发现有问题，但始终不成功，非常期待解答!

**Comment by zcdb** [comment]
请提供一下gamma.log

**Comment by lintong0402** [comment]
> 请提供一下gamma.log

gamma.log下没有日志，0字节

**Comment by kevintony001** [comment]
麻烦提供创建space报错的建表语句，插入数据导致崩溃的参数

**Comment by lintong0402** [comment]
> 麻烦提供创建space报错的建表语句，插入数据导致崩溃的参数

{
    "name": "spacetest",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 10000,
        "id_type": "Long",
        "retrieval_type": "IVFFLAT",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048
        }
    },
    "properties": {
        "url": {
            "type": "keyword"
        },
        "facevec": {
            "type": "vector",
            "dimension": 256,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048,
                "compress": false
            }
        }
    }
}

**Comment by zcdb** [comment]
创建space返回的信息可以提供一下吗？正常来说即便创建space失败，gamma.log也应该是有日志信息的

**Comment by lintong0402** [comment]
> 创建space返回的信息可以提供一下吗？正常来说即便创建space失败，gamma.log也应该是有日志信息的

我用的postman工具，请求直接超时了，看不到返回值，都是现查space状态才能看到space是否创建成功了

**Comment by zcdb** [comment]
curl -XGET http://master_server/_cluster/stats 通过这个接口看看会返回ps的信息吗？找一下看看有这几个日志文件吗？chubao-master-startup.log chubao-router-startup.log chubao-ps-startup.log

**Comment by lintong0402** [comment]
> curl -XGET http://master_server/_cluster/stats 通过这个接口看看会返回ps的信息吗？找一下看看有这几个日志文件吗？chubao-master-startup.log chubao-router-startup.log chubao-ps-startup.log

返回信息都很正常，如下：
[
    {
        "status":200,
        "ip":"127.0.0.1",
        "labels":[
            {
                "name":"models",
                "value":"master,ps,router"
            }
        ],
        "mem":{
            "total_in_bytes":4142473216,
            "free_in_bytes":203210752,
            "used_in_bytes":553607168,
            "used_percent":13.36417
        },
        "swap":{
            "total_in_bytes":4194299904,
            "free_in_bytes":4168650752,
            "used_in_bytes":25649152,
            "used_percent":0.611524
        },
        "fs":{
            "total_in_bytes":42927656960,
            "free_in_bytes":18848841728,
            "used_in_bytes":24078815232,
            "used_percent":1,
            "paths":[
                "datas/",
                "logs/"
            ]
        },
        "cpu":{
            "total_in_bytes":2,
            "user_percent":0.004509,
            "sys_percent":0.00501,
            "io_wait_percent":0.009018,
            "idle_percent":0.981463
        },
        "net":{
            "in_pre_second":1221,
            "out_pre_second":2232,
            "connect":19
        },
        "gc":{
            "calls":5,
            "routines":121
        },
        "active_conn":1
    }
]

**Comment by zcdb** [comment]
那么可以提供一下ALL.*log这几个日志的文件吗？

**Comment by lintong0402** [comment]
> 那么可以提供一下ALL.*log这几个日志的文件吗？

[logs.tar.gz](https://github.com/vearch/vearch/files/5699996/logs.tar.gz)

**Comment by lintong0402** [comment]
我怀疑是不是和硬件有关系，我的机器的硬件不满足vearch的需要？

**Comment by qihaoxiansheng** [comment]
你好，你是用源码安装的吗

**Comment by qihaoxiansheng** [comment]
能不能给我介绍一下你的安装步骤啊

**Comment by lintong0402** [comment]
> 能不能给我介绍一下你的安装步骤啊

是源码安装的，faiss和rocksdb的版本都是按tag来的，步骤主要参考两个网址：https://vearch.readthedocs.io/zh_CN/latest/quick-start-guide.html  ，https://github.com/vearch/vearch/wiki/%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91Vearch

**Comment by lintong0402** [comment]
> 能不能给我介绍一下你的安装步骤啊
我怀疑是机器的问题，我改用virtualbox在Mac电脑上虚拟出一个CentOS7的机器，用同样的操作步骤,同样版本的各种安装软件包，成功编译并成功运行，插入数据也正常了，然后看了一下原来有问题的机器cpu信息如下
：
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version 1.5.3
stepping	: 3
microcode	: 0x1
cpu MHz		: 2299.996
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm abm
bogomips	: 4599.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version 1.5.3
stepping	: 3
microcode	: 0x1
cpu MHz		: 2299.996
cache size	: 4096 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm abm
bogomips	: 4599.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

这是经过虚拟化的，cpu指令集都少了不少，所以我猜测是和虚拟化有关系。而我Mac电脑虚拟出的机器指令集很多的。相关感兴趣的人员可以复现并证实一下我的猜测。

**Comment by lintong0402** [comment]
> 能不能给我介绍一下你的安装步骤啊
我怀疑是机器的问题，我在Mac上用virtualbox 虚拟出来一台CentOS7的机器，用同样的操作步骤、同样的软件安装包编译，并成功运行，数据插入也正常了，原来出问题的机器是虚拟过的，cpu信息如下：
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version 1.5.3
stepping	: 3
microcode	: 0x1
cpu MHz		: 2299.996
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm abm
bogomips	: 4599.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version 1.5.3
stepping	: 3
microcode	: 0x1
cpu MHz		: 2299.996
cache size	: 4096 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm abm
bogomips	: 4599.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

看指令集少了不少，而我在Mac上虚拟出的机器指令集是比较多的，所以我怀疑是和虚拟有关系，感兴趣的相关人员可以证实一下我的想法
