### ISSUE TITLE
Change max_size  for space after created ?

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#29]
When I create space , system required max_size for space . I set max_size :1000 
Example : 
"engine": {"name": "gamma", "metric_type": method,"max_size":1000}

When I index item into system. Total  document is limit at 1000.
How can I change limit max_size  for index new item ?  (Example max_size=50000)

**Comment by ansjsun** [comment]
the max_size  is engine can store document num
if space created , it can not change . so you need create it Large enough，
@ljeagle @wxingda , I don't think we need to limit the size

**Comment by ljeagle** [comment]
The max_size is the maximum documents which can be stored in each partition.  Once it is set, it can not be changed anymore. When creating space, you should set an appropriate value according the maximum scale of your data.

**Comment by phamthanhtri** [comment]
Thanks for answer . 
When I deploy system into production. I can set  appropriate maximum for data. Example 5 million items for 2 server partition.
After a while running, system have more data insert from users and reach maximum. I can scale more partition server for system but I can't change maximum items. How can system vearch suppport dynamic for scale maximum items?

**Comment by ansjsun** [comment]
There are two ways to solve this problem 
* rebuild index 
* create a new space ,you need to search both tables in the once, like this  http://ip:port/db1,db1/table1,tabl2/_search this api very like elasticsearch

**Comment by phamthanhtri** [comment]
Thanks suggest from @ansjsun . But I think two ways can't solve for real time system: 
  1. rebuild index: I must use number of servers equals running server for index, then I change into new system . It consumes a lot of resources and time
  2. create new space:  I think speed of system will be reduced. Because I execute two requests per search then combined result from it
