### ISSUE TITLE
grpc多分片下搜索返回结果错误

### ISSUE THREAD

**Issue by aircov** [vearch/vearch#292]
result_items里面的结果第一条不是max_score对应的id和分数

这是返回top10的结果。
> {'total_hits': 100000, 'max_score': 1.0000001192092896, 'max_took': 0, 'max_took_id': 0, 'result_items': [{'score': 0.6409494876861572, 'p_key': '000000000000000000000000000000069632', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.6409494876861572}]}}, {'score': 0.6177768707275391, 'p_key': '000000000000000000000000000000051725', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.6177768707275391}]}}, {'score': 0.6129254102706909, 'p_key': '000000000000000000000000000000070478', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.6129254102706909}]}}, {'score': 0.608948826789856, 'p_key': '000000000000000000000000000000097605', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.608948826789856}]}}, {'score': 0.6004608273506165, 'p_key': '000000000000000000000000000000073122', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.6004608273506165}]}}, {'score': 0.5817891955375671, 'p_key': '000000000000000000000000000000050548', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.5817891955375671}]}}, {'score': 0.5816992521286011, 'p_key': '000000000000000000000000000000070284', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.5816992521286011}]}}, {'score': 0.5762649774551392, 'p_key': '000000000000000000000000000000028508', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.5762649774551392}]}}, {'score': 0.5735417604446411, 'p_key': '000000000000000000000000000000098008', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.5735417604446411}]}}, {'score': 0.5726918578147888, 'p_key': '000000000000000000000000000000007969', 'source': {'vector_result': [{'field': 'title', 'source': '', 'score': 0.5726918578147888}]}}]}

并且如果多次请求的话result_items的结果会变。

**Comment by aircov** [comment]
如果使用restAPI请求返回结果是正确的，第一条就是max_score对应的docID

**Comment by gDreamcatcher** [comment]
麻烦提供一下以下内容：

1. vearch和gamma版本号，或commitID
2. grpc客户端
3. 建表语句
4. grpc和restful的搜索语句

**Comment by aircov** [comment]
> 麻烦提供一下以下内容：
> 
> 1. vearch和gamma版本号，或commitID
> 2. grpc客户端
> 3. 建表语句
> 4. grpc和restful的搜索语句

**Comment by aircov** [comment]
> 麻烦提供一下以下内容：
> 
> 1. vearch和gamma版本号，或commitID
> 2. grpc客户端
> 3. 建表语句
> 4. grpc和restful的搜索语句

1.版本号3.2.2
2.grpc客户端是generate_python.sh生成的python客户端。其他需要第三方依赖安装的都是最新版
3.

>
 mapping = {
    "name": SpaceName,
    "dynamic_schema": "strict",
    "partition_num": 25,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 100000,
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048, 
            "nsubvector": 32,  
            "hnsw": {  # IVFPQ+HNSW 组合索引方式
                "nlinks": 32, 
                "efConstruction": 
                "efSearch": 64  
            },
        }
    },
    "properties": {
        "title": {
            "type": "vector",
            "dimension": 32, 
            "format": "normalization", 
            "store_type": "RocksDB", 
            "store_param": {
                "cache_size": 2048
            }
        }
    }
}


4.搜索语句参考例子curl：

> 	dsl = {
		"query": {
			"sum": [
				{
					"field": "title",
					"feature": feature,
					"format": "normalization"
				}
			]
		},
		"retrieval_param": {
			"nprobe": 20,  
			"metric_type": "InnerProduct",
			"parallel_on_queries": 1  # 默认1， 搜索间并行；0代表桶间并行
		},
		"online_log_level": "debug",
		"quick": False,  
		"client_type": "leader",
	}


grpc：
> 	vector_name = ''
	# vearch表字段名称和类型
	for k, v in c.field_map.items():
		if v == dpb.FieldType.VECTOR:
			vector_name = k
			break
	request = {
		"_id": "",
		"title": feature
	}
	vec_field = rpb.VectorQuery(
		name=vector_name,
		value=np.array(request[vector_name], dtype=np.float32).tobytes(),
		min_score=0.0,
		max_score=100.0
	)
	res = c.search(
		top_n=10,  # 返回前10个
		vec_fields=[vec_field],
		fields=request.keys(),
		online_log_level="debug",
		is_vector_value=True,
		has_rank=1,  
		parallel_based_on_query = False,
		l2_sqrt = False,
		ivf_flat = False,
		multi_vector_rank=0,
		retrieval_params=json.dumps({"nprobe": 20, "metric_type": "InnerProduct", "parallel_on_queries": 1})
	)
	print(res)

**Comment by gDreamcatcher** [comment]
你好，你在search中加一个sort_fields参数，具体如下：
```python
res = c.search(
      top_n=10, # 返回前10个
      vec_fields=[vec_field],
      fields=request.keys(),
      online_log_level="debug",
      is_vector_value=True,
      has_rank=1,
      parallel_based_on_query = False,
      l2_sqrt = False,
      ivf_flat = False,
      multi_vector_rank=0,
      sort_fields = [rpb.SortField(field = '_score', type = True)],
      retrieval_params=json.dumps({"nprobe": 20, "metric_type": "InnerProduct", "parallel_on_queries": 1})
)
print(res)
```

**Comment by aircov** [comment]
> 你好，你在search中加一个sort_fields参数，具体如下：
> 
> ```python
> res = c.search(
>       top_n=10, # 返回前10个
>       vec_fields=[vec_field],
>       fields=request.keys(),
>       online_log_level="debug",
>       is_vector_value=True,
>       has_rank=1,
>       parallel_based_on_query = False,
>       l2_sqrt = False,
>       ivf_flat = False,
>       multi_vector_rank=0,
>       sort_fields = [rpb.SortField(field = '_score', type = True)],
>       retrieval_params=json.dumps({"nprobe": 20, "metric_type": "InnerProduct", "parallel_on_queries": 1})
> )
> print(res)
> ```

ok，可以了，谢谢
