### ISSUE TITLE
数据查询返回值疑惑

### ISSUE THREAD

**Issue by lintong0402** [vearch/vearch#294]
我向space里插入了一条数据，然后按照同样的向量再去查询，返回的json结果看不是预期
**表空间定义；**
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "demo_space",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 10000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 64,
            "nsubvector": 2
        }
    },
    "properties": {
        "pic_url": {
            "type": "keyword"
        },
        "face_vec": {
            "type": "vector",
            "dimension": 8,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 512,
                "compress": false
            }
        }
    }
}
' http://127.0.0.1:8817/space/lintong_db/_create

**插入数据：**
curl -XPOST -H "content-type: application/json"  -d'
{
    "pic_url": "url2",
    "face_vec": {
        "feature":[0.1,0.2,0.3,0.4,0.5,0.6,0.1,0.8]
    }
}
' http://127.0.0.1:9001/lintong_db/demo_space

**查询数据：**
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        "sum": [{
            "field": "face_vec",
            "feature": [0.1, 0.2, 0.3, 0.4, 0.5,0.6,0.7,0.8],
            "min_score": 0.0,
            "boost": 1.0
        }],
        "filter": []
    },
    "retrieval_param": {
        "nprobe": 20
    },
    "fields": ["pic_url"],
    "is_brute_search": 0,
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "l2_sqrt": false,
    "sort": [{"pic_url":{"order": "asc"}}],
    "size": 10
}
' http://127.0.0.1:9001/lintong_db/demo_space/_search

**返回结果是这样的**
{
    "took":1,
    "timed_out":false,
    "_shards":{
        "total":1,
        "successful":1
    },
    "hits":{
        "total":0,
        "max_score":-1
    }
}

这个返回结果是查到数据，还是没查到数据，took与hits的含义具体代表什么？

**Comment by gDreamcatcher** [comment]
`took`是服务器响应的耗时，单位是毫秒;
` hits`是搜索命中的结果；
你这种情况就是搜索没有返回结果，原因是建表时指定的是10000开始建索引，而你只插入了一条，现在还没有索引，所以在search的时候需要指定is_brute_search为1，就是指明使用暴力搜索。

**Comment by lintong0402** [comment]
> 你这种情况就是搜索没有返回结果，原因是建表时指定的是10000开始建索引，而你只插入了一条，现在还没有索引，所以在search的时候需要指定is_brute_search为1，就是指明使用暴力搜索。

把is_brute_search改为1，也查不出来，另外我按id查询，发现查询出来的向量值并不等于插入时的向量值（IVFPQ与IVFFLAT两种方式我都试过），不知道是哪个地方没有设置对。
比如安排好IVFFLAT插入的向量值为[0.1,0.2,0.3,0.4]按id查询出来的值却成为[0.18257418,0.36514837,0.5477226,0.73029673]
过程如下：

* 1.建表空间 vec_space
```
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "vec_space",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 8192,
        "id_type": "String",
        "retrieval_type": "IVFFLAT",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2
        } 
    },
    "properties": {
        "face_url": {
            "type": "keyword"
        },
        "face_vec": {
            "type": "vector",
            "dimension": 4,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 512,
                "compress": false
            }
        }
    }
}
' http://127.0.0.1:8817/space/lintong_db/_create
```
* 2 插入数据
```
curl -XPOST -H "content-type: application/json"  -d'
{
    "face_url": "home/abc/1",
    "face_vec": {
        "feature": [0.1, 0.2, 0.3, 0.4]
    }
}
' http://127.0.0.1:9001/lintong_db/vec_space
```
返回值：
```json
{"_index":"lintong_db","_type":"vec_space","_id":"-2763285366003747542","status":200}
```
* 3.按id查询这条数据
```
curl -XGET http://127.0.0.1:9001/lintong_db/vec_space/-2763285366003747542

```
查询结果：
```json
{"_index":"lintong_db","_type":"vec_space","_id":"-2763285366003747542","found":true,"_source":{"face_url":"home/abc/1","face_vec":{"feature":[0.18257418,0.36514837,0.5477226,0.73029673],"source":""}}}

* 5按特征查询
```bash
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        "sum": [{
            "field": "face_vec",
            "feature": [0.1, 0.2, 0.3, 0.4],
            "min_score": 0.0,
            "boost": 1.0
        }],
        "filter": []
    },
    "retrieval_param": {
        "parallel_on_queries": 1,
        "nprobe": 2,
        "metric_type": "L2"
    }
    "fields": ["face_url", "face_vec"],
    "is_brute_search": 1,
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "l2_sqrt": false,
    "sort": [{"face_url":{"order": "asc"}}],
    "size": 10
}
' http://127.0.0.1:9001/lintong_db/vec_space/_search

```
查询结果:
```json
{"took":0,"timed_out":false,"_shards":{},"hits":{"total":0,"max_score":-1}
```

**Comment by gDreamcatcher** [comment]
向量值改变的问题：是因为建表的时候制定了"format": "normalization"，这个时候服务器会自动把你的向量的每一维度除以向量的`L2`范数；
搜索没结果建议：同时指定min_score和max_score，或者两个都不要

**Comment by lintong0402** [comment]
> 搜索没结果建议：同时指定min_score和max_score，或者两个都不要

min_score=0.0
max_score=1.0
还是搜索不到

两个全去掉，也搜索不到

把boost去掉，或设置成1.0，也搜索不到

**Comment by wxingda** [comment]
发下gamma.log

**Comment by gDreamcatcher** [comment]
你测试的时候使用的是`IVFFLAT`还是`IVFPQ`, 目前只有`IVFPQ`支持暴力搜索

**Comment by lintong0402** [comment]
> 你测试的时候使用的是`IVFFLAT`还是`IVFPQ`, 目前只有`IVFPQ`支持暴力搜索

IVFPQ也试了，不行

**Comment by lintong0402** [comment]
> 发下gamma.log

[gamma.log.tar.gz](https://github.com/vearch/vearch/files/5724258/gamma.log.tar.gz)

**Comment by wxingda** [comment]
![image](https://user-images.githubusercontent.com/12606514/102777058-cefbdf00-43ca-11eb-86cc-82f45c3bb8da.png)
vearch检查到搜索的向量长度不正确，看看是不是要检索的向量传的不够

**Comment by lintong0402** [comment]
> vearch检查到搜索的向量长度不正确，看看是不是要检索的向量传的不够

* 创建表空间语句
```
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "vec_space",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 8192,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2,
            "nsubvector": 2
        }
    },
    "properties": {
        "face_url": {
            "type": "keyword"
        },
        "face_vec": {
            "type": "vector",
            "dimension": 4,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 512,
                "compress": false
            }
        }
    }
}
' http://127.0.0.1:8817/space/lintong_db/_create
```
* 查询语句
```
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        "sum": [{
            "field": "face_vec",
            "feature": [0.1, 0.2, 0.3, 0.4]
        }],
        "filter":[]
    },
    "retrieval_param": {
        "parallel_on_queries": 1,
        "nprobe": 2,
        "metric_type": "L2"
    }
    "fields":["face_url", "face_vec"],
    "is_brute_search": 1,
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "l2_sqrt": false,
    "sort": [{"face_url":{"order": "asc"}}],
    "size": 10
}
' http://127.0.0.1:9001/lintong_db/vec_space/_search
```

**Comment by lintong0402** [comment]
> vearch检查到搜索的向量长度不正确，看看是不是要检索的向量传的不够

应该是查询的json里面，缺少内容导致，换成以下的查询，终于查询成功了！另外我发现score的值就是L2的距离吧，本示例中为0

```
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        "sum": [{
            "field": "face_vec",
            "feature": [0.1, 0.2, 0.3, 0.4],
            "min_score": 0.0,
            "max_score": 1.0,
            "boost": 1.0
        }],
        "filter": []
    },
    "retrieval_param": {
        "nprobe": 20
    },
    "fields": ["face_url", "face_vec"],
    "is_brute_search": 1,
    "online_log_level": "debug",
    "quick": false,
    "vector_value": false,
    "client_type": "leader",
    "l2_sqrt": false,
    "sort": [{"face_url":{"order": "asc"}}],
    "size": 10
}
' http://127.0.0.1:9001/lintong_db/vec_space/_search
```
返回值：
```
{
    "took":1,
    "timed_out":false,
    "_shards":{
        "total":1,
        "successful":1
    },
    "hits":{
        "total":1,
        "max_score":0,
        "hits":[
            {
                "_index":"lintong_db",
                "_type":"vec_space",
                "_id":"5428358968988923942",
                "_score":0,
                "_extra":{
                    "vector_result":[
                        {
                            "field":"face_vec",
                            "source":"",
                            "score":0
                        }
                    ]
                },
                "_source":{
                    "face_url":"home/abc/1",
                    "face_vec":{
                        "feature":[
                            0.18257418,
                            0.36514837,
                            0.5477226,
                            0.73029673
                        ],
                        "source":""
                    }
                }
            }
        ]
    }
}
```
