### ISSUE TITLE
3.2.5版本engine编译失败

### ISSUE THREAD

**Issue by WeiYan-Lynn** [vearch/vearch#296]
当前用的gcc-8.2.0版本编译，报错
/opt/huawei/compile/go/src/github.com/vearch/vearch/engine/c_api/gamma_api.cc: In function ‘void* Init(const char*, int)’:
/opt/huawei/compile/go/src/github.com/vearch/vearch/engine/c_api/gamma_api.cc:37:54: error: operand type ‘bool*’ is incompatible with argument 1 of ‘__sync_fetch_and_or’
   bool flag = __sync_fetch_and_or(&log_dir_flag, true);
麻烦问下应该用什么样的版本编译呢

**Comment by wxingda** [comment]
可能是gcc版本太高了，参考下https://forum.vertica.com/discussion/239675/building-filterfunctions-in-vertica-9-1-0-1-fails
里面的` if (!__sync_fetch_and_or(reinterpret_cast<unsigned char*>(&(this->canceled)), reinterpret_cast<unsigned char*>(true))) {`

**Comment by WeiYan-Lynn** [comment]
之前看到这个修改方式了，修改后也成功编译了，vearch这边会考虑修改这个地方，兼容更高版本的gcc吗

**Comment by wxingda** [comment]
后续会在高版本上面做兼容

**Comment by WeiYan-Lynn** [comment]
好的感谢
