### ISSUE TITLE
3.2.5导完数据，加载特别慢问题

### ISSUE THREAD

**Issue by aircov** [vearch/vearch#299]
3.2.5批量导3000w数据，数据导完后，curl health 发现数据并没有完全加载进去，比如doc_num：5000000，过两分钟再curl health，doc_num:10000000，加载完3000w数据大约需要10分钟。
     同样的数据，使用3.2.2版本基本数据全部导入后可以立即查询，3000w数据都加载进去了

**Comment by aircov** [comment]
顺便问下，3.2.5的修改点和差一点可以方便出一份文档吗？

**Comment by aircov** [comment]
并且3.2.5在加载这3000w数据的时候会崩，segmentation fault，core dumped，然后vearch目录下面会生成一个类似core.25045的文件

**Comment by gyd-a** [comment]
你描述的插入完数据后一段时间后health接口查询到正确数量，正常现象。建议使用单条插入，单次批量插入量太大可能产生插入数据丢失现象，建议不要用太大批量数。
