### ISSUE TITLE
编译和安装问题

### ISSUE THREAD

**Issue by dongjinshark** [vearch/vearch#30]
编译的时候报错
在vearch/engine/gamma/index/gamma_index_ivfpq.h 文件中#include "faiss/AuxIndexStructures.h"，但实际上这个头文件是faiss/impl/AuxIndexStructures.h，是faiss版本的问题还是我哪里步骤错了？

**Comment by ljeagle** [comment]
please use faiss v1.5.3

**Comment by dongjinshark** [comment]
> please use faiss v1.5.3
嗯，用这个版本版本可以了，最好在安装文档里提示下吧
