### ISSUE TITLE
3.2.2vearch集群插数据时，机器意外崩溃，数据恢复问题

### ISSUE THREAD

**Issue by aircov** [vearch/vearch#300]
5台ps，由于机器里面有其他应用程序在使用，消耗了大量内存，数据再导入过程中5台ps都挂了，然后删除了每个分片下data/table/最大的num.profile和num.str.profile，可以恢复三台ps 的数据，但是另外两台启动的过程中gamma报错【partition recovery get server info err:partition_not_exist  、 server can not find on master,maybe server is offline, nodeId:[34]】，partition注册不到master，不知道如何恢复数据，望解答

**Comment by kuailelijuan** [comment]
麻烦提供下 您这5台机器怎么部署的，另外还有建表语句。可以先通过 curl master:/_cluster/health 查看一下状态。

**Comment by aircov** [comment]
@kuailelijuan 你好
5台机器都作为ps和router，额外还有一台机器是master。
curl health只返回三台机器的信息，另外两台显示partition not found。【service internal error。invalid memory  address or nil pointer dereference xxxx】

建表语句:
`mapping = {
	"name": SpaceName,
	"dynamic_schema": "strict",
	"partition_num": 5,
	"replica_num": 1,
	"engine": {
		"name": "gamma",
		"index_size": 2600000*16,
		"retrieval_type": "IVFPQ",
		"retrieval_param": {
			"metric_type": "InnerProduct",
			"ncentroids": 65536 * 16, 
			"nsubvector": 16,  
			"hnsw": {  
				"nlinks": 32,  
				"efConstruction": 1000,  
				"efSearch": 80  
			},
		}
	},
	"properties": {
		"title": {
			"type": "vector",
			"dimension": 32,  
			"format": "normalization", 
			"store_type": "RocksDB",  
			"store_param": {
				"cache_size": 2048*4
			}
		}
	}
}`
