### ISSUE TITLE
Is 3.2.5 and 3.2.2 compatible

### ISSUE THREAD

**Issue by xbugliu** [vearch/vearch#301]
请问3.2.5是否进入了release的状态，还有和3.2.2是否是兼容的。

3.2.2用了一段时间了，有3个比较严重且容易复现的bug:
1. meta.txt会丢失。
2. str.profile会破坏。
3. raft的日志文件会破坏。

请问是否在3.2.5版本fix.

**Comment by kuailelijuan** [comment]
3.2.5和3.2.2是不兼容的。
麻烦您提供下部署方式，建表语句。
您提到的这些问题，可以发一下日志出来看下吗，便于排查？

**Comment by xbugliu** [comment]
建表语句：
{
"name":"test",
"partition_num":3,
"replica_num":1,
"engine":{
"name":"gamma",
"id_type":"Long",
"index_size":100000,
"max_size":100000000,
"nprobe":64,
"retrieval_type":"IVFPQ",
"retrieval_param":{
"metric_type":"L2",
"ncentroids":2048,
"nsubvector":128
}
},
"properties":{
"timestamp":{
"type":"integer",
"index":true
},
"groupid":{
"type":"string",
"index":true
},
"objectid":{
"type":"integer",
"index":false
},
"feature0":{
"type":"vector",
"dimension":2048,
"store_type":"RocksDB",
"store_param":{
"cache_size":2000
}
}
}
}


问题1 会导致load失败，报错日志：
init partition err :[readObjectStart: expect { or n, but found ^@, error found in #0 byte of ...||..., bigger context ...||...]

问题2会导致crash：
![image](https://user-images.githubusercontent.com/2310720/102996247-b53ed100-455d-11eb-8d19-e941a3e55d6d.png)

问题3的日志：init partition err :[start partition[116] open raft store engine error: corrput data at /datas/raft/116/0000000000000003-00000000000025ac.log:25466190 (unexpected eof)]
raft日志破坏这个在频繁重启机器的情况下很容易出现，etcd已经有fix方案: 
https://github.com/etcd-io/etcd/blob/ae7862e8bc8007eb396099db4e0e04ac026c8df5/server/wal/repair.go

**Comment by xbugliu** [comment]
> 3.2.5和3.2.2是不兼容的。
> 麻烦您提供下部署方式，建表语句。
> 您提到的这些问题，可以发一下日志出来看下吗，便于排查？

请问不兼容是接口不兼容，还是底层数据存储不兼容？

**Comment by kuailelijuan** [comment]
底层数据存储不兼容
