### ISSUE TITLE
发现通过search搜索时有些doc的信息无法通过ID query接口获取

### ISSUE THREAD

**Issue by aelous** [vearch/vearch#302]
通过search搜索出来的一堆doc里，出现了有的doc的id无法通过 接口`curl -XGET http://router_server/$db_name/$space_name/$id` 获取到(目前只发现一例)，请问这可能是什么原因

**Comment by gyd-a** [comment]
你好，请问你用的哪个版本。

**Comment by aelous** [comment]
3.2.0
