### ISSUE TITLE
partition_num的值会影响检索的召回率吗

### ISSUE THREAD

**Issue by NLPOR** [vearch/vearch#304]
您好，请问单机情况下，配置replica_num=1,partition_num=3时的召回率比配置replica_num=1,partition_num=1时的召回率低很多，响应时间快很多，这个时正常的吗，分区数回影响召回率吗

**Comment by gyd-a** [comment]
一般情况下，partition_num数量对召回影响很小，vearch是在各ps节点中计算，在router进行合并结果。

**Comment by NLPOR** [comment]
请问有技术交流群吗，能否分享下，谢谢

**Comment by gyd-a** [comment]
你可以留下邮箱我给你发群二维码，该群只用于大家进行技术交流，使用中遇到什么问题还需要提issues，vearch团队会定期回答。

**Comment by qihaoxiansheng** [comment]
995376273@qq.comqq.com

**Comment by qihaoxiansheng** [comment]
995376273@qq.com

**Comment by NLPOR** [comment]
529379497@qq.com谢谢

**Comment by zcdb** [comment]
https://github.com/vearch/vearch/issues/307 群二维码这里面有 可以扫一下
