### ISSUE TITLE
vearch启动出错

### ISSUE THREAD

**Issue by realdalabengba** [vearch/vearch#306]
你好，我执行./bin/vearch -conf config.toml时返回Illegal instruction，请问这是什么原因呢？
版本3.2.0，文件结构如下：
```
├── bin
│   └── vearch
├── config.toml
└── lib
    ├── libfaiss.so
    ├── libgamma.so
    ├── libgamma.so.0.1
    ├── librocksdb.so
    ├── librocksdb.so.6.2
    └── librocksdb.so.6.2.2
```

**Comment by gyd-a** [comment]
./bin/vearch -conf config.toml all，all表示master，router，ps同时启动。配置文件中的ip改成运行机器的ip。

**Comment by realdalabengba** [comment]
我重新描述下吧。我现在用集群部署，流程是：在发布平台的机器上编译打包上传打包文件，然后待部署的机器再拉取打包文件进行部署。部署即执行 ./bin/vearch -conf config.toml master（或router、ps）。然后大概率会执行失败，只返回 illegal instruction(core dumped)，有的机器偶尔会成功，请问这可能是什么原因呢？

**Comment by realdalabengba** [comment]
已解决，是rocksdb默认编译设置了 -march=native导致（https://github.com/facebook/rocksdb/blob/master/INSTALL.md）
