### ISSUE TITLE
求交流群

### ISSUE THREAD

**Issue by qihaoxiansheng** [vearch/vearch#307]
您好，可以加一下您这边的交流群吗？可以的话，可以发到我的邮箱：995376273@qq.com，谢谢！

**Comment by zcdb** [comment]
[cid:41023E4F-B0A5-4650-BB9B-EA5EDD82DB33]

在 2020年12月24日，16:12，qihaoxiansheng <notifications@github.com> 写道：

﻿

您好，可以加一下您这边的交流群吗？可以的话，可以发到我的邮箱：995376273@qq.com<mailto:995376273@qq.com>，谢谢！

**Comment by zcdb** [comment]
![image](https://user-images.githubusercontent.com/53439076/103076312-6dc14f00-4608-11eb-8577-b99a6a453402.png)

**Comment by qihaoxiansheng** [comment]
页面打不开，可以直接发到邮箱吗

**Comment by jackleeforce** [comment]
二维码过期了，可以再发一个吗？ @zcdb
