### ISSUE TITLE
用docker 启动失败并且没有日志？

### ISSUE THREAD

**Issue by george-wang2016** [vearch/vearch#309]
我成功在本地编译了3.2.5的镜像，但是run之后容器马上退出了，也找不到日志？容器状态是Exited (132)

**Comment by kuailelijuan** [comment]
麻烦提供下docker 容器启动命令。

**Comment by george-wang2016** [comment]
nohup docker run --name=vearch_master -p 8817:8817 -p 9009:9009 -v $PWD/config.toml:/vearch/config.toml vearch/vearch:3.2.5 all &
nohup docker run --name=vearch_master -p 8817:8817 -p 9009:9009 -v $PWD/config.toml:/vearch/config.toml -v $PWD/logs:/vearch/logs vearch/vearch:3.2.5 all &
 docker run -it --name=vearch_master -p 8817:8817 -p 9009:9009 -v $PWD/config.toml:/vearch/config.toml -v $PWD/logs:/vearch/logs vearch/vearch:3.2.5 all
用的example配置文件, router端口改成了9009

**Comment by george-wang2016** [comment]
没人管，自己回复一个吧，之前用的centos7.4有问题，后来换了7.5就可以了
