### ISSUE TITLE
自动生成的_id为负数是正常的吗？

### ISSUE THREAD

**Issue by realdalabengba** [vearch/vearch#310]
插入数据返回如下：
{"_index":"db_test","_type":"d512","_id":"-4211133329032722799","status":200}。
请问这_id为负数是正常的吗？什么情况下会出现负数呢？

**Comment by zcdb** [comment]
这个是正常的，这是随机生成的，正数和负数都会出现的

**Comment by realdalabengba** [comment]
好的。
目前我部署了2台router，3台ps，3分片3副本，IVFPQ模式，总量为2500万512维测试数据。但对查询（请求只有向量，没其他过滤）的压测效果并不好，几十qps下响应时间都不太稳定，请问可能是什么原因呢？

**Comment by realdalabengba** [comment]
> 这个是正常的，这是随机生成的，正数和负数都会出现的

好的。
目前我部署了2台router，3台ps，3分片3副本，IVFPQ模式，总量为2500万512维测试数据。但对查询（请求只有向量，没其他过滤）的压测效果并不好，几十qps下响应时间都不太稳定，请问可能是什么原因呢？
