### ISSUE TITLE
求加交流群

### ISSUE THREAD

**Issue by terlanch** [vearch/vearch#312]
您好 可以加一下微信交流群吗 可以发到邮箱 841634721@qq.com

**Comment by gyd-a** [comment]
https://github.com/vearch/vearch/issues/307

**Comment by PatronusZ** [comment]
> #307

您好，这个链接里的二维码已经失效，能麻烦您提供一个新的吗？

**Comment by gyd-a** [comment]
![Uploading 企业咚咚20210111193138.png…]()

**Comment by gyd-a** [comment]
![微信群](https://user-images.githubusercontent.com/52058819/104177548-ec5d1f80-5443-11eb-9c24-14610ee756c6.png)

**Comment by jackleeforce** [comment]
二维码过期了，能否再发一下 @gyd-a

**Comment by richxnh** [comment]
同求二维码，谢谢！@gyd-a

**Comment by gyd-a** [comment]
![weixinqun](https://user-images.githubusercontent.com/52058819/106074438-d68b7200-6146-11eb-8cd2-ac5900bbc0c3.jpg)

**Comment by Adamyucc** [comment]
@gyd-a 能否再分享一下二维码，万分感谢

**Comment by php-cpm** [comment]
求加群
