### ISSUE TITLE
vearch最新版3.2.5跟faiss 1.6.4是兼容的吗

### ISSUE THREAD

**Issue by TopHK** [vearch/vearch#313]
现在编译gamma时会报错。（vearch/engine/index/impl/gpu/gamma_gpu_resources.cpp:19:41: fatal error: faiss/gpu/utils/MemorySpace.h: No such file or directory
 #include <faiss/gpu/utils/MemorySpace.h>
compilation terminated.）

gamma工程的文件index/impl/gpu/gamma_gpu_resources.cpp会引入头文件：MemorySpace.h
 18 #include "gamma_gpu_resources.h"
 19 #include <faiss/gpu/utils/MemorySpace.h>
 20 #include <faiss/impl/FaissAssert.h>
 21 #include <limits>
 22 #include "log.h"

但faiss 1.6.4版本的faiss/gpu/utils文件夹下并没有MemorySpace.h

**Comment by gyd-a** [comment]
vearch CPU模型是兼容faiss 1.6.4的，gpu模型需要用faiss 1.6.3。
https://github.com/facebookresearch/faiss/issues/1581 看着faiss gpu需要gcc6.1以上的支持，vearch兼容faiss gpu1.6.4估计还需要评估一下，应该等后面版本的faiss再统一兼容了。
