### ISSUE TITLE
启动时有大量的【Cannot delete 】日志，不知道有什么影响

### ISSUE THREAD

**Issue by xbugliu** [vearch/vearch#314]
版本：3.2.2

ERROR 2021-01-05 12:50:52,462 field_range_index.cc:315 Cannot delete [360745]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360745]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360746]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360746]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360747]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360747]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360748]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360748]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360749]
ERROR 2021-01-05 12:50:52,463 field_range_index.cc:315 Cannot delete [360749]
ERROR 2021-01-05 12:50:52,464 field_range_index.cc:315 Cannot delete [360750]
ERROR 2021-01-05 12:50:52,464 field_range_index.cc:315 Cannot delete [360750]
ERROR 2021-01-05 12:50:52,464 field_range_index.cc:315 Cannot delete [360751]
ERROR 2021-01-05 12:50:52,464 field_range_index.cc:315 Cannot delete [360751]
ERROR 2021-01-05 12:50:52,464 field_range_index.cc:315 Cannot delete [360752]
ERROR 2021-01-05 12:50:52,464 field_range_index.cc:315 Cannot delete [360752]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360753]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360753]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360754]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360754]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360755]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360755]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360756]
ERROR 2021-01-05 12:50:52,465 field_range_index.cc:315 Cannot delete [360756]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360757]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360757]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360758]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360758]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360759]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360759]
ERROR 2021-01-05 12:50:52,466 field_range_index.cc:315 Cannot delete [360760]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360760]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360761]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360761]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360762]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360762]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360763]
ERROR 2021-01-05 12:50:52,467 field_range_index.cc:315 Cannot delete [360763]
ERROR 2021-01-05 12:50:52,468 field_range_index.cc:315 Cannot delete [360764]
ERROR 2021-01-05 12:50:52,468 field_range_index.cc:315 Cannot delete [360764]
ERROR 2021-01-05 12:50:52,468 field_range_index.cc:315 Cannot delete [360765]
ERROR 2021-01-05 12:50:52,468 field_range_index.cc:315 Cannot delete [360765]
ERROR 2021-01-05 12:50:52,468 field_range_index.cc:315 Cannot delete [360766]
ERROR 2021-01-05 12:50:52,468 field_range_index.cc:315 Cannot delete [360766]

**Comment by wxingda** [comment]
最新版本已修复该问题，请及时更新

**Comment by xbugliu** [comment]
> 最新版本已修复该问题，请及时更新

能帮忙指一下是哪个commit吗，线上版本，先打个补丁，不能快速升级到3.2.5。

**Comment by wxingda** [comment]
https://github.com/vearch/gamma/commit/5de7389674e6b1abb5cc1114b9db4909ab9649db

**Comment by xbugliu** [comment]
thanks
