### ISSUE TITLE
搜索过程中，出现的一个问题？

### ISSUE THREAD

**Issue by qihaoxiansheng** [vearch/vearch#316]
您好，在搜索过程中出现这样一个问题，希望官方人员可以给与解决的建议。错误信息如下：
![image](https://user-images.githubusercontent.com/75019315/104000210-df88c380-51d8-11eb-8e15-3f994770eb1e.png)

**Comment by kevintony001** [comment]
麻烦排查一下参数，也可以发一下接口名称，已经对应的查询接口参数，我们帮你分析一下。

**Comment by qihaoxiansheng** [comment]
解决了，是特征码的问题。
