### ISSUE TITLE
怎么求与某个向量最相近的向量呢？

### ISSUE THREAD

**Issue by dongjinshark** [vearch/vearch#32]
我有一些向量，怎么求与某个向量最相近的向量呢？

**Comment by ansjsun** [comment]
首先你的向量距离是可以通过内积进行计算的，一个向量相当于一个文档。
然后你可以参考 https://github.com/vearch/vearch/blob/master/test/test_vearch.py
这个测试用例的流程 。 search 就是查询到与请求向量最相似的topn个文档的返回
