### ISSUE TITLE
长向量更新不了

### ISSUE THREAD

**Issue by JoeAu** [vearch/vearch#322]
版本:3.2.0单机版
space 
`{
          "name": "image",
          "partition_num": 1,
          "replica_num": 1,
          "engine": {
            "name": "gamma",
            "retrieval_type": "IVFPQ",
            "retrieval_param": {
                "metric_type": "L2",
                "ncentroids": 2048,
                "nsubvector": 64
            }
          },
          "properties": {
            "id": {
              "type": "string",
              "index": False
            },
            "tags": {
              "type": "string",
              "array": True,
              "index": True
            },
            "level": {
              "type": "integer",
              "index": True
            },
            "w": {
              "type": "float",
              "index": True
            },
            "vec": {
              "type": "vector",
              "store_type": "RocksDB",
              "dimension": 25088,
            },
            "vec2": {
              "type": "vector",
              "store_type": "RocksDB",
              "dimension": 2,
            }
          }
        }`

insert 和 update
`{
                "id": imgfile,
                "tags": tags,
                "level": level,
                "w": w,
                "vec": {
                    "feature": vec
                },
                "vec2": {
                    "feature": vec2
                }
            }`

bug一描述：
1. 删除space，重新创建space。用insert插入数据, _id为自己生成的md5 id，vec长度25088， vec2长度2，通过vec,vec2 search都没问题。
2. 执行update，_id不变，相同_id的记录vec，vec2的值都改变，修改返回成功，通过新的vec,search发现排序不正确, vec2 search没问题。。通过_id查询记录，发现vec没更新到，vec2更新了。
3. 步骤二改为insert，问题一样。vec没更新到，vec2更新了。

bug二描述：
delete by _id，后search，被删除的记录搜索不到，结果正确。但重新insert该记录（_id一样），被删除的记录仍然搜索不到。

**Comment by zcdb** [comment]
bug一是可能是实现的机制导致的，按照现在的实现机制是会都更新的，但是现在update是异步的，如果向量比较大的话，可能这个异步执行需要的时间会相比小向量更长，另外是优先执行建索引的操作，之后才是更新的操作。请问搜索的时候索引是否已经都建好了？如果都建好了update才会比较快的执行生效
bug二是一个已知问题，在新版本已经修复了。
