### ISSUE TITLE
数据写入过程中，会不时出现status=550的情况

### ISSUE THREAD

**Issue by qihaoxiansheng** [vearch/vearch#323]
您好，在数据写入过程中，会报这样的错误："status":550,"error":"gamma create doc err code :[-2]"。出现这个情况，在gamma日志中也定位不到具体的原因。
这个错误这段时间经常遇到，每次遇到这种情况，等待一段时间，又可以恢复正常，但不明白是什么原因。

**Comment by qihaoxiansheng** [comment]
这个是gamma.log日志中的内容：
INFO 2021-01-15 16:07:28,831 table.cc:45 Table created success!
INFO 2021-01-15 16:07:28,832 gamma_engine.cc:202 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-01-15 16:07:28,832 gamma_api.cc:48 Engine init successed!
INFO 2021-01-15 16:07:28,832 raw_vector_factory.h:36 Store parameters [{cache size=1073741824, segment size=1000000, compress=0}]
INFO 2021-01-15 16:07:28,832 vector_buffer_queue.cc:80 vector buffer queue init success! buffer byte size=1073741824, buffer vector size=65536, chunk number=1024, stored number=0
INFO 2021-01-15 16:07:28,833 vector_file_mapper.cc:62 map success! max byte size=163840000000, file path=/data/node/data/102/vectors/feature/vector.dat, mapped vector number=0
INFO 2021-01-15 16:07:28,833 mmap_raw_vector.cc:95 Init success! vector byte size=16384, flush batch size=1000, dimension=4096, ntotal=0, init max_size=1000000
INFO 2021-01-15 16:07:28,833 raw_vector.cc:222 raw vector init success! name=feature, has source=0, multi_vids=0, vector_byte_size=16384, dimension=4096, compress=0
INFO 2021-01-15 16:07:28,833 raw_vector.cc:461 start flushing, raw vector=feature
INFO 2021-01-15 16:07:28,833 vector_manager.cc:118 Create index model [IVFPQ]
INFO 2021-01-15 16:07:28,833 raw_vector.cc:388 flusher=feature is started!
INFO 2021-01-15 16:07:28,834 gamma_index_ivfpq.cc:197 ncentroids =2048, nsubvector =64, nbits_per_idx =8
INFO 2021-01-15 16:07:29,365 realtime_mem_data.cc:89 init success! total_mem_bytes=1474584576, current max size=20480000
INFO 2021-01-15 16:07:29,365 table.cc:172 Add field name [camId], type [4], index [0]
INFO 2021-01-15 16:07:29,365 table.cc:172 Add field name [communityId], type [0], index [0]
INFO 2021-01-15 16:07:29,365 table.cc:172 Add field name [depId2], type [0], index [0]
INFO 2021-01-15 16:07:29,365 table.cc:172 Add field name [depId3], type [0], index [0]
INFO 2021-01-15 16:07:29,366 table.cc:172 Add field name [grid], type [0], index [0]
INFO 2021-01-15 16:07:29,366 table.cc:172 Add field name [shotTime], type [1], index [0]
INFO 2021-01-15 16:07:29,366 table.cc:172 Add field name [_id], type [4], index [0]
INFO 2021-01-15 16:07:29,547 table.cc:227 Create table 102 success!
INFO 2021-01-15 16:07:29,547 gamma_engine.cc:491 create table [102] success!
INFO 2021-01-15 16:07:29,548 table.cc:79 the key=table_dumped_num isn't in db, skip loading
INFO 2021-01-15 16:07:29,633 raw_vector.cc:394 flusher=feature exit successfully!
INFO 2021-01-15 16:07:29,633 raw_vector.cc:471 stop flushing, raw vector=feature
INFO 2021-01-15 16:07:29,634 mmap_raw_vector.cc:143 disk_vector_num=0, vec_num=0
INFO 2021-01-15 16:07:29,634 mmap_raw_vector.cc:180 load vectors success, nflushed=0
INFO 2021-01-15 16:07:29,634 raw_vector.cc:461 start flushing, raw vector=feature
INFO 2021-01-15 16:07:29,634 vector_manager.cc:622 vector [feature] load success!
INFO 2021-01-15 16:07:29,634 raw_vector.cc:388 flusher=feature is started!
INFO 2021-01-15 16:07:29,634 gamma_engine.cc:1011 load engine success! max docid=0, load directory=, clean directorys(not done)=[]
INFO 2021-01-15 16:07:29,847 table.cc:45 Table created success!
INFO 2021-01-15 16:07:29,847 gamma_engine.cc:202 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-01-15 16:07:29,847 gamma_api.cc:48 Engine init successed!
INFO 2021-01-15 16:07:29,847 raw_vector_factory.h:36 Store parameters [{cache size=1073741824, segment size=1000000, compress=0}]
INFO 2021-01-15 16:07:29,848 vector_buffer_queue.cc:80 vector buffer queue init success! buffer byte size=1073741824, buffer vector size=65536, chunk number=1024, stored number=0
INFO 2021-01-15 16:07:29,848 vector_file_mapper.cc:62 map success! max byte size=163840000000, file path=/data/node/data/104/vectors/feature/vector.dat, mapped vector number=0
INFO 2021-01-15 16:07:29,848 mmap_raw_vector.cc:95 Init success! vector byte size=16384, flush batch size=1000, dimension=4096, ntotal=0, init max_size=1000000
INFO 2021-01-15 16:07:29,848 raw_vector.cc:222 raw vector init success! name=feature, has source=0, multi_vids=0, vector_byte_size=16384, dimension=4096, compress=0
INFO 2021-01-15 16:07:29,848 raw_vector.cc:461 start flushing, raw vector=feature
INFO 2021-01-15 16:07:29,848 vector_manager.cc:118 Create index model [IVFPQ]
INFO 2021-01-15 16:07:29,848 raw_vector.cc:388 flusher=feature is started!
INFO 2021-01-15 16:07:29,848 gamma_index_ivfpq.cc:197 ncentroids =2048, nsubvector =64, nbits_per_idx =8
INFO 2021-01-15 16:07:30,065 raw_vector.cc:418 flusher waiting......, expected num=2101776, flushed num=2101771
INFO 2021-01-15 16:07:30,387 realtime_mem_data.cc:89 init success! total_mem_bytes=1474584576, current max size=20480000
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [camId], type [4], index [0]
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [communityId], type [0], index [0]
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [depId2], type [0], index [0]
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [depId3], type [0], index [0]
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [grid], type [0], index [0]
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [shotTime], type [1], index [0]
INFO 2021-01-15 16:07:30,387 table.cc:172 Add field name [_id], type [4], index [0]
INFO 2021-01-15 16:07:30,486 table.cc:227 Create table 104 success!
INFO 2021-01-15 16:07:30,486 gamma_engine.cc:491 create table [104] success!
INFO 2021-01-15 16:07:30,487 table.cc:79 the key=table_dumped_num isn't in db, skip loading
INFO 2021-01-15 16:07:30,548 raw_vector.cc:394 flusher=feature exit successfully!
INFO 2021-01-15 16:07:30,548 raw_vector.cc:471 stop flushing, raw vector=feature
INFO 2021-01-15 16:07:30,548 mmap_raw_vector.cc:143 disk_vector_num=0, vec_num=0
INFO 2021-01-15 16:07:30,548 mmap_raw_vector.cc:180 load vectors success, nflushed=0
INFO 2021-01-15 16:07:30,549 raw_vector.cc:461 start flushing, raw vector=feature
INFO 2021-01-15 16:07:30,549 raw_vector.cc:388 flusher=feature is started!
INFO 2021-01-15 16:07:30,549 vector_manager.cc:622 vector [feature] load success!
INFO 2021-01-15 16:07:30,549 gamma_engine.cc:1011 load engine success! max docid=0, load directory=, clean directorys(not done)=[]
ERROR 2021-01-15 16:07:32,716 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,819 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,819 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,902 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,902 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,902 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,903 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,903 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,903 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,903 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,903 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,909 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:32,909 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,018 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,018 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,018 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,018 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,018 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,020 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,020 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,020 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,020 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,020 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,020 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,021 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,021 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,021 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,025 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,048 table.cc:336 Field num [6] not equal to [7]
ERROR 2021-01-15 16:07:33,049 table.cc:336 Field num [6] not equal to [7]

**Comment by zcdb** [comment]
建表语句和插入语句可以发一下吗？报错信息显示你插入数据的时候少插了一个字段的数据

**Comment by qihaoxiansheng** [comment]
根据你说的，解决这个问题了，谢啦
