### ISSUE TITLE
ps服务拒绝连接

### ISSUE THREAD

**Issue by qihaoxiansheng** [vearch/vearch#325]
您好，ps服务在使用过程中，出现了connection refused情况，这一般是什么原因造成的？

**Comment by zcdb** [comment]
可以提供一下详细的日志信息吗？如PS.*.LOG？

**Comment by qihaoxiansheng** [comment]
您好，下面是PS.ERROR.LOG中的日志文件
ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]

**Comment by qihaoxiansheng** [comment]
上次出现问题后，删除了一些库之后变得正常了，今天又出现了拒绝连接的情况，

**Comment by yktang** [comment]
> 您好，下面是PS.ERROR.LOG中的日志文件
> ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,945 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,945 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,946 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,946 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,947 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,947 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,948 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,948 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,949 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,949 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]
> ERROR 2021-02-03 10:07:30,950 log_util.go:62 partition_not_leader
> ERROR 2021-02-03 10:07:30,950 handler_document.go:222 Add doc failed, err: [partition_not_leader]

请问这个问题解决了吗？我也是一样的问题
