### ISSUE TITLE
IVFPQ + HNSW + OPQ 索引内存占用问题

### ISSUE THREAD

**Issue by realdalabengba** [vearch/vearch#326]
您好，我使用的版本是3.2.0，IVFPQ + HNSW + OPQ索引，数据量为10亿（ANN_SIFT1B数据集）。
配置：
`{
    "name": "d128",
    "partition_num": 64,
    "replica_num": 2,
    "engine": {
        "name": "gamma",
        "index_size": 3276800,
        "id_type": "Long",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "L2",
            "ncentroids": 32768,
            "nsubvector": 64,
            "hnsw" : {
                "nlinks": 32,
                "efConstruction": 200,
                "efSearch": 64
            },
            "opq": {
                "nsubvector": 64
            }
        }
    },
    "properties": {
        "pic_vector": {
            "type": "vector",
            "dimension": 128,
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 1024,
                "compress": false    
            }
        }
    }
}`

现象：数据插入完后，内存一直在增长，目前总使用内存2300G。各个机器文档数均匀，但内存使用分布为20G至60G。
问题：
1、这内存使用量是不是不太合理？
2、为什么内存使用会怎么不均匀呢？

感谢！

**Comment by zcdb** [comment]
可以提高下curl -XGET {{MASTER}}/_cluster/health 和 curl -XGET {{MASTER}}/_cluster/stats 返回的结果吗？另外可以提供下gamma.log方便我们查看具体的日志信息吗？

**Comment by realdalabengba** [comment]
[health_json.log](https://github.com/vearch/vearch/files/5929858/health_json.log
[stats_json.log](https://github.com/vearch/vearch/files/5929861/stats_json.log)
)
HI，上面是log信息。IVFPQ索引在亿级别数量级时都会有这样的问题，重启后内存会降低。

**Comment by realdalabengba** [comment]
[health_json.log](https://github.com/vearch/vearch/files/5929871/health_json.log)
[stats_json.log](https://github.com/vearch/vearch/files/5929872/stats_json.log)
HI，上面是返回结果，IVFPQ也会有同样的问题，数据量达到几千万或者亿级别，机器内存使用量开始分化，有的很高，重启服务后内存降低很多。是不是gamma有内存没有释放？

**Comment by zcdb** [comment]
只有插入操作吗？有其他操作吗？

**Comment by realdalabengba** [comment]
没其他操作，一般当分区建立索引后，分化就会比较明显，有的机器内存消耗增大很多。我观察到，有的机器有两个StateLeader分片，有的一个，有的都是StateFollower，一般2个leader会是都是StateFollower的两倍。我猜想是不是StateLeader处理referful 写的时候有内存泄漏呢
