### ISSUE TITLE
Couldn't follow exactly the QuickStart Guide: Image Search Returns 0 Hit

### ISSUE THREAD

**Issue by jinzishuai** [vearch/vearch#327]
Here is the procedure

# 1. Start Services

## 1. Run vearch-3.2.5 container

* get docker image from [docker hub](https://hub.docker.com/r/vearch/vearch)
```
docker pull vearch/vearch:3.2.5
```
* Run the container
```
seki@xubuntu-20:~/src/vearch/config$ pwd
/home/seki/src/vearch/config
seki@xubuntu-20:~/src/vearch/config$ ls
config.go  config.toml  config.toml.example  images
seki@xubuntu-20:~/src/vearch/config$ docker run --rm -p 8817:8817 -p 9001:9001 -v $PWD/config.toml:/vearch/config.toml  vearch/vearch:3.2.5 all 
```

## 1.2 Start Python Plugin on the host server/VM

Make sure the submodule is checked out
```
seki@xubuntu-20:~/src/vearch/plugin$ ./bin/run.sh image
```

# 2. Follow the [QuickStart](https://github.com/vearch/vearch/blob/master/docs/Quickstart.md)

* create db: `curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' http://127.0.0.1:4101/db/_create`: it worked
* create space: it worked too.
```
curl -XPUT -H "content-type: application/json" -d' { "name": "test",
"dynamic_schema": "strict", "partition_num": 2, "replica_num": 1, "engine":
{"name":"gamma","index_size":10000,	"retrieval_type": "IVFPQ", "retrieval_param": {"metric_type": "InnerProduct","ncentroids": -1,"nsubvector": -1}}, "properties": { "url": { "type": "keyword", "index":true}, "feature1": { "type": "vector", "dimension":512, "format": "normalization"}}} ' http://127.0.0.1:4101/space/test/_create
```
* insert data: note that the output is not exactly the same as in the documentation.
```
seki@xubuntu-20:~$ curl -XPOST -H "content-type: application/json"  -d' { "url": "../images/COCO_val2014_000000123599.jpg", "feature1":{"feature":"../images/COCO_val2014_000000123599.jpg"}} ' http://127.0.0.1:4101/test/test/AW63W9I4JG6WicwQX_RC
{"_index":"test","_type":"test","_id":"AW63W9I4JG6WicwQX_RC","status":200}
```
**I wonder if I did this part correcttly, particularly about the url. Does the URL refer to locations on my client or it is already in the plugin/vearch service?** It seems that the above image exists relative to the `src` folder of the plugin.
```
(yolo5-zerobox) seki@xubuntu-20:~/src/vearch/plugin/src$ pwd
/home/seki/src/vearch/plugin/src
(yolo5-zerobox) seki@xubuntu-20:~/src/vearch/plugin/src$ ls ../images/COCO_val2014_000000123599.jpg -l
-rw-rw-r-- 1 seki seki 27911 Jan  9 20:54 ../images/COCO_val2014_000000123599.jpg
(yolo5-zerobox) seki@xubuntu-20:~/src/vearch/plugin/src$ 
```
* search: **This is where it is really problematic: since we are searching for the exactly the same image, shouldn't we get a hit?**
```
seki@xubuntu-20:~$ curl -H "content-type: application/json" -XPOST -d '{ "query": { "sum": [{"feature":"../images/COCO_val2014_000000123599.jpg", "field":"feature1"}]}}' http://127.0.0.1:4101/test/test/_search
{"took":0,"timed_out":false,"_shards":{"total":2,"failed":2},"hits":{"total":0,"max_score":-1}}
```

Could  you please help me find out what I did wrong? Thank you very much!

**Comment by gDreamcatcher** [comment]
add  a param **"is_brute_search":1**  in you request, eg:
```bash
curl -H "content-type: application/json" -XPOST -d '{ "query": { "sum": [{"feature":"../images/COCO_val2014_000000123599.jpg", "field":"feature1"}]},"is_brute_search":1}' http://127.0.0.1:4101/test/test/_search
```

**Comment by jinzishuai** [comment]
@gDreamcatcher  it worked! Thank you so much!

Should the quickstart guide be updated with this field?

**Comment by gDreamcatcher** [comment]
Thank you for your advice,  it is be updated in commit[`b2002375f1570ea107d6ea1f95c57411cd89bb97`]
