### ISSUE TITLE
Docker Hub 上面的 vearch 和 vearch_env 这两个镜像有没有使用文档

### ISSUE THREAD

**Issue by jackleeforce** [vearch/vearch#328]
看了下官方的安装说明文档，貌似比较复杂，需要编译。于是搜索了下docker的部署方案，发现下面两个镜像：

- https://hub.docker.com/r/vearch/vearch
- https://hub.docker.com/r/vearch/vearch_env

最后一次更新还是十几天前，但是这两个镜像好像在官方文档里面并没有体现：https://vearch.readthedocs.io/zh_CN/latest/quick-start-guide.html

能否写写这两个镜像的使用？

**Comment by gyd-a** [comment]
https://github.com/vearch/vearch/blob/master/docs/SourceCompileDeploymentZH_CN.md这个文档里面有使用docker部署的方式。

**Comment by jackleeforce** [comment]
@gyd-a thanks
