### ISSUE TITLE
GPU创建空间失败

### ISSUE THREAD

**Issue by PatronusZ** [vearch/vearch#332]
能够成功建立IVFPQ的表空间，且能成功插入/查询图片。但当我尝试建立GPU的表空间时，出现报错：{"code":550,"msg":"create partition err: create gamma table has err:[-2] "}

vearch版本：3.2.0，docker部署，参照：https://github.com/vearch/vearch/blob/master/docs/SourceCompileDeployment.md#use-vearch-image-deploy
docker启动服务时的语句如下：docker run -itd --gpus all --name=vearch_test1 -p 8817:8817 -p 9001:9001 --restart=always -v $PWD/config/config.toml:/vearch/config.toml -v $PWD/logs:/vearch/logs vearch/vearch:3.2.0 all
按照Quickstart文档启用了图像插件：https://github.com/vearch/vearch/blob/master/docs/Quickstart.md#deploy-your-own-plugin-service

建库语句：curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' http://127.0.0.1:4101/db/_create
建表语句参照：https://github.com/vearch/vearch/blob/master/docs/APILowLevelOnGPU.md#create-space
实际输入的建表语句：curl -v --user "root:secret" -H "content-type: application/json" -XPUT -d' {"name":"vector_space","dynamic_schema":"strict","partition_num":1,"replica_num":1,"engine":{"name":"gamma","index_size":0,"max_size":100000,"retrieval_type":"GPU","retrieval_param":{"ncentroids":1024,"nsubvector":-1}},"properties":{"string":{"type":"keyword","index":true},"int":{"type":"integer","index":true},"float":{"type":"float","index":true},"vector":{"type":"vector","model_id":"img","dimension":128,"format":"normalization"},"string_tags":{"type":"string","array":true,"index":true},"int_tags":{"type":"integer","array":true,"index":true},"float_tags":{"type":"float","array":true,"index":true}},"models":[{"model_id":"vgg16","fields":["string"],"out":"feature"}]} ' http://127.0.0.1:4101/space/test/_create

可能会用到的日志
[gamma.log](https://github.com/vearch/vearch/files/5872205/gamma.log)
[ALL.ERROR.log](https://github.com/vearch/vearch/files/5872206/ALL.ERROR.log)

**Comment by wxingda** [comment]
https://github.com/vearch/gamma/blob/25b601743e2ba181cf81d9faab78c015d7ca0e05/CMakeLists.txt#L12
如果需要用gpu版，需要把上面那行的off改成on，然后重新编译gamma

**Comment by PatronusZ** [comment]
> https://github.com/vearch/gamma/blob/25b601743e2ba181cf81d9faab78c015d7ca0e05/CMakeLists.txt#L12
> 如果需要用gpu版，需要把上面那行的off改成on，然后重新编译gamma

好的我会尝试下，另外我是按照https://github.com/vearch/vearch/blob/master/docs/SourceCompileDeployment.md#use-vearch-image-deploy当中的步骤进行docker部署，那么编译gamma是在宿主机进行？还是说需要进入容器后，将源代码git clone下来编译？

**Comment by PatronusZ** [comment]
已暂时放弃docker部署，使用源代码重新编译，问题解决
