### ISSUE TITLE
属性（时间）过滤问题

### ISSUE THREAD

**Issue by qihaoxiansheng** [vearch/vearch#333]
您好，vearch使用过程中，遇到了一个属性过滤的问题，希望可以得到解答。
我使用的vearch版本是3.2.0，使用vearch的range对时间进行属性过滤。比如一条特征码的的索引为10000，time属性的索引为
17：26，然后gte和lte的值为：[17：00, 17：30]。使用这个时间区间进行搜索时，不会返回索引为10000的这条特征码。当修改gte和lte的值为[15:00, 17:30]，再次进行搜索时，可以返回索引为10000的这条特征码。

**Comment by wxingda** [comment]
3.2.0的过滤有些不太准确，最新版的3.2.5已经修复该问题

**Comment by qihaoxiansheng** [comment]
最新版的3.2.5中，源码中哪个地方修改了该问题？
![image](https://user-images.githubusercontent.com/75019315/105933069-c90fb280-6088-11eb-9a95-8a33fd820c91.png)
![image](https://user-images.githubusercontent.com/75019315/105933091-d167ed80-6088-11eb-913d-a3fccc0e740c.png)

**Comment by wxingda** [comment]
https://github.com/vearch/gamma/commit/5de7389674e6b1abb5cc1114b9db4909ab9649db
可以参考下这次提交

**Comment by qihaoxiansheng** [comment]
这里面哪个位置，可以具体标一下吗？麻烦你了啊！
![image](https://user-images.githubusercontent.com/75019315/105936184-2e19d700-608e-11eb-9faf-81a38c581e63.png)

**Comment by wxingda** [comment]
那次提交的代码都需要同步修改
