### ISSUE TITLE
Is there an API to list all data?

### ISSUE THREAD

**Issue by jinzishuai** [vearch/vearch#334]
After many inserts using API like `curl -XPOST -H "content-type: application/json"  -d' { "url": "../images/COCO_val2014_000000123599.jpg", "feature1":{"feature":"../images/COCO_val2014_000000123599.jpg"}} ' http://127.0.0.1:4101/test/test/AW63W9I4JG6WicwQX_RC`, is there a way to get a list of all objects within the same space?

Thanks a lot

**Comment by zcdb** [comment]
There is no such interface now

**Comment by jinzishuai** [comment]
thanks @zcdb. Is there any other way to get that kind of information, even indirectly or manually? Thanks

**Comment by zcdb** [comment]
If you have to get it, gamma has an interface to get data through doc_id which starts from 0. In theory, you can get all the data from 0 to the amount of data inserted. The interface is GetDocByDocID，https://github.com/vearch/gamma/blob/master/c_api/gamma_api.h:L126. Maybe you can get all data by it.
