### ISSUE TITLE
建库错误：invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ChenCongZhu2017** [vearch/vearch#338]
建库 curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' 172.17.x.x:9012/db/_create

提示按名称找不到数据库，请问有大佬碰到过吗？

版本
vearch 3.2.5
faiss 1.6.3 
rocksdb-6.17.0

ERROR 2021-01-27 19:33:46,279 log_util.go:51 can not found db by name:[db] err:[db_notexists]
ERROR 2021-01-27 19:33:46,279 http_server.go:334 recover panic. runtime error: invalid memory address or nil pointer dereference, goroutine 307 [running]:
github.com/vearch/vearch/util/netutil.(*Server).CatchPanicAndSendErrReply(0xc0000a3640, 0x17f5ba0, 0xc0008f2380)
	/home/vearch/go/src/github.com/vearch/vearch/util/netutil/http_server.go:331 +0xba
panic(0x14320a0, 0x225ac90)
	/usr/lib/golang/src/runtime/panic.go:969 +0x1b9
github.com/vearch/vearch/router/document.docParse(0x17fb9e0, 0xc0010d8080, 0xc000893f00, 0x0, 0xc0010c0c90, 0xc000ef4a48, 0x7)
	/home/vearch/go/src/github.com/vearch/vearch/router/document/doc_parse.go:695 +0x71
github.com/vearch/vearch/router/document.(*DocumentHandler).handleUpdateDoc(0xc000337300, 0x17fb9e0, 0xc0010d8080, 0x17f5ba0, 0xc0008f2380, 0xc000893f00, 0x17e6b60, 0xc0000a8770, 0x0, 0x0, ...)
	/home/vearch/go/src/github.com/vearch/vearch/router/document/doc_http.go:231 +0x1b1
github.com/vearch/vearch/util/netutil.(*Server).doHandles.func1(0x17f5ba0, 0xc0008f2380, 0xc000893f00)
	/home/vearch/go/src/github.com/vearch/vearch/util/netutil/http_server.go:288 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000b7ecc0, 0x17f5ba0, 0xc0008f2380, 0xc000893f00)
	/usr/lib/golang/src/net/http/server.go:2042 +0x44
github.com/vearch/vearch/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0009289a0, 0x17f5ba0, 0xc0008f2380, 0xc000893d00)
	/home/vearch/go/src/github.com/vearch/vearch/vendor/github.com/gorilla/mux/mux.go:162 +0x106
github.com/vearch/vearch/util/netutil.(*Server).ServeHTTP(0xc0000a3640, 0x17f5ba0, 0xc0008f2380, 0xc000893d00)
	/home/vearch/go/src/github.com/vearch/vearch/util/netutil/http_server.go:142 +0x63
net/http.serverHandler.ServeHTTP(0xc0000ce380, 0x17f5ba0, 0xc0008f2380, 0xc000893d00)
	/usr/lib/golang/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00012f720, 0x17fb9e0, 0xc0007f5f40)
	/usr/lib/golang/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2969 +0x36c

**Comment by kevintony001** [comment]
执行完成创建db后，需要创建space，我看到在插入数据的时候报错的，麻烦看一下是否创建db以及space成功，如果都创建成功的话，麻烦发一下创建space的建表语句，以及插入数据的参数，谢谢。

**Comment by kevintony001** [comment]
麻烦参考建库建表以及插入数据文档：https://github.com/vearch/zh_docs/tree/master/docs/source/use_op

**Comment by gyd-a** [comment]
rockdb建议使用v3.2.2版本的，https://github.com/vearch/vearch/blob/master/docs/BinaryInstallationZH_CN.md

**Comment by ChenCongZhu2017** [comment]
> 执行完成创建db后，需要创建space，我看到在插入数据的时候报错的，麻烦看一下是否创建db以及space成功，如果都创建成功的话，麻烦发一下创建space的建表语句，以及插入数据的参数，谢谢。

找到原因了，是我端口错了，谢谢

**Comment by ChenCongZhu2017** [comment]
> rockdb建议使用v6.2.2版本的，https://github.com/vearch/vearch/blob/master/docs/SourceCompileDeploymentZH_CN.md

好的，谢谢~
