### ISSUE TITLE
create partition err: create gamma table has err:[4294967294]

### ISSUE THREAD

**Issue by winself** [vearch/vearch#34]
I creat table when I use 
"curl -XPOST -H "content-type:application/json" -d '{
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "resnet",
        "dimension": 2048
    }
}' http://127.0.0.1:4101/test/test/_create " 

It got "{"code": 550, "msg": "create partition err: create gamma table has err:[4294967294] "}" 

I find when I change the dimension ,it meets the problem . If I use 512 as the dimension,it successed. 

why? 
Look forward to your reply. 
Thank you ~

**Comment by wxingda** [comment]
Please provide the **gamma.log** content.

**Comment by winself** [comment]
INFO 2019-11-01 10:51:07,914 profile.cc:42 Profile created success!
INFO 2019-11-01 10:51:07,914 gamma_engine.cc:164 GammaEngine setup successed!
INFO 2019-11-01 10:51:07,914 gamma_api.cc:315 Engine init successed!
INFO 2019-11-01 10:51:07,914 vector_manager.cc:86 ivfpq parameters: metric_type=0, nprobe=10, ncentroids=256, nsubvector=32, nbits_per_idx=8
ERROR 2019-11-01 10:51:07,914 memory_raw_vector.cc:34 vector memory alloc err , max_doc_size_ [10000000], dimension_ [2048]
ERROR 2019-11-01 10:51:07,914 vector_manager.cc:112 Raw vector feature init error, code [2]!
INFO 2019-11-01 10:51:07,914 profile.cc:204 Add field name [_id], type [4], index [0]
INFO 2019-11-01 10:51:07,914 profile.cc:204 Add field name [_source], type [4], index [0]
INFO 2019-11-01 10:51:07,914 profile.cc:204 Add field name [_version], type [1], index [0]
INFO 2019-11-01 10:51:07,914 profile.cc:204 Add field name [_slot], type [0], index [0]
INFO 2019-11-01 10:51:07,914 profile.cc:204 Add field name [label], type [4], index [0]
INFO 2019-11-01 10:51:07,914 profile.cc:204 Add field name [imageurl], type [4], index [0]
INFO 2019-11-01 10:51:07,915 profile.cc:204 Add field name [boundingbox], type [4], index [0]
INFO 2019-11-01 10:51:07,915 profile.cc:228 Create table 20 success!
ERROR 2019-11-01 10:51:07,915 gamma_engine.cc:395 Cannot create table!
INFO 2019-11-01 10:51:07,967 profile.cc:42 Profile created success!
INFO 2019-11-01 10:51:07,967 gamma_engine.cc:164 GammaEngine setup successed!
INFO 2019-11-01 10:51:07,967 gamma_api.cc:315 Engine init successed!
INFO 2019-11-01 10:51:07,967 vector_manager.cc:86 ivfpq parameters: metric_type=0, nprobe=10, ncentroids=256, nsubvector=32, nbits_per_idx=8
ERROR 2019-11-01 10:51:07,967 memory_raw_vector.cc:34 vector memory alloc err , max_doc_size_ [10000000], dimension_ [2048]
ERROR 2019-11-01 10:51:07,967 vector_manager.cc:112 Raw vector feature init error, code [2]!
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [_id], type [4], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [_source], type [4], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [_version], type [1], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [_slot], type [0], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [boundingbox], type [4], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [label], type [4], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:204 Add field name [imageurl], type [4], index [0]
INFO 2019-11-01 10:51:07,967 profile.cc:228 Create table 21 success!
ERROR 2019-11-01 10:51:07,967 gamma_engine.cc:395 Cannot create table!

@wxingda  


I am  not familiar with go and distributed system.
Look forward to your reply.
Thank you ~

**Comment by winself** [comment]
single mode @wxingda

**Comment by ansjsun** [comment]
sorry， it is our mistake
the default engine has 10 000 000 document , but you create 2048 , means 2048*40000000 bytes need , your memory not enough。next version we will fixed it.

now you have two way to fix it .

> open file vearch/plugin/src/main.py in line 272

````
"engine": {"name": "gamma", "metric_type": method},
````
to 
````
"engine": {"name": "gamma", "metric_type": method , "max_size":100000},
````

**Comment by qiutianme** [comment]
ERROR 2019-11-01 10:51:07,967 memory_raw_vector.cc:34 vector memory alloc err , max_doc_size [10000000], dimension [2048]

This is out of memory error，10 millions is too big to your system. Two solutions: 

1. You can reduce the max_size parameter when creating the table. reference: https://vearch.readthedocs.io/en/latest/use_op/op_space.html#create-space

2. Please pull the latest code(v0.2) from github, and use Mmap store type which can store raw vector to disk

**Comment by gDreamcatcher** [comment]
if you want use resnet model or alexnet model , please remenber change these:
1、update vgg16 to resnet or alexnet in the dict image_config dict in the file plugin/src/config.py
2、add self.load_model() in the __init__ method of BaseModel and change the dimision to right num(alexnet=256, resnet=2048) in plugin/src/image_retrieval/image_extract/resnet.py or alexnet.py.Or you just need pull the newest code!

What's more, if you want change params (eg the num of ps and max_size of docs) when creating table, you  can use this API.
https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md
There are some demos for creating tabel in this file.
https://github.com/vearch/vearch/blob/master/test/test_vearch.py

Last at all , thanks for your issue, if you have any questions, please contact us in time and we will answer them for you as soon as possible！

**Comment by winself** [comment]
thank you very much  ~  @ansjsun @qiutianme @gDreamcatcher @wxingda  

I will try it again . I learn a lot from you. thank you again.
