### ISSUE TITLE
单机创建表空间失败 create partition err: create gamma table has err:[-2]

### ISSUE THREAD

**Issue by ChenCongZhu2017** [vearch/vearch#341]
ldd vearch

	linux-vdso.so.1 =>  (0x00007ffea4bec000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efd1656f000)
	libgamma.so.0.1 => /home/vearch/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1 (0x00007efd161e9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007efd15e1b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efd1678b000)
	libfaiss.so => /home/vearch/vearch_libs/faiss-1.6.3-install/lib/libfaiss.so (0x00007efd15a97000)
	librocksdb.so.6.2 => /home/vearch/vearch_libs/rocksdb-6.2.2-install/lib/librocksdb.so.6.2 (0x00007efd15366000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007efd14f03000)
	libzstd.so.1 => /usr/local/lib/libzstd.so.1 (0x00007efd168e0000)
	libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007efd12a0f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007efd12707000)
	libm.so.6 => /lib64/libm.so.6 (0x00007efd12405000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007efd121df000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007efd11fc9000)
	librt.so.1 => /lib64/librt.so.1 (0x00007efd11dc1000)
	libz.so.1 => /lib64/libz.so.1 (0x00007efd11bab000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007efd119a7000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007efd11685000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007efd11449000)

ldd /home/vearch/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1

	linux-vdso.so.1 =>  (0x00007ffd01d89000)
	libfaiss.so => /home/vearch/vearch_libs/faiss-1.6.3-install/lib/libfaiss.so (0x00007fde2ebdf000)
	librocksdb.so.6.2 => /home/vearch/vearch_libs/rocksdb-6.2.2-install/lib/librocksdb.so.6.2 (0x00007fde2e4ae000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fde2e04b000)
	libzstd.so.1 => /usr/local/lib/libzstd.so.1 (0x00007fde2f43f000)
	libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007fde2bb57000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fde2b84f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fde2b54d000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fde2b327000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fde2b111000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fde2aef5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fde2ab27000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fde2f2e9000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fde2a91f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fde2a709000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fde2a505000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fde2a1e3000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fde29fa7000)

创建库操作：
curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' 172.17.16.16:8817/db/_create

参考例子创建表空间
```
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "space1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 32
        }
    },
    "properties": {
        "field1": {
            "type": "keyword"
        },
        "field2": {
            "type": "integer"
        },
        "field3": {
            "type": "float",
            "index": true
        },
        "field4": {
            "type": "string",
            "array": true,
            "index": true
        },
        "field5": {
            "type": "integer",
            "index": true
        },
        "field6": {
            "type": "vector",
            "dimension": 128
        },
        "field7": {
            "type": "vector",
            "dimension": 256,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048,
                "compress": false
            }
        }
    }
}
' 172.17.16.16:8817/space/test/_create
```
以下为gamma.log的错误日志 parse compress error
INFO 2021-01-28 15:47:40,928 gamma_api.cc:88 Version [[sha1]:25b6017 [author]:GitHub [time]:2021-01-07 15:57:14 +0800 [branch]: (HEAD, origin/master, origin/HEAD, master)]
INFO 2021-01-28 15:47:41,005 table.cc:48 Table created success!
INFO 2021-01-28 15:47:41,005 gamma_engine.cc:285 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-01-28 15:47:41,009 gamma_engine.cc:164 memory trim thread start......
INFO 2021-01-28 15:47:41,034 gamma_engine.cc:82 System info: threads_max [190181] max_map_count [65530] pid_max [32768]
INFO 2021-01-28 15:47:41,034 gamma_engine.cc:89 max_threads [32765] concurrent_threshold [1820]
INFO 2021-01-28 15:47:41,034 gamma_api.cc:52 Engine init successed!
ERROR 2021-01-28 15:47:41,034 raw_vector.cc:391 parse compress error
INFO 2021-01-28 15:47:41,034 table.cc:124 Table compress [0]
INFO 2021-01-28 15:47:41,034 table.cc:131 Add field name [_id], type [4], index [0]
INFO 2021-01-28 15:47:41,034 table.cc:131 Add field name [field5], type [0], index [1]
INFO 2021-01-28 15:47:41,034 table.cc:131 Add field name [field4], type [4], index [1]
INFO 2021-01-28 15:47:41,034 table.cc:131 Add field name [field3], type [2], index [1]
INFO 2021-01-28 15:47:41,034 table.cc:131 Add field name [field2], type [0], index [0]
INFO 2021-01-28 15:47:41,034 table.cc:131 Add field name [field1], type [4], index [0]
INFO 2021-01-28 15:47:41,035 table.cc:173 Create table 1 success! item length=27, field num=6
ERROR 2021-01-28 15:47:41,035 gamma_engine.cc:571 Cannot create table!
INFO 2021-01-28 15:47:41,109 table.cc:48 Table created success!
INFO 2021-01-28 15:47:41,109 gamma_engine.cc:285 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-01-28 15:47:41,109 gamma_api.cc:52 Engine init successed!
ERROR 2021-01-28 15:47:41,115 raw_vector.cc:391 parse compress error
INFO 2021-01-28 15:47:41,115 table.cc:124 Table compress [0]
INFO 2021-01-28 15:47:41,115 table.cc:131 Add field name [_id], type [4], index [0]
INFO 2021-01-28 15:47:41,115 table.cc:131 Add field name [field5], type [0], index [1]
INFO 2021-01-28 15:47:41,115 table.cc:131 Add field name [field4], type [4], index [1]
INFO 2021-01-28 15:47:41,115 table.cc:131 Add field name [field3], type [2], index [1]
INFO 2021-01-28 15:47:41,115 table.cc:131 Add field name [field2], type [0], index [0]
INFO 2021-01-28 15:47:41,115 table.cc:131 Add field name [field1], type [4], index [0]
INFO 2021-01-28 15:47:41,115 table.cc:173 Create table 1 success! item length=27, field num=6
ERROR 2021-01-28 15:47:41,115 gamma_engine.cc:571 Cannot create table!
INFO 2021-01-28 15:47:41,189 table.cc:48 Table created success!
INFO 2021-01-28 15:47:41,189 gamma_engine.cc:285 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-01-28 15:47:41,189 gamma_api.cc:52 Engine init successed!
ERROR 2021-01-28 15:47:41,189 raw_vector.cc:391 parse compress error
INFO 2021-01-28 15:47:41,189 table.cc:124 Table compress [0]
INFO 2021-01-28 15:47:41,189 table.cc:131 Add field name [_id], type [4], index [0]
INFO 2021-01-28 15:47:41,189 table.cc:131 Add field name [field5], type [0], index [1]
INFO 2021-01-28 15:47:41,189 table.cc:131 Add field name [field4], type [4], index [1]
INFO 2021-01-28 15:47:41,189 table.cc:131 Add field name [field3], type [2], index [1]
INFO 2021-01-28 15:47:41,189 table.cc:131 Add field name [field2], type [0], index [0]
INFO 2021-01-28 15:47:41,189 table.cc:131 Add field name [field1], type [4], index [0]
INFO 2021-01-28 15:47:41,189 table.cc:173 Create table 1 success! item length=27, field num=6
ERROR 2021-01-28 15:47:41,189 gamma_engine.cc:571 Cannot create table!

ALL.ERROR.log的log
ERROR 2021-01-28 15:47:41,035 gamma.go:94 creat table for gamma error table: space1 cost time :0.307597
ERROR 2021-01-28 15:47:41,115 gamma.go:94 creat table for gamma error table: space1 cost time :5.636226000000001
ERROR 2021-01-28 15:47:41,189 gamma.go:94 creat table for gamma error table: space1 cost time :0.222939
ERROR 2021-01-28 15:47:41,190 cluster_service.go:392 create partition err: create gamma table has err:[-2]
ERROR 2021-01-28 15:47:41,234 cluster_api.go:297 createSpaceService err: create partition err: create gamma table has err:[-2]

**Comment by gyd-a** [comment]
什么版本的代码？

**Comment by zcdb** [comment]
如果不使用压缩去掉"compress": false即可，如果要使用的话需要是个json串格式的语句,比如
“compress”: {
    "rate":16
}

**Comment by ChenCongZhu2017** [comment]
> 什么版本的代码？

现在master上主干代码

**Comment by ChenCongZhu2017** [comment]
> 如果不使用压缩去掉"compress": false即可，如果要使用的话需要是个json串格式的语句,比如
> “compress”: {
> "rate":16
> }

去掉compress之后可以创建了...
