### ISSUE TITLE
GPU查询及创建索引失败

### ISSUE THREAD

**Issue by PatronusZ** [vearch/vearch#342]
vearch版本：3.2.0_1，源码GPU编译，faiss 1.6.3，cuda 10.0
建库语句：curl -XPUT -H "content-type:application/json" -d '{"name": "test"}' http://127.0.0.1:4101/db/_create
建表语句：curl -XPUT -H "content-type: application/json" -d' { "name": "test3", "dynamic_schema": "strict", "partition_num": 2, "replica_num": 1, "engine": {"name":"gamma","index_size":0, "retrieval_type": "GPU", "retrieval_param": {"metric_type": "InnerProduct","ncentroids": 1024,"nsubvector": -1}}, "properties": { "url": { "type": "keyword", "index":true}, "feature1": { "type": "vector", "dimension":512, "format": "normalization"}}} ' http://127.0.0.1:4101/space/test/_create

按照QuickStart.md中提到的插件，使用IVFPQ建表并插入图片，可以正常查询；但改为使用上述语句进行GPU建表，并插入少量图片后，无法正常查询。
插入图片语句：curl -XPOST -H "content-type: application/json"  -d' { "url": "/home/vearch/datas/val2014/COCO_val2014_000000000502.jpg", "feature1":{"feature":"/home/vearch/datas/val2014/COCO_val2014_000000000502.jpg"}} ' http://127.0.0.1:4101/test/test3/1
查询语句：curl -H "content-type: application/json" -XPOST -d '{ "query": { "sum": [{"feature":"/home/vearch/datas/val2014/COCO_val2014_000000000042.jpg", "field":"feature1"}]}}' http://127.0.0.1:4101/test/test3/_search
提示报错：{"took":1,"timed_out":false,"_shards":{"total":2,"failed":2},"hits":{"total":0,"max_score":-1}}

后来猜测是因为GPU版本不支持自动创建索引，遂尝试调用_forcemerge接口创建索引：curl -XPOST http://127.0.0.1:9001/test/test3/_forcemerge
返回：{"_shards":{"total":2,"successful":2}}
依旧查询失败。
创建索引时gamma.log输出如下：
INFO 2021-01-28 02:58:31,548 gamma_index_ivfpq_gpu.cc:402 GPU indexing
ERROR 2021-01-28 02:58:31,549 gamma_index_ivfpq.cc:320 vector total count [0] less then 8192, failed!
ERROR 2021-01-28 02:58:31,549 vector_manager.cc:192 vector table feature1 indexing failed!
ERROR 2021-01-28 02:58:31,549 gamma_engine.cc:744 Create index failed!
INFO 2021-01-28 02:58:31,549 gamma_index_ivfpq_gpu.cc:402 GPU indexing
ERROR 2021-01-28 02:58:31,549 gamma_index_ivfpq.cc:320 vector total count [1] less then 8192, failed!
ERROR 2021-01-28 02:58:31,549 vector_manager.cc:192 vector table feature1 indexing failed!
ERROR 2021-01-28 02:58:31,549 gamma_engine.cc:744 Create index failed!

**Comment by wxingda** [comment]
gpu索引目前不支持暴力搜，所以需要至少插入8192条数据，建立索引后才能搜索

**Comment by PatronusZ** [comment]
@wxingda 建议将这个限制加到文档里，且gpu版本是否还有其他的限制未在文档中说明？
另外gamma.log日志此句是否拼写错误：
less then 8192 > less than 8192

**Comment by wxingda** [comment]
后续会更新文档，其他限制暂时没有，确实有拼写错误，欢迎提pull request共同开发
