### ISSUE TITLE
Patition分区导致磁盘空间翻倍

### ISSUE THREAD

**Issue by NLPOR** [vearch/vearch#346]
我的vearch版本是3.2.2, docker的：
1. 我两台机器两个ps节点，建表时设置patition参数时，这样设置：
"partition_num": 2,
"replica_num": 1,
然后curl master_server/_cluster/health   中返回的结果是下面这个
        "partition_num": 2,
        "replica_num": 2,
实际上我在往表中写数据的时候也发现磁盘是partition:1的两倍，不知道是什么原因，还请指导下，谢谢
如果需要详细的配置和建表参数，可以另发

**Comment by zcdb** [comment]
我们测试了一下这种情况，是没法发现这个问题的。测试的时候试试插入更多数据，比如20万或者更多。另外这个接口返回的结果是错误的，但是不影响使用，我们会修改下

**Comment by NLPOR** [comment]
好的，多谢，这个问题在写入数据量较多时没有这个问题，只是返回结果和写入少量数据时是一致的，误导性较大
