### ISSUE TITLE
设置向量压缩时建表报错

### ISSUE THREAD

**Issue by NLPOR** [vearch/vearch#347]
1. 我建表的时候想把向量压缩下，省点磁盘和内存，建表参数为vector参数为这样，
"vector": {
    "type": "vector",
    "model_id": "img",
    "dimension": 128,
    "store_param": {"compress": True},           
    "store_type": "RocksDB",
    "format": "normalization"
}
然后报了这个错： {"code":550,"msg":"create partition err: create gamma table has err:[-2] "}，不知为何
如果需要详细的配置文件和建表参数，可以另发

**Comment by zcdb** [comment]
如要使用压缩，请使用如下语法 "store_param": {"compress": {"rate": 16}},

**Comment by NLPOR** [comment]
好的，请问这样设置对精度和检索速度会有影响吗

**Comment by NLPOR** [comment]
我使用的版本是3.2.2的docker环境， 改为 "store_param": {"compress": {"rate": 16}}后还是同样报 {"code":550,"msg":"create partition err: create gamma table has err:[-2] "}，与"store_param": {"compress": True}无差别

**Comment by zcdb** [comment]
请问有安装zfp吗，可以贴一下gamma.log

**Comment by NLPOR** [comment]
运行建表语句时的gamma.log日志：
INFO 2021-02-01 06:36:43,698 gamma_api.cc:85 Version [[sha1]:d56163b [author]:GitHub [time]:2020-10-26 11:50:27 +0000 [branch]: (HEAD, origin/master, origin/HEAD)]
INFO 2021-02-01 06:36:43,769 table.cc:48 Table created success!
INFO 2021-02-01 06:36:43,769 gamma_engine.cc:212 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-02-01 06:36:43,769 gamma_api.cc:49 Engine init successed!
INFO 2021-02-01 06:36:43,769 gamma_engine.cc:89 memory trim thread start......
ERROR 2021-02-01 06:36:43,769 raw_vector.cc:395 parse compress error
INFO 2021-02-01 06:36:43,769 table.cc:125 Table compress [0]
INFO 2021-02-01 06:36:43,769 table.cc:132 Add field name [float], type [2], index [1]
INFO 2021-02-01 06:36:43,769 table.cc:132 Add field name [string], type [4], index [1]
INFO 2021-02-01 06:36:43,769 table.cc:132 Add field name [_id], type [4], index [0]
INFO 2021-02-01 06:36:43,769 table.cc:174 Create table 2 success! item length=14, field num=3
ERROR 2021-02-01 06:36:43,769 gamma_engine.cc:489 Cannot create table!
INFO 2021-02-01 06:36:43,833 table.cc:48 Table created success!
INFO 2021-02-01 06:36:43,833 gamma_engine.cc:212 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-02-01 06:36:43,833 gamma_api.cc:49 Engine init successed!
ERROR 2021-02-01 06:36:43,833 raw_vector.cc:395 parse compress error
INFO 2021-02-01 06:36:43,833 table.cc:125 Table compress [0]
INFO 2021-02-01 06:36:43,833 table.cc:132 Add field name [float], type [2], index [1]
INFO 2021-02-01 06:36:43,833 table.cc:132 Add field name [string], type [4], index [1]
INFO 2021-02-01 06:36:43,833 table.cc:132 Add field name [_id], type [4], index [0]
INFO 2021-02-01 06:36:43,833 table.cc:174 Create table 1 success! item length=14, field num=3
ERROR 2021-02-01 06:36:43,833 gamma_engine.cc:489 Cannot create table!
INFO 2021-02-01 06:36:43,896 table.cc:48 Table created success!
INFO 2021-02-01 06:36:43,896 gamma_engine.cc:212 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-02-01 06:36:43,896 gamma_api.cc:49 Engine init successed!
ERROR 2021-02-01 06:36:43,896 raw_vector.cc:395 parse compress error
INFO 2021-02-01 06:36:43,896 table.cc:125 Table compress [0]
INFO 2021-02-01 06:36:43,896 table.cc:132 Add field name [float], type [2], index [1]
INFO 2021-02-01 06:36:43,896 table.cc:132 Add field name [string], type [4], index [1]
INFO 2021-02-01 06:36:43,896 table.cc:132 Add field name [_id], type [4], index [0]
INFO 2021-02-01 06:36:43,897 table.cc:174 Create table 2 success! item length=14, field num=3
ERROR 2021-02-01 06:36:43,897 gamma_engine.cc:489 Cannot create table!
INFO 2021-02-01 06:36:43,959 table.cc:48 Table created success!
INFO 2021-02-01 06:36:43,959 gamma_engine.cc:212 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-02-01 06:36:43,959 gamma_api.cc:49 Engine init successed!
ERROR 2021-02-01 06:36:43,959 raw_vector.cc:395 parse compress error
INFO 2021-02-01 06:36:43,959 table.cc:125 Table compress [0]
INFO 2021-02-01 06:36:43,959 table.cc:132 Add field name [float], type [2], index [1]
INFO 2021-02-01 06:36:43,959 table.cc:132 Add field name [string], type [4], index [1]
INFO 2021-02-01 06:36:43,959 table.cc:132 Add field name [_id], type [4], index [0]
INFO 2021-02-01 06:36:43,959 table.cc:174 Create table 1 success! item length=14, field num=3
ERROR 2021-02-01 06:36:43,959 gamma_engine.cc:489 Cannot create table!
INFO 2021-02-01 06:36:44,018 table.cc:48 Table created success!
INFO 2021-02-01 06:36:44,018 gamma_engine.cc:212 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-02-01 06:36:44,018 gamma_api.cc:49 Engine init successed!
ERROR 2021-02-01 06:36:44,018 raw_vector.cc:395 parse compress error
INFO 2021-02-01 06:36:44,018 table.cc:125 Table compress [0]
INFO 2021-02-01 06:36:44,018 table.cc:132 Add field name [float], type [2], index [1]
INFO 2021-02-01 06:36:44,018 table.cc:132 Add field name [string], type [4], index [1]
INFO 2021-02-01 06:36:44,018 table.cc:132 Add field name [_id], type [4], index [0]
INFO 2021-02-01 06:36:44,018 table.cc:174 Create table 2 success! item length=14, field num=3
ERROR 2021-02-01 06:36:44,018 gamma_engine.cc:489 Cannot create table!
INFO 2021-02-01 06:36:44,078 table.cc:48 Table created success!
INFO 2021-02-01 06:36:44,078 gamma_engine.cc:212 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-02-01 06:36:44,078 gamma_api.cc:49 Engine init successed!
ERROR 2021-02-01 06:36:44,078 raw_vector.cc:395 parse compress error
INFO 2021-02-01 06:36:44,078 table.cc:125 Table compress [0]
INFO 2021-02-01 06:36:44,078 table.cc:132 Add field name [float], type [2], index [1]
INFO 2021-02-01 06:36:44,078 table.cc:132 Add field name [string], type [4], index [1]
INFO 2021-02-01 06:36:44,078 table.cc:132 Add field name [_id], type [4], index [0]
INFO 2021-02-01 06:36:44,078 table.cc:174 Create table 1 success! item length=14, field num=3
ERROR 2021-02-01 06:36:44,078 gamma_engine.cc:489 Cannot create table!


我的用的vearch是直接docker pull vearch/vearch:3.2.2的，没有进行单独安装zfp

**Comment by NLPOR** [comment]
ok，我这里建表成功了，设置成 "store_param": {"compress": {"rate": 16}}之后，“store_type”也要改为"RocksDB"，似乎是Mmap不支持压缩？另外更新版本后能否相应的更新下文档呀，这个问题困扰了好几天

**Comment by zcdb** [comment]
好的，后续我们会更新下文档

**Comment by NLPOR** [comment]
还有个问题就是"store_param": {"compress": {"rate": 16}}是怎么进行向量压缩的呢，压缩倍率是多少呀，是否会影响精度和速度呢，大概有多少影响呀

**Comment by zcdb** [comment]
rate=16即压缩率50%，对精度没有明显影响，速度的话主要看使用场景，如果搜索并发很高是会有影响的，建议还是结合自己的场景压测一下比较好

**Comment by realdalabengba** [comment]
日志上 Table compress 为 0，为0不是不压缩吗？
