### ISSUE TITLE
v3.2.5版本的ivfflat模式的string字段会被截断

### ISSUE THREAD

**Issue by KOKKEI** [vearch/vearch#352]
v3.2.5版本的ivfflat模式查询时，返回结果里string字段会被截断，只显示前面部分字符。

**Comment by zcdb** [comment]
多长的字符串呢？

**Comment by KOKKEI** [comment]
插入数据的，string字段超过50甚至更多，多次查询发现超过30个字符就会被截断。通过如下id查询则可以获取完整字符串：curl -XGET http://router_server/$db_name/$space_name/$id

**Comment by KOKKEI** [comment]
1、是否有限制？或者查询语句中需要指定参数？
查询语句如下：
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        "sum": [{
            "field": "field2",
            "feature": []
        }]
    },
    "retrieval_param": {
        "parallel_on_queries": 1,
        "nprobe": 80,
        "metric_type": "L2"
    },
    "is_brute_search":0,
    "size":10
}
' http://router_server/$db_name/$space_name/_search

**Comment by zcdb** [comment]
你好，我这边无法复现这种情况，可以贴一下curl -XGET http://router_server/$db_name/$space_name/$id 和 该查询语句返回的具体结果吗？另外建表语句可以提供一下吗？
