### ISSUE TITLE
gamma  test_file.cc相关接口疑问

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#355]
通过资源项目成员，得知GetDocByID这个接口指通过_id（即主键）来获取do
我在
test::Create();
test::Add();
后 使用GetDocByID这个接口指通过_id（即主键）来获取doc，没有获得任何结果

std::string data = "10";
int len = data.size();

// 存储结果的
char *doc_str;
int doc_len;

int ret = GetDocByID(test::opt.engine, (char *)(data.c_str()), len, &doc_str, &doc_len);

tig_gamma::Doc doc;
doc.Deserialize(doc_str, doc_len);

**Comment by zcdb** [comment]
此问题已经在相关issue中回复了，如果没有更多问题，将关掉此issue
