### ISSUE TITLE
gamma接口TermFilter问题

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#356]
```
tig_gamma::TermFilter term_filter;
term_filter.field = "field1";
term_filter.value = "1315\00115248";
term_filter.is_union = 1;
```
我在查看了TermFileter的源码后，也不太清楚调用的方法，请问如何实现这样的查询？
```
"term": {
                 "field1": ["100", "200", "300"],
                 "operator": "or"
             },
```

期待早日回复，谢谢

**Comment by zcdb** [comment]
修改成如下方式即可 term_filter.value = "100\001200\001300";

**Comment by rrjia** [comment]
谢谢，这种方式在实例代码中有看到，但是这种手动写得方法，如何使用代码实现呢？是否如下面代码所示？
```
filed = [100, 200, 300]
term_filter.value = std::to_string(field[0]) + "\00" + std::to_string(field[1]) + "\00" +std::to_string(field[2]) + "\00";
```
还有operator的and, or,not都是采用以下代码实现么？
```
term_filter.is_union = 1;
```

**Comment by zcdb** [comment]
filed = [100, 200, 300]
term_filter.value = std::to_string(field[0]) + "\001" + std::to_string(field[1]) + "\001" +std::to_string(field[2]);
其中“\001”为分隔符

term过滤现在只支持and/or
or即term_filter.is_union = 1
and即is_union=0

**Comment by rrjia** [comment]
感谢解答
