### ISSUE TITLE
使用 Docker 镜像模式部署，关于数据持久化。

### ISSUE THREAD

**Issue by caolist** [vearch/vearch#357]
目前单机部署了 vearch，正常运行，但是 docker 容器停止后，建好的库、表空间以及数据就会丢失，请问有没有官方推荐的数据持久化方法，如果没有，我该如何映射数据目录到宿主机，非常感谢!

**Comment by gDreamcatcher** [comment]
可以参考docker的官方文档：[docker use bind mounts](https://docs.docker.com/get-started/06_bind_mounts/)

**Comment by caolist** [comment]
> 可以参考 docker 的官方文档：[docker use bind mounts](https://docs.docker.com/get-started/06_bind_mounts/)

谢谢，但是我是想知道 vearch 的数据存储目录是哪个，我好做映射。

**Comment by gDreamcatcher** [comment]
> > 可以参考 docker 的官方文档：[docker use bind mounts](https://docs.docker.com/get-started/06_bind_mounts/)
> 
> 谢谢，但是我是想知道 vearch 的数据存储目录是哪个，我好做映射。

数据目录文件在config.tom文件里配置，具体在这个位置https://github.com/vearch/vearch/blob/80bed7cd53da326da7476351787704cff46f4890/config/config.toml.example#L5

**Comment by caolist** [comment]
> > > 可以参考 docker 的官方文档：[docker use bind mounts](https://docs.docker.com/get-started/06_bind_mounts/)
> > 
> > 
> > 谢谢，但是我是想知道 vearch 的数据存储目录是哪个，我好做映射。
> 
> 数据目录文件在 config.tom 文件里配置，具体在这个位置
> 
> https://github.com/vearch/vearch/blob/80bed7cd53da326da7476351787704cff46f4890/config/config.toml.example#L5

感谢你的回答！

**Comment by 1961670021** [comment]
> 目前单机部署了 vearch，正常运行，但是 docker 容器停止后，建好的库、表空间以及数据就会丢失，请问有没有官方推荐的数据持久化方法，如果没有，我该如何映射数据目录到宿主机，非常感谢!

请求你的问题解决了吗 我也遇到了这个问题 服务器重启后数据全部丢失了

**Comment by gDreamcatcher** [comment]
> 请求你的问题解决了吗 我也遇到了这个问题 服务器重启后数据全部丢失了

容器启动时将数据目录映射到宿主机，具体方法可以参考上面的回答

**Comment by 1961670021** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
