### ISSUE TITLE
Vearch插入数据返回状态码为201

### ISSUE THREAD

**Issue by allforyou2016** [vearch/vearch#358]
我是通过一键式安装脚本的方式在centos7.5中安装了vearch,创建了库和表，然后在插入数据时返回状态码201
建表空间
`
{
    "name": "space1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 32
        }
    },
    "properties": {
        "field1": {
            "type": "integer"
        },
        "field2": {
            "type": "vector",
            "dimension": 2
        }
    }
}
`

然后插入数据
http://*******/db_name/space1
`{
    "field1": 1,
    "field2": {
        "feature": [0.1, 0.6]
    }
}`
此时返回结果
`{
    "_index": "db_name",
    "_type": "space1",
    "_id": "-8165616050163467529",
    "status": 201,
    "_shards": {
        "total": 0,
        "successful": 1,
        "failed": 0
    },
    "result": "created",
    "_seq_no": 1,
    "_primary_term": 1
}`

请问为什么不是返回200而是201？

**Comment by gDreamcatcher** [comment]
目前一键安装脚本只支持3.2.0之前的版本，3.2.0之后版本在功能和性能上有大的更新，我们会尽快提供最新版本的一键部署脚本，在此期间你可以通过docker方式或源码编译方式，使用最新的vearch版本。

**Comment by allforyou2016** [comment]
> 目前一键安装脚本只支持3.2.0之前的版本，3.2.0之后版本在功能和性能上有大的更新，我们会尽快提供最新版本的一键部署脚本，在此期间你可以通过docker方式或源码编译方式，使用最新的vearch版本。

我装的是3.1.0，建库和建表空间都没有问题，只是插入数据时返回的是201，实际数据貌似已经插入成功了，不知道这个201表示哪里出错了

**Comment by gDreamcatcher** [comment]
> 我装的是3.1.0，建库和建表空间都没有问题，只是插入数据时返回的是201，实际数据貌似已经插入成功了，不知道这个201表示哪里出错了

3.1.0版本插入数据成功返回的状态码是201，后面版本才将这个状态码改回200

**Comment by allforyou2016** [comment]
> > 我装的是3.1.0，建库和建表空间都没有问题，只是插入数据时返回的是201，实际数据貌似已经插入成功了，不知道这个201表示哪里出错了
> 
> 3.1.0版本插入数据成功返回的状态码是201，后面版本才将这个状态码改回200

啊是这样啊，感谢
