### ISSUE TITLE
查询结果的问题

### ISSUE THREAD

**Issue by allforyou2016** [vearch/vearch#359]
我在vearch中创建了库和表空间，
建表空间
`
{
    "name": "space1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 32
        }
    },
    "properties": {
        "field1": {
            "type": "integer"
        },
        "field2": {
            "type": "vector",
            "dimension": 2
        }
    }
}
`

然后插入了五条数据

`
{
    "field1": 2,
    "field2": {
        "feature": [0.1, 0.2]
    }
}
`
`
{
    "field1": 3,
    "field2": {
        "feature": [0.1, 0.3]
    }
}
`
`
{
    "field1": 4,
    "field2": {
        "feature": [0.1, 0.4]
    }
}
`
`
{
    "field1": 5,
    "field2": {
        "feature": [0.1, 0.5]
    }
}
`
`
{
    "field1":6,
    "field2": {
        "feature": [0.1, 0.6]
    }
}
`
然后查询
`
{
    "query": {
        "sum": [{
            "field": "field2",
            "feature": [0.1, 0.3]
        }]
    },
    "online_log_level": "debug",
    "quick": false,
    "vector_value": true,
    "size": 5
}
`

发现返回结果得分最高的是[0.1,0.6]那条数据，而且不管我用 [0.1, 0.1]还是 [0.1, 0.2]  [0.1, 0.3]去查询得分最高的都是[0.1,0.6]，没有变化，就很奇怪
`
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "failed": 0,
        "successful": 1
    },
    "hits": {
        "total": 5,
        "max_score": 0.1900000125169754,
        "hits": [
            {
                "_index": "db_name",
                "_type": "space1",
                "_id": "-8165616050163467529",
                "_score": 0.1900000125169754,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "field2",
                            "source": "",
                            "score": 0.1900000125169754
                        }
                    ]
                },
                "_source": {
                    "field1": 1,
                    "field2": {
                        "feature": [
                            0.1,
                            0.6
                        ],
                        "source": ""
                    }
                }
            },
            {
                "_index": "db_name",
                "_type": "space1",
                "_id": "-3775866771430342154",
                "_score": 0.1600000113248825,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "field2",
                            "source": "",
                            "score": 0.16000001132488251
                        }
                    ]
                },
                "_source": {
                    "field1": 5,
                    "field2": {
                        "feature": [
                            0.1,
                            0.5
                        ],
                        "source": ""
                    }
                }
            },
            {
                "_index": "db_name",
                "_type": "space1",
                "_id": "5747644233178300514",
                "_score": 0.1300000101327896,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "field2",
                            "source": "",
                            "score": 0.13000001013278961
                        }
                    ]
                },
                "_source": {
                    "field1": 4,
                    "field2": {
                        "feature": [
                            0.1,
                            0.4
                        ],
                        "source": ""
                    }
                }
            },
            {
                "_index": "db_name",
                "_type": "space1",
                "_id": "-7184984088451668444",
                "_score": 0.10000000149011612,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "field2",
                            "source": "",
                            "score": 0.10000000149011612
                        }
                    ]
                },
                "_source": {
                    "field1": 3,
                    "field2": {
                        "feature": [
                            0.1,
                            0.3
                        ],
                        "source": ""
                    }
                }
            },
            {
                "_index": "db_name",
                "_type": "space1",
                "_id": "8329909827097503024",
                "_score": 0.07000000029802322,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "field2",
                            "source": "",
                            "score": 0.070000000298023224
                        }
                    ]
                },
                "_source": {
                    "field1": 2,
                    "field2": {
                        "feature": [
                            0.1,
                            0.2
                        ],
                        "source": ""
                    }
                }
            }
        ]
    }
}
`
谁能告诉我我哪里的错误导致查询的不准确吗？

**Comment by zcdb** [comment]
这是正常的，用内积计算的时候就是[0.1, 0.6]得分最高最相似。你要的是那种两个相同向量的结果才是最相似的吧，这个时候你可以使用L2或者将向量归一化然后使用内积

**Comment by allforyou2016** [comment]
> 这是正常的，用内积计算的时候就是[0.1, 0.6]得分最高最相似。你要的是那种两个相同向量的结果才是最相似的吧，这个时候你可以使用L2或者将向量归一化然后使用内积

OK，谢谢
