### ISSUE TITLE
Feature request: _delete_by_query api

### ISSUE THREAD

**Issue by qbzenker** [vearch/vearch#36]
Seriously awesome project! Thank you for building this and putting this out. 

Was wondering if you're planning to implement a "delete_by_query" api, [akin to Elasticsearch's](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html)? I am hoping to delete documents by an indexed `keyword` field.

Thanks!

**Comment by ljeagle** [comment]
Not any plans to implement a "delete_by_query" api yet. But it seems a good idea, maybe we can add it to the tasks list. Thank you for your recommendation.

**Comment by ljeagle** [comment]
@qbzenker  Vearch now support "delete_by_query" api. The usage is show below:
curl -H "content-type: application/json" -XPOST -d'
{
    "query": {
        ...
    }
}
' http://router_server/$db_name/$space_name/_delete_by_query

**Comment by qbzenker** [comment]
Amazing - thanks @ljeagle. Closing issue.
