### ISSUE TITLE
关于各个版本教程文档的问题

### ISSUE THREAD

**Issue by allforyou2016** [vearch/vearch#362]
我在https://vearch.readthedocs.io/zh_CN/latest/ 只看到latest版本的教程，之前的版本比如0.X 和3.1.0等版本没有教程？（PS：Vearch项目很好，希望不断发展壮大）

**Comment by allforyou2016** [comment]
Vearch是京东团队在升级维护吗

**Comment by gDreamcatcher** [comment]
> 我在https://vearch.readthedocs.io/zh_CN/latest/ 只看到latest版本的教程，之前的版本比如0.X 和3.1.0等版本没有教程？（PS：Vearch项目很好，希望不断发展壮大）

在这里可以看到v3.2.0版本的文档[3.2.0](https://github.com/vearch/zh_docs/tree/v3.2.0), 其它版本的信息由于当时的疏忽，并没有打tag，需要查看的话只能查看commit信息了

**Comment by caolist** [comment]
希望开发团队可以提供更完善的官方wiki，谢谢。

**Comment by caolist** [comment]
> > 我在 https://vearch.readthedocs.io/zh_CN/latest/ 只看到 latest 版本的教程，之前的版本比如 0.X 和 3.1.0 等版本没有教程？（PS：Vearch 项目很好，希望不断发展壮大）
> 
> 在这里可以看到 v3.2.0 版本的文档 [3.2.0](https://github.com/vearch/zh_docs/tree/v3.2.0), 其它版本的信息由于当时的疏忽，并没有打 tag，需要查看的话只能查看 commit 信息了

希望开发团队可以提供更完善的官方 wiki，谢谢。
