### ISSUE TITLE
数据量比较大的时候，查询偶尔会出现超时情况。

### ISSUE THREAD

**Issue by jackleeforce** [vearch/vearch#363]
- 版本:3.2.5
- 安装方式: Docker

- Gamma.log
```
INFO 2021-02-25 05:31:04,101 gamma_engine.cc:464 filter [0.00195312]ms flat compute 1 [845.703]ms search 0 [0.0310059]ms merge result [0.0148926]ms search total [0.00805664]ms pack results [0.148926]ms  total cost [845.913]ms
```

- ALL.ERROR.log
```
ERROR 2021-02-25 05:31:03,758 client.go:499 rpc cost time error:&Error{Code:RECOVER,Msg:more than 800 Millisecond,XXX_unrecognized:[],}
```
看日志好像是RPC通讯超过800ms 就会当做失败的查询，但是过一会马上再查又正常了，请问这个是个什么样的问题？800ms的值有地方配置吗？

**Comment by gDreamcatcher** [comment]
`POST  /$dbName/$spaceName/_ps_rpc_timeout_set -d '{"rpc_timeout": 1000}'  `  可以通过这个接口动态修改超时时间

**Comment by jackleeforce** [comment]
> `POST /$dbName/$spaceName/_ps_rpc_timeout_set -d '{"rpc_timeout": 1000}' ` 可以通过这个接口动态修改超时时间

只能通过接口的方式没有静态配置项去修改是么？

**Comment by gDreamcatcher** [comment]
这个目前只支持动态修改

**Comment by jackleeforce** [comment]
> 这个目前只支持动态修改

好的，明白了。谢谢。
