### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by allforyou2016** [vearch/vearch#364]
正常使用Vearch的情况下，发送一个建表的请求，返回“{"code":550,"msg":"revoke lease 7445707874535342629 error :context deadline exceeded"}”
建表请求如下
`
{
    "name": "space1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
      "name": "gamma",
      "index_size": 70000,
      "max_size": 70000000,
      "id_type": "String",
      "retrieval_type": "IVFPQ",
      "retrieval_param": {
        "metric_type": "L2",
        "ncentroids": 2048,
        "nsubvector": 32
      }
    },
    "properties": {
      "no": {
        "type": "keyword"
      },
      "fe": {
        "type": "vector",
        "dimension": 128,
        "store_type": "Mmap"
      },
      "vm": {
        "type": "keyword"
      }
    }
  }
`

然后我又这样请求了一次，还是发生了错误，不过错误信息发生了变换，链接被关闭，发现任何连接Vearch的请求都已经不正常了，然后登上Centos服务器查看Vearch健康状态

![1614314479(1)](https://user-images.githubusercontent.com/21984896/109255998-0b671380-7830-11eb-952f-1a8c53efb425.jpg)

然后重新执行systemctl start vearch 又恢复正常，此时发现最初建的表已经出现了，若删除该表再次执行最初建表请求，错误又将复现
请问这可能是什么情况，是不是我max_size设置太大了，我测试服务器内存只有2G

**Comment by gDreamcatcher** [comment]
可以提供一下你的vearch版本和gamma.log的日志吗？目前暂时看不出问题，不过如果你使用的是3.2.2之前的版本，vearch在最开始建表的时候就会申请所有doc需要的内存，机器内存不够的话确实会报错的

**Comment by allforyou2016** [comment]
> 可以提供一下你的vearch版本和gamma.log的日志吗？目前暂时看不出问题，不过如果你使用的是3.2.2之前的版本，vearch在最开始建表的时候就会申请所有doc需要的内存，机器内存不够的话确实会报错的

3.1.0版本，没找到gamma.log的位置╮(╯﹏╰）╭

**Comment by allforyou2016** [comment]
希望新版本的一键式安装能早日出现

**Comment by gDreamcatcher** [comment]
> 希望新版本的一键式安装能早日出现

@gyd-a 麻烦提供一下
