### ISSUE TITLE
多节点多分片下数据无法插入

### ISSUE THREAD

**Issue by kousyaku** [vearch/vearch#365]
两台ps，两个分片各两个副本，停掉其中一台ps后，数据无法进行插入操作。

**Comment by kousyaku** [comment]
3.2.5版本

**Comment by gDreamcatcher** [comment]
麻烦提供一下接口返回的错误信息和错误日志

**Comment by kousyaku** [comment]
停掉一个节点后 单条数据插入返回
{
    "error": {
        "root_cause": [
            {
                "type": "",
                "reason": "partition_not_leader"
            }
        ],
        "type": "",
        "reason": "partition_not_leader"
    },
    "status": 400
}

ERROR.log没有相关信息的输出

**Comment by gDreamcatcher** [comment]
leader需要一半以上的投票，2个副本挂掉一个就选不出leader了， 建议副本设置成3个及3个以上
