### ISSUE TITLE
插入一定量数据后，PS节点会无故挂掉

### ISSUE THREAD

**Issue by PatronusZ** [vearch/vearch#369]
版本：3.2.0_1，GPU源码编译
4台服务器分别部署：master、router、ps1、ps2
建表语句：
`curl -XPUT -H "content-type: application/json" -d'
{
    "name": "ts_space_gpu",
    "partition_num": 2,
    "replica_num": 2,
    "engine": {
        "name": "gamma",
        "index_size": 0,
        "id_type": "String",
        "retrieval_type": "GPU",
        "retrieval_param": {
		    "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 64
        }
    },
    "properties": {
        "url": {
            "type": "keyword",
			"index":true
        },
        "feature1": {
            "type": "vector",
            "dimension": 128,
			"format": "normalization",
			"store_type": "Mmap",
			"store_param": {
                "cache_size": 2048
				}
        }
    }
}
' http://192.xxx.xxx.xxx:8817/space/ts_db/_create`
现象：插入约20万条数据后，ps1节点经常会报错退出，且无法正常启动服务，vearch整体退出后（关闭master/router/ps2并分别重启），依然无法正常启动ps1。
ps1节点报错：`IndexShards shard 0 select modulo 2 = 0
  IndexIVFPQ size 49000 -> GpuIndexIVFPQ indicesOptions=3 usePrecomputed=0 useFloat16=1 reserveVecs=0
IndexShards shard 0 select modulo 2 = 0
  IndexIVFPQ size 53500 -> GpuIndexIVFPQ indicesOptions=3 usePrecomputed=0 useFloat16=1 reserveVecs=0
Faiss assertion 'err == cudaSuccess || err == cudaErrorInvalidValue' failed in int faiss::gpu::getDeviceForAddress(const void*) at gpu/utils/DeviceUtils.cu:106; details: unknown error 11
Aborted
`
ps1节点gamma.log
[gamma.log](https://github.com/vearch/vearch/files/6080312/gamma.log)

PS.ERROR.log
[PS.ERROR.log](https://github.com/vearch/vearch/files/6080314/PS.ERROR.log)

**Comment by wxingda** [comment]
ps1节点是不是没安装rocksdb？

**Comment by PatronusZ** [comment]
两个ps节点都没有安装rocksdb，建表也是选择的Mmap存储，这个会有影响吗？ @wxingda

**Comment by PatronusZ** [comment]
> ps1节点是不是没安装rocksdb？

@wxingda 安装rocksdb并重新编译了gamma和vearch，这样解决了数据持久化的问题，但节点挂掉的问题没有解决，我清空了4台服务器上的datas目录和logs目录，并重新建库表，目前插入了1400万条数据，ps节点暂时没有再挂过。

不过又发现了新的问题：
数据在持续插入时，ps节点的内存占用会越来越高。我单台15G的内存，初始free 14G，在插入1400万条数据后，used 5.4G、buff/cache 6.9G、free 3.3G。暂停插入后，内存占用无明显下降趋势，请问这个是什么原因，如何解决？

版本3.2.0_1，GPU编译
建表语句：
`curl -XPUT -H "content-type: application/json" -d'
{
    "name": "ts_space_gpu",
    "partition_num": 2,
    "replica_num": 2,
    "engine": {
        "name": "gamma",
        "index_size": 0,
        "id_type": "String",
        "retrieval_type": "GPU",
        "retrieval_param": {
		    "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 64
        }
    },
    "properties": {
        "url": {
            "type": "keyword",
			"index":true
        },
        "feature1": {
            "type": "vector",
            "dimension": 128,
			"format": "normalization",
			"store_type": "RocksDB",
			"store_param": {
                "cache_size": 2048,
				"compress": {"rate":16}
				}
        }
    }
}
' http://xxx.xxx.xxx.xxx:8817/space/ts_db/_create`

**Comment by wxingda** [comment]
索引和标量都是放在内存里的，目前我们正在针对内存占用做优化
