### ISSUE TITLE
Docker example issu

### ISSUE THREAD

**Issue by bartengine27** [vearch/vearch#37]
Hi,

  After starting the docker example with

`./run_docker.sh`

I get the following output:

`
...
Successfully tagged ansj/vearch:0.2
Start service by all in one model
good luck service is ready you can visit http://127.0.0.1:9001 to use it
`

The following cURL

`curl -XPOST -H "content-type:application/json" -d '{
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' http://127.0.0.1:9001/test/test/_create`

fails with the message

`{"_index":"test","_type":"test","_id":"_create","status":550,"error":{"index":"","index_uuid":"","shard":"0","type":"","reason":"db:[test] space:[test] err:[space not exists]"}}`

Please note that the example cURL on https://github.com/vearch/vearch/blob/master/docs/Quickstart.md mentions port 4101, is that correct?

Any idea how I can debug this?

Thanks,
Bart

**Comment by ansjsun** [comment]
the quick_start example is image plugin api  it use 4001 port. 
but plugin is not included in docker 。
you need https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md to use it.

**Comment by ansjsun** [comment]
if you not install python plugin . you only can use low level api 
example:
https://github.com/vearch/vearch/blob/master/test/test_vearch.py

* create db 
````
curl -XPUT -H "content-type: application/json" -d'
{
	"name":"test_vector_db"
}
' http://127.0.0.1:8817/db/_create
````


* create space 
````
curl -XPUT -H "content-type: application/json" -d'
{
	"name": "vector_space",
	"dynamic_schema": "strict",
	"partition_num": 1,
	"replica_num": 1,
	"engine": {
		"name": "gamma",
		"index_size": 9999,
		"max_size": 100000
	},
	"properties": {
		"string": {
			"type": "keyword",
			"index": "true"
		},
		"int": {
			"type": "integer",
			"index": "true"
		},
		"float": {
			"type": "float",
			"index": "true"
		},
		"vector": {
			"type": "vector",
			"model_id": "img",
			"dimension": 128,
			"format": "normalization"
		},
		"string_tags": {
			"type": "string",
			"array": true,
			"index": "true"
		},
		"int_tags": {
			"type": "integer",
			"array": true,
			"index": "true"
		},
		"float_tags": {
			"type": "float",
			"array": true,
			"index": "true"
		}
	}
}
' http://127.0.0.1:8817/space/test_vector_db/_create
````

**Comment by bartengine27** [comment]
Thanks ansjsun! Will try that over the weekend!

**Comment by TapdancingRodent** [comment]
Is there a docker build with the plugin? Or will you add one? It isn't on the Roadmap.

**Comment by gDreamcatcher** [comment]
Hi,TapdancingRodent, we will add one in the future, thanks for your advice!

**Comment by gDreamcatcher** [comment]
@TapdancingRodent We have provided a Dockerfile file at this path `plugin/Dockerfile`, you can have a try.
