### ISSUE TITLE
gamma 引擎用入库数据检索无法获得任何结果

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#375]
但是还有一个问题麻烦请教，我在测试程序中向引擎中写入了40W条数据，建立IVFPQ(倒排乘积量化)索引，然后使用其中100条向量进行检索，并且我已经打开了暴力检索的选项，

[test.zip](https://github.com/vearch/vearch/files/6113692/test.zip)

但是在搜索操作时获取不到任何结果。
测试代码已上传附件

**Comment by zcdb** [comment]
添加如下代码即可：
    vector_query.min_score = 0;
    vector_query.max_score = 10000;

**Comment by rrjia** [comment]
已解决
