### ISSUE TITLE
vearch 重启后数据错乱

### ISSUE THREAD

**Issue by 1961670021** [vearch/vearch#376]
启动后占用大量内存，启动成功后数据错乱，且使用原id无法查询出数据

{"took":81,"timed_out":false,"_shards":{"total":1,"failed":0,"successful":1},"hits":{"total":6845317,"max_score":0.9999998807907104,"hits":[{"_index":"ueb_image","_type":"ueb_sku_img","_id":"eb.cn/i","_score":0.9999998807907104,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.99999988079071045}]},"_version":1,"_source":{"boundingbox":"m","imageurl":"l/372963.02-1.jpg?excludeDel=false97ee26bb37066c5ac6b7006cb16faeac3","img_name":"963.02/norma","img_type":"age/","label":"72963.0266386850normalALL373101-","platform_code":"372","sku":"2.jpgh"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"558.01-","_score":0.9767773747444153,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.97677737474441528}]},"_version":1,"_source":{"boundingbox":"4","imageurl":"se136d78887ffc5947c8f694e86d60b098372558.0166388100mainALL373311.01","img_name":"cludeDel=fal","img_type":".jpg","label":"-7.jpghttp://image.ueb.cn/image/","platform_code":"?ex","sku":"373311"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"47fb5c1","_score":0.8473206162452698,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.84732061624526978}]},"_version":1,"_source":{"boundingbox":"9","imageurl":"388240normalALL372712-7.jpghttp://image.ueb.cn/image/372712/normal/372","img_name":"0ed6137168266","img_type":"b74e44","label":"712-7.jpg?excludeDel=false475178","platform_code":"7ac","sku":"05c402"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"72857-1","_score":0.8473206162452698,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.84732061624526978}]},"_version":1,"_source":{"boundingbox":"5","imageurl":"n/image/372857/normal/372857-15.jpg?excludeDel=false1caddfe46cb23982ff64c","img_name":"p://image.ueb.c","img_type":".jpg","label":"1071b25806a37285766371340normalA","platform_code":"htt","sku":"LL373075-"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"cn/imag","_score":0.7730207443237305,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.77302074432373047}]},"_version":1,"_source":{"boundingbox":"e","imageurl":"-7.jpg?excludeDel=false528cab2665780fb90e17a87b3e40c3cf17097512070160","img_name":"ormal/170975","img_type":"/17097","label":"normalALL170975.01-1.jpghttp://i","platform_code":"5/n","sku":"mage.u"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"/image.","_score":0.7730207443237305,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.77302074432373047}]},"_version":1,"_source":{"boundingbox":"u","imageurl":"rmal/170975.02-5.jpg?excludeDel=false06472345436126b70e4021fa91f9ba25170975","img_name":"ge/170975.02/no","img_type":"eb.cn/","label":".0212070230normalALL170975.02-4.","platform_code":"ima","sku":"jpghttp:/"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"053c3dc","_score":0.7586466073989868,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.75864660739898682}]},"_version":1,"_source":{"boundingbox":"c","imageurl":"40normalALL276560.02-6.jpghttp://image.ueb.cn/image/276560.02/normal/2765","img_name":"276560.02316822","img_type":"e02f","label":"60.02-6.jpg?excludeDel=falsee5c2","platform_code":"54f","sku":"ab919a43f"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"8-2.jpg","_score":0.753860354423523,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.753860354423523}]},"_version":1,"_source":{"boundingbox":"h","imageurl":"image/353838/main/353838-2.jpg?excludeDel=falsea6f0c7045227e42ad549","img_name":"mage.ueb.cn/","img_type":"ttp:","label":"fbdd2bbcac2135383860609590mainAL","platform_code":"//i","sku":"L35384"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"3.jpght","_score":0.7471604347229004,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.74716043472290039}]},"_version":1,"_source":{"boundingbox":"t","imageurl":"ge/98111.04/normal/98111.04-3.jpg?excludeDel=false519994e587f53d858","img_name":".ueb.cn/ima","img_type":"p://im","label":"afe7ef261de36af98111.0457722840n","platform_code":"age","sku":"ormal"}},{"_index":"ueb_image","_type":"ueb_sku_img","_id":"0168784","_score":0.7260794639587402,"_extra":{"vector_result":[{"field":"feature","source":"","score":0.72607946395874023}]},"_version":1,"_source":{"boundingbox":"1","imageurl":"pghttp://image.ueb.cn/image/380461/main/380461-4.jpg?excludeDel=fal","img_name":"LL380461-4.j","img_type":"70ma","label":"se4549d6cd48ff0231798d21ad961077","platform_code":"inA","sku":"4d3804"}}]}}

**Comment by 1961670021** [comment]
且使用原id无法查询出数据

**Comment by wxingda** [comment]
请提供下软件版本和建表语句

**Comment by 1961670021** [comment]
BUILD_VERSION="0.3"

**Comment by 1961670021** [comment]
BUILD_VERSION="0.3"

{
    "name":"ueb_sku_img",
    "partition_num":1,
    "replica_num":1,
    "engine":{
        "name":"gamma",
        "metric_type":"InnerProduct",
		"index_size": 100000,
        "max_size": 50000000
    },
    "properties":{
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword",
			"index": "true"
        },
		"sku": {
            "type": "keyword",
			"index": "true"
        },
		"img_type": {
            "type": "keyword",
			"index": "true"
        },
		"img_name": {
            "type": "keyword",
			"index": "true"
        },
		"platform_code": {
            "type": "keyword",
			"index": "true"
        },
		"feature": {
			"type":"vector",
			"dimension":512,
			"format":"normalization",
			"store_type":"RocksDB",
			"store_param": {
                "cache_size": 2048
            }
		}
    },
	"models": [{
		"model_id": "vgg16",
		"fields": ["feature"],
		"out": "feature"
	}]
}
