### ISSUE TITLE
create schema problem

### ISSUE THREAD

**Issue by uouo111845** [vearch/vearch#38]
Hi,
I try to create schema ,and I follow the example code 'APILowLevel.md'.
create schema
curl -v --user "root:secret" -H "content-type: application/json" -XPUT -d'
  {
      "name": "tpy",
      "dynamic_schema": "strict",
      "partition_num": 2,
      "replica_num": 1,
      "engine": {"name":"gamma", "max_size":1000000,"nprobe":10,"metric_type":-1,"ncentroids":-1,".....

fails with the message:
E1103 13:16:54.846912   21292 cluster_api.go:340] [ERROR] createSpaceService err: revoke lease 6509229987518300959 error :context deadline exceeded

Does anyone help me,how to fix this error?

Thanks,
celine

**Comment by ansjsun** [comment]
startup with vearch by what`s model? cluster or single 
Recommend you take a look at the test cases。

the error means create by partition is time out .   This is usually due to a  partition  service crash

**Comment by uouo111845** [comment]
> startup with vearch by what`s model? cluster or single
> Recommend you take a look at the test cases。
> 
> the error means create by partition is time out . This is usually due to a partition service crash

hi
my model is single just like stand-alone mode conf.toml( 'https://vearch.readthedocs.io/en/latest/quick-start-guide.html')

I can create db,but I have the error when I create the space.

Here is my code:
~/go/src/github.com/vearch/vearch$ cat conf.toml 
[global]
    # the name will validate join cluster by same name
    name = "vearch"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    data = ["datas/"]
    # log path , If you are in a production environment, You'd better set absolute paths
    log = "logs/"
    # default log type for any model
    level = "debug"
    # master <-> ps <-> router will use this key to send or receive data
    signkey = "vearch"
    skip_auth = true

# if you are master you'd better set all config for router and ps and router and ps use default config it so cool
[[masters]]
    # name machine name for cluster
    name = "m1"
    # ip or domain
    address = "127.0.0.1"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370

[router]
    # port for server
    port = 9001

[ps]
    # port for server
    rpc_port = 8081
    # raft config begin
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 200 #ms
    raft_retain_logs = 10000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1

create space:
~/go/src/github.com/vearch/vearch$ 
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "tpy",
    "dynamic_schema": "strict",
    "partition_num": 2,
    "replica_num": 1,
    "engine": {"name":"gamma", "max_size":1000000,"nprobe":10,"metric_type":-1,"ncentroids":-1,"nsubvector":-1,"nbits_per_idx":-1},
    "properties": {
        "image_type": {
            "type": "keyword"
        },
        "fku": {
            "type": "integer",
            "index":"false"
        },
        "tags": {
            "type": "keyword",
            "array":true,
            "index":"true"
        },
        "image_vec": {
            "type": "vector",
            "model_id": "img",
            "dimension": 5000
        }
    }
}
' http://127.0.0.1:8817/space/db_name/_create


Please help me how to fix it.

Thanks.
celine

**Comment by ansjsun** [comment]
you can try by this 
https://github.com/vearch/vearch/blob/master/test/test_vearch.py

* create db 
````
curl -XPUT -H "content-type: application/json" -d'
{
	"name":"test_vector_db"
}
' http://127.0.0.1:8817/db/_create
````


* create space 
````
curl -XPUT -H "content-type: application/json" -d'
{
	"name": "vector_space",
	"dynamic_schema": "strict",
	"partition_num": 1,
	"replica_num": 1,
	"engine": {
		"name": "gamma",
		"index_size": 9999,
		"max_size": 100000
	},
	"properties": {
		"string": {
			"type": "keyword",
			"index": "true"
		},
		"int": {
			"type": "integer",
			"index": "true"
		},
		"float": {
			"type": "float",
			"index": "true"
		},
		"vector": {
			"type": "vector",
			"model_id": "img",
			"dimension": 128,
			"format": "normalization"
		},
		"string_tags": {
			"type": "string",
			"array": true,
			"index": "true"
		},
		"int_tags": {
			"type": "integer",
			"array": true,
			"index": "true"
		},
		"float_tags": {
			"type": "float",
			"array": true,
			"index": "true"
		}
	}
}
' http://127.0.0.1:8817/space/test_vector_db/_create
````

**Comment by uouo111845** [comment]
It works!
Thanks a lot.

celine
