### ISSUE TITLE
create partition err: create gamma table has err:[-2] 

### ISSUE THREAD

**Issue by 1961670021** [vearch/vearch#381]
{
	"name": "ueb_sku_img",
	"partition_num": 1,
	"replica_num": 1,
	"engine": {
		"name": "gamma",
		"retrieval_type": "HNSW",
		"metric_type": "InnerProduct",
		"index_size": 100000,
		"retrieval_param": {
			"metric_type": "InnerProduct",
			"nlinks": 32,
			"efConstruction": 40
		}
	},
	"properties": {
		"imageurl": {
			"type": "vector",
			"dimension": 512,
			"format": "normalization",
			"store_type": "RocksDB",
			"store_param": {
				"cache_size": 2048
			}
		},
		"sku": {
			"type": "keyword",
			"index": true
		},
		"img_type": {
			"type": "keyword",
			"index": true
		},
		"img_name": {
			"type": "keyword",
			"index": true
		},
		"platform_code": {
			"type": "keyword",
			"index": true
		}
	}
}

**Comment by zcdb** [comment]
hnsw只支持store_type为MemoryOnly

**Comment by 1961670021** [comment]
create partition err: create gamma table has err:[-1] 又是啥原因 谢谢

{
    "name": "space1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 32
        }
    },
    "properties": {
        "field1": {
            "type": "keyword"
        },
        "field2": {
            "type": "integer"
        },
        "field3": {
            "type": "float",
            "index": true
        },
        "field4": {
            "type": "string",
            "array": true,
            "index": true
        },
        "field5": {
            "type": "integer",
            "index": true
        },
        "field6": {
            "type": "vector",
            "dimension": 128
        },
        "field7": {
            "type": "vector",
            "dimension": 256,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048
            }
        }
    }
}

**Comment by zcdb** [comment]
麻烦贴一下gamma.log吧
