### ISSUE TITLE
初始化数据时，速度缓慢

### ISSUE THREAD

**Issue by 1961670021** [vearch/vearch#388]
十台服务的情况下，一小时只能新增二万记录，过于缓慢
[I 210320 16:34:32 web:2250] 200 POST /ueb_image/ueb_sku_img/35993 (127.0.0.1) 1149461.67ms
[I 210320 16:34:33 web:2250] 200 POST /ueb_image/ueb_sku_img/35995 (127.0.0.1) 1151002.42ms
[I 210320 16:34:35 web:2250] 200 POST /ueb_image/ueb_sku_img/35994 (127.0.0.1) 1152259.95ms
[I 210320 16:34:36 web:2250] 200 POST /ueb_image/ueb_sku_img/36007 (127.0.0.1) 1152422.67ms
[I 210320 16:34:37 web:2250] 200 POST /ueb_image/ueb_sku_img/36008 (127.0.0.1) 1153733.95ms
[I 210320 16:34:39 web:2250] 200 POST /ueb_image/ueb_sku_img/36009 (127.0.0.1) 1154944.33ms
[I 210320 16:34:40 web:2250] 200 POST /ueb_image/ueb_sku_img/36010 (127.0.0.1) 1156189.77ms
[I 210320 16:34:41 web:2250] 200 POST /ueb_image/ueb_sku_img/36016 (127.0.0.1) 1156709.53ms
[I 210320 16:34:43 web:2250] 200 POST /ueb_image/ueb_sku_img/36022 (127.0.0.1) 1156647.38ms
[I 210320 16:34:44 web:2250] 200 POST /ueb_image/ueb_sku_img/36029 (127.0.0.1) 1156547.41ms
[I 210320 16:34:45 web:2250] 200 POST /ueb_image/ueb_sku_img/36034 (127.0.0.1) 1157916.29ms
[I 210320 16:34:47 web:2250] 200 POST /ueb_image/ueb_sku_img/36035 (127.0.0.1) 1159361.66ms
[I 210320 16:34:48 web:2250] 200 POST /ueb_image/ueb_sku_img/36036 (127.0.0.1) 1160724.13ms
[I 210320 16:34:50 web:2250] 200 POST /ueb_image/ueb_sku_img/36038 (127.0.0.1) 1161035.16ms
[I 210320 16:34:51 web:2250] 200 POST /ueb_image/ueb_sku_img/35927 (127.0.0.1) 1160536.27ms
[I 210320 16:34:52 web:2250] 200 POST /ueb_image/ueb_sku_img/35932 (127.0.0.1) 1161807.08ms
[I 210320 16:34:54 web:2250] 200 POST /ueb_image/ueb_sku_img/35933 (127.0.0.1) 1163060.33ms
[I 210320 16:34:55 web:2250] 200 POST /ueb_image/ueb_sku_img/35935 (127.0.0.1) 1164338.41ms
[I 210320 16:34:56 web:2250] 200 POST /ueb_image/ueb_sku_img/35943 (127.0.0.1) 1164616.68ms
[I 210320 16:34:58 web:2250] 200 POST /ueb_image/ueb_sku_img/35953 (127.0.0.1) 1164668.63ms
[I 210320 16:34:59 web:2250] 200 POST /ueb_image/ueb_sku_img/35959 (127.0.0.1) 1164503.59ms
[I 210320 16:35:00 web:2250] 200 POST /ueb_image/ueb_sku_img/36089 (127.0.0.1) 1164445.91ms
[I 210320 16:35:02 web:2250] 200 POST /ueb_image/ueb_sku_img/36090 (127.0.0.1) 1165856.39ms
[I 210320 16:35:03 web:2250] 200 POST /ueb_image/ueb_sku_img/36091 (127.0.0.1) 1167246.03ms
[I 210320 16:35:04 web:2250] 200 POST /ueb_image/ueb_sku_img/36092 (127.0.0.1) 1168479.68ms

**Comment by zcdb** [comment]
你是如何插入数据的呢？可以使用批量插入的接口或者提高插入的并发量

**Comment by 1961670021** [comment]
是并发执行的呢，这个日志是image-extract-plugin的日志，应该是慢在提取图片特征这一步了，针对image-extract-plugin有啥提高效率的方法吗

**Comment by zcdb** [comment]
特征提取这块没啥明显提效的方法，我们提供image-extract-plugin只是比较通用的图片特征提取插件，如果是真实场景建议还是按照自己的场景来训练特征提取模型

**Comment by gDreamcatcher** [comment]
> 是并发执行的呢，这个日志是image-extract-plugin的日志，应该是慢在提取图片特征这一步了，针对image-extract-plugin有啥提高效率的方法吗

你可以配置GPU进行提取特征，配置位置如下：
https://github.com/vearch/python-algorithm-plugin/blob/bae65c4f3b9a3c05ed49eecc7e1576bc9418c855/src/config.py#L19
