### ISSUE TITLE
Help, I cannot build successfully because of undefined reference.

### ISSUE THREAD

**Issue by BismarckDD** [vearch/vearch#39]
host@host:~/Practice/go/src/github.com/vearch/vearch$ go1.11.2 build -a --tags=vector -o  vearch
\# github.com/vearch/vearch/ps/engine/gammacb
/home/host/workplace/Practice/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `faiss::IndexIVFPQ::encode_vectors(long, float const*, long const*, unsigned char*) const'
collect2: error: ld returned 1 exit status

OS: ubuntu 18.04
GCC: 7.4.0 (os)
Golang: go1.11.2 (go1.10 get)
Openblas: latest on github (compile && installation)
Faiss: v1.5.3 release (compile && installation, --without-cuda due to no GPU)
vearch: latest on github

gamma.so is built sucessfully and certain at the target position.
Could anyone give some advices? Thanks very much!

**Comment by ljeagle** [comment]
Which version of faiss did you use? Now, vearch should use faiss v1.5.3.

**Comment by BismarckDD** [comment]
> Which version of faiss did you use? Now, vearch should use faiss v1.5.3.

Surely v1.5.3, if compiled with later version.
Compiler willnot find some function because "utils.h" is to "utils/utils.h" and its content changed.

**Comment by ljeagle** [comment]
so can you show the information of "ldd [the installed gamma.so]"？

**Comment by BismarckDD** [comment]
> so can you show the information of "ldd [the installed gamma.so]"？

	linux-vdso.so.1 (0x00007ffd236fa000)
	libfaiss.so => /opt/OpenBLAS/lib/libfaiss.so (0x00007f211c493000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f211c10a000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f211bedb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f211bcc3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f211baa4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f211b6b3000)
	libopenblas.so.0 => /opt/OpenBLAS/lib/libopenblas.so.0 (0x00007f211a76e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f211a3d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f211cae0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f211a1cc000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f2119ded000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f2119bad000)

**Comment by ljeagle** [comment]
you can check if /opt/OpenBLAS/lib/libfaiss.so is the real v1.5.3  faiss.

**Comment by BismarckDD** [comment]
> you can check if /opt/OpenBLAS/lib/libfaiss.so is the real v1.5.3 faiss.

Thank you very much!
I have a former built libfaiss.so here.
Already solved this issue.
