### ISSUE TITLE
docker启动vearch时报错，open vearch/config.toml no such file or dictory

### ISSUE THREAD

**Issue by iot-rookie** [vearch/vearch#390]
请问下我再windows和ubantu下启动镜像，都遇到这个问题，该如何解决

**Comment by kevintony001** [comment]
cat ../config/config.toml.example > config.toml
nohup docker run -p 8817:8817 -p 9001:9001 -v $PWD/config.toml:/vearch/config.toml  vearch/vearch:3.2.6 all &
需要从下载一下源代码，修改一下config.toml文件中的配置，然后执行docker run
