### ISSUE TITLE
直接使用run_docker.sh,完毕之后,启动报错

### ISSUE THREAD

**Issue by NanOns** [vearch/vearch#397]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/vearch/bin/vearch": stat /vearch/bin/vearch: no such file or directory: unknown.

是哪里出错了,还是不应该使用这个进行安装

**Comment by gDreamcatcher** [comment]
看情况是你执行失败了，你可以直接使用
```
docker pull vearch/vearch
````
获取最新的镜像。

**Comment by git4wht** [comment]
1.应该是没有Build成功，如果成功的化会在、/vearch/build文件夹下包含bin，lib两个文件夹。
2.检查你生成的镜像/vearch/bin/vearch是不是存在
