### ISSUE TITLE
PS节点插入一定的数据之后就没有办法继续插入数据了，大约1000万多一些？

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#399]
本人使用三台机器，其中一台用作router，另外两台都配置了master和PS，即整体2 master, 2 ps, 1 router,但是测试过程中经常发现数据插入到1000多万后，会无法再插入了，无论是批量插入还是单个插入，在使用restful API post后，不会有返回，全部卡在第一条log。"batch_insert post start"，查看master PS所在的服务区，CPU利用率几乎降至5%以下，等待好久 不见好；
    print("batch_insert post start")
    msg = requests.post(rooter_ip + f"/{db_table_name}/{db_space_name}/_bulk", headers=headers,
                       data=final)
    print("batch_insert post end")
通过查看log发现一台机器出现如下log，这是其中的一台启动了master 和ps的机器。没有其他error log，没有PS.ERROR.log没有Master.ERROR.log
132 2021/04/01 04:52:46 server.go:358: INFO : client has closed this connection: 10.4.44.207:46031
133 2021/04/01 04:55:23 server.go:358: INFO : client has closed this connection: 10.4.44.207:46393
134 2021/04/01 04:58:19 server.go:358: INFO : client has closed this connection: 10.4.44.207:46903
135 2021/04/01 05:01:08 server.go:358: INFO : client has closed this connection: 10.4.44.207:47447
136 2021/04/01 05:02:26 server.go:358: INFO : client has closed this connection: 10.4.44.207:47631
请问有谁知道这个是什么问题吗？

**Comment by gyd-a** [comment]
麻烦你提供一下建表参数和gamma.log日志

**Comment by qingfengshiran** [comment]
> 麻烦你提供一下建表参数和gamma.log日志 #

**Comment by qingfengshiran** [comment]
> 麻烦你提供一下建表参数和gamma.log日志

[table.txt](https://github.com/vearch/vearch/files/6242710/table.txt)
[Uploading gamma.log…]()

**Comment by qingfengshiran** [comment]
> 麻烦你提供一下建表参数和gamma.log日志

麻烦再帮忙看看了，谢谢

**Comment by qingfengshiran** [comment]
> 麻烦你提供一下建表参数和gamma.log日志

麻烦再帮忙看看了，另外，我写的时候是批量写，10个并发，每个并发20000每次，但是，写不进去之后是可以search的

**Comment by qingfengshiran** [comment]
> 麻烦你提供一下建表参数和gamma.log日志

我现在试100个并发，每个batch大小改为200，目前写到4000万，没有出现问题，之前从来没有到过这个数量级

**Comment by zcdb** [comment]
之前一个batch20000插入，插入量太大了，应该提高并发降低batch大小，不然可能出现写入压力太大导致ps没有心跳，从而程序挂掉

**Comment by qingfengshiran** [comment]
> 之前一个batch20000插入，插入量太大了，应该提高并发降低batch大小，不然可能出现写入压力太大导致ps没有心跳，从而程序挂掉

好的，谢谢，目前已经插入8000万了，应该没有问题了
