### ISSUE TITLE
unexpected signal during runtime execution

### ISSUE THREAD

**Issue by peratchi** [vearch/vearch#40]
after running this command: ./vearch -conf conf.toml getting below error.

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7fe08dc49ae0]

runtime stack:
runtime.throw(0x1574410, 0x2a)
        /root/.go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /root/.go/src/runtime/signal_unix.go:378 +0x47c

goroutine 254 [syscall]:
runtime.cgocall(0x11e53c0, 0xc000febb98, 0x0)
        /root/.go/src/runtime/cgocall.go:128 +0x5b fp=0xc000febb68 sp=0xc000febb30 pc=0x4067fb
github.com/vearch/vearch/ps/engine/gammacb._Cfunc_Load(0x7fe064004b10, 0x7fe000000000)
        _cgo_gotypes.go:528 +0x49 fp=0xc000febb98 sp=0xc000febb68 pc=0x11b11d9
github.com/vearch/vearch/ps/engine/gammacb.New.func8(0xc0001bd3b0, 0xc)
        /root/go/src/github.com/vearch/vearch/ps/engine/gammacb/gamma.go:102 +0x5f fp=0xc000febbd8 sp=0xc000febb98 pc=0x11be0cf
github.com/vearch/vearch/ps/engine/gammacb.New(0xc000613774, 0xc, 0x0, 0xc000ab4f30, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/vearch/vearch/ps/engine/gammacb/gamma.go:102 +0x61a fp=0xc000febd38 sp=0xc000febbd8 pc=0x11b2cfa

I have installed go (go version go1.13.4 linux/amd64) gcc version 7.4.0 , faiss : 1.5.3

getting below error also often

./vearch -conf conf.toml
./vearch: error while loading shared libraries: libgamma.so.0.1: cannot open shared object file: No such file or directory
but i have such file inside gamma folder. 
[100%] Linking CXX shared library libgamma.so
[100%] Built target gamma
[100%] Built target gamma
Install the project...
-- Install configuration: "Release"
-- Installing: /root/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
-- Installing: /root/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so
-- Set runtime path of "/root/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1" to ""
-- Installing: /root/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/include/gamma_api.h

please any one help me to fix this issue

**Comment by wxingda** [comment]
> ./vearch: error while loading shared libraries: libgamma.so.0.1: cannot open shared object file: No such file or directory

You can execute `export LD_LIBRARY_PATH=/root/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/:$LD_LIBRARY_PATH` before running.

**Comment by qiutianme** [comment]
> after running this command: ./vearch -conf conf.toml getting below error.
> 
> fatal error: unexpected signal during runtime execution
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7fe08dc49ae0]
> 
> runtime stack:
> runtime.throw(0x1574410, 0x2a)
> /root/.go/src/runtime/panic.go:774 +0x72
> runtime.sigpanic()
> /root/.go/src/runtime/signal_unix.go:378 +0x47c
> 
> goroutine 254 [syscall]:
> runtime.cgocall(0x11e53c0, 0xc000febb98, 0x0)
> /root/.go/src/runtime/cgocall.go:128 +0x5b fp=0xc000febb68 sp=0xc000febb30 pc=0x4067fb
> github.com/vearch/vearch/ps/engine/gammacb._Cfunc_Load(0x7fe064004b10, 0x7fe000000000)
> _cgo_gotypes.go:528 +0x49 fp=0xc000febb98 sp=0xc000febb68 pc=0x11b11d9

Check if there is dirty data in the data directory which is configured in **conf.toml**, and **clear the data directory**

_conf.toml:_
_[global]
    # the name will validate join cluster by same name
    name = "vearch"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    **data = ["datas/"]**_

**Comment by peratchi** [comment]
Thanks a lot
