### ISSUE TITLE
数据dump之后load报错

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#401]
int tig_gamma::ReadInvertedLists(faiss::IOReader*, tig_gamma::realtime::RTInvertIndex*): 假设 ‘(size_t)ids[pos] < rt_data->cur_invert_ptr_->nids_’ 失败。

**Comment by zcdb** [comment]
提供下更完整的gamma.log吧

**Comment by WeiYan-Lynn** [comment]
我们也遇到这个问题了，有点奇怪的是
gamma_index_io.cc的184-187行，为啥用if，不用while呢，只让他扩大两倍，不然就断言，这个是有什么考虑吗
      if ((size_t)ids[pos] >= rt_data->cur_invert_ptr_->nids_) {
        rt_data->cur_invert_ptr_->ExtendIDs();
        assert((size_t)ids[pos] < rt_data->cur_invert_ptr_->nids_);
      } @zcdb

**Comment by wxingda** [comment]
之前是认为扩充两倍就能满足要求，可以改成多次扩充
