### ISSUE TITLE
Benchmark conditions question

### ISSUE THREAD

**Issue by sgjurano** [vearch/vearch#41]
Hello!
I'm interested in your system, however I have some questions about your [benchmark](https://github.com/vearch/vearch/blob/master/engine/gamma/benchs/README.md#cluster-experiments) conditions.

1. Did you use 5 bare metal servers for VGG100M tests and obtain ~120QPS without filtering by integer field?
2. What is the "integer field filtering"? :)
3. Which CPU and how many RAM your servers has?
4. How many RAM indexes use and how large is the database? 
5. Is it true, that your system maintains full copy of the database in each PartitionServer?

**Comment by ansjsun** [comment]
2. What is the "integer field filtering"? :)
````
`integer field filtering` is a query filter , example
{
"query": {
      "filter":[
          {
              "range":{
                  "int_field":{
                      "gte":1,
                      "lte":1000
                  }
              }
          }
       ]
  }
}

it means only   int_fileld in range 1-1000   hits
````
3. Is it true, that your system maintains full copy of the database in each PartitionServer?
````
not full copy of the database in each PartitionServer.
it use document id , hash to one partition  .
if partition has replica ， the  replica full copy leader partition。 
````

**Comment by ljeagle** [comment]
1.  Yes, we deployed on 5 machines, each of which was deployed a PS composed of 3 partitions. And there were about 700W vectors in each partition. After recalling from the quantized index, the candidate TopN recall vectors are further used to calculate the distances from the query vector in Vearch. In this VGG100M test, TopN is selected as Top100, and then we obtain ~120QPS without filtering by integer field.

3. The configuration of machines in the test is shown below:
CPU model: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPU cores: 2CPU 16 core, 32 logic processing unit
RAM: 62G

4. Occupied about 50G in each machine. However most of the memory(about 41G) is occupied by the original vectors, used for fine-grained calculation. The quantized vector index is not very large, just no more than 1G, and the left is occupied by the scalars of the documents.

**Comment by sgjurano** [comment]
Thank you for your answers.

1. Can rocksdb store data on disk or vearch use it as in-memory-only database?
2. Is fine-grained distance calculation optional?
3. What metrics types are supported now? Just L2 or may be dot-product too?

**Comment by ljeagle** [comment]
1. Now vearch can support to use rocksdb to store original vectors, you can configure how much memory for storing vectors as you like.
2. Now it is not optional, but we will expose the parameter for choosing as soon as possible.
3.Both L2 and dot-product are supported,
4. Yeath, it's already in production.
5. About billion scale. you can see the experiments of VGG1B in detail.

**Comment by sgjurano** [comment]
Thank you! I will try Vearch for our tasks :)
