### ISSUE TITLE
是否考虑增加地理信息过滤功能？

### ISSUE THREAD

**Issue by caolist** [vearch/vearch#412]
Vearch 使用感受，检索条件中的 filter 部分感觉与 Elasticsearch  相似，目前在做图片检索相关，刚好会利用地理坐标作为图片的检索过滤条件，请问 Vearch 有没有考虑扩充 filter 的计划，加入类似 Elasticsearch 中 geo_bounding_box query, geo_distance 等 GEO条件过滤功能?

非常感谢,一如既往支持 Vearch 的发展.

**Comment by wxingda** [comment]
目前vearch主要是作为向量数据库使用，filter功能只是对向量搜索提供了简单的过滤功能，暂时没有计划扩充filter，谢谢支持

**Comment by ljeagle** [comment]
> Vearch 使用感受，检索条件中的 filter 部分感觉与 Elasticsearch 相似，目前在做图片检索相关，刚好会利用地理坐标作为图片的检索过滤条件，请问 Vearch 有没有考虑扩充 filter 的计划，加入类似 Elasticsearch 中 geo_bounding_box query, geo_distance 等 GEO条件过滤功能?
> 
> 非常感谢,一如既往支持 Vearch 的发展.

有兴趣欢迎加入进来，开发此feature
