### ISSUE TITLE
GPU vearch环境实时写入不能查询到已写入的数据

### ISSUE THREAD

**Issue by Chenhongcai800** [vearch/vearch#414]
vearch GPU环境写入1条后一直查询不到,看日志gpu index一直没有完成索引，但是cpu环境是可以立马查到的

**Comment by wxingda** [comment]
gpu索引要插入doc数量到达指定条数"index_size"后才能建索引，cpu索引也一样，不过cpu环境在不建索引的情况下采用暴力搜，所以能够查到

**Comment by Chenhongcai800** [comment]
index_size  必须大于8192才能创建表空间  "GPU model doc size:[1] less than 8192








在 2021-04-19 09:44:55，"wxd" ***@***.***> 写道：

gpu索引要插入doc数量到达指定条数"index_size"后才能建索引，cpu索引也一样，不过cpu环境在不建索引的情况下采用暴力搜，所以能够查到

**Comment by Chenhongcai800** [comment]
发现3.1.0 和3.2.5 是不支持store_type为MemoryOnly  所以将版本升级到了最新版本v3.2.7 但是发现Mmap  MemoryOnly都不支持实时写入数据实时查询，这就没法满足实时相似度查询的场景了，请问针对这个问题该如何解决


实时写入查询提示”gamma_engine.cc:322 index not trained!“




















在 2021-04-19 09:44:55，"wxd" ***@***.***> 写道：

gpu索引要插入doc数量到达指定条数"index_size"后才能建索引，cpu索引也一样，不过cpu环境在不建索引的情况下采用暴力搜，所以能够查到

**Comment by Chenhongcai800** [comment]
在 2021-04-22 19:07:41，"牧羊人" ***@***.***> 写道：

发现3.1.0 和3.2.5 是不支持store_type为MemoryOnly  所以将版本升级到了最新版本v3.2.7 但是发现Mmap  MemoryOnly都不支持实时写入数据实时查询，这就没法满足实时相似度查询的场景了，请问针对这个问题该如何解决


实时写入查询提示”gamma_engine.cc:322 index not trained!“




















在 2021-04-19 09:44:55，"wxd" ***@***.***> 写道：

gpu索引要插入doc数量到达指定条数"index_size"后才能建索引，cpu索引也一样，不过cpu环境在不建索引的情况下采用暴力搜，所以能够查到
