### ISSUE TITLE
是否考虑支持按space级别的冷热数据隔离

### ISSUE THREAD

**Issue by xbugliu** [vearch/vearch#415]
目前我们用vearch已经一段时间了，是按每天一个space的方案（类似数据库分区）来管理特征的，因为vearch的索引都在内存里面：
1. 时间较长后，内存占用会较大
2. 几天前的数据属于冷数据，访问频率很低，是否可以冷加载的方式（比如mmap）

**Comment by ljeagle** [comment]
1、v3.2.7已经支持table持久化了，向量可以存储在磁盘，索引可以dump到磁盘。
2、是个好建议，我们考虑一下。

**Comment by xbugliu** [comment]
我们真实测试的内存占用数据，看看是否可以作为内存优化的参考
![image](https://user-images.githubusercontent.com/2310720/116058850-d56cd100-a6b2-11eb-80c5-d6c72118d811.png)
