### ISSUE TITLE
Visual Search API : insert data into space

### ISSUE THREAD

**Issue by peratchi** [vearch/vearch#42]
I am getting below error in VisionSearch insert API

INFO:main:request -- /search/search_space/_insert -- { "imageurl": "COCO_val2014_000000000042.jpg"}
DEBUG:main: File "main.py", line 323, in pkg_result assert isinstance(response_body_list, list), response_body_list AssertionError: {"status": 550, "error": {"index": "", "index_uuid": "", "shard": "0", "type": "", "reason": "descriptor 'init' requires a 'super' object but received a 'str'"}}
DEBUG:main:response -- /search/search_space/_insert -- {"status": 550, "error": {"index": "", "index_uuid": "", "shard": "0", "type": "", "reason": "descriptor 'init' requires a 'super' object but received a 'str'"}}

got below error when i run bash ./bin/run.sh video

FileNotFoundError: [Errno 2] No such file or directory: '/root/go/src/github.com/vearch/vearch/plugin/model/20180402-114759'
INFO:main:request -- /video/video/_create -- {"db": true, "method": 1, "columns": {"imageurl": {"type": "keyword"}, "boundingbox": {"type": "keyword"}, "label": {"type": "keyword"}}, "feature": {"type": "vector", "filed": "imageurl", "model_id": "vgg16", "dimension": 512}}
DEBUG:main:response -- /video/video/_create -- {'code': 200, 'db_msg': 'success', 'space_msg': 'success'}
{'code': 200, 'db_msg': 'success', 'space_msg': 'success'}
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil 55. 78.100 / 55. 78.100
libavcodec 57.107.100 / 57.107.100
libavformat 57. 83.100 / 57. 83.100
libavdevice 57. 10.100 / 57. 10.100
libavfilter 6.107.100 / 6.107.100
libavresample 3. 7. 0 / 3. 7. 0
libswscale 4. 8.100 / 4. 8.100
libswresample 2. 9.100 / 2. 9.100
libpostproc 54. 7.100 / 54. 7.100
pycache: Is a directory
ffmpeg process is killed!

Please help me out

**Comment by peratchi** [comment]
Now I am getting below error in VisionSearch insert API

INFO:main:request -*- /search/search_space/_insert -*- {  "imageurl": "COCO_val2014_000000000042.jpg"}
DEBUG:main:  File "main.py", line 323, in pkg_result     assert isinstance(response_body_list, list), response_body_list AssertionError: {"status": 550, "error": {"index": "", "index_uuid": "", "shard": "0", "type": "", "reason": "descriptor '__init__' requires a 'super' object but received a 'str'"}}
DEBUG:main:response -*- /search/search_space/_insert -*- {"status": 550, "error": {"index": "", "index_uuid": "", "shard": "0", "type": "", "reason": "descriptor '__init__' requires a 'super' object but received a 'str'"}}

Please help me out

**Comment by gDreamcatcher** [comment]
I'm sorry for the trouble，you have two questions：

    1、When Inserting， system can not found the path of imageurl you input, if you just want try, you can change it to "../images/image_retrieval/test/COCO_val2014_000000123599.jpg".
    2、When video, you should download model(https://doc-04-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6dv77kdo4rmi7obitkj9i1ea02csobe9/1573344000000/18056234690049221457/*/1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-?e=download) in plugin/model folder and unzip it firstly.

I hope this can help you！

**Comment by peratchi** [comment]
Thank you so much @gDreamcatcher. Now I am able to insert image. 
But for video I am not able to download model from here https://doc-04-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6dv77kdo4rmi7obitkj9i1ea02csobe9/1573344000000/18056234690049221457/*/1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-?e=download.. getting error message like i don't have access to that page. can you pls help me

**Comment by gDreamcatcher** [comment]
That  model come from [facenet](https://github.com/davidsandberg/facenet). You can find other ways on the Internet to download it. Best wish to you!

**Comment by peratchi** [comment]
Thank you @gDreamcatcher. I did as you suggested... 

my last question what is the visual searchAPI to add and search videos?

if i pass video in search API can i get video's id as result?

**Comment by gDreamcatcher** [comment]
I am sorry to say you can not get video's id as result. But we are going to add this feature. Currently, it only supports the search of portrait images in the live video stream.
