### ISSUE TITLE
中文文档的『更新』操作是错误的

### ISSUE THREAD

**Issue by Kevin922** [vearch/vearch#423]
> https://vearch.readthedocs.io/zh_CN/stable/use_op/op_doc.html#id4

更新
更新时必须指定唯一标识id

```
curl -H "content-type: application/json" -XPOST -d'
{
    "field1": "value1",
    "field2": "value2",
    "field3": {
        "feature": [0.1, 0.2]
    }
}
' http://router_server/$db_name/$space_name/$id/_update
```
请求路径中指定唯一标识$id，使用指定id插入的方式进行数据覆盖更新(后续可支持单个字段修改)。

这个文档，错了。
这个文档，错了。
这个文档，错了。

你们的英文文档才是对的，这个错误，耽误我时间。
要不然就只维护一份英文文档嘛，自然会有人翻译的

**Comment by Maslino** [comment]
错在哪？

**Comment by Kevin922** [comment]
![image](https://user-images.githubusercontent.com/3774756/119788803-0ab04d00-bf05-11eb-882f-884cd8526f0f.png)

![image](https://user-images.githubusercontent.com/3774756/119788879-1c91f000-bf05-11eb-9379-d78aa901f4d8.png)


可能是vearch版本问题吧
