### ISSUE TITLE
ARM平台编译

### ISSUE THREAD

**Issue by ganleiboy** [vearch/vearch#429]
请问vearch支持arm平台吗？有朋友在arm平台编译成功的吗？能否交流一下经验，多谢🙏

**Comment by zcdb** [comment]
如果要在arm平台上编译，编译gamma的时候要去掉avx2和sse指令集的支持，有没有其它的限制暂时还不清楚，我们没有在arm测试过

**Comment by ganleiboy** [comment]
> 如果要在arm平台上编译，编译gamma的时候要去掉avx2和sse指令集的支持，有没有其它的限制暂时还不清楚，我们没有在arm测试过，之前是有用户在arm64上面编译成功过。

嗯嗯，我尝试移除了指令集，gamma可以编译，但代码编译到后面又遇到了其他的问题，想请教一下该如何解决呢？
`
[100%] Linking CXX shared library libgamma.so
[100%] Built target gamma
[100%] Built target gamma
Install the project...
-- Install configuration: "Release"
-- Installing: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
-- Set runtime path of "/home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1" to ""
-- Up-to-date: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so
-- Up-to-date: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/include/gamma_api.h
/home/go/src/github.com/vearch/vearch/build
build vearch
# github.com/vearch/vearch/ps/engine/gamma
/usr/bin/ld: warning: librocksdb.so.6, needed by ../ps/engine/gammacb/lib/lib/libgamma.so, not found (try using -rpath or -rpath-link)
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::ColumnFamilyOptions::ColumnFamilyOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Cleanable::Cleanable()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::ReadOptions::ReadOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Status::ToString[abi:cxx11]() const'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DBOptions::DBOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::NewBlockBasedTableFactory(rocksdb::BlockBasedTableOptions const&)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Slice::ToString[abi:cxx11](bool) const'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::kDefaultToAdaptiveMutex'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DBOptions::IncreaseParallelism(int)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::NewLRUCache(unsigned long, int, bool, double, std::shared_ptr<rocksdb::MemoryAllocator>, bool)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Cleanable::~Cleanable()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::DB**)'
collect2: error: ld returned 1 exit status
build deploy tool
`

**Comment by ganleiboy** [comment]
> 如果要在arm平台上编译，编译gamma的时候要去掉avx2和sse指令集的支持，有没有其它的限制暂时还不清楚，我们没有在arm测试过，之前是有用户在arm64上面编译成功过。

嗯嗯，我尝试移除了指令集，gamma可以编译，但代码编译到后面又遇到了其他的问题，想请教一下该如何解决呢？
`echo $ROOT`

**Comment by ganleiboy** [comment]
> 如果要在arm平台上编译，编译gamma的时候要去掉avx2和sse指令集的支持，有没有其它的限制暂时还不清楚，我们没有在arm测试过，之前是有用户在arm64上面编译成功过。

嗯嗯，我尝试移除了指令集，gamma可以编译，但代码编译到后面又遇到了其他的问题，想请教一下该如何解决呢？
`[100%] Linking CXX shared library libgamma.so
[100%] Built target gamma
[100%] Built target gamma
Install the project...
-- Install configuration: "Release"
-- Installing: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
-- Set runtime path of "/home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1" to ""
-- Up-to-date: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so
-- Up-to-date: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/include/gamma_api.h
/home/go/src/github.com/vearch/vearch/build
build vearch
# github.com/vearch/vearch/ps/engine/gamma
/usr/bin/ld: warning: librocksdb.so.6, needed by ../ps/engine/gammacb/lib/lib/libgamma.so, not found (try using -rpath or -rpath-link)
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::ColumnFamilyOptions::ColumnFamilyOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Cleanable::Cleanable()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::ReadOptions::ReadOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Status::ToString[abi:cxx11]() const'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DBOptions::DBOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::NewBlockBasedTableFactory(rocksdb::BlockBasedTableOptions const&)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Slice::ToString[abi:cxx11](bool) const'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::kDefaultToAdaptiveMutex'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DBOptions::IncreaseParallelism(int)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::NewLRUCache(unsigned long, int, bool, double, std::shared_ptr<rocksdb::MemoryAllocator>, bool)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Cleanable::~Cleanable()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::DB**)'
collect2: error: ld returned 1 exit status
build deploy tool`

**Comment by ganleiboy** [comment]
> 如果要在arm平台上编译，编译gamma的时候要去掉avx2和sse指令集的支持，有没有其它的限制暂时还不清楚，我们没有在arm测试过，之前是有用户在arm64上面编译成功过。

嗯嗯，我尝试移除了指令集，gamma可以编译，但代码编译到后面又遇到了其他的问题，想请教一下该如何解决呢？

```
[100%] Linking CXX shared library libgamma.so
[100%] Built target gamma
[100%] Built target gamma
Install the project...
-- Install configuration: "Release"
-- Installing: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1
-- Set runtime path of "/home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so.0.1" to ""
-- Up-to-date: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/lib/libgamma.so
-- Up-to-date: /home/go/src/github.com/vearch/vearch/ps/engine/gammacb/lib/include/gamma_api.h
/home/go/src/github.com/vearch/vearch/build
build vearch
# github.com/vearch/vearch/ps/engine/gamma
/usr/bin/ld: warning: librocksdb.so.6, needed by ../ps/engine/gammacb/lib/lib/libgamma.so, not found (try using -rpath or -rpath-link)
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::ColumnFamilyOptions::ColumnFamilyOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Cleanable::Cleanable()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::ReadOptions::ReadOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Status::ToString[abi:cxx11]() const'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DBOptions::DBOptions()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::NewBlockBasedTableFactory(rocksdb::BlockBasedTableOptions const&)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Slice::ToString[abi:cxx11](bool) const'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::kDefaultToAdaptiveMutex'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DBOptions::IncreaseParallelism(int)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::NewLRUCache(unsigned long, int, bool, double, std::shared_ptr<rocksdb::MemoryAllocator>, bool)'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Cleanable::~Cleanable()'
../ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::DB**)'
collect2: error: ld returned 1 exit status
build deploy tool
```

**Comment by ganleiboy** [comment]
> 如果要在arm平台上编译，编译gamma的时候要去掉avx2和sse指令集的支持，有没有其它的限制暂时还不清楚，我们没有在arm测试过，之前是有用户在arm64上面编译成功过。

还想请问一下，能找到以前编译成功的用户信息吗？我希望能请教学习一下，谢谢啦。

**Comment by zcdb** [comment]
/usr/bin/ld: warning: librocksdb.so.6, needed by ../ps/engine/gammacb/lib/lib/libgamma.so, not found (try using -rpath or -rpath-link)
从信息中看，是无法找到rocksdb，安装一下rocksdb并指定动态依赖库路径吧

**Comment by ganleiboy** [comment]
> /usr/bin/ld: warning: librocksdb.so.6, needed by ../ps/engine/gammacb/lib/lib/libgamma.so, not found (try using -rpath or -rpath-link)
> 从信息中看，是无法找到rocksdb，安装一下rocksdb并指定动态依赖库路径吧

嗯嗯，已经在arm64平台上编译完成，这个issue可以关闭哈，谢谢啦。

**Comment by RoseLucy** [comment]
> > /usr/bin/ld: warning: librocksdb.so.6, needed by ../ps/engine/gammacb/lib/lib/libgamma.so, not found (try using -rpath or -rpath-link)
> > 从信息中看，是无法找到rocksdb，安装一下rocksdb并指定动态依赖库路径吧
> 
> 嗯嗯，已经在arm64平台上编译完成，这个issue可以关闭哈，谢谢啦。

您好，请问带有ARM编译器的基础镜像是dockerhub上面的这个【18711326907/vearch_env_arm】镜像，还是您自己做的呢。🙏
