### ISSUE TITLE
Result data invalid when search 

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#44]
After I index data sucessfully. When I search into vearch, result meta data invalid on many fields (_id , imageurl. boundingbox) in some records

 "_id":"f21.photo.",
"_score":0.9498358964920044,
"_version":1,
"_source":{
"boundingbox":"dn/a029e43973939bcd",
"imageurl":"c282.jpg1561476103594084352198.0,58.0,630.0,710.0http://f",
"uid":212077
}
It looks like the data has type "keyword" got mixed up.

Space info
   "columns": {
                "imageurl": {
                    "type": "keyword"
                },
                "boundingbox": {
                    "type": "keyword"
                },
                "uid": {
                    "type": "integer"
                }
            }

**Comment by gDreamcatcher** [comment]
Could you please show me your request body when creating table?

**Comment by phamthanhtri** [comment]
Request create table from your source plugin python  : 

- file main.py

{
                "dynamic_schema": "strict",
                "partition_num": 2, 
                "replica_num": 1,
                "name": self.space_name,
                "engine": {"name": "gamma", "metric_type": 0,"max_size":50000000,"index_size":100000},
                "properties": {}
}

- file video.py

{"db": True,
            "method": 1,
            "columns": {
                "imageurl": {
                    "type": "keyword"
                },
                "boundingbox": {
                    "type": "keyword"
                },
                "uid": {
                    "type": "integer"
                }
            },
            "feature": {
                "type": "vector",
                "filed": "imageurl",
                "model_id": "vgg16",
                "dimension": 512
            }
            }
 data["properties"].update(columns)
 data["properties"]["feature"] = feature

**Comment by gDreamcatcher** [comment]
Do you have any problem when using image search?  When using video, the 'label' column is required!  For more infomation, you can infer the function _create_DB_space_ in video.py .
Note: After you change param in config.py and execute bash ./bin/run.sh video, you do not need create table and insert data yourself, the video file will do them automatically.

**Comment by phamthanhtri** [comment]
Yes, my issues when query image search. I modify file video.py  for face retrieval from image search with my data and I didn't used field "label". I test with little data (45000 vector) , it is OK . But when I index with lots of data (~42 mil vector) , it has problem. 
 
About result query search: Data in field "vector_result"  also is valid , but data in field "source"  and "_id" are  invalid  on many records

**Comment by gDreamcatcher** [comment]
I am sorry to your trouble. Can you show me your code?

**Comment by phamthanhtri** [comment]
Which code part do you need?
 I get vector and meta data from database and index into vearch through  server main.py with custom function insert_already_data

This is my function index. It call server http://{SERVER_MAIN}:4101
**def index_data():**
	for doc in iter_es_docs(es=es,es_host=es_hosts,es_index=vecs_index,es_type=vecs_type,query={"_source": ["photoId","url","uid","_aknn_vector","bbox"]}):
		try:
		    id_item =doc['_id']
		    if doc['_source']['_aknn_vector'] is not None:
		        lst_str_bbox = [str(i) for i in doc['_source']['bbox']]
		        bbox = ",".join(lst_str_bbox)
		        data = dict(uid=int(doc['_source']['uid']),
		            feat=doc['_source']['_aknn_vector'],
		            boundingbox=bbox,
		            imageurl=doc['_source']['url'],
		            _id=id_item
		            )
		        res = requests.post(
		                f"{config.video['ip']}:{config.port}/{config.video['db']}/{config.video['space']}/_insert",
		                data=json.dumps(data),
		                headers={"content-type":"application/json"})

 **def insert_already_data(self, ip,data):**
        results = []
        res_data = dict()
        res_data["boundingbox"] = data.pop("boundingbox", None)
        res_data["imageurl"] = data["imageurl"]
        res_data["uid"] =  data["uid"]
        feat =  data.pop("feat")
        feat = (feat/np.linalg.norm(feat)).tolist() 
        res_data["feature"] = {"source": data["imageurl"], "feature": feat}
        response_body = requests.post(ip, headers=_HEADERS, data=json.dumps(res_data))
        results.append(response_body.json())
        return results

**Comment by gDreamcatcher** [comment]
I don't see any problems in this code. If you alreadly have the feature, I suggest you use [APILowLevel](https://github.com/vearch/vearch/blob/master/docs/APILowLevel.md) directly instead of [APIVisualSearch](https://github.com/vearch/vearch/blob/master/docs/APIVisualSearch.md).

**Comment by phamthanhtri** [comment]
Hi @gDreamcatcher 

Thanks for your support . I resolved my issues.  I remove folder partition data on server, raft will auto build new data.Fortunately, it's correct

**Comment by gDreamcatcher** [comment]
Congratulations！
