### ISSUE TITLE
如何知道一张表里有多少数据呢

### ISSUE THREAD

**Issue by 1961670021** [vearch/vearch#441]
如何知道一张表里有多少数据呢

**Comment by gyd-a** [comment]
https://vearch.readthedocs.io/zh_CN/latest/use_op/cluster_status.html  health接口

**Comment by 1961670021** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
