### ISSUE TITLE
GPU 环境 显存使用率如何限制

### ISSUE THREAD

**Issue by Chenhongcai800** [vearch/vearch#442]
目前gpu 显卡 使用率很低，但是显存却很高 ，超过显存问题就会出现

terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:53: Error: 'err == cudaSuccess' failed: failed to cudaHostAlloc 268435456 bytes (error 2 out of memory)
SIGABRT: abort
PC=0x7f51a19f5387 m=23 sigcode=18446744073709551610

**Comment by wxingda** [comment]
https://github.com/vearch/gamma/blob/acace19c6090540c8ed1fa8c4cef6aeb04c623dd/index/impl/gpu/gamma_index_ivfpq_gpu.cc#L368
可以通过修改这里来调整gpu缓存大小来减少显存的使用
