### ISSUE TITLE
None of the masters has the same ip address as current local master server's ip

### ISSUE THREAD

**Issue by xqtbox** [vearch/vearch#46]
When I use vearch on two servers,I get the following error message：

None of the masters has the same ip address as current local master server's ip

please help me@！@

**Comment by xqtbox** [comment]
When I used 127.0.0.1 , it worked perfectly on a standalone server. When changing to IP address, report this error

**Comment by ansjsun** [comment]
in config.toml 

````

# if you are master you'd better set all config for router and ps and router and ps use default config it so cool
[[masters]]
    #name machine name for cluster
    name = "m1"
    #ip or domain
    address = "192.1681.10"
    ......

[[masters]]
    #name machine name for cluster
    name = "m1"
    #ip or domain
    address = "192.1681.11"
    ......
````

Set your real IP, in address

**Comment by xqtbox** [comment]
@ansjsun  Thank you, but this does not solve the problem.     I found the real reason

**Comment by xqtbox** [comment]
Since it is started in docker, the direct network communication between "docker <-> host machine" and "docker <-> other machines " is disabled by default. 
Therefore, if you want to run through docker, you must add this parameter: `--net = host` to directly equate the docker with the host's network;
 and with this parameter, you don't need to map the port with `-p`.

**Comment by xqtbox** [comment]
参考《Docker容器访问宿主机网络》：https://jingsam.github.io/2018/10/16/host-in-docker.html
