### ISSUE TITLE
部署Vearch的硬件要求的疑问

### ISSUE THREAD

**Issue by Alsace-lee** [vearch/vearch#467]
**镜像版本 vearch/vearch:3.2.7 :**
"version": {
                        "build_version": "3.2.7",
                        "build_time": "2021-06-08 11:54.34",
                        "commit_id": "c4f50ca332787cd97a86d99d6e840f7651beefdd"
                    }

**采用相同的镜像和命令，在若干台测试机上测得如下现象：**
Intel(R) Xeon(R) Silver 4208       （CentOS Linux release 7.6.1810） 能够启动并服务
Intel(R) Xeon(R) CPU E5-2620 v2 (CentOS Linux release 7.8.2003） 启动后容器退出且无日志
Intel(R) Xeon(R) CPU E5649         (CentOS Linux release 7.5.1804） 启动后容器退出且无日志

三台机器CentOS版本均为7.5以上，而且没有明显现象说明与系统版本有关。
唯一能够正常启动Vearch的机器的CPU型号较高且支持AVX2与AVX512指令集

猜测这种现象和机器CPU指令集相关
请问是否注意到过这种现象与问题？

**Comment by zcdb** [comment]
需要支持avx2，avx512没有要求

**Comment by Alsace-lee** [comment]
> 需要支持avx2，avx512没有要求

了解，感谢支持。
