### ISSUE TITLE
you can use hnsw as ivfpq coarse_quantizer

### ISSUE THREAD

**Issue by guobayang** [vearch/vearch#47]
from [faiss](https://github.com/facebookresearch/faiss/wiki/Indexing-1M-vectors)
HNSW obtains much better speed / precision operating points than IVFFlat (eg. 0.020 ms vs. 0.140 ms to get > 0.9 recall at 1), at a higher memory cost

**Comment by ljeagle** [comment]
Thanks for your good idea! We will do some experiments as your suggestion. Actually we have done some work for HNSW.  The biggest problem for HNSW is the high memory cost, especially when the data scale is more than 100 million.

**Comment by guobayang** [comment]
Hnsw  as a
