### ISSUE TITLE
3.2.7版本 插入数据达到设置的index_size时ps节点崩溃，并且重启失败

### ISSUE THREAD

**Issue by bluestar21** [vearch/vearch#473]
使用集群方式搭建的vearch集群，1master，1router，3ps，建表语句如下：
table_config = {
    "name": VEARCH_TABLE_NAME,
    "partition_num": 3,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 500000,
        "max_size": 100000000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 64
        }
    },
    "properties": {
        "item_id": {
            "type": "string"
        },
        "fingerprint": {
            "type": "vector",
            "dimension": 1536,
            "format": "normalization",
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 1024
            }
        }
    }
},
插入数据时，达到设置的index_size时ps 节点崩溃，然后重新启动失败，报错如下：
2021/06/18 19:52:39 startup.go:65: [ERROR] start server by version:[3.2.6] commitID:[e7389f6bd9c4dd354273584f2bcc7250b1db8357]
2021/06/18 19:52:39 startup.go:74: [ERROR] The Config File Is: /etc/vearch.d/config.toml
2021-06-18 19:52:39,548 :0: [WARN.] truncate last logfile's N@96 index at: 3739852^M
2021-06-18 19:52:39,548 :0: [WARN.] truncate last logfile's N@96 index at: 3739852^M
2021-06-18 19:52:40,937 :0: DEBUG: raft[2] random election timeout randElectionTick=9, config.ElectionTick=5, randTick=4
2021-06-18 19:52:40,937 :0: DEBUG: raft[2] random election timeout randElectionTick=9, config.ElectionTick=5, randTick=4
2021-06-18 19:52:40,937 :0: DEBUG: [raft][2] became follower at term[1] leader[0].
2021-06-18 19:52:40,937 :0: DEBUG: [raft][2] became follower at term[1] leader[0].
2021-06-18 19:52:40,937 :0: DEBUG: newRaft[2] [peers: ["nodeID":"360","peerID":"0","priority":"0","type":"PeerNormal"], term: 1, commit: 500006, applied: 500006, lastindex: 500006, lastterm: 1]
2021-06-18 19:52:40,937 :0: DEBUG: newRaft[2] [peers: ["nodeID":"360","peerID":"0","priority":"0","type":"PeerNormal"], term: 1, commit: 500006, applied: 500006, lastindex: 500006, lastterm: 1]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by bluestar21** [comment]
清除了raft 日志可以重启，但是每次到达index_size的时候ps节点还是崩溃。

**Comment by zcdb** [comment]
看着像分配内存失败，看看建索引时内存占用多少呢

**Comment by zcdb** [comment]
另外麻烦提供一下gamma.log吧

**Comment by bluestar21** [comment]
> 看着像分配内存失败，看看建索引时内存占用多少呢

启动之后看着看内存不高,gamma.log如下：
INFO 2021-06-18 21:45:47,876 gamma_api.cc:88 Version [[sha1]:0bda185 [author]:GitHub [time]:2021-05-24 18:35:19 +0800 [branch]: (HEAD)]
INFO 2021-06-18 21:45:47,958 table.cc:39 Table created success!
INFO 2021-06-18 21:45:47,958 gamma_engine.cc:283 GammaEngine setup successed! bitmap_bytes_size=268435456
INFO 2021-06-18 21:45:47,958 gamma_engine.cc:163 memory trim thread start......
INFO 2021-06-18 21:45:47,969 gamma_engine.cc:81 System info: threads_max [255915] max_map_count [262144] pid_max [65536]
INFO 2021-06-18 21:45:47,969 gamma_engine.cc:88 max_threads [65536] concurrent_threshold [1927]
INFO 2021-06-18 21:45:47,969 gamma_api.cc:52 Engine init successed!
INFO 2021-06-18 21:45:47,970 vector_manager.cc:119 store params={"cache_size":1024,"segment_size":500000,"compress":{}}
INFO 2021-06-18 21:45:47,970 vector_manager.cc:126 after merge, store parameters [{"cache_size":1024,"segment_size":500000,"compress":{}}]
INFO 2021-06-18 21:45:47,970 vector_manager.cc:136 create raw vector success, vec_name[fingerprint] store_type[Mmap]
INFO 2021-06-18 21:45:47,970 mmap_raw_vector.cc:68 store_params_.compress.IsEmpty() is true, not use zfp
INFO 2021-06-18 21:45:47,970 storage_manager.cc:99 lrucache cache_size[1024M], string lrucache cache_size[0M]
INFO 2021-06-18 21:45:47,970 lru_cache.h:342 LruCache[fingerprint] open! Max_size[16603], max_overflow[873]
INFO 2021-06-18 21:45:47,970 lru_cache.h:196 MemoryPool info, cell_size_=61440,max_cell_num_=17976,use_cell_num_=0
INFO 2021-06-18 21:45:47,970 block.cc:29 Block info, seg_id[0] per_block_size[61440] item_length[6144] header_size[30] seg_block_capacity[2000000]
INFO 2021-06-18 21:45:47,970 vector_block.cc:21 VectorBlock construction!
INFO 2021-06-18 21:45:47,970 block.cc:29 Block info, seg_id[1] per_block_size[61440] item_length[6144] header_size[30] seg_block_capacity[2000000]
INFO 2021-06-18 21:45:47,970 vector_block.cc:21 VectorBlock construction!
INFO 2021-06-18 21:45:47,970 storage_manager.cc:159 load gamma storage success! options={segment_size=500000, fixed_value_bytes=6144, seg_block_capacity=2000000}, segment num=2
INFO 2021-06-18 21:45:47,970 storage_manager.cc:138 init gamma storage success! options={segment_size=500000, fixed_value_bytes=6144, seg_block_capacity=2000000}, segment num=2
INFO 2021-06-18 21:45:47,970 mmap_raw_vector.cc:77 init mmap raw vector success! vector byte size=6144, path=/data/vearch/data/2/vectors/fingerprint
INFO 2021-06-18 21:45:47,970 raw_vector.cc:231 raw vector init success! name=fingerprint, has source=0, multi_vids=0, vector_byte_size=6144, dimension=1536, compress={}
INFO 2021-06-18 21:45:47,970 vector_manager.cc:157 Create index model [IVFPQ]
INFO 2021-06-18 21:45:47,970 gamma_index_ivfpq.cc:320 ncentroids =2048, nsubvector =64, nbits_per_idx =8, metric_type =0, bucket_init_size =1000, bucket_max_size =1280000
INFO 2021-06-18 21:45:48,015 realtime_mem_data.cc:93 init success! total_mem_bytes=147480576, current max size=2048000
INFO 2021-06-18 21:45:48,015 vector_manager.cc:181 create vectors and indexes success! models=[IVFPQ]
INFO 2021-06-18 21:45:48,015 table.cc:102 Table compress [0]
INFO 2021-06-18 21:45:48,015 table.cc:109 Add field name [_id], type [4], index [0]
INFO 2021-06-18 21:45:48,015 table.cc:109 Add field name [item_id], type [4], index [0]
INFO 2021-06-18 21:45:48,015 table.cc:128 Create table 2 success! item length=20, field num=2
INFO 2021-06-18 21:45:48,015 storage_manager.cc:99 lrucache cache_size[512M], string lrucache cache_size[512M]
INFO 2021-06-18 21:45:48,015 lru_cache.h:342 LruCache[2_table] open! Max_size[7785], max_overflow[409]
INFO 2021-06-18 21:45:48,015 lru_cache.h:196 MemoryPool info, cell_size_=65520,max_cell_num_=8694,use_cell_num_=0
INFO 2021-06-18 21:45:48,015 lru_cache.h:342 LruCache[2_string] open! Max_size[7783], max_overflow[409]
INFO 2021-06-18 21:45:48,015 lru_cache.h:196 MemoryPool info, cell_size_=65536,max_cell_num_=8692,use_cell_num_=0
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[0] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[0] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[1] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[1] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[2] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[2] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[3] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[3] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[4] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 block.cc:29 Block info, seg_id[4] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,015 storage_manager.cc:159 load gamma storage success! options={segment_size=102400, fixed_value_bytes=20, seg_block_capacity=400000}, segment num=5
INFO 2021-06-18 21:45:48,015 storage_manager.cc:138 init gamma storage success! options={segment_size=102400, fixed_value_bytes=20, seg_block_capacity=400000}, segment num=5
INFO 2021-06-18 21:45:48,015 table.cc:147 init storageManager success! vector byte size=20, path=/data/vearch/data/2/table
INFO 2021-06-18 21:45:48,016 gamma_engine.cc:628 create table [2] success!
INFO 2021-06-18 21:45:48,016 async_flush.h:70 async flush executor is started!
INFO 2021-06-18 21:45:48,116 async_flush.h:75 async flush executor exit successfully!
INFO 2021-06-18 21:45:48,117 gamma_engine.cc:1163 read doc num=400002 from /data/vearch/data/2/retrieval_model_index/2021-06-18-13:43:24/dump.done
INFO 2021-06-18 21:45:48,117 storage_manager.cc:352 gamma storage truncate to size=400002, current segment num=4, last offset=92802
INFO 2021-06-18 21:45:48,117 table.cc:54 Load doc_num [499999] truncate to [400002]
INFO 2021-06-18 21:45:48,117 lru_cache.h:378 LruCache[2_table] cur_size[0] cells_size[0] hits[0] set_hits[0] misses[1] evict_num_[0]
INFO 2021-06-18 21:45:48,117 lru_cache.h:378 LruCache[2_string] cur_size[0] cells_size[0] hits[0] set_hits[0] misses[1] evict_num_[0]
INFO 2021-06-18 21:45:48,176 lru_cache.h:378 LruCache[2_table] cur_size[31] cells_size[31] hits[100000] set_hits[0] misses[31] evict_num_[0]
INFO 2021-06-18 21:45:48,179 lru_cache.h:378 LruCache[2_string] cur_size[19] cells_size[19] hits[100000] set_hits[0] misses[19] evict_num_[0]
INFO 2021-06-18 21:45:48,236 lru_cache.h:378 LruCache[2_table] cur_size[62] cells_size[62] hits[200000] set_hits[0] misses[62] evict_num_[0]
INFO 2021-06-18 21:45:48,243 lru_cache.h:378 LruCache[2_string] cur_size[37] cells_size[37] hits[200000] set_hits[0] misses[37] evict_num_[0]
INFO 2021-06-18 21:45:48,330 lru_cache.h:378 LruCache[2_table] cur_size[94] cells_size[94] hits[300000] set_hits[0] misses[94] evict_num_[0]
INFO 2021-06-18 21:45:48,340 lru_cache.h:378 LruCache[2_string] cur_size[55] cells_size[55] hits[300000] set_hits[0] misses[55] evict_num_[0]
INFO 2021-06-18 21:45:48,396 table.cc:82 Table load successed! doc num [400002]
INFO 2021-06-18 21:45:48,399 gamma_engine.cc:1187 Loading from /data/vearch/data/2/retrieval_model_index/2021-06-18-13:43:24
INFO 2021-06-18 21:45:48,458 storage_manager.cc:352 gamma storage truncate to size=400002, current segment num=1, last offset=400002
INFO 2021-06-18 21:45:48,458 mmap_raw_vector_io.cc:23 mmap load success! vec num=400002
INFO 2021-06-18 21:45:48,458 vector_manager.cc:706 vector [fingerprint] load success!
INFO 2021-06-18 21:45:48,458 gamma_index_ivfpq.cc:1335 /data/vearch/data/2/retrieval_model_index/2021-06-18-13:43:24/fingerprint.000/ivfpq.index isn't existed, skip loading
INFO 2021-06-18 21:45:48,458 vector_manager.cc:718 vector [fingerprint_IVFPQ] load gamma index success!
INFO 2021-06-18 21:45:48,458 gamma_engine.cc:1229 load engine success! max docid=400002, load directory=/data/vearch/data/2/retrieval_model_index/2021-06-18-13:43:24, clean directorys(not done)=[]
INFO 2021-06-18 21:45:48,458 async_flush.h:70 async flush executor is started!
INFO 2021-06-18 21:45:48,638 block.cc:29 Block info, seg_id[4] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,638 block.cc:29 Block info, seg_id[4] per_block_size[65520] item_length[20] header_size[30] seg_block_capacity[400000]
INFO 2021-06-18 21:45:48,644 gamma_engine.cc:682 table cost [0.00488281]ms, vec store cost [0.000976562]ms
INFO 2021-06-18 21:45:48,644 table.cc:264 Add item _id [v5v3vv], num [410000]
INFO 2021-06-18 21:45:48,811 gamma_engine.cc:682 table cost [0.00488281]ms, vec store cost [0.000976562]ms
INFO 2021-06-18 21:45:48,811 table.cc:264 Add item _id [v51Dfd], num [420000]
INFO 2021-06-18 21:45:48,983 gamma_engine.cc:682 table cost [0.00708008]ms, vec store cost [0.000976562]ms
INFO 2021-06-18 21:45:48,983 table.cc:264 Add item _id [v5cUfE], num [430000]
INFO 2021-06-18 21:45:49,140 gamma_engine.cc:682 table cost [0.00390625]ms, vec store cost [0.000976562]ms
INFO 2021-06-18 21:45:49,140 table.cc:264 Add item _id [v4Lpzm], num [440000]
INFO 2021-06-18 21:45:49,330 gamma_engine.cc:682 table cost [0.00415039]ms, vec store cost [0.00292969]ms
INFO 2021-06-18 21:45:49,330 table.cc:264 Add item _id [v50OdY], num [450000]
INFO 2021-06-18 21:45:49,488 gamma_engine.cc:682 table cost [0.00390625]ms, vec store cost [0.000976562]ms
INFO 2021-06-18 21:45:49,488 table.cc:264 Add item _id [v5hAcV], num [460000]
INFO 2021-06-18 21:45:49,643 table.cc:264 Add item _id [v5oMjy], num [470000]
INFO 2021-06-18 21:45:49,807 gamma_engine.cc:682 table cost [0.00488281]ms, vec store cost [0.00317383]ms
INFO 2021-06-18 21:45:49,807 table.cc:264 Add item _id [v4ZKPn], num [480000]
INFO 2021-06-18 21:45:49,980 gamma_engine.cc:682 table cost [0.0141602]ms, vec store cost [0.00390625]ms
INFO 2021-06-18 21:45:49,980 table.cc:264 Add item _id [v580is], num [490000]
INFO 2021-06-18 21:45:55,338 gamma_engine.cc:877 GetDocIDbyKey [v5q9IC] error!
INFO 2021-06-18 21:45:55,564 gamma_engine.cc:877 GetDocIDbyKey [v5q9Ik] error!
INFO 2021-06-18 21:45:55,659 gamma_engine.cc:877 GetDocIDbyKey [v5q9I4] error!
INFO 2021-06-18 21:45:55,802 gamma_engine.cc:877 GetDocIDbyKey [v5q9Jz] error!
INFO 2021-06-18 21:45:55,998 gamma_engine.cc:877 GetDocIDbyKey [v5q9IA] error!
INFO 2021-06-18 21:45:56,370 gamma_engine.cc:877 GetDocIDbyKey [v5q9JE] error!
INFO 2021-06-18 21:45:56,445 gamma_engine.cc:877 GetDocIDbyKey [v5q9J8] error!
INFO 2021-06-18 21:45:56,648 gamma_engine.cc:877 GetDocIDbyKey [v5q9Hb] error!
INFO 2021-06-18 21:45:56,672 gamma_engine.cc:877 GetDocIDbyKey [v5q9HA] error!
INFO 2021-06-18 21:45:56,735 gamma_engine.cc:877 GetDocIDbyKey [v5q9KB] error!
INFO 2021-06-18 21:46:00,167 gamma_engine.cc:877 GetDocIDbyKey [v5q9JV] error!
INFO 2021-06-18 21:46:00,577 gamma_engine.cc:877 GetDocIDbyKey [v5q9KS] error!
INFO 2021-06-18 21:46:00,616 gamma_engine.cc:877 GetDocIDbyKey [v5q9HN] error!
INFO 2021-06-18 21:46:00,894 gamma_engine.cc:877 GetDocIDbyKey [v5q9J9] error!
INFO 2021-06-18 21:46:01,653 gamma_engine.cc:877 GetDocIDbyKey [v5q9KN] error!
INFO 2021-06-18 21:46:01,742 gamma_engine.cc:877 GetDocIDbyKey [v5q9Hg] error!
INFO 2021-06-18 21:46:01,961 gamma_engine.cc:877 GetDocIDbyKey [v5q9H0] error!
INFO 2021-06-18 21:46:02,421 gamma_engine.cc:877 GetDocIDbyKey [v5q9IT] error!
INFO 2021-06-18 21:46:02,639 gamma_engine.cc:877 GetDocIDbyKey [v5q9IO] error!
INFO 2021-06-18 21:46:03,064 gamma_engine.cc:877 GetDocIDbyKey [v5q9Jk] error!
INFO 2021-06-18 21:46:03,997 gamma_engine.cc:877 GetDocIDbyKey [v5ovq0] error!
INFO 2021-06-18 21:46:04,467 gamma_engine.cc:877 GetDocIDbyKey [v5q9Jl] error!
INFO 2021-06-18 21:46:04,633 gamma_engine.cc:877 GetDocIDbyKey [v5q9K0] error!
INFO 2021-06-18 21:46:05,704 gamma_engine.cc:877 GetDocIDbyKey [v5q9Je] error!
INFO 2021-06-18 21:46:06,562 gamma_engine.cc:877 GetDocIDbyKey [v5oMtJ] error!
INFO 2021-06-18 21:46:06,650 gamma_engine.cc:877 GetDocIDbyKey [v5q9IJ] error!
......
INFO 2021-06-18 21:51:06,404 gamma_engine.cc:877 GetDocIDbyKey [v5qHOu] error!
INFO 2021-06-18 21:51:06,842 gamma_engine.cc:877 GetDocIDbyKey [v5qHPu] error!
INFO 2021-06-18 21:51:07,447 gamma_engine.cc:877 GetDocIDbyKey [v5qYQj] error!
INFO 2021-06-18 21:51:07,584 gamma_engine.cc:877 GetDocIDbyKey [v5qHNI] error!
INFO 2021-06-18 21:51:07,718 gamma_engine.cc:877 GetDocIDbyKey [v5qYQx] error!
INFO 2021-06-18 21:51:08,454 gamma_engine.cc:877 GetDocIDbyKey [v5qYSB] error!
INFO 2021-06-18 21:51:08,774 gamma_engine.cc:877 GetDocIDbyKey [v5qYR2] error!
INFO 2021-06-18 21:51:08,804 gamma_engine.cc:877 GetDocIDbyKey [v5qHQ2] error!
INFO 2021-06-18 21:51:10,427 gamma_engine.cc:877 GetDocIDbyKey [v5qYQ0] error!
INFO 2021-06-18 21:51:11,143 gamma_engine.cc:877 GetDocIDbyKey [v5qHOE] error!
INFO 2021-06-18 21:51:11,152 block.cc:29 Block info, seg_id[1] per_block_size[61440] item_length[6144] header_size[30] seg_block_capacity[2000000]
INFO 2021-06-18 21:51:11,152 vector_block.cc:21 VectorBlock construction!
INFO 2021-06-18 21:51:11,152 gamma_engine.cc:675 Begin indexing.
INFO 2021-06-18 21:51:11,152 gamma_engine.cc:682 table cost [0.0300293]ms, vec store cost [0.156982]ms

**Comment by bluestar21** [comment]
> 另外麻烦提供一下gamma.log吧

另外咱们有交流群么？可以加入进去么？

**Comment by bluestar21** [comment]
> 另外麻烦提供一下gamma.log吧

另外，我这个集群之前是安装过3.1.0，遇到数据更新有问题，然后重新编译的3.2.7版本，替换了rocksdb和gamma的动态链接库，刚才发现个问题，我建表的replica_num 设置的是1，但是查询集群状态的时候显示的3
[
    {
        "errors":null,
        "db_name":"image_vectors",
        "space_num":1,
        "doc_num":1499452,
        "size":805306368,
        "spaces":[
            {
                "size":805306368,
                "partitions":[
                    {
                        "pid":1,
                        "doc_num":499855,
                        "size":268435456,
                        "replica_num":1,
                        "path":"/data/vearch/",
                        "status":4,
                        "color":"green",
                        "ip":"10.21.89.193",
                        "node_id":180,
                        "raft_status":{
                            "ID":1,
                            "NodeID":180,
                            "Leader":180,
                            "Term":3,
                            "Index":499858,
                            "Commit":499858,
                            "Applied":499858,
                            "Vote":180,
                            "PendQueue":0,
                            "RecvQueue":0,
                            "AppQueue":0,
                            "Stopped":false,
                            "RestoringSnapshot":false,
                            "State":"StateLeader",
                            "Replicas":{
                                "180":{
                                    "Match":499858,
                                    "Commit":499858,
                                    "Next":499859,
                                    "State":"ReplicaStateProbe",
                                    "Snapshoting":false,
                                    "Paused":false,
                                    "Active":false,
                                    "LastActive":"1624246278287031539",
                                    "Inflight":0
                                }
                            }
                        },
                        "index_status":0
                    },
                    {
                        "pid":2,
                        "doc_num":499798,
                        "size":268435456,
                        "replica_num":1,
                        "path":"/data/vearch/",
                        "status":4,
                        "color":"green",
                        "ip":"10.21.91.209",
                        "node_id":360,
                        "raft_status":{
                            "ID":2,
                            "NodeID":360,
                            "Leader":360,
                            "Term":4,
                            "Index":499810,
                            "Commit":499810,
                            "Applied":499810,
                            "Vote":360,
                            "PendQueue":0,
                            "RecvQueue":0,
                            "AppQueue":0,
                            "Stopped":false,
                            "RestoringSnapshot":false,
                            "State":"StateLeader",
                            "Replicas":{
                                "360":{
                                    "Match":499810,
                                    "Commit":499810,
                                    "Next":499811,
                                    "State":"ReplicaStateProbe",
                                    "Snapshoting":false,
                                    "Paused":false,
                                    "Active":false,
                                    "LastActive":"1624246711478001597",
                                    "Inflight":0
                                }
                            }
                        },
                        "index_status":0
                    },
                    {
                        "pid":3,
                        "doc_num":499799,
                        "size":268435456,
                        "replica_num":1,
                        "path":"/data/vearch/",
                        "status":4,
                        "color":"green",
                        "ip":"10.21.92.231",
                        "node_id":540,
                        "raft_status":{
                            "ID":3,
                            "NodeID":540,
                            "Leader":540,
                            "Term":4,
                            "Index":499826,
                            "Commit":499826,
                            "Applied":499826,
                            "Vote":540,
                            "PendQueue":0,
                            "RecvQueue":0,
                            "AppQueue":0,
                            "Stopped":false,
                            "RestoringSnapshot":false,
                            "State":"StateLeader",
                            "Replicas":{
                                "540":{
                                    "Match":499826,
                                    "Commit":499826,
                                    "Next":499827,
                                    "State":"ReplicaStateProbe",
                                    "Snapshoting":false,
                                    "Paused":false,
                                    "Active":false,
                                    "LastActive":"1624246783740450208",
                                    "Inflight":0
                                }
                            }
                        },
                        "index_status":0
                    }
                ],
                "status":"green",
                "name":"thumbnail_features",
                "partition_num":3,
                "replica_num":3,
                "doc_num":1499452
            }
        ],
        "status":"green"
    }
]

达到index_size时还是崩溃，报上面的错误，上述的是否跟升级集群的方式有关系？导致的集群本身有问题呢？

**Comment by bluestar21** [comment]
> 看着像分配内存失败，看看建索引时内存占用多少呢
将集群重置了之后重新编译部署，减小了index_size的值，没有再出现该问题，可能是之前升级出现了问题
已解决

**Comment by Yaningkong** [comment]
我也好像遇到了类似的问题 请问您是怎么解决的？
我用的单机3.2.5 重新编译后还是会存在这个问题

**Comment by bluestar21** [comment]
> 我也好像遇到了类似的问题 请问您是怎么解决的？
> 我用的单机3.2.5 重新编译后还是会存在这个问题

后来我是直接把集群重置了，然后直接编译的最新版本的vearch，这个问题就消失了，之前直接替换so的方式应该是有问题
