### ISSUE TITLE
数据插入问题

### ISSUE THREAD

**Issue by wuzhuhua** [vearch/vearch#477]
vearch版本3.2.5 
表空间：{
    "name": "testspace",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "retrieval_type": "IVFFLAT",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048
        }
    },
    "properties": {
        "name": {
            "type": "string",
            "array": true,
            "index": true
        },
        "age": {
            "type": "integer",
            "index": true
        },
        "fea": {
            "type": "vector",
            "dimension": 512,
            "format": "normalization",
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048
            }
        }
    }
}
创建时数据：{
    "name": "ceh",
    "age": 28,
    "fea": {
        "feature": [
            0.26836604,
            0.024692293,
            0.8286631,
            0.050325096,
            0.098363765,
            0.66199154,
            0.24451903,
            0.01591612,
            0.62562793,
            0.41290408,
            0.116320096,
            0.9588706,
            0.40760303,
            0.69786274,
            0.84488356,
            0.008081466,
            0.0038567781,
            0.0075597875,
            0.34425068,
            0.54004055,
            0.93992835,
            0.24638586,
            0.4932025,
            0.156326,
            0.8992662,
            0.9339397,
            0.34686276,
            0.29298013,
            0.9028069,
            0.47069475,
            0.32545975,
            0.9574138,
            0.34609947,
            0.76082164,
            0.22329412,
            0.31601182,
            0.155479,
            0.1033292,
            0.2881884,
            0.114403814,
            0.9976475,
            0.41210306,
            0.810169,
            0.20240392,
            0.43111962,
            0.5060809,
            0.6278585,
            0.7569111,
            0.12334278,
            0.42272246,
            0.7120326,
            0.1486018,
            0.7739042,
            0.45109165,
            0.51802236,
            0.78203505,
            0.18208627,
            0.85528606,
            0.11212016,
            0.65382934,
            0.97613597,
            0.06461053,
            0.17187172,
            0.8198602,
            0.8819639,
            0.4438069,
            0.83611685,
            0.43996572,
            0.0505903,
            0.624816,
            0.037864026,
            0.5774362,
            0.88650805,
            0.78096133,
            0.3915644,
            0.47060484,
            0.023232516,
            0.1551089,
            0.92607385,
            0.56514263,
            0.577661,
            0.61527044,
            0.9555713,
            0.1982027,
            0.5814657,
            0.004283162,
            0.16292559,
            0.45934582,
            0.53559583,
            0.57461137,
            0.533482,
            0.4182197,
            0.36306468,
            0.85498023,
            0.12196377,
            0.60525304,
            0.6455522,
            0.88246626,
            0.7611625,
            0.3591637,
            0.92095155,
            0.85183305,
            0.7283171,
            0.41387105,
            0.9918418,
            0.8833136,
            0.073557034,
            0.8874401,
            0.6489706,
            0.79070693,
            0.7845129,
            0.6569745,
            0.94918084,
            0.443569,
            0.2121738,
            0.95591545,
            0.20381778,
            0.5604421,
            0.21529745,
            0.9139911,
            0.13150552,
            0.54448193,
            0.29415482,
            0.675101,
            0.2082808,
            0.2785053,
            0.5791195,
            0.6747096,
            0.108426504,
            0.6333939,
            0.9155863,
            0.6358611,
            0.2709469,
            0.81195664,
            0.44393194,
            0.8517166,
            0.0494787,
            0.5497646,
            0.01170631,
            0.36255515,
            0.6075342,
            0.62513703,
            0.47496933,
            0.7064684,
            0.70632297,
            0.09237285,
            0.44666573,
            0.0255166,
            0.7990024,
            0.1454833,
            0.33215603,
            0.4429051,
            0.3930556,
            0.54409766,
            0.55549824,
            0.7917775,
            0.4716004,
            0.088877305,
            0.7248025,
            0.9725116,
            0.87478197,
            0.72068644,
            0.1109563,
            0.44294348,
            0.9340049,
            0.43593454,
            0.22124517,
            0.6047332,
            0.32461044,
            0.35991585,
            0.4378695,
            0.13912612,
            0.056708626,
            0.00063921,
            0.66108644,
            0.6666512,
            0.7592233,
            0.9175524,
            0.6476801,
            0.45783833,
            0.9288131,
            0.78273153,
            0.2676912,
            0.30582476,
            0.6131802,
            0.086518444,
            0.2158142,
            0.08675974,
            0.07738203,
            0.54525405,
            0.8085955,
            0.9802063,
            0.36211118,
            0.6056699,
            0.37454286,
            0.7992778,
            0.28451243,
            0.3086626,
            0.40148464,
            0.389035,
            0.35495454,
            0.17459226,
            0.0439905,
            0.5917109,
            0.28727904,
            0.7029084,
            0.8133961,
            0.8486162,
            0.26539698,
            0.54082066,
            0.2739465,
            0.11112035,
            0.8957087,
            0.36889797,
            0.3508036,
            0.3668916,
            0.8226712,
            0.07589065,
            0.41913608,
            0.75261605,
            0.3139406,
            0.8507366,
            0.68823916,
            0.9207085,
            0.731868,
            0.40662584,
            0.52060723,
            0.055064205,
            0.6997289,
            0.6701613,
            0.23310865,
            0.6896913,
            0.9439183,
            0.9180685,
            0.6158894,
            0.27410117,
            0.24744384,
            0.52457064,
            0.8743577,
            0.25062484,
            0.6854026,
            0.19445951,
            0.9505803,
            0.2613613,
            0.3297277,
            0.8000567,
            0.21264397,
            0.98625314,
            0.90834236,
            0.71467394,
            0.31401762,
            0.028824154,
            0.48296165,
            0.84084535,
            0.6196715,
            0.21240172,
            0.07013163,
            0.36851817,
            0.9716909,
            0.62718767,
            0.27170026,
            0.6665525,
            0.72434497,
            0.7773281,
            0.40376297,
            0.6102957,
            0.91705084,
            0.21717343,
            0.317229,
            0.07866012,
            0.17339756,
            0.13720833,
            0.08850604,
            0.3160465,
            0.41537142,
            0.46267024,
            0.025401896,
            0.34762117,
            0.7641518,
            0.16166446,
            0.9811934,
            0.6608675,
            0.062322024,
            0.6246225,
            0.79891515,
            0.9219971,
            0.2970668,
            0.17324011,
            0.8182708,
            0.5827196,
            0.8299047,
            0.9845694,
            0.769173,
            0.8510356,
            0.74572974,
            0.9747299,
            0.04876776,
            0.64912796,
            0.8224138,
            0.47674105,
            0.33290216,
            0.8620952,
            0.5919475,
            0.868269,
            0.7083449,
            0.39318123,
            0.7150737,
            0.65761834,
            0.028671002,
            0.28432116,
            0.4235948,
            0.92008966,
            0.99457407,
            0.43523702,
            0.09801108,
            0.39186212,
            0.5384698,
            0.25998104,
            0.1428744,
            0.97484976,
            0.45360777,
            0.95673835,
            0.1982176,
            0.8835184,
            0.8495083,
            0.93486464,
            0.38264677,
            0.173441,
            0.9383939,
            0.34254888,
            0.7021602,
            0.93140566,
            0.8613866,
            0.56915534,
            0.9784844,
            0.97818214,
            0.7485921,
            0.058212038,
            0.65169376,
            0.5375905,
            0.97379625,
            0.7601789,
            0.5941076,
            0.95930374,
            0.6123481,
            0.07854081,
            0.6359341,
            0.24785806,
            0.439907,
            0.218436,
            0.84785825,
            0.84663033,
            0.42008236,
            0.4339445,
            0.7517461,
            0.85308313,
            0.52059597,
            0.78832436,
            0.53786653,
            0.60036725,
            0.8704488,
            0.6908983,
            0.05550408,
            0.3304085,
            0.72467524,
            0.65495753,
            0.81356883,
            0.5048973,
            0.4386203,
            0.43296245,
            0.4787801,
            0.15313661,
            0.6702747,
            0.9284859,
            0.39123115,
            0.5394938,
            0.32705748,
            0.05875666,
            0.4306172,
            0.3482409,
            0.3525349,
            0.0473264,
            0.1611355,
            0.5298567,
            0.30891603,
            0.46329668,
            0.5590431,
            0.9304031,
            0.8527687,
            0.691707,
            0.7840851,
            0.8343776,
            0.6242499,
            0.41909862,
            0.39448074,
            0.59148246,
            0.774245,
            0.1489329,
            0.12488451,
            0.56904,
            0.33916584,
            0.7234579,
            0.84771216,
            0.77432346,
            0.939753,
            0.32177937,
            0.6204515,
            0.6248609,
            0.8280863,
            0.4283083,
            0.7850521,
            0.50980836,
            0.13610247,
            0.8214191,
            0.930216,
            0.9817804,
            0.28927594,
            0.7190687,
            0.1533869,
            0.64606017,
            0.9407161,
            0.836289,
            0.46646327,
            0.07290547,
            0.4537889,
            0.2588815,
            0.37773567,
            0.348703,
            0.91547054,
            0.71830326,
            0.65227705,
            0.2030132,
            0.89799273,
            0.064652026,
            0.003989506,
            0.0010861708,
            0.7029421,
            0.4778189,
            0.00473906,
            0.2752213,
            0.61982495,
            0.23129201,
            0.8094854,
            0.88337696,
            0.81021357,
            0.62876004,
            0.39104104,
            0.32973135,
            0.78893906,
            0.070575826,
            0.8540704,
            0.25943047,
            0.11539844,
            0.07530724,
            0.05516581,
            0.6485505,
            0.83089596,
            0.48101443,
            0.19431376,
            0.7503405,
            0.38203833,
            0.9815576,
            0.26279318,
            0.43009892,
            0.2555569,
            0.6151536,
            0.23352072,
            0.12357963,
            0.3165304,
            0.81556284,
            0.6620875,
            0.28760844,
            0.88983405,
            0.16070308,
            0.9302074,
            0.8766334,
            0.953741,
            0.0091505125,
            0.70802253,
            0.0752192,
            0.42495614,
            0.8019018,
            0.33769026,
            0.24403569,
            0.4059612,
            0.9249358,
            0.7479002,
            0.79568017,
            0.4384034,
            0.6775272,
            0.19744822,
            0.506711,
            0.26036102,
            0.07192887,
            0.6157198,
            0.59356,
            0.30066994,
            0.90195286,
            0.5589125,
            0.73253024,
            0.16009869,
            0.7611452,
            0.83305305,
            0.0878741,
            0.6270088,
            0.46566245,
            0.6483415,
            0.32698622,
            0.35424063,
            0.642624,
            0.764082
        ]
    }
}
创建返回结果：{
    "error": {
        "root_cause": [
            {
                "type": "",
                "reason": "gamma create doc err code:[-4]"
            }
        ],
        "type": "",
        "reason": "gamma create doc err code:[-4]"
    },
    "status": 400
}

**Comment by zcdb** [comment]
贴一下gamma.log，err code -4 应该是插入向量的时候失败，看看gamma.log里面有更详细的信息不

**Comment by wuzhuhua** [comment]
INFO 2021-06-22 08:39:59,192 table_io.cc:22 Table load successed! doc num=0
INFO 2021-06-22 08:39:59,192 vector_manager.cc:692 vector [fea] load success!
INFO 2021-06-22 08:39:59,192 gamma_engine.cc:1229 load engine success! max docid=0, load directory=, clean directorys(not done)=[]
INFO 2021-06-22 08:39:59,192 async_flush.h:70 async flush executor is started!
INFO 2021-06-22 08:40:20,498 table.cc:335 Add item _id [3909114122161983027], num [0]
ERROR 2021-06-22 08:40:20,498 raw_vector.cc:279 Doc [0] len 2044]
INFO 2021-06-22 08:45:42,014 table.cc:335 Add item _id [-3942801722916704376], num [0]
ERROR 2021-06-22 08:45:42,014 raw_vector.cc:279 Doc [0] len 2044]
INFO 2021-06-22 08:46:07,103 table.cc:335 Add item _id [9107010991952935589], num [0]
ERROR 2021-06-22 08:46:07,103 raw_vector.cc:279 Doc [0] len 2044]
这是gamma日志

**Comment by wuzhuhua** [comment]
> 贴一下gamma.log，err code -4 应该是插入向量的时候失败，看看gamma.log里面有更详细的信息不

INFO 2021-06-22 08:39:59,192 table_io.cc:22 Table load successed! doc num=0
INFO 2021-06-22 08:39:59,192 vector_manager.cc:692 vector [fea] load success!
INFO 2021-06-22 08:39:59,192 gamma_engine.cc:1229 load engine success! max docid=0, load directory=, clean directorys(not done)=[]
INFO 2021-06-22 08:39:59,192 async_flush.h:70 async flush executor is started!
INFO 2021-06-22 08:40:20,498 table.cc:335 Add item _id [3909114122161983027], num [0]
ERROR 2021-06-22 08:40:20,498 raw_vector.cc:279 Doc [0] len 2044]
INFO 2021-06-22 08:45:42,014 table.cc:335 Add item _id [-3942801722916704376], num [0]
ERROR 2021-06-22 08:45:42,014 raw_vector.cc:279 Doc [0] len 2044]
INFO 2021-06-22 08:46:07,103 table.cc:335 Add item _id [9107010991952935589], num [0]
ERROR 2021-06-22 08:46:07,103 raw_vector.cc:279 Doc [0] len 2044]
这是gamma.log

**Comment by zcdb** [comment]
数据维度不对，512维应该是2048，gamma日志显示是2044，少了4个字节

**Comment by wuzhuhua** [comment]
> 数据维度不对，512维应该是2048，gamma日志显示是2044，少了4个字节
确实是少了4字节，单条插入的问题解决了，
不过批量插入时，是否需要修改请求的大小限制？
目前批量插入时报：
{
    "error": {
        "root_cause": [
            {
                "type": "",
                "reason": "ReadMapCB: expect \" after }, but found \u0000, error found in #1 byte of ...|{|..., bigger context ...|{|..."
            }
        ],
        "type": "",
        "reason": "ReadMapCB: expect \" after }, but found \u0000, error found in #1 byte of ...|{|..., bigger context ...|{|..."
    },
    "status": 400
}

**Comment by zcdb** [comment]
看着像是批量插入数据的格式不对，具体的格式可以参考下文档 https://vearch.readthedocs.io/zh_CN/latest/

**Comment by wuzhuhua** [comment]
> 看着像是批量插入数据的格式不对，具体的格式可以参考下文档 https://vearch.readthedocs.io/zh_CN/latest/
换了一下格式报：{
    "error": {
        "root_cause": [
            {
                "type": "",
                "reason": "Unmarshal: there are bytes left after unmarshal, error found in #10 byte of ...|985305]}}\\n|..., bigger context ...|502,0.8498061,0.8411212,0.48700887,0.040985305]}}\\n|..."
            }
        ],
        "type": "",
        "reason": "Unmarshal: there are bytes left after unmarshal, error found in #10 byte of ...|985305]}}\\n|..., bigger context ...|502,0.8498061,0.8411212,0.48700887,0.040985305]}}\\n|..."
    },
    "status": 400
}
批量插入参数如下：{"name":"ceh","age":28,"fea":{"feature":[0.72665733,0.2716765,0.38069457,0.8085939,0.08393119,0.73594093,0.7249987,0.57338256,0.14549686,0.061833773,0.6514583,0.59770733,0.27428815,0.6111973,0.2298629,0.13393821,0.9084506,0.5973749,0.051602047,0.0044077234,0.55177087,0.2665096,0.5783675,0.580333,0.7880934,0.0062502567,0.031215932,0.8213389,0.7980273,0.05669996,0.2558137,0.83996826,0.9665965,0.58535635,0.62566155,0.6831048,0.5620882,0.5059568,0.45232385,0.2810218,0.1392065,0.57055634,0.5601642,0.804811,0.2737397,0.94482917,0.65281487,0.99423283,0.47130027,0.68849987,0.84958345,0.37056983,0.60930014,0.30597347,0.30222973,0.6328536,0.0691727,0.8066483,0.11601801,0.9508748,0.79495794,0.52005905,0.8936805,0.31467384,0.87471426,0.24791208,0.09690166,0.5777513,0.88282734,0.20323864,0.07716063,0.3400235,0.14413323,0.5863059,0.06624593,0.356589,0.284877,0.5775899,0.6364821,0.72966176,0.9208801,0.99002826,0.14168593,0.7435631,0.099888615,0.8159346,0.4320944,0.8364571,0.16292973,0.42837158,0.6999859,0.8675497,0.01860178,0.25244132,0.65744025,0.53476447,0.43457764,0.3088692,0.37366033,0.5254424,0.8422009,0.15041801,0.0065061767,0.7414079,0.32290667,0.3610854,0.3513668,0.7297761,0.89930063,0.9687012,0.60022247,0.27217185,0.98908037,0.83345467,0.95472765,0.9375637,0.89658624,0.318047,0.76936966,0.28771037,0.51461923,0.3195767,0.7142357,0.33925307,0.9882651,0.048931487,0.04164786,0.8327778,0.95281637,0.78037304,0.41690066,0.83670926,0.09948485,0.16216527,0.9305645,0.2226894,0.24544802,0.5785117,0.84829265,0.58912945,0.7888761,0.48372993,0.37379766,0.28091702,0.41493636,0.5915068,0.20163901,0.25579572,0.18537398,0.29524156,0.9186902,0.68172586,0.69211966,0.71989757,0.37663037,0.31457284,0.7844762,0.361448,0.0025319646,0.90175945,0.48978722,0.35691515,0.64059263,0.08505685,0.13909352,0.046166074,0.9252857,0.53447855,0.38213396,0.6360423,0.37468097,0.33528057,0.7301482,0.4580651,0.36241293,0.97135997,0.5002923,0.5228719,0.87775165,0.60088277,0.55207783,0.8177027,0.51545614,0.7037624,0.004096939,0.06767164,0.45056883,0.5956469,0.1983998,0.48721936,0.24803402,0.7493647,0.54023796,0.3850602,0.23300189,0.34231538,0.4824933,0.35409787,0.8049049,0.957083,0.8469606,0.17720146,0.5168696,0.9025866,0.8787548,0.5103941,0.9617557,0.1943737,0.91546565,0.8669234,0.5070875,0.8351997,0.319283,0.4188451,0.7033723,0.6708271,0.3681684,0.6571669,0.7537753,0.7610146,0.13125043,0.007261016,0.77784723,0.90195966,0.96397144,0.08317209,0.727979,0.6639921,0.15011677,0.38260657,0.72448117,0.06710956,0.39070764,0.8738073,0.26366612,0.80698204,0.29384094,0.10617938,0.22303487,0.765343,0.75491065,0.1884475,0.8386481,0.39122403,0.133248,0.2212901,0.8619872,0.42327672,0.42906728,0.5458081,0.91708803,0.3384684,0.24370721,0.4748516,0.67345595,0.8587233,0.16650963,0.011140956,0.82624847,0.82462263,0.3732768,0.424283,0.032437094,0.7540655,0.64410263,0.45819807,0.89013684,0.4438302,0.7124731,0.371135,0.76801974,0.0432664,0.842883,0.9723698,0.7927032,0.1318874,0.80081874,0.3128422,0.5842319,0.46641952,0.9268062,0.71140355,0.39324853,0.2279055,0.8553274,0.3540098,0.13817425,0.7957487,0.5297578,0.7901094,0.4666978,0.3031228,0.55608064,0.2686397,0.3730973,0.48696038,0.6109847,0.0054586018,0.09139575,0.6357749,0.574053,0.15470326,0.95407915,0.759857,0.2891035,0.4684816,0.65708023,0.46092746,0.3763422,0.3724658,0.90395945,0.3621165,0.31484187,0.45937145,0.7156906,0.37417907,0.093960814,0.20797053,0.78718543,0.52014476,0.09266843,0.0721992,0.14766654,0.5181398,0.48734394,0.9530871,0.039227743,0.8309071,0.41146868,0.4656472,0.36639377,0.43059188,0.29473177,0.3435311,0.2892206,0.09864476,0.29442233,0.7861668,0.5334532,0.6832391,0.49858117,0.54626167,0.7734835,0.37038317,0.6282385,0.079966724,0.0073295003,0.6899503,0.2951635,0.137662,0.18758085,0.6741378,0.4819053,0.76023793,0.49823534,0.31340405,0.8025048,0.7639103,0.5745748,0.21372408,0.27510944,0.44602194,0.65170753,0.1490404,0.79182416,0.4249469,0.097129054,0.024077697,0.20648295,0.23912823,0.033631653,0.61522627,0.97762764,0.5734436,0.7911179,0.34099105,0.6018324,0.7555073,0.73935074,0.22853965,0.6516122,0.47018182,0.64839906,0.18917283,0.09250765,0.47748533,0.0995151,0.69308084,0.6955378,0.4872458,0.6264044,0.9425364,0.78406566,0.24326734,0.20532885,0.68271506,0.2582224,0.3004368,0.43220633,0.8606234,0.82538635,0.9401143,0.22584999,0.44515324,0.63181734,0.16231473,0.17871526,0.8550692,0.03839572,0.7176009,0.7399993,0.6067783,0.11251817,0.6972738,0.2606648,0.9900155,0.51855415,0.28736007,0.5559358,0.80712163,0.8808682,0.9100578,0.048040684,0.47037748,0.36626408,0.1257209,0.74045336,0.041896753,0.18681023,0.34912136,0.24460995,0.12187092,0.9593549,0.6456455,0.8310563,0.84349656,0.3746435,0.61624444,0.009206284,0.61670595,0.42680067,0.6543714,0.45336893,0.6778602,0.5330413,0.6638046,0.18742815,0.9488535,0.23382704,0.66316617,0.8165359,0.1866158,0.8052858,0.5711148,0.2514056,0.9127908,0.038563322,0.8655997,0.8092698,0.1534049,0.64487714,0.7412322,0.79529226,0.58963186,0.2303966,0.8507411,0.66920155,0.3232963,0.5516712,0.70964456,0.6841388,0.0945501,0.81018347,0.3676857,0.44819072,0.45419303,0.0737041,0.00623981,0.20380355,0.08939797,0.522476,0.7078197,0.7462512,0.22914189,0.109859355,0.7619663,0.8095576,0.8144311,0.39991823,0.5212269,0.4367491,0.9084487,0.7985324,0.0015885618,0.32103962,0.6430423,0.12996909,0.13364545,0.3555286,0.8505076,0.527451,0.8139463,0.66121674,0.4134129,0.9041085,0.6803799,0.17662261,0.2802502,0.8498061,0.8411212,0.48700887,0.040985305]}}\n
{"name":"ceh","age":28,"fea":{"feature":[0.72665733,0.2716765,0.38069457,0.8085939,0.08393119,0.73594093,0.7249987,0.57338256,0.14549686,0.061833773,0.6514583,0.59770733,0.27428815,0.6111973,0.2298629,0.13393821,0.9084506,0.5973749,0.051602047,0.0044077234,0.55177087,0.2665096,0.5783675,0.580333,0.7880934,0.0062502567,0.031215932,0.8213389,0.7980273,0.05669996,0.2558137,0.83996826,0.9665965,0.58535635,0.62566155,0.6831048,0.5620882,0.5059568,0.45232385,0.2810218,0.1392065,0.57055634,0.5601642,0.804811,0.2737397,0.94482917,0.65281487,0.99423283,0.47130027,0.68849987,0.84958345,0.37056983,0.60930014,0.30597347,0.30222973,0.6328536,0.0691727,0.8066483,0.11601801,0.9508748,0.79495794,0.52005905,0.8936805,0.31467384,0.87471426,0.24791208,0.09690166,0.5777513,0.88282734,0.20323864,0.07716063,0.3400235,0.14413323,0.5863059,0.06624593,0.356589,0.284877,0.5775899,0.6364821,0.72966176,0.9208801,0.99002826,0.14168593,0.7435631,0.099888615,0.8159346,0.4320944,0.8364571,0.16292973,0.42837158,0.6999859,0.8675497,0.01860178,0.25244132,0.65744025,0.53476447,0.43457764,0.3088692,0.37366033,0.5254424,0.8422009,0.15041801,0.0065061767,0.7414079,0.32290667,0.3610854,0.3513668,0.7297761,0.89930063,0.9687012,0.60022247,0.27217185,0.98908037,0.83345467,0.95472765,0.9375637,0.89658624,0.318047,0.76936966,0.28771037,0.51461923,0.3195767,0.7142357,0.33925307,0.9882651,0.048931487,0.04164786,0.8327778,0.95281637,0.78037304,0.41690066,0.83670926,0.09948485,0.16216527,0.9305645,0.2226894,0.24544802,0.5785117,0.84829265,0.58912945,0.7888761,0.48372993,0.37379766,0.28091702,0.41493636,0.5915068,0.20163901,0.25579572,0.18537398,0.29524156,0.9186902,0.68172586,0.69211966,0.71989757,0.37663037,0.31457284,0.7844762,0.361448,0.0025319646,0.90175945,0.48978722,0.35691515,0.64059263,0.08505685,0.13909352,0.046166074,0.9252857,0.53447855,0.38213396,0.6360423,0.37468097,0.33528057,0.7301482,0.4580651,0.36241293,0.97135997,0.5002923,0.5228719,0.87775165,0.60088277,0.55207783,0.8177027,0.51545614,0.7037624,0.004096939,0.06767164,0.45056883,0.5956469,0.1983998,0.48721936,0.24803402,0.7493647,0.54023796,0.3850602,0.23300189,0.34231538,0.4824933,0.35409787,0.8049049,0.957083,0.8469606,0.17720146,0.5168696,0.9025866,0.8787548,0.5103941,0.9617557,0.1943737,0.91546565,0.8669234,0.5070875,0.8351997,0.319283,0.4188451,0.7033723,0.6708271,0.3681684,0.6571669,0.7537753,0.7610146,0.13125043,0.007261016,0.77784723,0.90195966,0.96397144,0.08317209,0.727979,0.6639921,0.15011677,0.38260657,0.72448117,0.06710956,0.39070764,0.8738073,0.26366612,0.80698204,0.29384094,0.10617938,0.22303487,0.765343,0.75491065,0.1884475,0.8386481,0.39122403,0.133248,0.2212901,0.8619872,0.42327672,0.42906728,0.5458081,0.91708803,0.3384684,0.24370721,0.4748516,0.67345595,0.8587233,0.16650963,0.011140956,0.82624847,0.82462263,0.3732768,0.424283,0.032437094,0.7540655,0.64410263,0.45819807,0.89013684,0.4438302,0.7124731,0.371135,0.76801974,0.0432664,0.842883,0.9723698,0.7927032,0.1318874,0.80081874,0.3128422,0.5842319,0.46641952,0.9268062,0.71140355,0.39324853,0.2279055,0.8553274,0.3540098,0.13817425,0.7957487,0.5297578,0.7901094,0.4666978,0.3031228,0.55608064,0.2686397,0.3730973,0.48696038,0.6109847,0.0054586018,0.09139575,0.6357749,0.574053,0.15470326,0.95407915,0.759857,0.2891035,0.4684816,0.65708023,0.46092746,0.3763422,0.3724658,0.90395945,0.3621165,0.31484187,0.45937145,0.7156906,0.37417907,0.093960814,0.20797053,0.78718543,0.52014476,0.09266843,0.0721992,0.14766654,0.5181398,0.48734394,0.9530871,0.039227743,0.8309071,0.41146868,0.4656472,0.36639377,0.43059188,0.29473177,0.3435311,0.2892206,0.09864476,0.29442233,0.7861668,0.5334532,0.6832391,0.49858117,0.54626167,0.7734835,0.37038317,0.6282385,0.079966724,0.0073295003,0.6899503,0.2951635,0.137662,0.18758085,0.6741378,0.4819053,0.76023793,0.49823534,0.31340405,0.8025048,0.7639103,0.5745748,0.21372408,0.27510944,0.44602194,0.65170753,0.1490404,0.79182416,0.4249469,0.097129054,0.024077697,0.20648295,0.23912823,0.033631653,0.61522627,0.97762764,0.5734436,0.7911179,0.34099105,0.6018324,0.7555073,0.73935074,0.22853965,0.6516122,0.47018182,0.64839906,0.18917283,0.09250765,0.47748533,0.0995151,0.69308084,0.6955378,0.4872458,0.6264044,0.9425364,0.78406566,0.24326734,0.20532885,0.68271506,0.2582224,0.3004368,0.43220633,0.8606234,0.82538635,0.9401143,0.22584999,0.44515324,0.63181734,0.16231473,0.17871526,0.8550692,0.03839572,0.7176009,0.7399993,0.6067783,0.11251817,0.6972738,0.2606648,0.9900155,0.51855415,0.28736007,0.5559358,0.80712163,0.8808682,0.9100578,0.048040684,0.47037748,0.36626408,0.1257209,0.74045336,0.041896753,0.18681023,0.34912136,0.24460995,0.12187092,0.9593549,0.6456455,0.8310563,0.84349656,0.3746435,0.61624444,0.009206284,0.61670595,0.42680067,0.6543714,0.45336893,0.6778602,0.5330413,0.6638046,0.18742815,0.9488535,0.23382704,0.66316617,0.8165359,0.1866158,0.8052858,0.5711148,0.2514056,0.9127908,0.038563322,0.8655997,0.8092698,0.1534049,0.64487714,0.7412322,0.79529226,0.58963186,0.2303966,0.8507411,0.66920155,0.3232963,0.5516712,0.70964456,0.6841388,0.0945501,0.81018347,0.3676857,0.44819072,0.45419303,0.0737041,0.00623981,0.20380355,0.08939797,0.522476,0.7078197,0.7462512,0.22914189,0.109859355,0.7619663,0.8095576,0.8144311,0.39991823,0.5212269,0.4367491,0.9084487,0.7985324,0.0015885618,0.32103962,0.6430423,0.12996909,0.13364545,0.3555286,0.8505076,0.527451,0.8139463,0.66121674,0.4134129,0.9041085,0.6803799,0.17662261,0.2802502,0.8498061,0.8411212,0.48700887,0.040985305]}}\n
