### ISSUE TITLE
高并发下属性锁耗时过长的优化

### ISSUE THREAD

**Issue by WeiYan-Lynn** [vearch/vearch#481]
当前在高并发下进行在线搜索，发现性能瓶颈在于lru_cache.h里的锁，std::lock_guard<std::mutex> lock(mtx_);大概会多耗时100-200ms，这个有优化计划吗

**Comment by gyd-a** [comment]
你可以cache的大小设置大一些试试。

**Comment by gyd-a** [comment]
你cup使用在95%左右的情况，cache的延时是多少。

**Comment by WeiYan-Lynn** [comment]
基本就是这么多啊，然后perf看了下cpu占用率，8成都在锁

**Comment by wxingda** [comment]
lru_cache.h 已经删除
