### ISSUE TITLE
what is the future plan of this project? Or is this project slowly dying?

### ISSUE THREAD

**Issue by jdhao** [vearch/vearch#488]
Judging from the activity of this repo, it seems that vearch is not actively maintained. The vearch documentation is also terribly lacking and is not up to the standard for an enterprise-level open source project.

Currently, I think vearch still has a little edge over its competitor, you know who, [milvus](https://github.com/milvus-io/milvus), but milvus is actively developed and widely publicized, with its feature catching up to vearch.

There is a high chance that people will finally switch to milvus and drop vearch, if this project keeps its current state of development.

So what is the future plan of the vearch team?  cc @ljeagle @zcdb

**Comment by ljeagle** [comment]
Sorry for just seeing your issue. First thank you very much for concerning vearch.  You know, generally there are many projects and things in large scale business enterprise.  Vearch is just one project of our team. Indeed, our energy, time and resources are very limited, so the activity and release process of vearch are relatively slow. We look forward to the participation and contribution of the professionals who pay attention to the project like you！
As for vearch,  we focus on the high availability in production, not just a scientific tool or an useless toy.  We believe in the real value，making innovations and our own contributions,  we hope our own works on valuable models should be useful for solving the problems in actual business scenario, so we never just wrap any ANN algorithm in research or papers without consideration or practice. That is the reason why so many large enterprises like HUAWEI, iFLYTEK, OPPO, IQIYI and etc. still choose vearch in the condition of litter publicity investment.  
We are doing some useful and interesting work which can improve the performance in actual scenario, hope it would be open sourced as soon as possible, but need time to test and verify. You can pay attention to the roadmap of the project. It will be updated recently. Thank you！

**Comment by ljeagle** [comment]
> Judging from the activity of this repo, it seems that vearch is not actively maintained. The vearch documentation is also terribly lacking and is not up to the standard for an enterprise-level open source project.
> 
> Currently, I think vearch still has a little edge over its competitor, you know who, [milvus](https://github.com/milvus-io/milvus), but milvus is actively developed and widely publicized, with its feature catching up to vearch.
> 
> There is a high chance that people will finally switch to milvus and drop vearch, if this project keeps its current state of development.
> 
> So what is the future plan of the vearch team? cc @ljeagle @zcdb

Sorry for just seeing your issue. First thank you very much for concerning vearch. You know, generally there are many projects and things in large scale business enterprise. Vearch is just one project of our team. Indeed, our energy, time and resources are very limited, so the activity and release process of vearch are relatively slow. We look forward to the participation and contribution of the professionals who pay attention to the project like you！
As for vearch, we focus on the high availability in production, not just a scientific tool or an useless toy. We believe in the real value，making innovations and our own contributions, we hope our own works on valuable models should be useful for solving the problems in actual business scenario, so we never just wrap any ANN algorithm in research or papers without consideration or practice. That is the reason why so many large enterprises like HUAWEI, iFLYTEK, OPPO, IQIYI and etc. still choose vearch in the condition of litter publicity investment.
We are doing some useful and interesting work which can improve the performance in actual scenario, hope it would be open sourced as soon as possible, but need time to test and verify. You can pay attention to the roadmap of the project. It will be updated recently. Thank you！
