### ISSUE TITLE
not enuogh ps, 这个要怎么处理才能跑起hello world

### ISSUE THREAD

**Issue by manlinting** [vearch/vearch#49]
* About to connect() to 127.0.0.1 port 8817 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8817 (#0)
* Server auth using Basic with user 'root'
> PUT /space/test_vector_db/_create HTTP/1.1
> Authorization: Basic cm9vdDpzZWNyZXQ=
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8817
> Accept: */*
> content-type: application/json
> Content-Length: 794
> 
* upload completely sent off: 794 out of 794 bytes
< HTTP/1.1 586 status code 586
< Content-Type: application/json
< Date: Fri, 29 Nov 2019 11:24:13 GMT
< Content-Length: 34
< 
* Connection #0 to host 127.0.0.1 left intact
{"code":586,"msg":"not enough PS"}# 

1129 19:24:13.779994    8686 master_cache.go:376] [INFO] remove space cache dbID:[1] space:[7] 
D1129 19:24:13.780293    8686 cluster_api.go:294] [DEBUG] create space, db: 
E1129 19:24:13.780307    8686 cluster_api.go:295] [ERROR] createSpaceService err: not enough PS
[GIN] 2019/11/29 - 19:24:13 | 586 |  5.004712717s |       127.0.0.1 | PUT      /space/test_vector_db/_create
D1129 19:24:18.293195    8686 startup.go:108] [DEBUG] mem.Alloc:14567416 mem.TotalAlloc:28089928 mem.HeapAlloc:14567416 mem.HeapSys:63766528 routing :106
D1129 19:24:24.281897    8686 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!
D1129 19:24:28.293387    8686 startup.go:108] [DEBUG] mem.Alloc:11770096 mem.TotalAlloc:28271904 mem.HeapAlloc:11770096 mem.HeapSys:63766528 routing :106
D1129 19:24:30.076020    8686 schedule_job.go:136] [DEBUG] Start clean task
I1129 19:24:30.076214    8686 schedule_job.go:36] [INFO] Start Walking Partitions!
I1129 19:24:30.076226    8686 schedule_job.go:58] [INFO] Complete Walking Partitions!
I1129 19:24:30.076427    8686 schedule_job.go:63] [INFO] Start Walking Spaces!
I1129 19:24:30.076440    8686 schedule_job.go:76] [INFO] Complete Walking Spaces!
I1129 19:24:30.076638    8686 schedule_job.go:86] [INFO] Start Walking Servers!
I1129 19:24:30.076648    8686 schedule_job.go:100] [INFO] Complete Walking Servers!
D1129 19:24:38.293590    8686 startup.go:108] [DEBUG] mem.Alloc:12016000 mem.TotalAlloc:28517808 mem.HeapAlloc:12016000 mem.HeapSys:63766528 routing :106
D1129 19:24:48.293766    8686 startup.go:108] [DEBUG] mem.Alloc:12213984 mem.TotalAlloc:28715792 mem.HeapAlloc:12213984 mem.HeapSys:63766528 routing :106
I1129 19:24:48.355768    8686 schedule_job.go:104] [INFO] Receive keepalive, leaseId: 6509230568158846988, ttl:188
D1129 19:24:58.293949    8686 startup.go:108] [DEBUG] mem.Alloc:12379072 mem.TotalAlloc:28880880 mem.HeapAlloc:12379072 mem.HeapSys:63766528 routing :106
D1129 19:25:08.294122    8686 startup.go:108] [DEBUG] mem.Alloc:12545384 mem.TotalAlloc:29047192 mem.HeapAlloc:12545384 mem.HeapSys:63766528 routing :106
D1129 19:25:18.294299    8686 startup.go:108] [DEBUG] mem.Alloc:12740464 mem.TotalAlloc:29242272 mem.HeapAlloc:12740464 mem.HeapSys:63766528 routing :106
D1129 19:25:24.282022    8686 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!

**Comment by ansjsun** [comment]
建表语句怎么写的啊？ 还有程序是怎么启动的





在2019年11月29日 19:25，lincolnlin 写道：
About to connect() to 127.0.0.1 port 8817 (#0)
Trying 127.0.0.1...
Connected to 127.0.0.1 (127.0.0.1) port 8817 (#0)
Server auth using Basic with user 'root'

PUT /space/test_vector_db/_create HTTP/1.1
Authorization: Basic cm9vdDpzZWNyZXQ=
User-Agent: curl/7.29.0
Host: 127.0.0.1:8817
Accept: /
content-type: application/json
Content-Length: 794

upload completely sent off: 794 out of 794 bytes
< HTTP/1.1 586 status code 586
< Content-Type: application/json
< Date: Fri, 29 Nov 2019 11:24:13 GMT
< Content-Length: 34
<
Connection #0 to host 127.0.0.1 left intact
{"code":586,"msg":"not enough PS"}#

1129 19:24:13.779994 8686 master_cache.go:376] [INFO] remove space cache dbID:[1] space:[7]
D1129 19:24:13.780293 8686 cluster_api.go:294] [DEBUG] create space, db:
E1129 19:24:13.780307 8686 cluster_api.go:295] [ERROR] createSpaceService err: not enough PS
[GIN] 2019/11/29 - 19:24:13 | 586 | 5.004712717s | 127.0.0.1 | PUT /space/test_vector_db/_create
D1129 19:24:18.293195 8686 startup.go:108] [DEBUG] mem.Alloc:14567416 mem.TotalAlloc:28089928 mem.HeapAlloc:14567416 mem.HeapSys:63766528 routing :106
D1129 19:24:24.281897 8686 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!
D1129 19:24:28.293387 8686 startup.go:108] [DEBUG] mem.Alloc:11770096 mem.TotalAlloc:28271904 mem.HeapAlloc:11770096 mem.HeapSys:63766528 routing :106
D1129 19:24:30.076020 8686 schedule_job.go:136] [DEBUG] Start clean task
I1129 19:24:30.076214 8686 schedule_job.go:36] [INFO] Start Walking Partitions!
I1129 19:24:30.076226 8686 schedule_job.go:58] [INFO] Complete Walking Partitions!
I1129 19:24:30.076427 8686 schedule_job.go:63] [INFO] Start Walking Spaces!
I1129 19:24:30.076440 8686 schedule_job.go:76] [INFO] Complete Walking Spaces!
I1129 19:24:30.076638 8686 schedule_job.go:86] [INFO] Start Walking Servers!
I1129 19:24:30.076648 8686 schedule_job.go:100] [INFO] Complete Walking Servers!
D1129 19:24:38.293590 8686 startup.go:108] [DEBUG] mem.Alloc:12016000 mem.TotalAlloc:28517808 mem.HeapAlloc:12016000 mem.HeapSys:63766528 routing :106
D1129 19:24:48.293766 8686 startup.go:108] [DEBUG] mem.Alloc:12213984 mem.TotalAlloc:28715792 mem.HeapAlloc:12213984 mem.HeapSys:63766528 routing :106
I1129 19:24:48.355768 8686 schedule_job.go:104] [INFO] Receive keepalive, leaseId: 6509230568158846988, ttl:188
D1129 19:24:58.293949 8686 startup.go:108] [DEBUG] mem.Alloc:12379072 mem.TotalAlloc:28880880 mem.HeapAlloc:12379072 mem.HeapSys:63766528 routing :106
D1129 19:25:08.294122 8686 startup.go:108] [DEBUG] mem.Alloc:12545384 mem.TotalAlloc:29047192 mem.HeapAlloc:12545384 mem.HeapSys:63766528 routing :106
D1129 19:25:18.294299 8686 startup.go:108] [DEBUG] mem.Alloc:12740464 mem.TotalAlloc:29242272 mem.HeapAlloc:12740464 mem.HeapSys:63766528 routing :106
D1129 19:25:24.282022 8686 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!

**Comment by manlinting** [comment]
https://github.com/vearch/vearch/blob/master/docs/Quickstart.md 按这个来的

**Comment by ansjsun** [comment]
````
on 192.168.1.1 , 192.168.1.2 run master
./vearch -conf conf.toml master
on 192.168.1.3 , 192.168.1.4 run ps
./vearch -conf conf.toml ps
on 192.168.1.5 run router
./vearch -conf conf.toml router
````

这三个都启动了吗？ 这个样子看上去是 ps 没有启动。
你可以通过 ./vearch -conf conf.toml all 一次启动三个
。还有Quickstart.md 是带着插件的

**Comment by manlinting** [comment]
![image](https://user-images.githubusercontent.com/2246110/69938859-57d27f00-1519-11ea-9059-48c9cd0c1e12.png)
进程都在，建表命令是这个
curl -XPUT -H "content-type: application/json" -d'
{
	"name":"space1",
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' ${MASTER}/space/test_vector_db/_create


curl -XPOST -H "content-type:application/json" -d '{
	"name","test_space",
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' $MASTER/space/test_vector_db/_create




curl -XPUT -H "content-type: application/json" -d'
{
    "name": "space1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 700,
        "max_size": 10000,
        "nprobe": 10,
        "metric_type": 0,
        "ncentroids": 256,
        "nsubvector": 32
    },
    "properties": {
        "field1": {
            "type": "keyword"
        },
        "field2": {
            "type": "integer"
        },
        "field3": {
            "type": "float",
                "index": "true"
        },
        "field4": {
            "type": "string",
            "array": true,
            "index": "true"
        },
        "field5": {
            "type": "integer",
            "array": false,
            "index": "true"
        },
        "field6": {
            "type": "vector",
            "dimension": 128
        },
        "field7": {
            "type": "vector",
            "dimension": 256,
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 2000
            }
        }
    }
}

返回日志是
I1202 15:36:02.797985   19027 cluster_service.go:253] [INFO] create space, db: test_vector_db, spaceName: space1 ,space :[{"name":"space1","version":1,"db_id":1,"enabled":null,"partitions":null,"partition_num":1,"replica_num":1,"properties":{"field1":{"type":"keyword"},"field2":{"type":"integer"},"field3":{"type":"float","index":"true"},"field4":{"type":"string","array":true,"index":"true"},"field5":{"type":"integer","array":false,"index":"true"},"field6":{"type":"vector","dimension":128},"field7":{"type":"vector","dimension":256,"store_type":"Mmap","store_param":{"cache_size":2000}}},"engine":{"name":"gamma","index_size":7,"max_size":1000,"nprobe":10,"metric_type":0,"ncentroids":256,"nsubvector":32,"nbits_per_idx":-1}}]
I1202 15:36:02.799662   19027 rpc_client.go:46] [INFO] instance client by rpc 127.0.0.1:8081
D1202 15:36:05.508662   19248 startup.go:108] [DEBUG] mem.Alloc:7073912 mem.TotalAlloc:9407016 mem.HeapAlloc:7073912 mem.HeapSys:65470464 routing :28
I1202 15:36:07.801671   19377 master_cache.go:376] [INFO] remove space cache dbID:[1] space:[13] 
D1202 15:36:07.801993   19027 cluster_api.go:294] [DEBUG] create space, db: 
E1202 15:36:07.802052   19027 cluster_api.go:295] [ERROR] createSpaceService err: not enough PS
[GIN] 2019/12/02 - 15:36:07 | 586 |   5.00620492s |       127.0.0.1 | PUT      /space/test_vector_db/_create
D1202 15:36:11.051294   19027 startup.go:108] [DEBUG] mem.Alloc:11270000 mem.TotalAlloc:18537056 mem.HeapAlloc:11270000 mem.HeapSys:64651264 routing :66
D1202 15:36:11.484009   19377 startup.go:108] [DEBUG] mem.Alloc:8358544 mem.TotalAlloc:9813096 mem.HeapAlloc:8358544 mem.HeapSys:65437696 routing :32
D1202 15:36:15.509047   19248 startup.go:108] [DEBUG] mem.Alloc:7166744 mem.TotalAlloc:9499848 mem.HeapAlloc:7166744 mem.HeapSys:65437696 routing :28
D1202 15:36:15.523796   19248 schedule_job.go:75] [DEBUG] PartitionIds not change, do nothing!
D1202 15:36:21.051680   19027 startup.go:108] [DEBUG] mem.Alloc:11457944 mem.TotalAlloc:18725000 mem.HeapAlloc:11457944 mem.HeapSys:64618496 routing :66
D1202 15:36:21.484579   19377 startup.go:108] [DEBUG] mem.Alloc:8402160 mem.TotalAlloc:9903528 mem.HeapAlloc:8402160 mem.HeapSys:65404928 routing :32
I1202 15:36:21.570567   19248 schedule_job.go:104] [INFO] Receive keepalive, leaseId: 6509230631094597129, ttl:188
D1202 15:36:25.509571   19248 startup.go:108] [DEBUG] mem.Alloc:7263336 mem.TotalAlloc:9596440 mem.HeapAlloc:7263336 mem.HeapSys:65404928 routing :28
D1202 15:36:31.052090   19027 startup.go:108] [DEBUG] mem.Alloc:11618384 mem.TotalAlloc:18885440 mem.HeapAlloc:11618384 mem.HeapSys:64585728 routing :66
D1202 15:36:31.484971   19377 startup.go:108] [DEBUG] mem.Alloc:7129920 mem.TotalAlloc:10000800 mem.HeapAlloc:7129920 mem.HeapSys:65470464 routing :32
D1202 15:36:35.510041   19248 startup.go:108] [DEBUG] mem.Alloc:7356600 mem.TotalAlloc:9689704 mem.HeapAlloc:7356600 mem.HeapSys:65372160 routing :28

**Comment by ansjsun** [comment]
这个看样子是成功了吧
