### ISSUE TITLE
cmakelist也写得太乱了

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#494]
gamma 的cmakelist.txt  99行
```
link_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/third_party/faiss/lib
)
```

## 第一third_party下没有faiss只有faiss1.6.4
![1629109212(1)](https://user-images.githubusercontent.com/13146304/129549215-e3cc981c-02ac-4b52-b7bc-6ae9077562f4.jpg)
## 第二：faiss1.6.4下也没有lib路径
![1629109233(1)](https://user-images.githubusercontent.com/13146304/129549304-69d91607-95bb-4254-86af-f53aa4ce2ab5.jpg)

**Comment by wxingda** [comment]
在执行cmake的时候，会检测third_party/faiss/lib路径是否存在，如果不存在，则调用build.sh生成

**Comment by rrjia** [comment]
get，感谢，但是我的build.sh好像没有生效执行，当我手动执行时显示没有权限，Permission denied
在gamma的cmakelist.txt中13行看到了您说的
```
exec_program(
    "sh"
    ${CMAKE_CURRENT_SOURCE_DIR}/third_party
    ARGS "build.sh" ${BUILD_WITH_GPU})
```
但是没有看到对于third_party/faiss/lib是否存在的判断语句，请问这个判断在什么位置？

**Comment by wxingda** [comment]
build.sh里面判断如果third_party/faiss不存在，则自动安装faiss，你手动执行失败，可能是build.sh没有执行权限

**Comment by rrjia** [comment]
修改了各项权限后顺利编译成功，但是再查看依赖库时发现：
```
undefined symbol: ZSTD_getDecompressedSize	(./libgamma.so)
```
但是中文文档中只提到了
```
[RocksDB](https://github.com/facebook/rocksdb) == 6.2.2 （可选），你不需要手动安装，脚本自动安装。但是你需要手动安装rocksdb的依赖。请参考如下安装方法：https://github.com/facebook/rocksdb/blob/master/INSTALL.md
[zfp](https://github.com/LLNL/zfp) == v0.5.5 (可选)，你不需要手动安装，脚本自动安装。
```
请问ZSTD库是否也有要求，如果有要求，请问对应版本的要求是？

**Comment by wxingda** [comment]
zstd对版本没要求
