### ISSUE TITLE
"compress":{"rate": 16}指的是什么压缩？

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#498]
"compress":{"rate": 16}指的是什么压缩？目前用设置了和未设置的测试对比发现，二者差异不是很大，CPU内存没有什么差异，对比结果如下：
集群配置：PS节点16C32G*20，router节点4C8G*10
数据量：8亿1700万，128维
设置"compress":{"rate": 16}，25并发

并发量 | TopK | nprobe | PS CPU | router CPU | PS内存 | P50 | P90 | P99 | QPS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
25 | 10 | 32 | 55% | 10% | 11.4G | 27 | 42 | 61 | 413
25 | 50 | 32 | 60% | 35% | 11.4G | 37 | 50 | 74 | 404
25 | 100 | 32 | 60% | 40% | 11.4G | 48 | 80 | 120 | 343

未设置"compress":{"rate": 16}，25并发

并发量 | TopK | nprobe | PS CPU | router CPU | PS内存 | P50 | P90 | P99 | QPS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
25 | 10 | 32 | 55% | 10% | 11.4G | 42 | 60 | 86 | 373
25 | 50 | 32 | 55% | 35% | 11.4G | 49 | 71 | 104 | 347
25 | 100 | 32 | 50% | 50% | 11.4G | 60 | 90 | 130 | 297

设置"compress":{"rate": 16}，50并发

并发量 | TopK | nprobe | PS CPU | router CPU | PS内存 | P50 | P90 | P99 | QPS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
50 | 10 | 32 | 90% | 15% | 11.4G | 45 | 60 | 76 | 667
50 | 50 | 32 | 90% | 50% | 11.4G | 55 | 84 | 116 | 604
50 | 100 | 32 | 30% | 70% | 11.4G | 90 | 206 | 300 | 400

未设置"compress":{"rate": 16}，50并发

并发量 | TopK | nprobe | PS CPU | router CPU | PS内存 | P50 | P90 | P99 | QPS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
50 | 10 | 32 | 80% | 15% | 11.4G | 66 | 100 | 142 | 578
50 | 50 | 32 | 80% | 50% | 11.4G | 70 | 105 | 145 | 550
50 | 100 | 32 | 60% | 75% | 11.4G | 102 | 200 | 281 | 374

**Comment by gyd-a** [comment]
"compress":{"rate": 16}控制原始向量是否进行压缩，如果使用该参数，原始向量将压缩50%进行存储。通常用在数量较大，磁盘资源受限，搜索时不进行精排的场景。

**Comment by gyd-a** [comment]
主要收益可以减少磁盘占用。

**Comment by zcdb** [comment]
你建表的时候是指定存储方式为rocksdb吗？这种情况下内存是没有明显变化的，主要是磁盘存储的时候会压缩

**Comment by qingfengshiran** [comment]
> 你建表的时候是指定存储方式为rocksdb吗？这种情况下内存是没有明显变化的，主要是磁盘存储的时候会压缩

是的，使用的是rocksdb，那其实没有什么差异了，精度没有变化，感觉速度稍微有一点点的提升好像，不过也不明显

**Comment by qingfengshiran** [comment]
> 主要收益可以减少磁盘占用。

好的了解，不过我使用的是rocksdb，没有什么收益

**Comment by qingfengshiran** [comment]
> "compress":{"rate": 16}控制原始向量是否进行压缩，如果使用该参数，原始向量将压缩50%进行存储。通常用在数量较大，磁盘资源受限，搜索时不进行精排的场景。

那请问对检索速度会有影响吗？
