### ISSUE TITLE
只有三台服务器如何布置集群

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#502]
如果按照推荐上的配置

master
192.168.1.1
192.168.1.2
ps
192.168.1.3
192.168.1.4
router
192.168.1.5

起码一个master 一个router 一个ps，只有一个计算节点了，那三台机器和单机有什么区别？

**Comment by ljeagle** [comment]
master是管理表及ps等元数据信息的分布式配置管理集群，它用3台以上是为了保障高可用，类似zookeeper，这些master节点本身没有什么计算逻辑，只是为了高可用。单机没法做到工业级高可用。如果是只有3台机器，可以每台机器上部署一个master节点，组成一个高可用分布式配置管理集群，然后再复用这3台机器，再分别部署3个不同的ps节点，ps主要是计算和存储，重逻辑。router可以按需部署，router主要是网络io消耗大一点。
