### ISSUE TITLE
分布式测试服务，启动时报错

### ISSUE THREAD

**Issue by rrjia** [vearch/vearch#506]
./vearch: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: no version information available (required by libgamma.so.0.1)
2021/09/14 18:17:18 startup.go:65: [ERROR] start server by version:[3.2.7] commitID:[065d9307c262d8226cdc7067ac3b70fdd40991be]
2021/09/14 18:17:18 startup.go:74: [ERROR] The Config File Is: config.toml
2021-09-14 18:17:18.352636 I | embed: name = m2
2021-09-14 18:17:18.352659 I | embed: data dir = /data/rrjia/datas/
2021-09-14 18:17:18.352676 I | embed: member dir = /data/rrjia/datas/member
2021-09-14 18:17:18.352688 I | embed: heartbeat = 100ms
2021-09-14 18:17:18.352699 I | embed: election = 3000ms
2021-09-14 18:17:18.352709 I | embed: snapshot count = 100000
2021-09-14 18:17:18.352725 I | embed: advertise client URLs = http://172.31.161.77:2370
2021-09-14 18:17:18.352759 W | etcdserver: MaxRequestBytes 33554432 exceeds maximum recommended size 10485760

请问是不是哪里需要配置？

**Comment by gyd-a** [comment]
可以简单描述一下你的部署方式吗？

**Comment by rrjia** [comment]
有三台机器，同时都作为master和PS，再启动第一台机器机器作为master时就报这样的错误了


[global]
    name = "vearch"
    data = ["/data/rrjia/datas/"]
    log = "/data/rrjia/logs/"
    level = "info"
    signkey = "vearch"
    skip_auth = true

# if you are master, you'd better set all config for router、ps and router, ps use default config it so cool
[[masters]]
    name = "m1"
    address = "172.31.169.102"
    api_port = 8817
    etcd_port = 2378
    etcd_peer_port = 2390
    etcd_client_port = 2370
[[masters]]
    name = "m2"
    address = "172.31.169.101"
    api_port = 8817
    etcd_port = 2378
    etcd_peer_port = 2390
    etcd_client_port = 2370
[[masters]]
    name = "m2"
    address = "172.31.161.103"
    api_port = 8817
    etcd_port = 2378
    etcd_peer_port = 2390
    etcd_client_port = 2370
[router]
    port = 9001
    skip_auth = true
[ps]
    rpc_port = 8081
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 200 #ms
    raft_retain_logs = 10000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1

**Comment by rrjia** [comment]
当另一台服务器启动时报错如下

Illegal instruction (core dumped)

**Comment by zcdb** [comment]
查看下你的服务器是否支持avx2

**Comment by rrjia** [comment]
<img width="786" alt="1631677106(1)" src="https://user-images.githubusercontent.com/13146304/133366765-5cb2d1b1-7c6c-47c4-8792-eff15eec587f.png">
支持的

**Comment by rrjia** [comment]
请问是否能够定位原因？或者建议排查方案

**Comment by kuailelijuan** [comment]
您好，请问下，是master启动不成功吗？master启动的命令可以发一下吗？

**Comment by rrjia** [comment]
> 您好，请问下，是master启动不成功吗？master启动的命令可以发一下吗？

是的，使用的官方教程中的启动master命令启动的

./vearch -conf config.toml master

**Comment by kuailelijuan** [comment]
是在docker 容器里面启动的吗？还是在物理机下启动的？/data/rrjia/datas/ 这个目录下是不是有旧数据，清空一下，再试试看。

**Comment by rrjia** [comment]
datas路径下没有数据，清空重启也是一样，是在物理机下启动的，物理机信息如下：
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by rrjia** [comment]
发现错误了，原来是master中有两个
[[masters]]
name = "m2"
但是有另两台服务器 启动时报错为：
Illegal instruction (core dumped)

也是物理机：系统信息如下
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by zcdb** [comment]
可以看一下另外两台机器支持指令集的情况吗？

**Comment by rrjia** [comment]
processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping	: 1
microcode	: 0xb000038
cpu MHz		: 1203.545
cache size	: 20480 KB
physical id	: 0
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 15
initial apicid	: 15
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 4199.69
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

**Comment by rrjia** [comment]
我使用了openBlas加速，有没有可能是这台服务器不支持

**Comment by zcdb** [comment]
openblas有可能不支持，另外rocksdb可能也有不支持的情况，可以参考这个 https://github.com/facebook/rocksdb/issues/7398

**Comment by rrjia** [comment]
感谢支持，的确是因为rocksdb编译中有不支持的指令集的情况造成的。
