### ISSUE TITLE
查询返回的score异常

### ISSUE THREAD

**Issue by zjsen668** [vearch/vearch#51]
我创建的space使用的metric_type为0，我理解向量搜索返回的score值应该是个小于1的数，但实际返回了类似19068.90234375这样的数值，请教是我理解的不对，还是操作有问题？

- 创建space的命令:

`curl -XPUT -H "content-type: application/json" -d'
{
    "name": "vgg_space",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 2000000,
        "nprobe": 30,
        "metric_type": 0,
        "ncentroids": 256,
        "nsubvector": 64
    },
    "properties": {
        "imgpath": {
            "type": "keyword",
            "index": "true"
        },
        "feature": {
            "type": "vector",
            "dimension": 128,
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2000
            }
        }
    }
}
' http://127.0.0.1:8817/space/afdb/_create`

- 向量搜索返回结果:
`{
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "failed": 0,
        "successful": 1
    },
    "hits": {
        "total": 3,
        "max_score": 19068.90234375,
        "hits": [
            {
                "_index": "afdb",
                "_type": "vgg_space",
                "_id": "AW7FmgiAoEgcpgFzKImk",
                "_score": 19068.90234375,
                "_extra": {
                    "vector_result": [
                        {
                            "field": "feature",
                            "source": "",
                            "score": 19068.90234375
                        }
                    ]
                },
                "_version": 1,
                "_source": {
                    "imgpath": "F:/dataset/antifraud/segmented/5FJ-2-3.jpg"
                }
            },`

**Comment by ansjsun** [comment]
0 是内积 ，内积需要做归一化。你的 不管是插入还是查询的向量都要做。

**Comment by zjsen668** [comment]
> 0 是内积 ，内积需要做归一化。你的 不管是插入还是查询的向量都要做。

明白了，非常感谢！
