### ISSUE TITLE
PS k8s 部署使用挂载盘，重启后索引数据未重新加载

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#514]
PS 节点是通过K8s启动，PVC挂载了一个云盘，之前试过少量数据重启后能够重新加载回索引，但这次是单节点3600万数据挂掉之后重启没有恢复数据，partition数量减1；
IVFPQ
v3.2.7最新
建表参数
<img width="390" alt="image" src="https://user-images.githubusercontent.com/42227773/134772941-99e45c60-70da-4be0-96fa-83893af911fb.png">

master节点log
<img width="1915" alt="image" src="https://user-images.githubusercontent.com/42227773/134773087-5c87af99-6196-44a2-95fb-7bd99e54dc62.png">

重启PS.INFO.log
<img width="961" alt="image" src="https://user-images.githubusercontent.com/42227773/134772987-c36fb28b-e32e-4e52-a0c1-59999bf54686.png">

重启gamma log：
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/42227773/134773104-40e8025b-e9e0-4ba8-aba8-f0b74e9d9773.png">

监控
<img width="789" alt="image" src="https://user-images.githubusercontent.com/42227773/134773120-a12c4a42-cdcc-4900-84f8-b6764c4918c3.png">

重启PS节点的datas
<img width="847" alt="image" src="https://user-images.githubusercontent.com/42227773/134773154-05162199-b39e-4240-a73e-ab4b34534b5f.png">

正常未重启PS节点的datas
<img width="885" alt="image" src="https://user-images.githubusercontent.com/42227773/134773173-abfa5fdc-9e7c-4f57-9893-d18396f2f450.png">

通过datas比较，我认为挂载盘是没有问题的。

执行flash出现如下错误
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/42227773/134773234-9ba87c34-25f8-4a21-9aad-42f0230528cf.png">

**Comment by ljeagle** [comment]
用的vearch哪个版本呢？

**Comment by qingfengshiran** [comment]
> 用的vearch哪个版本呢？

v3.2.7最新

**Comment by gyd-a** [comment]
可以提供一下health接口返回的参数吗？

**Comment by wxingda** [comment]
执行下dmesg -T或查看/var/log/messages，看下进程挂掉的原因

**Comment by gyd-a** [comment]
请问：1、重启前后ps ip会有变化吗？2、重启过程有搜索吗？搜索有使用数值过滤吗？

**Comment by kuailelijuan** [comment]
发一下您的config.toml 配置文件看下，谢谢。

**Comment by qingfengshiran** [comment]
> 执行下dmesg -T或查看/var/log/messages，看下进程挂掉的原因

已经重启了，而且是k8s部署，logs日志没有做映射到持久存储盘

**Comment by qingfengshiran** [comment]
> 请问：1、重启前后ps ip会有变化吗？2、重启过程有搜索吗？搜索有使用数值过滤吗？

1 重启前后ps ip不会有变化
2 重启过程有搜索，且搜索有使用数值过滤

**Comment by qingfengshiran** [comment]
> 发一下您的config.toml 配置文件看下，谢谢。
[config2distributed.txt](https://github.com/vearch/vearch/files/7230775/config2distributed.txt)

**Comment by gyd-a** [comment]
重启时标量索引会重建，标量索引存在线程安全的bug，应该是这个问题导致重启失败的，我们最近会提修复的代码。

**Comment by qingfengshiran** [comment]
> 重启时标量索引会重建，标量索引存在线程安全的bug，应该是这个问题导致重启失败的，我们最近会提修复的代码。

有什么办法先让我们这个故障的ps节点数据再加载到集群中吗？能新启动一个节点吗？

**Comment by yu-hailong** [comment]
> > 请问：1、重启前后ps ip会有变化吗？2、重启过程有搜索吗？搜索有使用数值过滤吗？
> 
> 1 重启前后ps ip不会有变化
> 2 重启过程有搜索，且搜索有使用数值过滤

请教下：
K8S 如何做到重启pod， IP没有变化

**Comment by qingfengshiran** [comment]
> > > 请问：1、重启前后ps ip会有变化吗？2、重启过程有搜索吗？搜索有使用数值过滤吗？
> > 
> > 
> > 1 重启前后ps ip不会有变化
> > 2 重启过程有搜索，且搜索有使用数值过滤
> 
> 请教下：
> K8S 如何做到重启pod， IP没有变化

具体的我也不清楚，公司专门有做集群部署这块的，你可以搜一下k8s 的statefulset

**Comment by yu-hailong** [comment]
> > > > 请问：1、重启前后ps ip会有变化吗？2、重启过程有搜索吗？搜索有使用数值过滤吗？
> > > 
> > > 
> > > 1 重启前后ps ip不会有变化
> > > 2 重启过程有搜索，且搜索有使用数值过滤
> > 
> > 
> > 请教下：
> > K8S 如何做到重启pod， IP没有变化
> 
> 具体的我也不清楚，公司专门有做集群部署这块的，你可以搜一下k8s 的statefulset

我们就是采用这种方式， statefulset 可以保证 hostname 即：网络id不发生变化，但是ip会变化的
