### ISSUE TITLE
使用标量索引的情况下，health或者删除space的时候，很慢，而且master节点会概率性挂掉

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#521]
如题，在表中单PS数据量超过2-3千万之后，会出现标题中的问题。
建表参数：
def ivfpq_hnsw_table_property():
    property = {
        "name": project_name,
        "partition_num": 20,
        "replica_num": 1,
        "engine": {
            "name": "gamma",
            "index_size": 2600000,
            "id_type": "String",
            "retrieval_type": "IVFPQ",
            "retrieval_param": {
                "metric_type": "L2",
                "ncentroids": 65536,
                "nsubvector": 64,
                "hnsw": {
                    "nlinks": 32,
                    "efConstruction": 200,
                    "efSearch": 64
                },
                "opq": {
                    "nsubvector": 64
                }
            }
        },
        "properties": {
            "url": {
                "type": "keyword",
            },
            "frame_idx": {
                "type": "integer",
            },
            "cat": {
                "type": "keyword",
                "index": True
            },
            "cat_detail": {
                "type": "keyword",
                "index": True
            },
            "note_id": {
                "type": "keyword",
            },
            "all_idx": {
                "type": "keyword",
            },
            "all_useful_idx": {
                "type": "keyword",
            },
            "all_used_idx": {
                "type": "keyword",
            },
            "create_time": {
                "type": "double",
                "index": True
            },
            "feat": {
                "type": "vector",
                "dimension": 128,
                "store_type": "RocksDB",
                "store_param": {
                    "cache_size": 2048
                }
            }
        }
    }
    return property
并且监控会出现状态断点的情况
<img width="915" alt="image" src="https://user-images.githubusercontent.com/42227773/136755161-b1a7a0a3-4143-43da-adf0-cf895282f543.png">
health接口必现：
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/42227773/136755739-e94d5646-b493-439b-acf3-3a943d400588.png">

**Comment by wxingda** [comment]
ps节点正常吗

**Comment by kuailelijuan** [comment]
提供一下相关的详细日志，master、ps，谢谢。
