### ISSUE TITLE
调用删除接口删除历史数据，实际内存空间并没有下降

### ISSUE THREAD

**Issue by paul-gpt** [vearch/vearch#522]
调用删除接口删除历史数据，实际内存空间并没有下降；
如果新增数据不断增长的情况下，怎么保障存足够的磁盘和内存空间，或者说有没有方法使被删除的数据不加载到内存？

**Comment by paul-rpc** [comment]
线上集群问题，麻烦及时回复一下？ 谢谢

**Comment by zcdb** [comment]
删除接口删除历史数据，会删除索引数据，但是其它数据如向量等是标记删除。你们的数据是包括向量和标量吗？3.2.7支持cache功能，可以设置标量数据占用的cache 大小来控制标量数据的内存占用，而向量数据则可以使用mmap或者rocksdb的方式来存储，不要将向量数据都放在内存中
