### ISSUE TITLE
实时插入查询PS节点挂掉

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#527]
PS节点：16C32G*40， 单节点3600万数据
软件版本：vearch3.2.7，gamma：a64cacf96d769b28be88879a156ad5b508a58028,自己编译
1、建表参数
    property = {
        "name": project_name,
        "partition_num": 40,
        "replica_num": 1,
        "engine": {
            "name": "gamma",
            "index_size": 2600000,
            "id_type": "String",
            "retrieval_type": "IVFPQ",
            "retrieval_param": {
                "metric_type": "L2",
                "ncentroids": 65536,
                "nsubvector": 64,
                "hnsw": {
                    "nlinks": 32,
                    "efConstruction": 200,
                    "efSearch": 64
                },
                "opq": {
                    "nsubvector": 64
                }
            }
        },
        "properties": {
            "url": {
                "type": "keyword",
            },
            "frame_idx": {
                "type": "integer",
            },
            "cat": {
                "type": "keyword",
                "index": True
            },
            "cat_detail": {
                "type": "keyword",
                "index": True
            },
            "note_id": {
                "type": "keyword",
            },
            "all_idx": {
                "type": "keyword",
            },
            "all_useful_idx": {
                "type": "keyword",
            },
            "all_used_idx": {
                "type": "keyword",
            },
            "create_time": {
                "type": "double",
                "index": True
            },
            "feat": {
                "type": "vector",
                "dimension": 128,
                "store_type": "RocksDB",
                "store_param": {
                    "cache_size": 2048
                }
            }
        }
    }
2、数据总量大约14.5亿；
3、实时插入的速度是10QPS，batch insert batch max size = 32；
4、实时查询的速度是10QPS，batch insert batch max size = 32；
5、容器的并发线程数量设置为1000；
6、出现ps节点多次频繁挂掉的情况，此时CPU使用率低于30%,以14点22分为例，上传了log，masterlog时间+8等于PS节点log时间
PS log
[ps21_logs.zip](https://github.com/vearch/vearch/files/7363036/ps21_logs.zip)
Master log
[master_logs.zip](https://github.com/vearch/vearch/files/7363049/master_logs.zip)

7、cpu使用率
<img width="911" alt="image" src="https://user-images.githubusercontent.com/42227773/137696979-5ad14ee4-1df7-482d-8352-3a98401b1619.png">

8、问题一：重启原因？会和batch的使用有关系吗？之前遇到过并发线程数量不够，导致重启，后增加至1000，再无线程数量不够的警告。

9、问题二：重启之后PS节点重启比较慢，看log主要耗费在如下的事情上。
<img width="964" alt="image" src="https://user-images.githubusercontent.com/42227773/137697352-a0780bae-f550-4b9c-ae1f-5c3cbc58dcad.png">
即使不插入的情况，重启节点也会遇到这些log，如何减少时间。

**Comment by wxingda** [comment]
运行dmesg，看下ps崩溃的原因

**Comment by wxingda** [comment]
> > > 另外，我使用的pod是16C，按照系统计算的参数是concurrent_threshold [252]，但是252经常出现线程不够用的警告，所以我手动修改成了1008，这个是否有影响呢？ <img alt="image" width="1167" src="https://user-images.githubusercontent.com/42227773/137706458-42fe3c9b-7f54-41af-8d34-399ca194519f.png"> @wxingda
> > 
> > 
> > 可能有影响，不过最好能够看下dmesg或者/var/log/messages，看下崩溃的原因；如果看不到这两个地方的信息，那就在搜索的时候先不用标量过滤，看下是不是标量索引的问题
> 
> dmesg有一个是这个，您看有用嘛？
> 
> [dmesg.log](https://github.com/vearch/vearch/files/7363663/dmesg.log)

从dmesg.log里没有找到相关日志，改变concurrent_threshold之前有崩溃的问题吗？

**Comment by qingfengshiran** [comment]
> > > > 另外，我使用的pod是16C，按照系统计算的参数是concurrent_threshold [252]，但是252经常出现线程不够用的警告，所以我手动修改成了1008，这个是否有影响呢？ <img alt="image" width="1167" src="https://user-images.githubusercontent.com/42227773/137706458-42fe3c9b-7f54-41af-8d34-399ca194519f.png"> @wxingda
> > > 
> > > 
> > > 可能有影响，不过最好能够看下dmesg或者/var/log/messages，看下崩溃的原因；如果看不到这两个地方的信息，那就在搜索的时候先不用标量过滤，看下是不是标量索引的问题
> > 
> > 
> > dmesg有一个是这个，您看有用嘛？
> > [dmesg.log](https://github.com/vearch/vearch/files/7363663/dmesg.log)
> 
> 从dmesg.log里没有找到相关日志，改变concurrent_threshold之前有崩溃的问题吗？

有，提示信息不同，提示线程数量超过252了，这个也比较奇怪，查询我试过，如果超过252则，会返回结果为空，并不会挂掉，但是增加了batch insert一起，就莫名的挂掉了

**Comment by Maslino** [comment]
可以通过环境变量 OMP_NUM_THREADS 来设置OpenMP线程数，比如你这个情况pod的cpu资源限制为8，那么可以设置
OMP_NUM_THREADS=8

**Comment by qingfengshiran** [comment]
> 可以通过环境变量 OMP_NUM_THREADS 来设置OpenMP线程数，比如你这个情况pod的cpu资源限制为8，那么可以设置 OMP_NUM_THREADS=8
> […](#)

**Comment by qingfengshiran** [comment]
> 可以通过环境变量 OMP_NUM_THREADS 来设置OpenMP线程数，比如你这个情况pod的cpu资源限制为8，那么可以设置 OMP_NUM_THREADS=8
> […](#)

嗯嗯 好的，不过总是感觉下面这三个参数都是65536是不是也有点小呢？但是好像还改不了，dockerfile增加提示readonly filesystem。。。
/proc/sys/vm/max_map_count
/proc/sys/kernel/pid_max
/proc/sys/kernel/threads-max

<img width="356" alt="image" src="https://user-images.githubusercontent.com/42227773/137858741-2d54bd81-a469-4bb1-b3a6-50ad97a89fb0.png">
<img width="713" alt="wecom-temp-23e6806e492321cdff70d0b343aa2152" src="https://user-images.githubusercontent.com/42227773/137858769-e2f5c116-9187-4041-8580-ec6e770ea8a7.png">

**Comment by wxingda** [comment]
修改下dockerfile的启动方式吧，改成启动一个脚本，然后把修改三个参数的语句放到脚本里，这样应该就能够修改最大线程数了

**Comment by wxingda** [comment]
docker run的时候加上--privileged参数试试呢

**Comment by qingfengshiran** [comment]
> docker run的时候加上--privileged参数试试呢

哦哦 好的，我试试

**Comment by qingfengshiran** [comment]
另外还有一个问题，重启的时候，会比较慢，很多如下的log，请问这个是在干什么？因为使用方式是实时插入查询的
<img width="916" alt="image" src="https://user-images.githubusercontent.com/42227773/137874184-45f9cb31-48a7-4da3-8b36-24440d998fba.png">

是否和如下的参数有关系呢？
<img width="328" alt="image" src="https://user-images.githubusercontent.com/42227773/137874456-cc23b35f-5209-4073-964b-c397a72c93b3.png">

**Comment by wxingda** [comment]
> 另外还有一个问题，重启的时候，会比较慢，很多如下的log，请问这个是在干什么？因为使用方式是实时插入查询的 <img alt="image" width="916" src="https://user-images.githubusercontent.com/42227773/137874184-45f9cb31-48a7-4da3-8b36-24440d998fba.png">
> 
> 是否和如下的参数有关系呢？ <img alt="image" width="328" src="https://user-images.githubusercontent.com/42227773/137874456-cc23b35f-5209-4073-964b-c397a72c93b3.png">

这是在更新索引，跟下面的参数没关系，你插入的数据是不是包含更新的数据？

**Comment by qingfengshiran** [comment]
> 使用flush来dump，`curl -XPOST {{ROUTER}}/test_vector_db/vector_space/_flush`，异常重启是不能dump的，重启后只能从最后一次dump的点开始重新建索引
哦哦 明白，那下面这个参数设定的是什么呢？从字面意思就是flush呢
![](https://user-images.githubusercontent.com/42227773/137874456-cc23b35f-5209-4073-964b-c397a72c93b3.png)
而且我发现所有的重启，update最后的total都不超过20万好像
gamma_index_ivfpq.cc:611 update index success! size=35, total=196119

**Comment by chenrulongmaster** [comment]
@qingfengshiran 能不能请教下k8s怎么部署的
