### ISSUE TITLE
go compiler 的时候发现invalid operation错误

### ISSUE THREAD

**Issue by LynnaPan** [vearch/vearch#53]
hi, 我在尝试编译的时候发现如下错误，请问如何fix哈？

![image](https://user-images.githubusercontent.com/14161717/70020063-7b9fce80-15c6-11ea-9d71-56f5d8110e37.png)

[root@localhost vearch]# go build -o vearch
  github.com/vearch/vearch/master/store
/root/go/pkg/mod/github.com/vearch/vearch@v0.0.0-20191129124852-683a43977ae6/master/store/distlock.go:164:15: invalid operation: ev.Type == "go.etcd.io/etcd/mvcc/mvccpb".DELETE (mismatched types "github.com/coreos/etcd/mvcc/mvccpb".Event_EventType and "go.etcd.io/etcd/mvcc/mvccpb".Event_EventType)
/root/go/pkg/mod/github.com/vearch/vearch@v0.0.0-20191129124852-683a43977ae6/master/store/etcdstore.go:201:39: cannot use store.cli (type *"go.etcd.io/etcd/clientv3".Client) as type *"github.com/coreos/etcd/clientv3".Client in argument to concurrency.NewSTM

  github.com/vearch/vearch/config
/root/go/pkg/mod/github.com/vearch/vearch@v0.0.0-20191129124852-683a43977ae6/config/config.go:222:5: cfg.PreVote undefined (type *embed.Config has no field or method PreVote)

**Comment by ansjsun** [comment]
一般这种情况 不是gopath 就是go版本 用vendor里面的 不要用自己的gopath





在2019年12月03日 12:12，Pan Lina 写道：

hi, 我在尝试编译的时候发现如下错误，请问如何fix哈？

[root@localhost vearch]# go build -o vearch

github.com/vearch/vearch/master/store

/root/go/pkg/mod/github.com/vearch/vearch@v0.0.0-20191129124852-683a43977ae6/master/store/distlock.go:164:15: invalid operation: ev.Type == "go.etcd.io/etcd/mvcc/mvccpb".DELETE (mismatched types "github.com/coreos/etcd/mvcc/mvccpb".Event_EventType and "go.etcd.io/etcd/mvcc/mvccpb".Event_EventType)
/root/go/pkg/mod/github.com/vearch/vearch@v0.0.0-20191129124852-683a43977ae6/master/store/etcdstore.go:201:39: cannot use store.cli (type *"go.etcd.io/etcd/clientv3".Client) as type *"github.com/coreos/etcd/clientv3".Client in argument to concurrency.NewSTM

github.com/vearch/vearch/config

/root/go/pkg/mod/github.com/vearch/vearch@v0.0.0-20191129124852-683a43977ae6/config/config.go:222:5: cfg.PreVote undefined (type *embed.Config has no field or method PreVote)

**Comment by LynnaPan** [comment]
感谢回复。又出现了新的问题，我都是按照推荐的版本按照的呀~
[root@localhost vearch]# go build -a --tags=vector -o  vearch
# github.com/vearch/vearch/ps/engine/gammacb
ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::string const&, rocksdb::DB**)'
ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Status::ToString() const'
ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
collect2: error: ld returned 1 exit status

**Comment by qiutianme** [comment]
> 感谢回复。又出现了新的问题，我都是按照推荐的版本安装的呀~
> [root@localhost vearch]# go build -a --tags=vector -o vearch github.com/vearch/vearch/ps/engine/gammacb
> ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::string const&, rocksdb::DB**)' ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `rocksdb::Status::ToString() const'
> ps/engine/gammacb/lib/lib/libgamma.so: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
> collect2: error: ld returned 1 exit status
> 
> ![image](https://user-images.githubusercontent.com/14161717/70028071-9e3de180-15de-11ea-93c1-f168b4fb027e.png)

@LynnaPan  这个错误应该是链接的时候没有找到rocksdb和faiss的so，请按照部署文档里面的提示设置"export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$vearch/ps/engine/gammacb/lib/lib:$FAISS_HOME/lib:$ROCKSDB_HOME"

如果已经export了LD_LIBRARY_PATH变量，那么请检查LD_LIBRARY_PATH变量的路径中能找到rocksdb和faiss的so

**Comment by LynnaPan** [comment]
我也是怀疑路径不对，但都检查了一圈都有的，如下：
![image](https://user-images.githubusercontent.com/14161717/70113224-5fb62e80-1693-11ea-8e4a-c0d7579bce47.png)

**Comment by LynnaPan** [comment]
hi, 我换了一个环境就ok了，可以close了
