### ISSUE TITLE
搜索结果总是空

### ISSUE THREAD

**Issue by oyange** [vearch/vearch#532]
自己创建space插入查询结果为空
插入查询的数据和https://github.com/vearch/vearch/issues/359#issue-812791564一致
使用pytest跑单元测试结果也为空
![image](https://user-images.githubusercontent.com/23448269/138245933-411a87f2-93e5-4ad1-ab04-d5f8a91ee4ad.png)

**Comment by zcdb** [comment]
搜索语句有问题，才会报 req_num should not less than 0，把你的搜索语句也贴一下吧

**Comment by oyange** [comment]
{
    "query": {
        "sum": [{
            "field": "feature1",
            "feature": [0.1, 0.2],
            "min_score": 0.5
        }],
    }
    "online_log_level": "debug", 
    "quick": false, 
    "vector_value": true, 
    "size": 5
}
