### ISSUE TITLE
Can I use vearch for search data based on disk ?

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#54]
Dear team 

I want to build system  data based on disk  (1T-scale datasets), I check your config vearch system , it has  config when create partition:

> max_size : max documents for each partition  
> index_size : default 100000, if index_size == 0 it will not auto indexed, if insert document num >= index_size , it will auto indexed

_max_size_ depends on the amount of memory on the server partition for to be initialized
_index_size = 0_ it will not auto indexed , Does it don't use RAM server ?

How can I config for search data based on disk?

**Comment by qiutianme** [comment]
@phamthanhtri  Yes，you can. In release v0.2, Vearch supports storing raw vector on disk, and there are two types: Mmap and RocksDB. Please refer the api doc: https://vearch.readthedocs.io/en/latest/use_op/op_space.html#create-space

For example, the following means that vearch will store field7's  raw vectors to disk file, then map vectors to memory address through mmap system call. There is a buffer queue to cache raw vectors before they are flushed to disk file, the cache size is 2000M Bytes(about 2G).  "cache_size" must be set for your case, if not cache_size=max_size * dimension * sizeof(float)
```
"field7": {
            "type": "vector",
            "dimension": 256,
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 2000
            }
        }
```

**Comment by phamthanhtri** [comment]
Thanks @qiutianme  

But when create space, I must define  "max_size"  for gamma engine  faiss. It depends on the amount of memory on the server . I could not extend the max_size limit to the system according disk .Example  I can't define max_size = 1 billion vector for used on disk  ?

**Comment by qiutianme** [comment]
@phamthanhtri  In release v0.2, the "max_size" doesn't depends on the amount of memory on the server any more, you can define max_size = 1 billion. But the "cache_size" depends on the amount of memory.

**Comment by phamthanhtri** [comment]
@qiutianme  
 I use v0.2  to create space with config : 
{
                "dynamic_schema": "strict",
                "partition_num": 1, #so luong part set vao tuong ung cho PS
                "replica_num": 1,
                "name": self.space_name,
                "engine": {"name": "gamma", "metric_type": 0,"max_size":1000000000,"index_size":7000},
                "properties": {}
 }

{"db": True,
            "method": 1,
            "columns": {
                "imageurl": {
                    "type": "keyword"
                },
                "uid": {
                    "type": "integer"
                },
                "label": {
                    "type": "integer"
                }
            },
            "feature": {
                "type": "vector",
                "filed": "imageurl",
                "model_id": "vgg16",
                "dimension": 512,
                "store_type": "RocksDB",
                "store_param": {
                "cache_size": 2000
                 }
            }
            }

With max_size = 1 billion , it crash vearch and show error log (attachment)

[error_vearch.txt](https://github.com/vearch/vearch/files/3949834/error_vearch.txt)

**Comment by qiutianme** [comment]
@phamthanhtri When the max size reaches 1 billion, the profile field will also occupy a large amount of memory. This is indeed a problem, and we will evaluate whether to support this scenario later. 

Our current main goal is to solve the problem of fast search and recall, so we have not considered the situation of storing such a large amount of data on a single machine for the time being. 

If the amount of data is too large, we recommend that you use our distributed storage solution, for example, each machine stores 100 million, and a total of 10 machines store 1 billion.

**Comment by phamthanhtri** [comment]
I used vearch for real time search and it's very good . So I want to use in another case . I have more big data  and  my server with big storage but don't  have much memory. 
I want to look up the results and don't care about the request execution time (example for stats)
.Thanks for your support  and hopefully in the future it will be added into vearch  :+1:

**Comment by cocodee** [comment]
> @phamthanhtri When the max size reaches 1 billion, the profile field will also occupy a large amount of memory. This is indeed a problem, and we will evaluate whether to support this scenario later.
> 
> Our current main goal is to solve the problem of fast search and recall, so we have not considered the situation of storing such a large amount of data on a single machine for the time being.
> 
> If the amount of data is too large, we recommend that you use our distributed storage solution, for example, each machine stores 100 million, and a total of 10 machines store 1 billion.
What do you mean by "profile field"?How could I estimate lowest memory usage when Rocksdb is used?For example, a cluster with only one ps server is set up.And if 100 million vector,each vector 512 long are inserted.What is the memory requirement for the ps server?
