### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by realdalabengba** [vearch/vearch#544]
你好，vearch使用过程中，发现存在缓慢的内存泄漏。服务运行几个星期，重启前后内存差达20G。建表语句如下：

`{
"name": "piv_vec",
"partition_num": 100,
"replica_num": 3,
"engine": {
"name": "gamma",
"index_size": 1228800,
"retrieval_type": "IVFPQ",
"retrieval_param": {
"metric_type": "L2",
"ncentroids": 8192,
"nsubvector": 128
}
},
"properties": {
"pic_vector": {
"type": "vector",
"dimension": 512,
"store_type": "RocksDB",
"store_param": {
"cache_size": 1024,
"compress": {
"rate": 16
}
}
}
}
}`

猜测与写入有关，麻烦帮忙看看，谢谢！

**Comment by gyd-a** [comment]
可以做下面几个对比测试：1、使用rockdb存储，搜索时不精排。然后做重启实验。2、使用rockdb存储，搜索时精排。然后做重启实验。3、使用Mmap存储，搜索时不精排。然后做重启实验。4、使用Mmap存储，搜索时精排。然后做重启实验。看一下这几种情况重启前后的内存占用差距。
