### ISSUE TITLE
部署方式引入的耗时问题

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#545]
我们的PS是使用k8s部署的，开始时使用和其他服务混部的方式，一台机器上只会有1-2个PS的pod，但是因为ps不是高可用的方式部署的，混部集群会定期清理机器，导致ps节点重启，在一段时间内不能服务，因此采用了机器独享的方式部署ps节点，即单一机器部署4个ps pod充分利用CPU和内存资源，但是这样部署后，检索耗时增加了5倍左右。

机器：腾讯云SA2
混部SA2: 延迟150-400ms
独占SA2: 延迟1000-1600ms
二种部署方式CPU利用率都在20%左右。

请问这个大约会是什么原因呢？
另外，vearch使用的是faiss，那么支持的是avx512指令集吗？我的部署集群是AMD的，用的是什么加速呢？

**Comment by zcdb** [comment]
> > 部署方式如何设置的？几个partition几个副本？默认是avx256加速，faiss的avx512应该需要另外编译支持，而且amd是比较新的架构才支持avx512指令集吧
> 
> 部署方式是40个partition，单副本，RockDB方式。 我们用的机器是支持avx256的，而且确认多个pod部署在同一台机器上，频繁使用avx会导致降频，应该就是这个影响的。 请问一下你们对集群部署有什么建议吗？

我们集群部署的话，k8s会尽量保障同一应用的pod在不同的物理机上。另外partition计算的时候默认会使用所有核，不清楚你们cpu资源隔离是怎么做，部署在同一物理机上partition之间应该会竞争cpu.
另外avx512的版本，目前还在内部测试中。

**Comment by qingfengshiran** [comment]
> > > 部署方式如何设置的？几个partition几个副本？默认是avx256加速，faiss的avx512应该需要另外编译支持，而且amd是比较新的架构才支持avx512指令集吧
> > 
> > 
> > 部署方式是40个partition，单副本，RockDB方式。 我们用的机器是支持avx256的，而且确认多个pod部署在同一台机器上，频繁使用avx会导致降频，应该就是这个影响的。 请问一下你们对集群部署有什么建议吗？
> 
> 我们集群部署的话，k8s会尽量保障同一应用的pod在不同的物理机上。另外partition计算的时候默认会使用所有核，不清楚你们cpu资源隔离是怎么做，部署在同一物理机上partition之间应该会竞争cpu. 另外avx512的版本，目前还在内部测试中。

我们是独占部署的，不过我将partition的机器设置了OMP_NUM_THREADS=15，我们一种是64 核的机器，部署4个15核，一种是CPU绑定核的虚机，直接16核的虚机，部署一个pod。
