### ISSUE TITLE
Vearch+不同版本的gamma耗时不同问题

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#550]
Vearch3.2.7+ gamma commit id 08e2745,这个版本gamma存在标量重启失败的问题，因此更换了gamma版本到a64cacf版本，但是发现batch耗时好像增加了很多，新版本的CPU使用率一直比较低；
机器配置，单节点16C32G内存。
数据量：3800万。
建表参数配置：
![](https://user-images.githubusercontent.com/42227773/134772941-99e45c60-70da-4be0-96fa-83893af911fb.png)

Vearch3.2.7+ gamma 08e2745查询QPS：
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/42227773/139635517-cd134ffd-c9ad-49bb-a23a-00837d701409.png">
Vearch3.2.7+ gamma 08e2745 CPU内存使用：
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/42227773/139635591-73b1430b-0eeb-4aac-aae1-6bb61e9a74a9.png">

Vearch3.2.7+ gamma a64cacf查询QPS：
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/42227773/139635695-89702191-db9e-4b7b-bc14-0731e4956065.png">
Vearch3.2.7+ gamma a64cacfCPU内存使用：
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/42227773/139635754-2d7f6cd7-0dd7-4876-b688-d9d292aa1c44.png">

**Comment by gyd-a** [comment]
方便统计一下各gamma日志的qps吗？

**Comment by qingfengshiran** [comment]
> 方便统计一下各gamma日志的tp99吗？

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/42227773/139649498-8c73b1a3-17f5-4c92-84c9-a7a87fb25022.png">
请问你说的是这个吗？
另外，router和master与gamma有关系吗？需要更新吗？

**Comment by qingfengshiran** [comment]
> 方便统计一下各gamma日志的tp99吗？

这个统计，你们有什么现成的脚本不？

**Comment by gyd-a** [comment]
你可以写一个类似这个样的awk统计，grep 'gamma_engine.cc:451' gamma.log | tail -n 100000 | awk -F '[[,]' '{print $1,$9}'|awk -F ']ms' '{print $1}'|awk '{print $2 "-" $3, $4}' | awk -F 'ms' '{print $1}'|awk '{split($1, a, "[-|:]");t=sprintf("%s %s %s %s %s %s", a[1],a[2],a[3],a[4],a[5],a[6]); ts=mktime(t);print ts, $2}'| awk 'BEGIN{start=0;end=0;c=0;total=0}{if(NR==1){start=$1}end=$1;c=c+1;a[c]=$2;total=total+$2;}END{len=asort(a,tA);i99=int(c*0.99);i90=int(c*0.9);cost=end-start;if(cost <= 0){cost=1}print "count=" c ", avg latency=" total/c "ms, tp99=" tA[i99] "ms, tp90=" tA[i90] "ms",",qps=" c /cost, "total cost=" cost "s"}'

**Comment by qingfengshiran** [comment]
> 你可以写一个类似这个样的awk统计，grep 'gamma_engine.cc:451' gamma.log | tail -n 100000 | awk -F '[[,]' '{print $1,$9}'|awk -F ']ms' '{print $1}'|awk '{print $2 "-" $3, $4}' | awk -F 'ms' '{print $1}'|awk '{split($1, a, "[-|:]");t=sprintf("%s %s %s %s %s %s", a[1],a[2],a[3],a[4],a[5],a[6]); ts=mktime(t);print ts, $2}'| awk 'BEGIN{start=0;end=0;c=0;total=0}{if(NR==1){start=$1}end=$1;c=c+1;a[c]=$2;total=total+$2;}END{len=asort(a,tA);i99=int(c_0.99);i90=int(c_0.9);cost=end-start;if(cost <= 0){cost=1}print "count=" c ", avg latency=" total/c "ms, tp99=" tA[i99] "ms, tp90=" tA[i90] "ms",",qps=" c /cost, "total cost=" cost "s"}'

我这边直接运行了一下，好像有点小问题
Vearch3.2.7+ gamma 08e2745：
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/42227773/139658520-dfa4ad16-e7cc-424e-805f-3fcd577dbe9a.png">
Vearch3.2.7+ gamma a64cacf：
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/42227773/139658561-edded5ad-2222-4b3d-821f-accea8267145.png">

**Comment by qingfengshiran** [comment]
现在发现以下现象，我用自己编译的镜像，作为router节点就出现延时比较严重的情况。
<img width="831" alt="image" src="https://user-images.githubusercontent.com/42227773/139783436-5631ee3f-b47e-43c9-b7e9-77b05aeda4de.png">

**Comment by zcdb** [comment]
这个比较奇怪啊，router不会直接调用gamma，ps才会调用gamma。编译的没有问题吧？

**Comment by qingfengshiran** [comment]
> 这个比较奇怪啊，router不会直接调用gamma，ps才会调用gamma。编译的没有问题吧？
> 另外问一下你搜索的时候有使用数值索引吗？搜索的时候有插入吗？

大约找到原因了，dockerhub上的vearch3.2.7和github上的v3.2.7代码不是同一个patch应该，github上的vearchv.3.2.7是4月28日打的tag，dockerhub的v3.2.7是6月8日更新的，当时dockerhub更新了3次v3.2.7，其中有一次就有解决batch search的问题。

**Comment by zcdb** [comment]
> > 这个比较奇怪啊，router不会直接调用gamma，ps才会调用gamma。编译的没有问题吧？
> > 另外问一下你搜索的时候有使用数值索引吗？搜索的时候有插入吗？
> 
> 大约找到原因了，dockerhub上的vearch3.2.7和github上的v3.2.7代码不是同一个patch应该，github上的vearchv.3.2.7是4月28日打的tag，dockerhub的v3.2.7是6月8日更新的，当时dockerhub更新了3次v3.2.7，其中有一次就有解决batch search的问题。

好的

**Comment by Maslino** [comment]
> > 这个比较奇怪啊，router不会直接调用gamma，ps才会调用gamma。编译的没有问题吧？
> > 另外问一下你搜索的时候有使用数值索引吗？搜索的时候有插入吗？
> 
> 大约找到原因了，dockerhub上的vearch3.2.7和github上的v3.2.7代码不是同一个patch应该，github上的vearchv.3.2.7是4月28日打的tag，dockerhub的v3.2.7是6月8日更新的，当时dockerhub更新了3次v3.2.7，其中有一次就有解决batch search的问题。

请问是解决batch search啥问题？

**Comment by qingfengshiran** [comment]
> > > 这个比较奇怪啊，router不会直接调用gamma，ps才会调用gamma。编译的没有问题吧？
> > > 另外问一下你搜索的时候有使用数值索引吗？搜索的时候有插入吗？
> > 
> > 
> > 大约找到原因了，dockerhub上的vearch3.2.7和github上的v3.2.7代码不是同一个patch应该，github上的vearchv.3.2.7是4月28日打的tag，dockerhub的v3.2.7是6月8日更新的，当时dockerhub更新了3次v3.2.7，其中有一次就有解决batch search的问题。
> 
> 请问是解决batch search啥问题？

就是batch search耗时，好像是没有使用并行查询，不过我没有找到具体的patch
