### ISSUE TITLE
GPU部署方案咨询

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#554]
我们现在有一个检索库的，现在16亿128维数据，大约1月增加1亿的底库量，目前用了15C50G*40Pod，CPU利用率在20-30%之间，想咨询一下，如果该用GPU部署，是否会节省资源？GPU大约需要多少资源？是否支持实时插入检索，之前看到的是不支持实时插入检索。

**Comment by wxingda** [comment]
GPU会节省资源，我们2亿128维数据，使用了2台16C32G的GPU服务器，QPS为1000，tp99小于15ms。
GPU索引不支持实时插入检索，插入数据后执行flush后才能被检索到

**Comment by qingfengshiran** [comment]
> GPU会节省资源，我们2亿128维数据，使用了2台16C32G的GPU服务器，QPS为1000，tp99小于15ms。
> GPU索引不支持实时插入检索，插入数据后执行flush后才能被检索到

GPU部署的话，元数据保存在哪里，索引又保存在哪里呢？
我看到你们的文档中只有这样的例子，能给一详细点的参数配置例子吗？
<img width="724" alt="image" src="https://user-images.githubusercontent.com/42227773/140453837-6daf733f-3dd5-4bf1-9417-54cc1d55bbf9.png">

**Comment by wxingda** [comment]
GPU目前只支持ivfpq索引，所以上图的配置就是所有的参数了，元数据和索引都保存在磁盘中

**Comment by qingfengshiran** [comment]
> GPU目前只支持ivfpq索引，所以上图的配置就是所有的参数了，元数据和索引都保存在磁盘中

好的，多谢
