### ISSUE TITLE
结合过滤的查询疑问

### ISSUE THREAD

**Issue by xiehuc** [vearch/vearch#57]
```
  if (condition->range_query_result &&
      condition->range_query_result->GetAllResult().size() == 1 &&
      condition->range_query_result->GetAllResult()[0].Size() < 50000) {
    const std::vector<int> docid_list = condition->range_query_result->ToDocs();
```
`gamma_index_ivfpq.cc` L429
范围查询1个结果集，并且结果集小于50000才过滤？大于直接穿透了？

```
    if (range_index_ptr_ != nullptr) {
      is_filterable = [this](int doc_id) -> bool {
        return (bitmap::test(docids_bitmap_, doc_id) ||
                (not range_index_ptr_->Has(doc_id)));
      };
    } else {
      is_filterable = [this](int doc_id) -> bool {
        return (bitmap::test(docids_bitmap_, doc_id));
      };
    }
```
`gamma_index_ivfpq.h` L541

is_filterable设置了，没有任何调用的地方，符合预期么？

**Comment by xiehuc** [comment]
```
    int ret = ((RTInvertedLists *)this->invlists)
                  ->rt_invert_index_ptr_->RetrieveCodes(
                      vid_list_data, vid_list_len, bucket_codes, bucket_vids);

```

`gamma_index_ivfpq.cc` L474 这个调用很低效吧。直接把整个倒排表复制一份了。

**Comment by qiutianme** [comment]
> ```
>   if (condition->range_query_result &&
>       condition->range_query_result->GetAllResult().size() == 1 &&
>       condition->range_query_result->GetAllResult()[0].Size() < 50000) {
>     const std::vector<int> docid_list = condition->range_query_result->ToDocs();
> ```
> 

@xiehuc   这是一个优化，结果集小于50000走if里面的优化流程，大于50000走后面的正常检索流程

>     if (range_index_ptr_ != nullptr) {
>       is_filterable = [this](int doc_id) -> bool {
>         return (bitmap::test(docids_bitmap_, doc_id) ||
>                 (not range_index_ptr_->Has(doc_id)));
>       };
>     } else {
>       is_filterable = [this](int doc_id) -> bool {
>         return (bitmap::test(docids_bitmap_, doc_id));
>       };
>     }

is_filterable确实是遗留代码，没有使用，后面我们整理一下

**Comment by qiutianme** [comment]
> ```
>     int ret = ((RTInvertedLists *)this->invlists)
>                   ->rt_invert_index_ptr_->RetrieveCodes(
>                       vid_list_data, vid_list_len, bucket_codes, bucket_vids);
> ```
> 
> `gamma_index_ivfpq.cc` L474 这个调用很低效吧。直接把整个倒排表复制一份了。

RetrieveCodes函数只是在上面的<50000优化中使用，不会复制整个到排表，所以不会低效的。

**Comment by xiehuc** [comment]
> > ```
> >   if (condition->range_query_result &&
> >       condition->range_query_result->GetAllResult().size() == 1 &&
> >       condition->range_query_result->GetAllResult()[0].Size() < 50000) {
> >     const std::vector<int> docid_list = condition->range_query_result->ToDocs();
> > ```
> 
> @xiehuc 这是一个优化，结果集小于50000走if里面的优化流程，大于50000走后面的正常检索流程

1. 已知 is_filterable 没有使用，即 `set_search_condition(condition)` 没有实际作用到
2. 正常检索流程没有一处使用condition、range_query_result、range_index_ptr_ 的地方

推论：正常检索流程filter功能不生效

是有这个疑问。

**Comment by qiutianme** [comment]
> > > ```
> > >   if (condition->range_query_result &&
> > >       condition->range_query_result->GetAllResult().size() == 1 &&
> > >       condition->range_query_result->GetAllResult()[0].Size() < 50000) {
> > >     const std::vector<int> docid_list = condition->range_query_result->ToDocs();
> > > ```
> > 
> > 
> > @xiehuc 这是一个优化，结果集小于50000走if里面的优化流程，大于50000走后面的正常检索流程
> 
> 1. 已知 is_filterable 没有使用，即 `set_search_condition(condition)` 没有实际作用到
> 2. 正常检索流程没有一处使用condition、range_query_result、range_index_ptr_ 的地方
> 
> 推论：正常检索流程filter功能不生效
> 
> 是有这个疑问。

在gamma_index_ivfpq.h L587 有使用range_index_ptr_

```
#define HANDLE_ONE                                         \
  do {                                                     \
    int doc_id = raw_vec_->vid2docid_[ids[j]];             \
    if ((range_index_ptr_ != nullptr &&                    \
         (not range_index_ptr_->Has(doc_id))) ||           \
        bitmap::test(docids_bitmap_, doc_id)) {            \
      codes += this->pq.M; /* increment pointer */         \
      j++;                 /* increment j*/                \
      continue;                                            \
    }                                                      \
```

**Comment by xiehuc** [comment]
🙏🙏，thanks了，明白了。
