### ISSUE TITLE
建立索引之后查询结果时而正常返回时而返回为空

### ISSUE THREAD

**Issue by Yuming-Xu** [vearch/vearch#579]
Vearch版本 3.2.7
建表语句
`{
    "name": "space1m_table2",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 900000,
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "L2",
            "ncentroids": 256,
            "nsubvector": 32
        }
    },
    "properties": {
        "field1": {
            "type": "vector",
            "dimension": 100,
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048,
                "compress": {"rate":16}
            }
        }
    }
}`

插入过程为单进程顺序插入，赋予id 0～999999，插入结束后也可正常通过id查询
`curl -XGET http://127.0.0.1:9001/test_spacev/space1m_table2/999996
{"_index":"test_spacev","_type":"space1m_table2","_id":"999996","found":true,"_source":{"field1":{"feature":[21,5,4,-15,-11,-12,-13,22,-8,-24,9,14,5,-4,2,9,-15,-11,-3,-7,2,6,-3,0,8,-2,-15,-7,1,17,9,-7,20,-4,12,15,-12,-5,15,-16,15,0,0,12,0,0,7,8,19,0,-16,4,-23,0,-10,15,0,-24,-5,-6,-6,20,-5,15,-18,-13,-22,14,-19,11,24,3,-15,-13,-18,8,-4,-4,-2,-21,0,-4,-22,-1,9,14,-1,2,9,-12,9,-13,-8,-18,-15,-11,-14,-19,-2,20],"source":""}}}`

插入过后gamma.log也显示正常建立索引
INFO 2021-11-28 21:19:26,821 async_writer.cc:120 AsyncWriter queue size[10001] > 10000, sleep 10ms
INFO 2021-11-28 21:19:26,837 block.cc:30 Block[1_table_2] info, per_block_size[65536] item_length[8] header_size[30] seg_block_capacity[400000]
INFO 2021-11-28 21:19:26,837 block.cc:30 Block[1_table_str_2] info, per_block_size[65536] item_length[65536] header_size[30] seg_block_capacity[400000]
INFO 2021-11-28 21:19:26,837 table.cc:396 table cost [2346.75]ms
INFO 2021-11-28 21:19:33,168 gamma_engine.cc:759 Begin indexing.
INFO 2021-11-28 21:19:33,168 gamma_engine.cc:766 Doc_num[1000000], BatchAdd[1000000] total cost [9252.5]ms
WARNING 2021-11-28 21:19:33,168 gamma_index_ivfpq.cc:488 Index_size[900000] is too big. The appropriate range is [ncentroids * 39, ncentroids * 256].index_size becomes ncentroids * 256[65536].
INFO 2021-11-28 21:19:54,689 gamma_index_ivfpq.cc:547 train successed!
INFO 2021-11-28 21:19:54,691 gamma_engine.cc:1019 vector manager indexing success!
INFO 2021-11-28 21:19:54,821 gamma_index_ivfpq.cc:700 Add time [0.00560303]ms, count 10000
.....
INFO 2021-11-28 21:20:07,494 gamma_index_ivfpq.cc:700 Add time [0.00497998]ms, count 980000
INFO 2021-11-28 21:20:07,593 gamma_index_ivfpq.cc:700 Add time [0.00485303]ms, count 990000
INFO 2021-11-28 21:20:07,705 gamma_index_ivfpq.cc:700 Add time [0.0170498]ms, count 1000000

取一个示例搜索语句为例子:
`curl -H "content-type: application/json" -XPOST -d'
{
"query": {
"sum": [{
"field": "field1", 
"feature": [0, -7, -19, -15, 5, -2, -10, 6, 15, 0, 9, -11, 1, -8, 13, -8, 13, -15, -20, -20, -10, 8, 19, -17, 11, -20, 21, -13, 10, 14, 7, -9, 9, -15, -18, 13, 4, -9, -16, -10, 15, -15, 11, 4, 21, 22, 11, 7, 16, -1, 9, 15, -5, -7, -5, -15, 6, -9, -19, -9, 8, 9, -9, 18, -5, -18, -6, 11, -15, 0, -21, -13, -7, -9, 21, -3, 18, 5, -8, -8, 2, -1, -19, -12, 18, -4, -17, -5, -9, -8, -18, -5, -21, 3, -11, 6, -11, 7, -13, 2]
}]
}, 
"retrieval_param": {
"recall_num": 100, 
"nprobe": 80, 
"metric_type": "L2"
}, 
"is_brute_search": 0,
"size": 10
}
' http://127.0.0.1:9001/test_spacev/space1m_table2/_search`

大部分时刻返回:
`{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1},"hits":{"total":0,"max_score":-1}}`
`{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1},"hits":{"total":0,"max_score":-1}}`

极少时刻返回:
`{"took":21,"timed_out":false,"_shards":{"total":1,"successful":1},"hits":{"total":10,"max_score":9466,"hits":[{"_index":"test_spacev","_type":"space1m_table2","_id":"230087","_score":6741},{"_index":"test_spacev","_type":"space1m_table2","_id":"199254","_score":7154},{"_index":"test_spacev","_type":"space1m_table2","_id":"151791","_score":8080},{"_index":"test_spacev","_type":"space1m_table2","_id":"708008","_score":8260},{"_index":"test_spacev","_type":"space1m_table2","_id":"39082","_score":8421},{"_index":"test_spacev","_type":"space1m_table2","_id":"230103","_score":8618},{"_index":"test_spacev","_type":"space1m_table2","_id":"180301","_score":9167},{"_index":"test_spacev","_type":"space1m_table2","_id":"230088","_score":9187},{"_index":"test_spacev","_type":"space1m_table2","_id":"141823","_score":9203},{"_index":"test_spacev","_type":"space1m_table2","_id":"487831","_score":9466}]}}`

同时注意到gamma.log的搜索记录:
`INFO 2021-11-28 21:21:15,149 gamma_engine.cc:459 filter [0.000976562]ms search prepare [1.57886]ms compute 1 [0.0690918]ms search 0 [0.00195312]ms merge result [0.00292969]ms search total [0]ms pack results [0.00219727]ms  total cost [1.65894]ms
INFO 2021-11-28 21:21:15,906 gamma_engine.cc:459 filter [0.000976562]ms search prepare [1.14917]ms compute 1 [0.0778809]ms search 0 [0.00317383]ms merge result [0.00195312]ms search total [0.000976562]ms pack results [0.000976562]ms  total cost [1.23804]ms
INFO 2021-11-28 21:21:16,739 gamma_engine.cc:459 filter [0.000976562]ms search prepare [1.20703]ms compute 1 [0.0600586]ms search 0 [0.00195312]ms merge result [0.00292969]ms search total [0.000976562]ms pack results [0.000976562]ms  total cost [1.27905]ms
INFO 2021-11-28 21:21:17,829 gamma_engine.cc:459 filter [0.00195312]ms search prepare [1.5979]ms compute 1 [10.9561]ms search 0 [0.00708008]ms merge result [0.00195312]ms search total [0.000976562]ms pack results [0.0429688]ms  total cost [12.6118]ms
INFO 2021-11-28 21:21:20,848 gamma_engine.cc:459 filter [0]ms search prepare [1.22803]ms compute 1 [0.0649414]ms search 0 [0.00195312]ms merge result [0.00292969]ms search total [0]ms pack results [0.00219727]ms  total cost [1.30298]ms`
并无任何报错信息，正常返回的查询耗时更长

考虑过是不是正常返回其实是暴力搜索结果，但是检查过暴力搜索，gamma.log中会有些许不同
将is_brute_search设置为1，搜索结果正常，从gamma.log中可以看到是:
`INFO 2021-11-28 21:35:25,760 gamma_engine.cc:459 filter [0.00195312]ms flat compute 1 [920.525]ms search 0 [0.0239258]ms merge result [0.00317383]ms search total [0.00195312]ms pack results [0.0900879]ms  total cost [920.655]ms`

Update:
使用msspacev1m就会出现这样的问题，而使用sift1m并且使用相同的配置就没有存在这样的问题（仅仅将数据维度从100修改为128）

**Comment by Maslino** [comment]
这个问题可能与向量维度不是nsubvector的整数倍有关。比如你这个例子，向量维度是100，nsubvector是32

**Comment by zcdb** [comment]
是的，对于原始的ivfpq是不支持向量维度不是nsubvector的整数倍的场景的，vearch内部做了兼容，但是这样可能会导致向量的分布出现变化，所以最好还是设置成能整除的

**Comment by Yuming-Xu** [comment]
确实是这个问题，修改之后就好了 感谢
