### ISSUE TITLE
build gamma fail

### ISSUE THREAD

**Issue by rebel2019** [vearch/vearch#584]
/vearch/go/src/github.com/vearch/vearch/engine/storage/block.h:16,
/vearch/go/src/github.com/vearch/vearch/engine/storage/block.cc:8:
/vearch/go/src/github.com/vearch/vearch/engine/storage/async_writer.h:11:10: fatal error: tbb/concurrent_queue.h: No such file or directory
   11 | #include <tbb/concurrent_queue.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by zcdb** [comment]
https://vearch.readthedocs.io/zh_CN/latest/quick-start-guide.html 参照文档安装一下依赖吧
