### ISSUE TITLE
ld gamma.so fail

### ISSUE THREAD

**Issue by rebel2019** [vearch/vearch#585]
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_loadDictHC'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_compress_fast_continue'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_resetStreamHC'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `BZ2_bzCompressEnd'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_setStreamDecode'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_freeStreamDecode'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `inflateInit2_'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_createStreamDecode'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `BZ2_bzDecompress'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `inflate'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_freeStream'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_compressBound'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `BZ2_bzCompressInit'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `deflateSetDictionary'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_decompress_safe_continue'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_freeStreamHC'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `deflateInit2_'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_loadDict'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `deflate'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_createStreamHC'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_createStream'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `inflateSetDictionary'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `deflateEnd'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `LZ4_compress_HC_continue'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `BZ2_bzDecompressInit'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `BZ2_bzCompress'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `inflateEnd'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `BZ2_bzDecompressEnd'
/bin/ld: ../ps/engine/gammacb/lib/lib/../lib/libgamma.so: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
collect2: error: ld returned 1 exit status
build deploy tool by vendor

**Comment by zcdb** [comment]
https://vearch.readthedocs.io/zh_CN/latest/quick-start-guide.html 参照文档安装一下rocksdb的相关依赖吧
