### ISSUE TITLE
小库高QPS查询

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#591]
我们有这样一种需求，回扫整个图片，如特定人脸，我们是这样用的：
底库：200张图片向量左右
算法：FLAT
待查库：10亿+，需要在短时间内找到10亿在底库中的命中情况
PS：25个15核30G机器，1个partition，25副本
router：120个4核8G机器
负责发起查询请求的机器：200个7核14G机器
TOPK=2
目前最高大约只能打到5万左右的QPS，再就很难上升了，发起请求的机器在150个台的时候也是差不多5万左右的QPS，最早测试的时候，用单台机器请求，QPS可以达到500。
使用发现，CPU都没有用到50%的利用率，查询延迟也很低，请问这能是哪里的瓶颈呢？有什么办法继续提升QPS呢？
如果用GPU能实现我们的需求吗？我们想把QPS提升到10万左右。

PS节点和router节点利用率稳定在35%-45%。
<img width="885" alt="image" src="https://user-images.githubusercontent.com/42227773/147175047-64a4ff4f-d280-4a55-9183-99ca3159504d.png">
查询节点CPU利用率在10%左右
<img width="870" alt="image" src="https://user-images.githubusercontent.com/42227773/147175101-2d07afe7-5e1b-4674-8bce-0a10fbdc14b0.png">
查询延迟50ms以内
<img width="882" alt="image" src="https://user-images.githubusercontent.com/42227773/147175149-9e9af537-d3a3-492f-b97e-626933225015.png">
查询的QPS
<img width="903" alt="image" src="https://user-images.githubusercontent.com/42227773/147175170-8f77f329-cabc-446c-9648-fe70442924dc.png">

**Comment by qingfengshiran** [comment]
@Maslino 因为我们还有其他很多场景用到你们这个库，有的底库10亿级，所以都是一套，如果用faiss自己搭建，可能还是要考虑分布式的事情吧

**Comment by zcdb** [comment]
你们现在的请求是单条还是批量的呢？

**Comment by qingfengshiran** [comment]
> 你们现在的请求是单条还是批量的呢？

批量请求，大部分在10条以内，最多几十个

**Comment by zcdb** [comment]
看看gamma.log里面有Resource temporarily unavailable这样的日志吗或者有啥error、warning？

**Comment by zcdb** [comment]
另外gpu暂时没有支持暴力搜，如果你们有需要，可以考虑自己先封装实现一下

**Comment by qingfengshiran** [comment]
> 看看gamma.log里面有Resource temporarily unavailable这样的日志吗或者有啥error、warning？

没有，看了一些日志，都是下面的log
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/42227773/147565610-b53f80b8-1955-4b70-8745-ed82f3d1b9d8.png">

**Comment by zcdb** [comment]
vearch内部是有限流的，但是没有相关的日志的话看来是没有达到上限。你们有看过router和ps的连接数和流量情况吗？另外尝试过增加ps的数量吗？

**Comment by qingfengshiran** [comment]
> vearch内部是有限流的，但是没有相关的日志的话看来是没有达到上限。
你们有看过router和ps的连接数和流量情况吗？
--》这个要怎么看呢？

另外尝试过增加ps的数量吗？
--》PS从20增加到25后QPS没有什么明显变化，CPU利用率倒是降低了，我试过单节点PS能达到4k-5k的QPS，CPU利用率可以到80%，按里说应该扩展副本就可以了
