### ISSUE TITLE
Bucket扩容

### ISSUE THREAD

**Issue by realdalabengba** [vearch/vearch#593]
你好，有两个问题请教下：
1、判断Bucket是否还能扩容依据cur_invert_ptr_->cur_bucket_keys_[bucket_no] * 2 >= (int)bucket_keys_limit_，但实际扩容的时候是根据ExtendCoefficient来确定扩容后的大小，那这里的 cur * 2是否合理？
2、默认的bucket_max_size设置的依据是什么呢？int总大小除以默认的bucket数量吗？

**Comment by zcdb** [comment]
1、是的，这里需要修改下
2、bucket_max_size默认设置是经验值，但是此参数可以在建表时传入指定，可以根据自己的需要设置

**Comment by realdalabengba** [comment]
好的，谢了
