### ISSUE TITLE
目前我们这边使用k8s无法部署vearch

### ISSUE THREAD

**Issue by chenrulongmaster** [vearch/vearch#597]
目前我们这边需求是使用k8s部署vearch，单实例模式，使用的镜像是3.2.8版本，数据映射到固定节点的本地文件夹，但是pod重启后，就无法加载ps数据，会报partition 找不到的异常信息

**Comment by gDreamcatcher** [comment]
发一下gamma.log的日志吧

**Comment by chenrulongmaster** [comment]
> 发一下gamma.log的日志吧

不好意思，我这边找到原因了，是少映射了一个文件夹

**Comment by chenrulongmaster** [comment]
给大家说一下，使用场景
1. 各个搜索vearch实例独立开来，防止各个业务影响
2. 各业务数据量不算太大，百万到5千万级别，维度128-300都有
3. 实例调度到指定节点使用本地文件系统，或者pvc存储（需要io性能比较高）
