### ISSUE TITLE
python plugin visual search API 出现“Expecting value: line 1 column 1 (char 0)"错误

### ISSUE THREAD

**Issue by LynnaPan** [vearch/vearch#60]
hi,
在用` bash ./bin/run.sh image`  deploy plugin后，我尝试用例子中的request来发create DB 请求：
```
curl -XPOST -H "content-type:application/json" -d '{
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' http://127.0.0.1:4101/test/test/_create
```
但返回如下错误：
```
INFO:main:request -*- /test/test/_create -*- {
    "db": true,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}
DEBUG:main:  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode     raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
DEBUG:main:response -*- /test/test/_create -*- Expecting value: line 1 column 1 (char 0)
```
我尝试把json放到文件中去curl也是一样的错误。
请问是否是python版本的问题？有版本要求吗？
thanks！

**Comment by gDreamcatcher** [comment]
You can try to change the value of db from true to True.

**Comment by LynnaPan** [comment]
thanks, after chaning db value from true to True, is solve this error problem.
however, new error pop up as:
`Expecting value: line 1 column 12 (char 11)`

**Comment by gDreamcatcher** [comment]
Could you please show me when and where this problem happen？

**Comment by LynnaPan** [comment]
I follow the steps in https://github.com/vearch/vearch/blob/master/docs/Quickstart.md 
these are my steps:
1.  deploy vearch by docker: `nohup docker run -p 8817:8817 -p 9001:9001 -v $PWD/config.toml:/vearch/config.toml  anjs/vearch:0.2 all &`
2. deploy the visual search plugin: `bash ./bin/run.sh image`
3. then try to send API request to create database and space: 
```
curl -XPOST -H "content-type:application/json" -d '{
    "db": True,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}' http://127.0.0.1:4101/test/test/_create 
```
In the readme, the db value is True, so I change to true as your suggestion as above, then this error happen:
```
INFO:main:request -*- /test/test/_create -*- {
    "db": True,
    "method": 0,
    "columns": {
        "imageurl": {
            "type": "keyword"
        },
        "boundingbox": {
            "type": "keyword"
        },
        "label": {
            "type": "keyword"
        }
    },
    "feature": {
        "type": "vector",
        "filed": "imageurl",
        "model_id": "vgg16",
        "dimension": 512
    }
}
DEBUG:main:  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode     raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 2 column 11 (char 12)
DEBUG:main:response -*- /test/test/_create -*- Expecting value: line 2 column 11 (char 12)
```

**Comment by gDreamcatcher** [comment]
I am sorry for this problem, I may have a mistake for what you said yesterday.   If you use `curl` send this request, the value of db in request body should be true, and if you use python send the request, the value of db should be True. And I suggest  you can add `traceback.print_exc()` at the 211th row between `except Exception as err:` and `err_info = util.catch_exc()` in main.py , and try agian. This will show more infomation of the error.  
In addition， here is a demo [用Vearch搭建一个图片搜索服务](https://my.oschina.net/ansj/blog/3117596) 
Best wishs!

**Comment by LynnaPan** [comment]
Thanks a lot. 
Finally the reason is IP address is not 127.0.0.1, which is my machine ip.
