### ISSUE TITLE
rpcx client protocol error:wrong magic number:72

### ISSUE THREAD

**Issue by springwings** [vearch/vearch#600]
建表的时候出现如下错误：
rpcx client protocol error:wrong magic number:72
该怎么解决

**Comment by gDreamcatcher** [comment]
请提供一下代码`commitID`和错误日志

**Comment by springwings** [comment]
> 请提供一下代码`commitID`和错误日志

cluster_api.go:280 createSpaceService err: need [] but got 0

**Comment by gDreamcatcher** [comment]
可以排查一下建表语句中partition数量是否正确，以及执行一下_cluster/stats看一下集群中是否有足够的server
