### ISSUE TITLE
vearch数据备份

### ISSUE THREAD

**Issue by culida** [vearch/vearch#609]
请问一下vearch的数据备份这一块需要怎么操作，有没有文档可供操作？
OS：CentOS7.7  vearch-version：vearch-3.1.0-1.el7.x86_64 单机安装，配置文件关于数据目录配置如下：
cat /data/vearch/config.toml 
[global]
    # the name will validate join cluster by same name
    name = "vdb"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    data = [
            "/data/vearch/datas/",
        ]  
    # log path , If you are in a production environment, You'd better set absolute paths

#后面想做数据备份，新增一台CentOS7.7机器，单机安装vearch-3.1.0-1.el7.x86_64，然后将原vearch的/data/vearch/datas/目录和配置文件拷贝到新的机器，成功启动，服务状态也是正常，如下：
 curl http://127.0.0.1:8817/_cluster/health  | python -m json.tool |grep "status"
                        "index_status": 2,
                        "raft_status": {
                        "status": 4
                "status": "green"
        "status": "green"
# 查询图片的时候返回如下：
{"_index":"sport","_type":"sport_img","_id":"264","found":false}

#gamma报错如下
INFO 2022-02-14 15:32:08,390 gamma_engine.cc:877 GetDocIDbyKey [264] error!

**Comment by gyd-a** [comment]
1、数据备份这块vearch暂时不支持。
2、重启后你可以调用health接口，看看两个集群的数据量是否相同；
3、你是调用这个curl -XGET http://router_server/$db_name/$space_name/$id 接口返回查询图片失败的吗？

**Comment by culida** [comment]
1、服务本身没有备份功能的话，我从os层面进行备份涉及到一个问题(假如我还原os的时候，os的ip已经变更过，是否会影响到集群(因为集群之前的master ip是旧节点ip))
2、重启后health接口，看看两个集群的数据量是相同的，doc_num数量一致
3、查询数据是使用这个接口的：curl -XGET http://router_server/$db_name/$space_name/$id

**Comment by gyd-a** [comment]
通常我们这样做，新创建一个集群，在新集群建表，建表参数和老集群，partition数量和老集群一样。kill掉ps，将老集群各partition的数据拷贝到新集群，partition id要对得上。然后重启。

**Comment by gyd-a** [comment]
get失败是不是因为你的partition id没对应上。

**Comment by culida** [comment]
> 通常我们这样做，新创建一个集群，在新集群建表，建表参数和老集群，partition数量和老集群一样。kill掉ps，将老集群各partition的数据拷贝到新集群，partition id要对得上。然后重启。

我这边的环境是单机版本。请问将老集群各partition的数据拷贝到新集群这个怎么理解？（是数据目录下的datas/文件夹直接复制过去吗？）



> get失败是不是因为你的partition id没对应上。

我通过http://master:8817/_cluster/stats接口查询新旧两个节点的vearch，看到id是相同的：
"partition_infos":[
            {
                "pid":1,
                "doc_num":3,
奇怪的是，导入数据的新集群虽然不能查询诗句，但是我使用这个接口：http://ps:9001/dbname/tablename/2 插入数据是正常的，并且新插入的数据可查询。
目前我这个vearch里面存在一千万的数据，是否存在这个问题：数据太大，迁移过去刚刚启动还没有初始化完成呢？继而导致查询失败

**Comment by culida** [comment]
附上服务日志：
[Master.DEBUG.log](https://github.com/vearch/vearch/files/8085031/Master.DEBUG.log)
[gamma.log](https://github.com/vearch/vearch/files/8085033/gamma.log)

**Comment by wxingda** [comment]
备份可参考https://vearch.readthedocs.io/zh-cn/latest/use_op/op_backup_migrate.html
