### ISSUE TITLE
导入CSV，detection设置为false不生效，依然会检测

### ISSUE THREAD

**Issue by 1990hjp** [vearch/vearch#61]
curl -XPOST -H "content-type:application/json" -d '{
    "method": "bulk",                                                         
    "imageurl": "../images/image_retrieval/test.csv",
    "detection": false
}' http://127.0.0.1:4101/test/test/_insert

**Comment by gDreamcatcher** [comment]
Thanks for your question, this is a bug， we will fix it  in next version. Now you can use single inport method, or fix the bug by yourself.
Fix Suggestion:
add follow 
```
for body in body_list:
     body['detection'] = data.get('detection', True)
```
before https://github.com/vearch/vearch/blob/6d5c1903a10d5e38e4a4775cf278b1cf3ca3d447/plugin/src/main.py#L347

**Comment by 1990hjp** [comment]
okay, thank you！
