### ISSUE TITLE
I want to join the wechat communication group

### ISSUE THREAD

**Issue by zhangsilence** [vearch/vearch#625]
After reading the source code for a period of time, I can actually test it. I have some questions that I would like to discuss with your team in depth. Therefore, could you please give me a contact information?

**Comment by ljeagle** [comment]
You can email vincent_jieli@yeah.net or join the wechat communication group through https://github.com/vearch/vearch/blob/master/docs/img/251120CB-8A61-4124-9336-B549D8D10607.png

**Comment by zhangsilence** [comment]
thank you
