### ISSUE TITLE
docker3.2.7镜像删除数据后，磁盘空间不释放

### ISSUE THREAD

**Issue by zhangsilence** [vearch/vearch#627]
你好，我在使用docker3.2.7镜像版本的delete_by_query接口删除之后发现_id查询不到了但是使用term仍可以查询到数据。磁盘的数据使用空间并没有下降。请问数据物理删除需要增加什么配置么，或者是其他的操作

**Comment by wxingda** [comment]
请问建表和查询语句是什么？

**Comment by zhangsilence** [comment]
使用这个语句进行删除/_delete_by_query
{
    "query": {
        "filter": [
            {
                "term": {
                    "featureId": [
                        "3510205853992970055"
                    ],
                    "operator": "or"
                }
            }
        ]
    }
}
建表语句：
{
    "name": "feature",
    "partition_num": 3,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "id_type": "String",
        "retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids": 2048,
            "nsubvector": 32
        }
    },
    "properties": {
        "featureId": {
            "type": "string",
            "index": true
        },
        "startTime": {
            "type": "integer",
            "index": true
        },
        "sourceIdentify": {
            "type": "string",
            "index": true
        },
        "sourceType": {
            "type": "integer"
        },
        "age": {
            "type": "integer"
        },
        "gender": {
            "type": "integer"
        },
        "dayNight": {
            "type": "integer"
        },
        "gaitVector": {
            "type": "vector",
            "dimension": 512,
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048
            }
        },
        "reidVector": {
            "type": "vector",
            "dimension": 512,
            "store_type": "RocksDB",
            "store_param": {
                "cache_size": 2048
            }
        }
    }
}
进行了大批量删除操作，发现电脑磁盘空间没有被释放：
然后进行了下列操作
使用删除语句之前，用_search的方法查出要删除的这条数据的_id值，然后进行删除，发现使用curl -XGET http://router_server/$db_name/$space_name/$id查询，查询不到相关数据信息，但是使用，_search方法term feartureId能够把数据查询出来。

**Comment by wxingda** [comment]
使用_search方法term feartureId查询的时候是不是没加向量？

**Comment by zhangsilence** [comment]
没有加向量，仅仅使用term feartureId

**Comment by wxingda** [comment]
featureId的值是不是与_id的值是一样的？

**Comment by zhangsilence** [comment]
不一样的，_id是vearch随机生成的

**Comment by zhangsilence** [comment]
最开始时候_id和featureId设置成一样的，但是在大批量数据进行插入的时候，报错。查看历史issues的回复，说是hash冲突。然后我对_id不指定具体值进行插入的数据。

**Comment by wxingda** [comment]
你试下用特征搜索被删除的doc看看还能搜到不，term过滤是要和特征一起用的，如果请求中只有term过滤而没有特征，那就会触发一个被废弃的功能，这个功能后期我会删除掉

**Comment by zhangsilence** [comment]
我关注的点是：删除数据如何能实现物理删除，就是删除数据，服务器的磁盘空间被释放。要想达到这个效果我应该如何去操作

**Comment by wxingda** [comment]
目前的删除操作都是标记删除

**Comment by zhangsilence** [comment]
谢谢大佬回答，点赞，爱心

**Comment by zhangsilence** [comment]
大佬，我想请教一下，在生产环境应该如何避免磁盘空间一直增长的问题，有什么方案思路可以提供一下么。

**Comment by wxingda** [comment]
频繁增删的表可以定时将数据导出，然后重建下表，这样既能够释放硬盘空间，还能更新索引

**Comment by zhangsilence** [comment]
大佬，我有两个疑惑的点，希望你给我解答一下：
1. 使用什么方式进行数据导出，是有现存的API还是利用导出工具一类的。
2. 在进行数据导出时，vearch的查询功能是不是不可用的状态。
