### ISSUE TITLE
ps issue

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#628]
...

**Comment by zcdb** [comment]
日志中有所发现吗

**Comment by qingfengshiran** [comment]
> 日志中有所发现吗

今天的一次重启，PS.ERROR.log没有日志，这个是gamma.log日志
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/42227773/162131422-052755bd-ea8b-4de4-9455-2880e7d16300.png">

**Comment by qingfengshiran** [comment]
> 日志中有所发现吗

麻烦有空帮忙看看哈，谢谢

**Comment by jrvin** [comment]
有啥进展吗？

**Comment by qingfengshiran** [comment]
> 有啥进展吗？

没有，现在还会出现

**Comment by qingfengshiran** [comment]
> 日志中有所发现吗

你好能帮忙看一下吗？
