### ISSUE TITLE
k8s部署疑问

### ISSUE THREAD

**Issue by hanqiushi** [vearch/vearch#629]
我这边尝试用k8s部署，有个疑问，master 的 address 要怎么写，ip的话需要节点创建出来才能确定，而且master pod重启的话ip也会变。
想问下，可行的k8s部署应该是怎样的，多谢

**Comment by gDreamcatcher** [comment]
master可以走主机网络的方式，或者使用etcd外置这样master可以使用域名的方式了

**Comment by hanqiushi** [comment]
多谢
