### ISSUE TITLE
模型与向量搜索引擎的同步问题

### ISSUE THREAD

**Issue by 34127chi** [vearch/vearch#63]
我理解向量搜索引擎是用来存储对应的文本向量、图像向量、视频向量  是线上检索服务的基础模块 因为这些向量是由模型编码文本、图像、视频得到的 所以当模型改变的时候 向量搜索引擎也要跟着同步更新 这个过程怎么做到无缝衔接的 （避免模型改变之后 向量搜索引擎中还是原来模型编码的结果）

**Comment by gDreamcatcher** [comment]
当你需要更新模型的时候，为了不影响线上使用， 你可以再创建一个库表存新模型的特征， 每次新请求都有两个模型同时提取特征插入到对应的库表里， 等新的库表中的数据和旧的同步了之后， 再将请求全部都切换到新的库表上。

**Comment by 34127chi** [comment]
> 当你需要更新模型的时候，为了不影响线上使用， 你可以再创建一个库表存新模型的特征， 每次新请求都有两个模型同时提取特征插入到对应的库表里， 等新的库表中的数据和旧的同步了之后， 再将请求全部都切换到新的库表上。

**Comment by Csraf** [comment]
搜索引擎实现双版本的功能
