### ISSUE TITLE
float和double类型的array建库不符合预期

### ISSUE THREAD

**Issue by qingfengshiran** [vearch/vearch#630]
建表的时候一个标量的参数是float，array，即下面的bboxInfo
<img width="411" alt="image" src="https://user-images.githubusercontent.com/42227773/161920960-33b5b327-2952-4d58-9382-9e3edb72ff9d.png">
插入的数据
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/42227773/161921448-dafe24e5-6334-4d17-aae7-689109d1bb23.png">

检索出来如下所示
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/42227773/161921519-f3e9e888-7107-492e-a166-bdb8efc6bd53.png">
请问是哪里有什么使用的问题吗？ids type是keyword用list没有问题。
vearch最新的3.2.7

**Comment by qingfengshiran** [comment]
> 建表的时候一个标量的参数是float，array，即下面的bboxInfo <img alt="image" width="411" src="https://user-images.githubusercontent.com/42227773/161920960-33b5b327-2952-4d58-9382-9e3edb72ff9d.png"> 插入的数据 <img alt="image" width="1410" src="https://user-images.githubusercontent.com/42227773/161921448-dafe24e5-6334-4d17-aae7-689109d1bb23.png">
> 
> 检索出来如下所示 <img alt="image" width="1918" src="https://user-images.githubusercontent.com/42227773/161921519-f3e9e888-7107-492e-a166-bdb8efc6bd53.png"> 请问是哪里有什么使用的问题吗？ids type是keyword用list没有问题。 vearch最新的3.2.7

看了一下，只有string支持array，我改成了vector，可以建表，但是插入不成功
<img width="519" alt="wecom-temp-f178eb9d03b41d12e3e8fada2795686d" src="https://user-images.githubusercontent.com/42227773/161929234-b46d1ced-7c8c-41eb-ab57-fa032709c475.png">

<img width="1895" alt="image" src="https://user-images.githubusercontent.com/42227773/161929188-f056ab08-394b-491e-85ac-0b28501061bd.png">

**Comment by Maslino** [comment]
bboxInfo 字段改成 vector 类型后插入不成功，是因为插入数据中 bboxInfo 格式有误，格式应该与feat字段一样，因为都是向量字段
