### ISSUE TITLE
faiss可以用旧数据重新创建索引么？

### ISSUE THREAD

**Issue by xincrazy** [vearch/vearch#635]
faiss索引创建完成之后，kmeans训练的中心点就不变了，如果想要重新训练，除了重新建space，然后重新写入数据，有直接应用旧数据训练的方法么？

**Comment by ljeagle** [comment]
可以把旧数据训练的聚类中心保存下来，后面接着使用就行

**Comment by xincrazy** [comment]
您所说的保存聚类中心是retrieval_model_index 这个目录所保存的数据么？把这个目录保存的数据拿出来，然后接着使用vearch就会基于现在的数据量计算新的聚类中心么？

**Comment by xincrazy** [comment]
自测已经清楚
