### ISSUE TITLE
主线版本删除比较慢

### ISSUE THREAD

**Issue by chaofeng-l** [vearch/vearch#637]
具体的删除代码，出于什么样的 考虑，加入sleep？？
int MultiFieldsRangeIndex::Delete(int docid, int field) {
  FieldRangeIndex *index = fields_[field];
  if (index == nullptr) {
    return 0;
  }
  FieldOperate *field_op = new FieldOperate(FieldOperate::DELETE, docid, field);
  table_->GetFieldRawValue(docid, field, field_op->value);

  while (field_operate_q_->size()) {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }

  field_operate_q_->push(field_op);

  return 0;
}

**Comment by wxingda** [comment]
现版本已去掉sleep
