### ISSUE TITLE
3台ps 依次重启，选不出leader

### ISSUE THREAD

**Issue by lujiajun619** [vearch/vearch#644]
{
    "code": 200,
    "msg": "success",
    "data": {
        "servers": [
            {
                "server": {
                    "name": 1,
                    "resource_name": "default",
                    "rpc_port": 8081,
                    "raft_heartbeat_port": 8898,
                    "raft_replicate_port": 8899,
                    "ip": "172.30.11.3",
                    "p_ids": [
                        1
                    ],
                    "private": false,
                    "version": {
                        "build_version": "3.2.7",
                        "build_time": "2022-02-21 08:54.29",
                        "commit_id": "4aa2be81a488303e5b8d25deabd5b46e326f0a31"
                    }
                },
                "partitions": [
                    {
                        "doc_num": 242276,
                        "size": 256339,
                        "path": "/iflytek/server/vearch1.0.0_1002/vearch_datas/",
                        "status": 3,
                        "raft_status": {
                            "ID": 1,
                            "NodeID": 1,
                            "Leader": 0,
                            "Term": 21990,
                            "Index": 242354,
                            "Commit": 242354,
                            "Applied": 242354,
                            "Vote": 1,
                            "PendQueue": 0,
                            "RecvQueue": 0,
                            "AppQueue": 0,
                            "Stopped": false,
                            "RestoringSnapshot": false,
                            "State": "StateCandidate",
                            "Replicas": null
                        },
                        "index_status": 2
                    }
                ]
            },
            {
                "server": {
                    "name": 2,
                    "resource_name": "default",
                    "rpc_port": 8081,
                    "raft_heartbeat_port": 8898,
                    "raft_replicate_port": 8899,
                    "ip": "172.30.8.100",
                    "p_ids": [
                        1
                    ],
                    "private": false,
                    "version": {
                        "build_version": "3.2.7",
                        "build_time": "2022-02-21 08:54.29",
                        "commit_id": "4aa2be81a488303e5b8d25deabd5b46e326f0a31"
                    }
                },
                "partitions": [
                    {
                        "doc_num": 242276,
                        "size": 256339,
                        "path": "/iflytek/server/vearch1.0.0_1002/vearch_datas/",
                        "status": 3,
                        "raft_status": {
                            "ID": 1,
                            "NodeID": 2,
                            "Leader": 0,
                            "Term": 21972,
                            "Index": 242354,
                            "Commit": 242354,
                            "Applied": 242354,
                            "Vote": 2,
                            "PendQueue": 0,
                            "RecvQueue": 0,
                            "AppQueue": 0,
                            "Stopped": false,
                            "RestoringSnapshot": false,
                            "State": "StateCandidate",
                            "Replicas": null
                        },
                        "index_status": 2
                    }
                ]
            },
            {
                "server": {
                    "name": 3,
                    "resource_name": "default",
                    "rpc_port": 8081,
                    "raft_heartbeat_port": 8898,
                    "raft_replicate_port": 8899,
                    "ip": "172.30.8.173",
                    "p_ids": [
                        1
                    ],
                    "private": false,
                    "version": {
                        "build_version": "3.2.7",
                        "build_time": "2022-02-21 08:54.29",
                        "commit_id": "4aa2be81a488303e5b8d25deabd5b46e326f0a31"
                    }
                },
                "partitions": [
                    {
                        "doc_num": 242276,
                        "size": 256339,
                        "path": "/iflytek/server/vearch1.0.0_1002/vearch_datas/",
                        "status": 3,
                        "raft_status": {
                            "ID": 1,
                            "NodeID": 3,
                            "Leader": 0,
                            "Term": 21016,
                            "Index": 242354,
                            "Commit": 242354,
                            "Applied": 242354,
                            "Vote": 3,
                            "PendQueue": 0,
                            "RecvQueue": 0,
                            "AppQueue": 0,
                            "Stopped": false,
                            "RestoringSnapshot": false,
                            "State": "StateCandidate",
                            "Replicas": null
                        },
                        "index_status": 2
                    }
                ]
            }
        ],
        "count": 3
    }
}

**Comment by kuailelijuan** [comment]
您好，麻烦提供下详细的日志， master、ps 相关的。

**Comment by wxingda** [comment]
该问题已修复https://github.com/vearch/vearch/pull/724
