### ISSUE TITLE
插入vector的数据被截断

### ISSUE THREAD

**Issue by onesnow123q** [vearch/vearch#645]
目前通过模型跑出来的feature为  
"feature": [
            -0.704264640808105,
            -0.335969209671021,
            -0.995647728443146,
            -0.0764617174863815,
            0.368747651576996,
            0.218709334731102,
            -0.394561916589737,
            -0.128590643405914,
            ……]

表结构中设置
"vector": {"type": "vector", "dimension": 768}

插入后查询，发现数据变成了
"feature": [
                -0.70426464,
                -0.3359692,
                -0.9956477,
                -0.07646172,
                0.36874765,
                0.21870933,
                -0.39456192,
                -0.12859064,
                ……]

请问有什么字段可以设置小数点后的位数吗？感谢~

**Comment by ljeagle** [comment]
目前只支持float类型，double占用位数过大，对存储和计算带来较大开销。

**Comment by Maslino** [comment]
这是查询接口在做json序列化的时候截断了，只保留小数点后8个数字
