### ISSUE TITLE
集群重启中遇到的集群状态问题

### ISSUE THREAD

**Issue by Alsace-lee** [vearch/vearch#650]
各位好，目前我们在2副本和3副本的集群中进行集群重启操作，有概率复现如下问题
1）集群ps节点重启期间如果存在请求写入，则有大概率，集群重启后无法选出主节点，但可进行搜索
2）ps 节点重启过程，主节点如果不是最后一个重启节点，否则集群重启后无法选出主节点，但可进行搜索
3）ps 全部进行重启时，个别节点重启后可能无法加入集群
在生产环境中，遇到这些问题我们很难有完整的规避手段来避免集群不可用，比较头疼
相关issue似乎较多，请问是否有注意到这些集群节点同步的问题与跟进。
如果需协助，我们可以提供完整复现流程和日志。
感谢！

**Comment by Alsace-lee** [comment]
经过今天的代码review并结合etcd中的数据来看
在顺序启动多个PS时，PS会按照启动顺序在etcd的server中写入PS的元信息，各个PS启动时会去读server节点的信息并感知同集群的PS
造成集群主从选举失败的现象在于：
后启动的PS可以读到先启动的PS在server节点上留下的信息，而先启动的没有感知到后启动的PS。
可能是对etcd上server节点的监听没有生效？

**Comment by wxingda** [comment]
该问题已修复https://github.com/vearch/vearch/pull/724
