### ISSUE TITLE
有新的微信群链接吗？

### ISSUE THREAD

**Issue by HaleyPei** [vearch/vearch#652]

**Comment by ljeagle** [comment]
![Uploading 62AAA18C-CC05-4EB0-BC46-4FC16E2757B7.png…]()

**Comment by ljeagle** [comment]
![Uploading 9E2341E7-31EF-45EA-BD7D-1294BEDAB5FF.png…]()

**Comment by ljeagle** [comment]
https://github.com/vearch/vearch/blob/master/docs/img/E572105C-ED6C-4096-AC92-20160B6DA97C.png
