### ISSUE TITLE
partition_not_ready exception

### ISSUE THREAD

**Issue by hanqiushi** [vearch/vearch#662]
使用vearch/vearch:3.2.7镜像，1 master， 2 ps，1 router
集群有重启过，之后ps选举leader失败，一个ps异常log如下：

 2022-08-09 02:56:52,807 :0: DEBUG: [raft->Step][2] is starting a new election at term[116534].

 2022-08-09 02:56:52,807 :0: DEBUG: [raft->Step][2] is starting a new election at term[116534].

 2022-08-09 02:56:52,807 :0: DEBUG: raft[2] random election timeout randElectionTick=7, config.ElectionTick=5, randTick=2

 2022-08-09 02:56:52,807 :0: DEBUG: raft[2] random election timeout randElectionTick=7, config.ElectionTick=5, randTick=2

 2022-08-09 02:56:52,807 :0: DEBUG: raft[2] became candidate at term 116535.

 2022-08-09 02:56:52,807 :0: DEBUG: raft[2] became candidate at term 116535.

 2022-08-09 02:56:52,807 :0: DEBUG: raft[2] received vote from 2 at term 116535.

 2022-08-09 02:56:52,807 :0: DEBUG: raft[2] received vote from 2 at term 116535.

 2022-08-09 02:56:52,807 :0: DEBUG: [raft->campaign][2 logterm: 1, index: 1849] sent vote request to 1 at term 116535.   raftFSM[0xc000562000]

 2022-08-09 02:56:52,807 :0: DEBUG: [raft->campaign][2 logterm: 1, index: 1849] sent vote request to 1 at term 116535.   raftFSM[0xc000562000]

 2022-08-09 02:56:52,807 :0: DEBUG: [Transport] get connection[Replicate] to 1[] failed,error is: cannot get node network information, nodeID=[1]

 2022-08-09 02:56:52,807 :0: DEBUG: [Transport] get connection[Replicate] to 1[] failed,error is: cannot get node network information, nodeID=[1]

另外一个ps的log基本一样，只不过是nodeId调换了下

请帮忙看看这个是什么问题，多谢

**Comment by hanqiushi** [comment]
@wxingda 
ps gamma.log

INFO 2022-08-09 02:26:46,784 gamma_api.cc:88 Version [[sha1]:ab7ea75 [author]:zhanchao1 [time]:2021-11-24 02:46:24 +0000 [branch]: (HEAD, origin/master, origin/HEAD, master)]
INFO 2022-08-09 02:26:46,786 bitmap_manager.cc:90 open bitmap file[/export/vdb/baud/datas/data/2/bitmap] success.
INFO 2022-08-09 02:26:46,786 bitmap_manager.cc:73 BitmapManager init successed. bytes_count=156251 bit_size=1250000
INFO 2022-08-09 02:26:46,801 table.cc:40 Table created success!
INFO 2022-08-09 02:26:46,801 gamma_engine.cc:281 GammaEngine setup successed! bitmap_bytes_size=156251
INFO 2022-08-09 02:26:46,801 gamma_engine.cc:163 memory trim thread start......
INFO 2022-08-09 02:26:47,038 gamma_engine.cc:81 System info: threads_max [2056664] max_map_count [262144] pid_max[65535]
INFO 2022-08-09 02:26:47,038 gamma_engine.cc:88 max_threads [65535] concurrent_threshold [1927]
INFO 2022-08-09 02:26:47,038 gamma_api.cc:52 Engine init successed!INFO 2022-08-09 02:26:47,068 vector_manager.cc:119 store params={"cache_size":1024,"segment_size":500000,"compress":{}}INFO 2022-08-09 02:26:47,068 vector_manager.cc:126 after merge, store parameters [{"cache_size":1024,"segment_size":500000,"compress":{}}]
INFO 2022-08-09 02:26:47,068 vector_manager.cc:119 store params={"cache_size":1024,"segment_size":500000,"compress":{}}INFO 2022-08-09 02:26:47,068 vector_manager.cc:126 after merge, store parameters [{"cache_size":1024,"segment_size":500000,"compress":{}}]
INFO 2022-08-09 02:26:47,068 vector_manager.cc:137 create raw vector success, vec_name[feature] store_type[MemoryOnly]
INFO 2022-08-09 02:26:47,069 memory_raw_vector.cc:124 extend segment sucess! nsegments=1
INFO 2022-08-09 02:26:47,069 memory_raw_vector.cc:42 init success, segment_size=500000
INFO 2022-08-09 02:26:47,069 memory_raw_vector.cc:75 store_params_.compress.IsEmpty() is true, not use zfp
INFO 2022-08-09 02:26:47,069 storage_manager.cc:102 Storage[feature]. lrucache cache_size[1024M], string lrucachecache_size[0M]
INFO 2022-08-09 02:26:47,069 lru_cache.h:341 LruCache[feature] open! Max_size[15565], max_overflow[819]
INFO 2022-08-09 02:26:47,069 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=16884,use_cell_num_=0
INFO 2022-08-09 02:26:47,070 block.cc:30 Block[feature_0] info, per_block_size[65536] item_length[1024] header_size[30] seg_block_capacity[2000000]
INFO 2022-08-09 02:26:47,071 storage_manager.cc:169 load storage[feature] success! options={segment_size=500000, fixed_value_bytes=1024, seg_block_capacity=2000000}, segment num=1
INFO 2022-08-09 02:26:47,071 storage_manager.cc:146 init storage[feature] success! options={segment_size=500000, fixed_value_bytes=1024, seg_block_capacity=2000000}, segment num=1
INFO 2022-08-09 02:26:47,071 memory_raw_vector.cc:84 init mmap raw vector success! vector byte size=1024, path=/export/vdb/baud/datas/data/2/vectors/feature
INFO 2022-08-09 02:26:47,071 raw_vector.cc:87 raw vector init success! name=feature, has source=0, multi_vids=0, vector_byte_size=1024, dimension=256, compress={}
INFO 2022-08-09 02:26:47,071 vector_manager.cc:163 Create index model [HNSW]
INFO 2022-08-09 02:26:47,071 gamma_index_hnswlib.cc:138 nlinks =38, efConstruction =380, metric_type =1
INFO 2022-08-09 02:26:47,107 vector_manager.cc:198 create vectors and indexes success! models=[HNSW]
INFO 2022-08-09 02:26:47,107 table.cc:103 Table compress [0]
INFO 2022-08-09 02:26:47,107 table.cc:110 Add field name [_id], type [4], index [0]
INFO 2022-08-09 02:26:47,107 table.cc:110 Add field name [image_url], type [4], index [1]
INFO 2022-08-09 02:26:47,107 table.cc:110 Add field name [group], type [4], index [1]
INFO 2022-08-09 02:26:47,107 table.cc:110 Add field name [face], type [4], index [1]
INFO 2022-08-09 02:26:47,108 table.cc:129 Create table 2 success! item length=32, field num=4
INFO 2022-08-09 02:26:47,108 storage_manager.cc:102 Storage[2_table]. lrucache cache_size[512M], string lrucache cache_size[512M]
INFO 2022-08-09 02:26:47,108 lru_cache.h:341 LruCache[2_table] open! Max_size[7783], max_overflow[409]
INFO 2022-08-09 02:26:47,108 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=8692,use_cell_num_=0
INFO 2022-08-09 02:26:47,108 lru_cache.h:341 LruCache[2_table_str] open! Max_size[7783], max_overflow[409]
INFO 2022-08-09 02:26:47,108 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=8692,use_cell_num_=0INFO 2022-08-09 02:26:47,108 lru_cache.h:341 LruCache[2_table_str] open! Max_size[7783], max_overflow[409]INFO 2022-08-09 02:26:47,108 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=8692,use_cell_num_=0INFO 2022-08-09 02:26:47,109 block.cc:30 Block[2_table_0] info, per_block_size[65536] item_length[32] header_size[30] seg_block_capacity[400000]INFO 2022-08-09 02:26:47,109 block.cc:30 Block[2_table_str_0] info, per_block_size[65536] item_length[65536] header_size[30] seg_block_capacity[400000]
INFO 2022-08-09 02:26:47,122 storage_manager.cc:169 load storage[2_table] success! options={segment_size=500000, fixed_value_bytes=32, seg_block_capacity=400000}, segment num=1
INFO 2022-08-09 02:26:47,122 storage_manager.cc:146 init storage[2_table] success! options={segment_size=500000, fixed_value_bytes=32, seg_block_capacity=400000}, segment num=1
INFO 2022-08-09 02:26:47,123 table.cc:147 init storageManager success! vector byte size=32, path=/export/vdb/baud/datas/data/2/table
INFO 2022-08-09 02:26:47,123 gamma_engine.cc:1310 Add range field [face]INFO 2022-08-09 02:26:47,397 gamma_engine.cc:1310 Add range field [group]
INFO 2022-08-09 02:26:47,498 gamma_engine.cc:1310 Add range field [image_url]INFO 2022-08-09 02:26:47,757 gamma_engine.cc:619 Load bitmap success.
INFO 2022-08-09 02:26:47,757 gamma_engine.cc:625 create table [2] success!INFO 2022-08-09 02:26:47,766 table.cc:630 read doc_num=1841 in table storage_mgr.
INFO 2022-08-09 02:26:47,766 mmap_raw_vector_io.cc:32 Mmap_raw_vector storage_mgr_ vec_num=1841INFO 2022-08-09 02:26:47,766 storage_manager.cc:387 Storage[feature] truncate to size=1841, current segment num=1, last offset=1841INFO 2022-08-09 02:26:47,774 mmap_raw_vector_io.cc:58 mmap load success! vec num=1841
INFO 2022-08-09 02:26:47,774 vector_manager.cc:739 vector [feature] load success!
INFO 2022-08-09 02:26:47,774 vector_manager.cc:761 vector_mgr load vec_num=1841
INFO 2022-08-09 02:26:47,774 storage_manager.cc:387 Storage[2_table] truncate to size=1841, current segment num=1, last offset=1841
INFO 2022-08-09 02:26:47,774 table.cc:55 Load doc_num [1841] truncate to [1841]
INFO 2022-08-09 02:26:47,782 table.cc:83 Table load successed! doc num [1841]
INFO 2022-08-09 02:26:47,783 gamma_engine.cc:1271 Begin indexing. indexing_size=1
INFO 2022-08-09 02:26:47,783 gamma_engine.cc:1283 load engine success! max docid=1841, load directory=, clean directorys(not done)=[]
INFO 2022-08-09 02:26:47,783 gamma_engine.cc:1019 vector manager indexing success!ERROR 2022-08-09 02:27:16,389 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:27:16,389 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string111INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string111INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string111INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string1
INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0ERROR 2022-08-09 02:27:16,390 field_range_index.cc:787 find node failed, key=string1
INFO 2022-08-09 02:27:16,390 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0INFO 2022-08-09 02:32:45,913 gamma_api.cc:88 Version [[sha1]:ab7ea75 [author]:zhanchao1 [time]:2021-11-24 02:46:24 +0000 [branch]: (HEAD, origin/master, origin/HEAD, master)]INFO 2022-08-09 02:32:45,915 bitmap_manager.cc:90 open bitmap file[/export/vdb/baud/datas/data/2/bitmap] success.
INFO 2022-08-09 02:32:45,915 bitmap_manager.cc:73 BitmapManager init successed. bytes_count=156251 bit_size=1250000
INFO 2022-08-09 02:32:45,929 table.cc:40 Table created success!INFO 2022-08-09 02:32:45,929 gamma_engine.cc:281 GammaEngine setup successed! bitmap_bytes_size=156251
INFO 2022-08-09 02:32:45,930 gamma_engine.cc:163 memory trim thread start......INFO 2022-08-09 02:32:45,964 gamma_engine.cc:81 System info: threads_max [2056664] max_map_count [262144] pid_max[65535]INFO 2022-08-09 02:32:45,965 gamma_engine.cc:88 max_threads [65535] concurrent_threshold [1927]
INFO 2022-08-09 02:32:45,965 gamma_api.cc:52 Engine init successed!
INFO 2022-08-09 02:32:45,967 vector_manager.cc:119 store params={"cache_size":1024,"segment_size":500000,"compress":{}}INFO 2022-08-09 02:32:45,967 vector_manager.cc:126 after merge, store parameters [{"cache_size":1024,"segment_size":500000,"compress":{}}]
INFO 2022-08-09 02:32:45,967 vector_manager.cc:137 create raw vector success, vec_name[feature] store_type[MemoryOnly]
INFO 2022-08-09 02:32:45,968 memory_raw_vector.cc:124 extend segment sucess! nsegments=1INFO 2022-08-09 02:32:45,968 memory_raw_vector.cc:42 init success, segment_size=500000
INFO 2022-08-09 02:32:45,968 memory_raw_vector.cc:75 store_params_.compress.IsEmpty() is true, not use zfpINFO 2022-08-09 02:32:45,968 storage_manager.cc:102 Storage[feature]. lrucache cache_size[1024M], string lrucachecache_size[0M]
INFO 2022-08-09 02:32:45,968 lru_cache.h:341 LruCache[feature] open! Max_size[15565], max_overflow[819]
INFO 2022-08-09 02:32:45,968 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=16884,use_cell_num_=0
INFO 2022-08-09 02:32:45,968 lru_cache.h:341 LruCache[feature] open! Max_size[15565], max_overflow[819]INFO 2022-08-09 02:32:45,968 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=16884,use_cell_num_=0INFO 2022-08-09 02:32:45,969 block.cc:30 Block[feature_0] info, per_block_size[65536] item_length[1024] header_size[30] seg_block_capacity[2000000]INFO 2022-08-09 02:32:45,969 storage_manager.cc:169 load storage[feature] success! options={segment_size=500000, fixed_value_bytes=1024, seg_block_capacity=2000000}, segment num=1INFO 2022-08-09 02:32:45,969 storage_manager.cc:146 init storage[feature] success! options={segment_size=500000, fixed_value_bytes=1024, seg_block_capacity=2000000}, segment num=1INFO 2022-08-09 02:32:45,969 memory_raw_vector.cc:84 init mmap raw vector success! vector byte size=1024, path=/export/vdb/baud/datas/data/2/vectors/featureINFO 2022-08-09 02:32:45,969 raw_vector.cc:87 raw vector init success! name=feature, has source=0, multi_vids=0, vector_byte_size=1024, dimension=256, compress={}INFO 2022-08-09 02:32:45,969 vector_manager.cc:163 Create index model [HNSW]INFO 2022-08-09 02:32:45,969 gamma_index_hnswlib.cc:138 nlinks =38, efConstruction =380, metric_type =1INFO 2022-08-09 02:32:46,000 vector_manager.cc:198 create vectors and indexes success! models=[HNSW]
INFO 2022-08-09 02:32:46,000 table.cc:103 Table compress [0]INFO 2022-08-09 02:32:46,000 table.cc:110 Add field name [_id], type [4], index [0]
INFO 2022-08-09 02:32:46,000 table.cc:110 Add field name [image_url], type [4], index [1]INFO 2022-08-09 02:32:46,000 table.cc:110 Add field name [group], type [4], index [1]
INFO 2022-08-09 02:32:46,000 table.cc:110 Add field name [face], type [4], index [1]INFO 2022-08-09 02:32:46,000 table.cc:129 Create table 2 success! item length=32, field num=4INFO 2022-08-09 02:32:46,000 storage_manager.cc:102 Storage[2_table]. lrucache cache_size[512M], string lrucache cache_size[512M]
INFO 2022-08-09 02:32:46,000 lru_cache.h:341 LruCache[2_table] open! Max_size[7783], max_overflow[409]
INFO 2022-08-09 02:32:46,000 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=8692,use_cell_num_=0INFO 2022-08-09 02:32:46,000 lru_cache.h:341 LruCache[2_table_str] open! Max_size[7783], max_overflow[409]INFO 2022-08-09 02:32:46,000 lru_cache.h:194 MemoryPool info, cell_size_=65536,max_cell_num_=8692,use_cell_num_=0INFO 2022-08-09 02:32:46,001 block.cc:30 Block[2_table_0] info, per_block_size[65536] item_length[32] header_size[30] seg_block_capacity[400000]INFO 2022-08-09 02:32:46,001 block.cc:30 Block[2_table_str_0] info, per_block_size[65536] item_length[65536] header_size[30] seg_block_capacity[400000]INFO 2022-08-09 02:32:46,002 storage_manager.cc:169 load storage[2_table] success! options={segment_size=500000, fixed_value_bytes=32, seg_block_capacity=400000}, segment num=1INFO 2022-08-09 02:32:46,002 storage_manager.cc:146 init storage[2_table] success! options={segment_size=500000, fixed_value_bytes=32, seg_block_capacity=400000}, segment num=1
INFO 2022-08-09 02:32:46,002 table.cc:147 init storageManager success! vector byte size=32, path=/export/vdb/baud/datas/data/2/table
INFO 2022-08-09 02:32:46,002 storage_manager.cc:146 init storage[2_table] success! options={segment_size=500000, fixed_value_bytes=32, seg_block_capacity=400000}, segment num=1
INFO 2022-08-09 02:32:46,002 table.cc:147 init storageManager success! vector byte size=32, path=/export/vdb/baud/datas/data/2/table
INFO 2022-08-09 02:32:46,003 gamma_engine.cc:1310 Add range field [face]
INFO 2022-08-09 02:32:46,125 gamma_engine.cc:1310 Add range field [group]
INFO 2022-08-09 02:32:46,225 gamma_engine.cc:1310 Add range field [image_url]
INFO 2022-08-09 02:32:46,367 gamma_engine.cc:619 Load bitmap success.
INFO 2022-08-09 02:32:46,367 gamma_engine.cc:625 create table [2] success!
INFO 2022-08-09 02:32:46,385 table.cc:630 read doc_num=1841 in table storage_mgr.
INFO 2022-08-09 02:32:46,385 mmap_raw_vector_io.cc:32 Mmap_raw_vector storage_mgr_ vec_num=1841
INFO 2022-08-09 02:32:46,385 storage_manager.cc:387 Storage[feature] truncate to size=1841, current segment num=1, last offset=1841
INFO 2022-08-09 02:32:46,393 mmap_raw_vector_io.cc:58 mmap load success! vec num=1841
INFO 2022-08-09 02:32:46,393 vector_manager.cc:739 vector [feature] load success!
INFO 2022-08-09 02:32:46,393 vector_manager.cc:761 vector_mgr load vec_num=1841
INFO 2022-08-09 02:32:46,393 storage_manager.cc:387 Storage[2_table] truncate to size=1841, current segment num=1, last offset=1841
INFO 2022-08-09 02:32:46,393 table.cc:55 Load doc_num [1841] truncate to [1841]
INFO 2022-08-09 02:32:46,413 table.cc:83 Table load successed! doc num [1841]
INFO 2022-08-09 02:32:46,414 gamma_engine.cc:1271 Begin indexing. indexing_size=1
INFO 2022-08-09 02:32:46,414 gamma_engine.cc:1283 load engine success! max docid=1841, load directory=, clean directorys(not done)=[]
INFO 2022-08-09 02:32:46,414 gamma_engine.cc:1019 vector manager indexing success!
ERROR 2022-08-09 02:33:14,453 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:33:14,453 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:33:14,453 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:33:14,453 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:33:14,453 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:33:14,453 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:33:14,454 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:33:14,454 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:33:14,454 field_range_index.cc:787 find node failed, key=string1
INFO 2022-08-09 02:33:14,454 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:33:14,454 field_range_index.cc:787 find node failed, key=string111
INFO 2022-08-09 02:33:14,454 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0
ERROR 2022-08-09 02:33:14,454 field_range_index.cc:787 find node failed, key=string1
INFO 2022-08-09 02:33:14,454 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0ERROR 2022-08-09 02:33:14,454 field_range_index.cc:787 find node failed, key=string1
INFO 2022-08-09 02:33:14,454 gamma_engine.cc:944 DelDocByFilter(), Delete doc num: 0

**Comment by hanqiushi** [comment]
"partition_infos": [
      {
        "pid": 2,
        "doc_num": 1841,
        "size": 270387,
        "path": "/export/vdb/baud/datas/",
        "status": 3,
        "raft_status": {
          "ID": 2,
          "NodeID": 2,
          "Leader": 0,
          "Term": 172854,
          "Index": 1849,
          "Commit": 1849,
          "Applied": 1849,
          "Vote": 2,
          "PendQueue": 0,
          "RecvQueue": 0,
          "AppQueue": 0,
          "Stopped": false,
          "RestoringSnapshot": false,
          "State": "StateCandidate",
          "Replicas": {}
        },
        "index_status": 2
      }
    ]
从stats看，应该是leader没选举出来，states=3只读状态，所以写入失败

**Comment by hanqiushi** [comment]
@wxingda 手动把data/raft路径下的文件删除，再次重启所有ps节点ok了，这个说明raft的文件有损坏么？

**Comment by guotf520** [comment]
我遇到的问题和你完全一样，partition leader一直选举不出来，有技术群吗？

**Comment by wxingda** [comment]
该问题已解决https://github.com/vearch/vearch/pull/724
