### ISSUE TITLE
is_brute_search适用范围

### ISSUE THREAD

**Issue by hanqiushi** [vearch/vearch#663]
请教个问题，如果想使用hnsw或其他非flat类型进行搜索，在size达到index_size之前，要如何搜索才能避免值为空？
本地使用is_brute_force参数在hnsw和scann类型进行测试，搜索结果为空值

例子：scann
建表参数：
"engine": {
        "name": "gamma",
        "index_size": 100000,
        "id_type": "String",
        "retrieval_type": "VEARCH",
        "retrieval_param": {
            "metric_type": "L2",
            "ncentroids": 1536,
            "nsubvector": 128,
            "reordering": true,
            "thread_num": 1
        }
    }

搜索条件：
{"query":{"sum":[{"field":"feature","feature":[-0.080631666,-0.08774832,-0.037647087,-0.03907042,-0.031206518,-0.03561884,0.01942846,-0.029534105,-0.03309243,-0.019997792,-0.03266543,-0.0493184,0.0038785753,0.022399662,-0.033234764,-0.069494106,-0.012649849,-0.015318593,0.100700624,0.10717678,-0.038287587,0.022239538,0.08853115,0.061487872,-0.08312249,0.12518191,-0.022630954,0.10803077,0.00036917633,-0.0015300802,-0.054228887,-0.005622155,0.0397465,0.019997792,-0.060206875,0.112443104,-0.08468816,0.005764488,0.072447516,0.026616279,-0.0990638,-0.046258237,-0.0074413493,0.1445392,0.010176812,0.073870845,0.05764488,0.18161696,0.036472842,-0.003914159,-0.049069315,0.05885471,0.1294519,0.00797065,0.0103903115,-0.018610045,-0.04269991,-0.06572228,-0.0059957793,0.032274015,0.0076148175,0.048926983,-0.03405318,-0.080774,-0.09329931,-0.033661764,0.031384435,0.04312691,-0.011564559,-0.1787703,-0.048749067,0.062377453,-0.07920834,-0.04049375,0.092943475,0.0056577385,-0.04084958,-0.028039608,0.13044824,-0.0007116652,0.01113756,0.070241354,0.043980908,-0.12190825,0.025744488,0.039710917,-0.019250544,0.002544203,0.07084627,0.041561246,0.037042174,-0.088388816,0.0066629653,-0.11407993,-0.0104614785,-0.015087302,0.06970761,0.041561246,0.039248336,-0.0809875,0.02172358,-0.038963668,-0.04746807,-0.020602707,-0.072767764,0.0051106457,0.07145119,-0.04504841,-0.12055609,-0.05771605,-0.13799188,0.0027754942,0.023822993,0.055047303,0.13607039,0.02149229,-0.00960748,-0.09465147,-0.01473147,-0.0146603035,0.04882023,-0.070668355,-0.04355391,-0.057893965,0.11849225,-0.035761178,-0.09002565,-0.0038785753,0.04924723,0.03960417,0.07621934,0.004519074,0.04988773,-0.011537872,-0.06735911,-0.023413785,-0.11614376,-0.025477614,-0.004376741,-0.03810967,0.04903373,-0.050243564,-0.015229635,0.07899484,0.15941301,-0.040778417,0.011955976,-0.026011363,0.004092075,0.0072234017,0.003558326,0.03362618,0.06305353,0.062911205,-0.019286128,0.014802637,0.014482386,-0.023716243,0.018076297,-0.11002344,0.010746145,0.058000714,0.10546878,-0.0809875,0.0016368299,0.049816564,-0.09216064,-0.050065648,0.06284004,0.014126554,0.11087744,-0.07444018,0.037398007,-0.049603064,0.07750034,-0.03864342,-0.07002786,-0.01266764,0.18844895,0.011030811,-0.07992,-0.018343171,0.058498878,0.0060491543,-0.06899594,-0.016973214,-0.079066,-0.0044834907,0.008824648,-0.005586572,-0.02149229,0.089740984,0.052449726,0.014126554,-0.04277108,0.028626733,0.015576572,-0.112443104,0.10134112,-0.02410766,-0.13920172,-0.057395797,-0.019713126,-0.06597137,0.10959644,-0.016697444,-0.18560228,0.048962567,0.00010674978,0.08255316,-0.02063829,-0.04113425,-0.13422006,0.010336937,0.01715113,0.037291255,-0.10774611,0.025619946,-0.033982012,0.0567553,0.06113204,0.04334041,0.024943866,-0.02554878,-0.018965878,-0.009927729,0.0406005,-0.066113696,0.063587286,0.021563455,-0.040991917,-0.10233746,-0.010354728,0.021527871,-0.009500731,0.100273624,-0.013521639,-0.010621603,0.08490166,0.031597935,0.028680107,0.078852504,-0.06348053,0.04355391,-0.05796513,-0.017346838,0.011066394,0.031935975,-0.034017596,-0.0008362066,-0.022915618,-0.028146358,-0.008504399,0.026046947,-0.09991779,-0.055865716],"min_score":0,"max_score":10000,"boost":1}]},"retrieval_param":{"nprobe": 512,"metric_type":"L2"},"is_brute_search":1,"size":5,"online_log_level": "debug"}

**Comment by hanqiushi** [comment]
对应的 gamma log
ERROR 2022-08-12 07:17:58,422 vector_manager.cc:495 faild search of query feature_VEARCH

**Comment by zcdb** [comment]
index_size对应的索引训练的阈值，即插入的数据量到达index_size开始训练，训练完才能构建索引进行索引。对于scann是需要训练的，hnsw是无需训练可以直接开始构建索引，所以对于hnsw来说，index_size设置1即可

**Comment by hanqiushi** [comment]
> index_size对应的索引训练的阈值，即插入的数据量到达index_size开始训练，训练完才能构建索引进行索引。对于scann是需要训练的，hnsw是无需训练可以直接开始构建索引，所以对于hnsw来说，index_size设置1即可

明白了。比如针对需要进行训练的类型，我这边用hnsw试验，vearch 3.2.7官方镜
建表参数：
{
    "name": "ts_space_1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 5,
        "retrieval_type": "HNSW",
        "retrieval_param": {
            "metric_type": "L2",
            "nlinks": 38,
            "efConstruction": 380,
            "efSearch": 280
        },
        "id_type": "String"
    },
    "properties": {
        "feature": {
            "dimension": 256,
            "type": "vector"
        },
        "image_url": {
            "index": true,
            "type": "string"
        },
        "face": {
            "index": true,
            "type": "string"
        },
        "group": {
            "type": "string",
            "array": true,
            "index": true
        }
    }
}
index_size设置为5，只插入一条数据，使用如下搜索条件(搜索向量与插入的向量相同)
{"query":{"sum":[{"field":"feature","feature":[-0.080631666,-0.08774832,-0.037647087,-0.03907042,-0.031206518,-0.03561884,0.01942846,-0.029534105,-0.03309243,-0.019997792,-0.03266543,-0.0493184,0.0038785753,0.022399662,-0.033234764,-0.069494106,-0.012649849,-0.015318593,0.100700624,0.10717678,-0.038287587,0.022239538,0.08853115,0.061487872,-0.08312249,0.12518191,-0.022630954,0.10803077,3.6917633E-4,-0.0015300802,-0.054228887,-0.005622155,0.0397465,0.019997792,-0.060206875,0.112443104,-0.08468816,0.005764488,0.072447516,0.026616279,-0.0990638,-0.046258237,-0.0074413493,0.1445392,0.010176812,0.073870845,0.05764488,0.18161696,0.036472842,-0.003914159,-0.049069315,0.05885471,0.1294519,0.00797065,0.0103903115,-0.018610045,-0.04269991,-0.06572228,-0.0059957793,0.032274015,0.0076148175,0.048926983,-0.03405318,-0.080774,-0.09329931,-0.033661764,0.031384435,0.04312691,-0.011564559,-0.1787703,-0.048749067,0.062377453,-0.07920834,-0.04049375,0.092943475,0.0056577385,-0.04084958,-0.028039608,0.13044824,-7.116652E-4,0.01113756,0.070241354,0.043980908,-0.12190825,0.025744488,0.039710917,-0.019250544,0.002544203,0.07084627,0.041561246,0.037042174,-0.088388816,0.0066629653,-0.11407993,-0.0104614785,-0.015087302,0.06970761,0.041561246,0.039248336,-0.0809875,0.02172358,-0.038963668,-0.04746807,-0.020602707,-0.072767764,0.0051106457,0.07145119,-0.04504841,-0.12055609,-0.05771605,-0.13799188,0.0027754942,0.023822993,0.055047303,0.13607039,0.02149229,-0.00960748,-0.09465147,-0.01473147,-0.0146603035,0.04882023,-0.070668355,-0.04355391,-0.057893965,0.11849225,-0.035761178,-0.09002565,-0.0038785753,0.04924723,0.03960417,0.07621934,0.004519074,0.04988773,-0.011537872,-0.06735911,-0.023413785,-0.11614376,-0.025477614,-0.004376741,-0.03810967,0.04903373,-0.050243564,-0.015229635,0.07899484,0.15941301,-0.040778417,0.011955976,-0.026011363,0.004092075,0.0072234017,0.003558326,0.03362618,0.06305353,0.062911205,-0.019286128,0.014802637,0.014482386,-0.023716243,0.018076297,-0.11002344,0.010746145,0.058000714,0.10546878,-0.0809875,0.0016368299,0.049816564,-0.09216064,-0.050065648,0.06284004,0.014126554,0.11087744,-0.07444018,0.037398007,-0.049603064,0.07750034,-0.03864342,-0.07002786,-0.01266764,0.18844895,0.011030811,-0.07992,-0.018343171,0.058498878,0.0060491543,-0.06899594,-0.016973214,-0.079066,-0.0044834907,0.008824648,-0.005586572,-0.02149229,0.089740984,0.052449726,0.014126554,-0.04277108,0.028626733,0.015576572,-0.112443104,0.10134112,-0.02410766,-0.13920172,-0.057395797,-0.019713126,-0.06597137,0.10959644,-0.016697444,-0.18560228,0.048962567,1.0674978E-4,0.08255316,-0.02063829,-0.04113425,-0.13422006,0.010336937,0.01715113,0.037291255,-0.10774611,0.025619946,-0.033982012,0.0567553,0.06113204,0.04334041,0.024943866,-0.02554878,-0.018965878,-0.009927729,0.0406005,-0.066113696,0.063587286,0.021563455,-0.040991917,-0.10233746,-0.010354728,0.021527871,-0.009500731,0.100273624,-0.013521639,-0.010621603,0.08490166,0.031597935,0.028680107,0.078852504,-0.06348053,0.04355391,-0.05796513,-0.017346838,0.011066394,0.031935975,-0.034017596,-8.362066E-4,-0.022915618,-0.028146358,-0.008504399,0.026046947,-0.09991779,-0.055865716],"min_score":-10000,"max_score":11111.0,"boost":1.0}],"filter":[{"term":{"group":["101"],"operator":"or"}}]},"retrieval_param":{"metric_type":"L2"},"is_brute_search":1,"size":5}
搜索结果为空：
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1
    },
    "hits": {
        "total": 0,
        "max_score": -1
    }
}
当我把搜索条件中的向量去掉，换成
{"query":{"filter":[{"term":{"group":["101"],"operator":"or"}}]},"retrieval_param":{"metric_type":"L2"},"is_brute_search":1,"size":5}
就可以搜索出来刚插入的一条数据了

是因为我搜索向量的方式不对么？

**Comment by hanqiushi** [comment]
插入语句参数：
{"index": {"_id": ""}}
{"face":"Jiangsl","feature":{"feature":[-0.080631666,-0.08774832,-0.037647087,-0.03907042,-0.031206518,-0.03561884,0.01942846,-0.029534105,-0.03309243,-0.019997792,-0.03266543,-0.0493184,0.0038785753,0.022399662,-0.033234764,-0.069494106,-0.012649849,-0.015318593,0.100700624,0.10717678,-0.038287587,0.022239538,0.08853115,0.061487872,-0.08312249,0.12518191,-0.022630954,0.10803077,3.6917633E-4,-0.0015300802,-0.054228887,-0.005622155,0.0397465,0.019997792,-0.060206875,0.112443104,-0.08468816,0.005764488,0.072447516,0.026616279,-0.0990638,-0.046258237,-0.0074413493,0.1445392,0.010176812,0.073870845,0.05764488,0.18161696,0.036472842,-0.003914159,-0.049069315,0.05885471,0.1294519,0.00797065,0.0103903115,-0.018610045,-0.04269991,-0.06572228,-0.0059957793,0.032274015,0.0076148175,0.048926983,-0.03405318,-0.080774,-0.09329931,-0.033661764,0.031384435,0.04312691,-0.011564559,-0.1787703,-0.048749067,0.062377453,-0.07920834,-0.04049375,0.092943475,0.0056577385,-0.04084958,-0.028039608,0.13044824,-7.116652E-4,0.01113756,0.070241354,0.043980908,-0.12190825,0.025744488,0.039710917,-0.019250544,0.002544203,0.07084627,0.041561246,0.037042174,-0.088388816,0.0066629653,-0.11407993,-0.0104614785,-0.015087302,0.06970761,0.041561246,0.039248336,-0.0809875,0.02172358,-0.038963668,-0.04746807,-0.020602707,-0.072767764,0.0051106457,0.07145119,-0.04504841,-0.12055609,-0.05771605,-0.13799188,0.0027754942,0.023822993,0.055047303,0.13607039,0.02149229,-0.00960748,-0.09465147,-0.01473147,-0.0146603035,0.04882023,-0.070668355,-0.04355391,-0.057893965,0.11849225,-0.035761178,-0.09002565,-0.0038785753,0.04924723,0.03960417,0.07621934,0.004519074,0.04988773,-0.011537872,-0.06735911,-0.023413785,-0.11614376,-0.025477614,-0.004376741,-0.03810967,0.04903373,-0.050243564,-0.015229635,0.07899484,0.15941301,-0.040778417,0.011955976,-0.026011363,0.004092075,0.0072234017,0.003558326,0.03362618,0.06305353,0.062911205,-0.019286128,0.014802637,0.014482386,-0.023716243,0.018076297,-0.11002344,0.010746145,0.058000714,0.10546878,-0.0809875,0.0016368299,0.049816564,-0.09216064,-0.050065648,0.06284004,0.014126554,0.11087744,-0.07444018,0.037398007,-0.049603064,0.07750034,-0.03864342,-0.07002786,-0.01266764,0.18844895,0.011030811,-0.07992,-0.018343171,0.058498878,0.0060491543,-0.06899594,-0.016973214,-0.079066,-0.0044834907,0.008824648,-0.005586572,-0.02149229,0.089740984,0.052449726,0.014126554,-0.04277108,0.028626733,0.015576572,-0.112443104,0.10134112,-0.02410766,-0.13920172,-0.057395797,-0.019713126,-0.06597137,0.10959644,-0.016697444,-0.18560228,0.048962567,1.0674978E-4,0.08255316,-0.02063829,-0.04113425,-0.13422006,0.010336937,0.01715113,0.037291255,-0.10774611,0.025619946,-0.033982012,0.0567553,0.06113204,0.04334041,0.024943866,-0.02554878,-0.018965878,-0.009927729,0.0406005,-0.066113696,0.063587286,0.021563455,-0.040991917,-0.10233746,-0.010354728,0.021527871,-0.009500731,0.100273624,-0.013521639,-0.010621603,0.08490166,0.031597935,0.028680107,0.078852504,-0.06348053,0.04355391,-0.05796513,-0.017346838,0.011066394,0.031935975,-0.034017596,-8.362066E-4,-0.022915618,-0.028146358,-0.008504399,0.026046947,-0.09991779,-0.055865716]},"group":["101"],"image_url":"Jiangsl-04425c90af6a4833b070255f8b32eb72.jpg"}

**Comment by zcdb** [comment]
index_size设置成5，但是只插入一条数据，这样是没有开始构建索引的，搜索语句中有向量会走索引进行检索，因此无结果，index_size改成1吧。而只使用term数值过滤检索就不会走索引，因此有结果。

**Comment by hanqiushi** [comment]
> index_size设置成5，但是只插入一条数据，这样是没有开始构建索引的，搜索语句中有向量会走索引进行检索，因此无结果，index_size改成1吧。而只使用term数值过滤检索就不会走索引，因此有结果。

明白了。对于其他索引类型也是一样的，对吧

**Comment by zcdb** [comment]
是的，但是对于ivfpq索引，我们支持了is_brute_search选项，也就是索引训练期间会通过flat方式进行搜索，其他的索引目前没有支持is_brute_search

**Comment by hanqiushi** [comment]
> 是的，但是对于ivfpq索引，我们支持了is_brute_search选项，也就是索引训练期间会通过flat方式进行搜索，其他的索引目前没有支持is_brute_search

明白了，多谢您的解答
