### ISSUE TITLE
集群重启后所有partition都无法选出leader

### ISSUE THREAD

**Issue by guotf520** [vearch/vearch#667]
集群使用3.2.8版本，3个节点，部署了3个master、router、ps。
ps进程容易因为各种原因挂掉，导致需要重启集群，但是重启后ps进程能正常启动，但是一直选择不出partition的leader，导致集群不可用。每个节点都发送了投票请求，但是都收不到其他节点的请求。
log: get Replicate connection failed,cannot get node network information, nodeID=[2]
get Replicate connection failed,cannot get node network information, nodeID=[2]
get Replicate connection failed,cannot get node network information, nodeID=[3]
get Replicate connection failed,cannot get node network information, nodeID=[3]

**Comment by guotf520** [comment]
建表语句：
{"name": space,  "partition_num": 5, "replica_num": 3,
                "engine": {
                    "name": "gamma",
                    "index_size": 10000,
                    "id_type": "Long",
                    "retrieval_type": "IVFPQ",
                    "retrieval_param": {
                        "metric_type": "InnerProduct",
                        "ncentroids": 512,
                        "nsubvector": 64
                    }
            },
            "properties": {
                "id_no": {"type": "string", "index":True},
                "timestamp": {"type": "string", "index":True},
                "datetime": {"type": "integer", "index": True},
                "img_feature": {"type": "vector", "dimension":4096, "store_type": "RocksDB",
                    "store_param": {
                        "cache_size": 1024,
                        "compress": {"rate":16}
                }}}
            }


副本大于1时，集群重启必定无法选择出分区leader，导致集群一直不可用，只能删除数据才能启动。

**Comment by guotf520** [comment]
即使表里只写了几十条数据，重启集群都无法选出分区leader。有没有技术交流群，麻烦拉一下。

**Comment by Maslino** [comment]
ps重启后，IP变了吗

**Comment by guotf520** [comment]
IP没有变，vearch是源码编译版，集群 16核 64G内存，资源是充足的。

**Comment by guotf520** [comment]
这么明显的问题，没有人遇到过吗？

**Comment by wxingda** [comment]
该问题已修复https://github.com/vearch/vearch/pull/724
