### ISSUE TITLE
search 80 dimension vector cause program panic

### ISSUE THREAD

**Issue by zhyon404** [vearch/vearch#67]
create a space like.
```
		"vector": {
			"type": "vector",
			"model_id": "img",
			"dimension": 80,
			"format": "normalization"
		}
```
program panic during search. 64 or 128 dimension work fine.
are there some restrictions on vector dimensions？

**Comment by zhyon404** [comment]
great work btw

**Comment by wxingda** [comment]
Please provide space creation statement.

**Comment by zhyon404** [comment]
> Please provide space creation statement.

{
	"name": "test_sapce",
	"dynamic_schema": "strict",
	"partition_num": 1,
	"replica_num": 1,
	"engine": {
		"name": "gamma",
		"index_size": 9999,
		"max_size": 100000
	},
	"properties": {
		"string": {
			"type": "text",
			"index": "false"
		},
		"int2": {
			"type": "integer",
			"index": "true"
		},
		"int": {
			"type": "integer",
			"index": "true"
		},
		"vector": {
			"type": "vector",
			"dimension": 80,
			"model_id": "img",
			"format": "normalization"
		}
	},
	"models": [{
		"model_id": "img",
		"fields": ["string"],
		"out": "feature"
	}]
}
@wxingda

**Comment by wxingda** [comment]
Provide the _chubao-ps-startup.log_ on panic.

**Comment by zhyon404** [comment]
not sure where is it?

**Comment by ansjsun** [comment]
nohup file  or  log dir   gamna.log




On 12/23/2019 22:49, zhyon404 wrote:

not sure where is it?

**Comment by zhyon404** [comment]
[nohup.txt](https://github.com/vearch/vearch/files/3997054/nohup.txt)
[gamma.log](https://github.com/vearch/vearch/files/3997056/gamma.log)

**Comment by zzypeak** [comment]
i had encountered the same problem,  after read the source code, i found that the default value of subvector in gamma is 64, thus if the vector's dimension doesn't divide by 64, the gamma will automatic ly fill up to 128, but in the after search it crashed.

**Comment by wxingda** [comment]
I'm sorry for this problem, it is fixed in the lastest version.
