### ISSUE TITLE
多服务器docker容器互相访问

### ISSUE THREAD

**Issue by guotf520** [vearch/vearch#671]
计划在3台服务器上使用docker部署vearch，每台服务器都部署master router ps 容器，实现集群最终3个master，3个router，3个ps，master容器启动前需要指定ip，怎么实现多个服务器之间docker 容器互相访问？

**Comment by zcdb** [comment]
实际上可以先分配master容器，再启动vearch进程。master容器先起来了的话ip就知道了，这样config.toml就可以配置了，再启动vearch进程，弄一个辅助脚本应该就行了

**Comment by guotf520** [comment]
在一个服务器上是可以的，但是多个服务器之间的docker容器之间无法访问，容器的ip之间都可以互相ping通，但是端口就是拒绝访问。

**Comment by zcdb** [comment]
telnet 看看端口是不是通的吧，另外能贴一下启动日志吗
