### ISSUE TITLE
占据系统buffer缓存不释放

### ISSUE THREAD

**Issue by guotf520** [vearch/vearch#673]
![image](https://user-images.githubusercontent.com/111826752/187842726-31d10094-8d05-4639-9e74-8ee3d1bebeb9.png)

写数据时，buffer缓存持续攀升，不会释放，buffer缓存占满之后，PS进程就会挂掉，怎么调节内存问题。

**Comment by guotf520** [comment]
内存基本用完的时候，出现过异常，PS节点挂了，不确定和内存有没有直接关系。
![image](https://user-images.githubusercontent.com/111826752/188623615-de15fe96-2ff4-45de-aadc-b9e10f83f853.png)

**Comment by zcdb** [comment]
缓存都是能复用的，正常来说ps不会占住这么多缓存导致缓存无法释放的，建议还是控制内存的使用量

**Comment by guotf520** [comment]
能介绍一下vearch主要哪些数据占用内存吗？目前了解的是建表时cache大小、向量数据自动产生的索引、非向量字段索引数据会占用内存。

**Comment by zcdb** [comment]
看向量数据的存储类型，向量数据本身也有可能存储在内存，另外不仅仅非向量字段的索引数据在内存，非向量字段数据本身也是在内存里面的。如果数据量特别大的情况下，程序本身内部会有一些map也会占用一定内存

**Comment by guotf520** [comment]
建表的时候能不能给一些建议，比如非向量字段多的话会不会影响集群性能，等。

**Comment by guotf520** [comment]
建表的时候能不能给一些建议，比如非向量字段多的话会不会影响集群性能，等。

**Comment by zcdb** [comment]
非向量字段一般根据业务需要来设置，主要还是参考索引的性能来设置集群机器的规模，这个有一些评测和介绍：https://github.com/vearch/vearch/wiki 。一般而言可以根据自己业务场景先评估单节点性能，再根据业务场景需要比如QPS和tp的要求来设置集群的节点数
