### ISSUE TITLE
如何获取已入库的向量id

### ISSUE THREAD

**Issue by cyxu11** [vearch/vearch#682]
您好！由于入库数据没有离线存储，现在需要知道已入库向量有哪些，请问通过什么方法可以解析文件获取已入库的id？

**Comment by zcdb** [comment]
1、第一种方法可以参照gamma代码库里面的table.cc中Load函数来解析持久化的数据，即table目录里面的内容，这个里面有入库的id
2、gamma里面实际上还有GetDocByDocID接口，这个接口是按照下标（即0、1、2这种）来获取doc信息，但是此接口未暴露出来，可以参考gamma.go里面的GetDocByID接口，将此接口暴露出来，遍历所有partition每个partition再从0到max_docid-1即可

**Comment by cyxu11** [comment]
非常感谢您的回复！近期我会尝试这两种方案获取一下
