### ISSUE TITLE
Faiss已经升级到1.7.2

### ISSUE THREAD

**Issue by frederic89** [vearch/vearch#684]
Faiss已经升级到1.7.2，请问vearch内的编译脚本可自动安装最新的faiss吗？我使用了https://zhuanlan.zhihu.com/p/118640909
中提到的faiss版本（实际上是v1.6.3），不知道现在vearch安装faiss版本是最新的吗？

**Comment by zcdb** [comment]
vearch gamma最新版已经支持到1.7.1，faiss 1.7.1和1.7.2接口应该没啥变化，不过我们没有测试过1.7.2，使用最新代码暂时只能源码编译: https://github.com/vearch/gamma/commit/87cea14003136476e1d5446f469cfab32174fb08
