### ISSUE TITLE
docker安装的vearch,用pythonSDK无法连接

### ISSUE THREAD

**Issue by myboqin** [vearch/vearch#689]
Python 3.8.10 
vearch 3.2.8.3
ubuntu 20.04

运行下面代码
new_engine.py
import vearch

engine_path = "/root/test/db/"
max_doc_size = 100000
engine = vearch.Engine(engine_path, max_doc_size)
log_path = "/root/test/log"
engine.init_log_dir(log_path)

会报错
![image](https://user-images.githubusercontent.com/20401347/195756247-02748f28-969e-4b43-8fe0-9e07dfe255ab.png)

**Comment by zcdb** [comment]
https://github.com/vearch/vearch-python/blob/master/demos/basic_usage.py 可以参考这个使用方式，你那是之前版本的使用方式
