### ISSUE TITLE
同样的请求多次查询会出现结果不一致

### ISSUE THREAD

**Issue by gtf520** [vearch/vearch#691]
数据库的数据里静止的，用同样的向量多次查询会出现结果不一致的情况，偶尔也会出现查不到数据。表中有20万条数据。
表结果如下：
body = {"name": space,  # 不能以数字或下划线开头，尽量不使用特殊字符等
                "partition_num": partition_num,
                "replica_num": replica_num,
                "engine": {  # 引擎配置
                    "name": "gamma",  
                    "index_size": 10000,  
                    "id_type": "Long",  # 指定唯一记录主键类型，支持String和Long(定义为Long可节省内存占用)
                    "retrieval_type": "IVFPQ",  # 了解下这些算法？看看效果好或坏，受哪些影响？
                    "retrieval_param": {
                        "metric_type": "InnerProduct",  # 只支持：L2或者InnerProduct
                        "ncentroids": 512,  # 聚类中心数量
                        "nsubvector": 64  # PQ拆分子向量大小
                    }
                },
                "properties": {  # 空间配置，定义表字段及类型
                    "bot_id": {"type": "string", "index": True},  # 设置index，后面检索时，才可以通过该字段进行筛选
                    "standard_id": {"type": "string"},
                    "standard": {"type": "string"},
                    "sentence": {"type": "string"},
                    "sentence_feature": {"type": "vector",
                                         "dimension": 312,
                                         "store_type": "RocksDB",  # 固定不变
                                         "store_param": {
                                             "cache_size": 1024
                                         }
                                         }
                }
                }

查询语句：
body = {
            "query": {
                "sum": [{
                    "field": "img_feature",
                    "feature": feature,
                    "min_score": 0,
                    "boost": 1
                }]
                ,
                "filter":[{
                    "term":{
                        "bot_id":idno_list,
                        "operator":"or"
                    }
                }]
            },
            "retrieval_param": {
                "nprobe": 2048
            },
            "fields": ["standard_id"],
            "is_brute_search": 0,
            "online_log_level": "debug",
            "quick": False,
            "vector_value": False,
            "client_type": "random",
            "l2_sqrt": False,
            "size": 2
        }

麻烦帮忙看一下原因。

**Comment by zcdb** [comment]
是多副本的吗？

**Comment by gtf520** [comment]
是一个副本，is_brute_search设置为1时才不会出现这种情况，但是性能有些低。

**Comment by zcdb** [comment]
"dimension": 312
"nsubvector": 64，这个设置成312能整除的数，如果不能整除，内部会补0导致数据变形的

**Comment by zcdb** [comment]
另外"nprobe": 2048 这个最好设置的比ncentroids小，虽然代码会判断nprobe是否超过了ncentroids进行修正，但是这样设置意义就不是很明显了

**Comment by gtf520** [comment]
好的，我调整一下。
