### ISSUE TITLE
怎么判断一个索引字段的数据在表中是否存在？

### ISSUE THREAD

**Issue by guotf520** [vearch/vearch#692]
在日常业务使用中，会在vearch中存储向量和非向量字段，非向量字段配置index 为 True，怎么判断非向量字段数值为某个值得数据是否存在？
{"name": space,  "partition_num": partition_num, "replica_num": replica_num,
                "engine": {
                    "name": "gamma",
                    "index_size": 20000,
                    "id_type": "Long",
                    "retrieval_type": "IVFPQ",
                    "retrieval_param": {
                        "metric_type": "InnerProduct",
                        "ncentroids": 512,
                        "nsubvector": 64
                    }
            },
            "properties": {
                "mobile": {"type": "string", "index":True},
                "voice_feature": {"type": "vector", "dimension":192, "store_type": "RocksDB",
                    "store_param": {
                        "cache_size": 1024,
                        # "compress": {"rate":16}
                }}}
            }

例如这个表，除了存储向量还存储了mobile的字段，怎么判断mobile为某个值得数据在vearch中是否存在？

**Comment by zcdb** [comment]
可以试试搜索语句只使用filter字段
