### ISSUE TITLE
删除重建表，服务直接挂了

### ISSUE THREAD

**Issue by zs420803498** [vearch/vearch#698]
在删除重建表时，任务直接挂了，重启之后也直接挂，后面手动添加、删除一次表结构之后好了，请问是什么原因，以下是gdb日志
![image](https://user-images.githubusercontent.com/8529017/204948759-b1b31f33-cc29-4073-896d-d562e4c90e91.png)

**Comment by guotf520** [comment]
用的vearch哪个版本？

**Comment by zs420803498** [comment]
3.2.7

**Comment by zs420803498** [comment]
![image](https://user-images.githubusercontent.com/8529017/210308187-6a40d0f3-90ca-41ce-a455-a2a37c68d0a1.png)
![image](https://user-images.githubusercontent.com/8529017/210308245-0972a64f-f2fb-4ea2-b358-d93ea6aeba93.png)
![image](https://user-images.githubusercontent.com/8529017/210308535-07355d18-7a69-4e5a-9f81-72d999eb8039.png)
再次重现了

**Comment by wxingda** [comment]
已修复
https://github.com/vearch/vearch/commit/6dc2dd8ca38034cd9872015be13698e60c3fa4b1
https://github.com/vearch/vearch/commit/20502adc66bbf5b7c8f03e6988c654e0133090a9
