### ISSUE TITLE
分区副本为3，集群重启后分区无法选举出Leader

### ISSUE THREAD

**Issue by guotf520** [vearch/vearch#699]
vearch 集群采用 3.2.7 docker 版，集群有3个ps节点，创建表时制定3个分区，3个副本。
![image](https://user-images.githubusercontent.com/111826752/205025563-bb42a9cf-ce8b-409d-9774-d716ee1b96e9.png)

建表语句如下：
{"name": space,  "partition_num": 3, "replica_num": 3,
                "engine": {
                    "name": "gamma",
                    "index_size": 20000,
                    "id_type": "Long",
                    "retrieval_type": "IVFPQ",
                    "retrieval_param": {
                        "metric_type": "InnerProduct",
                        "ncentroids": 512,
                        "nsubvector": 39
                    }
                },
                "properties": {
                    "bot_id": {"type": "string", "index":True},
                    "standard_id": {"type": "string", "index":True},
                    "standard": {"type": "string", "index":True},
                    "sentence": {"type": "string","index":True},
                    "sentence_feature": {"type": "vector", "dimension":312, "store_type": "RocksDB",
                                         "store_param": {
                                             "cache_size": 1024
                                         }}}
                }

集群配置文件如下：
[global]
    # the name will validate join cluster by same name
    name = "zycfc-test"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    data = ["/data/vearch/data"]
    # log path , If you are in a production environment, You'd better set absolute paths
    log = "/data/vearch/logs"
    # default log type for any model
    level = "debug"
    # master <-> ps <-> router will use this key to send or receive data
    signkey = "vearch-ai"
    skip_auth = true
    # tell Vearch whether it should manage it's own instance of etcd or not
    # self_manage_etcd = false
    # automatically remove the failed node and recover when new nodes join
    # auto_recover_ps = false
    # support access etcd basic auth,depend on self_manage_etcd = true
    # support_etcd_auth = false
    # ensure leader-follow raft data synchronization is consistent
    raft_consistent = true

# if you are master, you'd better set all config for router、ps and router, ps use default config it so cool
[[masters]]
    # name machine name for cluster
    name = "m1"
    # ip or domain
    address = "172.17.0.2"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370
    pprof_port = 6062
    # monitor
    monitor_port = 8818

[router]
    # port for server
    port = 9001

[ps]
    # port for server
    rpc_port = 8082
    # raft config begin
    ps_heartbeat_timeout = 5 #seconds
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 2000 #ms
    raft_retain_logs = 200000000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1
    raft_truncate_count = 100000000
    #when behind leader this value,will stop the server for search
    raft_diff_count = 100000
    # engine config
    engine_dwpt_num = 8
    # max size byte
    # max_size = 50000000
    pprof_port = 6061
    # if set true , this ps only use in db meta config
    private = false
    # seconds
    flush_time_interval = 600
    flush_count_threshold = 10000

整个集群重启后，ps节点恢复，但是分区无法选举出Leader。
![image](https://user-images.githubusercontent.com/111826752/205024459-60d9d16b-1b72-41d1-9f1b-e9eda7064956.png)

ps节点日志：

[ps1.log](https://github.com/vearch/vearch/files/10131339/ps1.log)

导致该表无法正常写入数据。
![image](https://user-images.githubusercontent.com/111826752/205028344-15b6478d-330d-4455-b3d1-115aba820460.png)

经过多次验证，该问题必定会出现。

**Comment by kuailelijuan** [comment]
删除 data/vearch/data 下面的raft文件夹，再试试看

**Comment by guotf520** [comment]
删除data/vearch/data 下面的raft文件夹也没有用。

**Comment by wxingda** [comment]
[
  {
    "db_name": "test_vector_db",
    "space_num": 1,
    "doc_num": 0,
    "size": 805306848,
    "spaces": [
      {
        "size": 805306848,
        "partitions": [
          {
            "pid": 7,
            "size": 268435616,
            "replica_num": 3,
            "path": "/export/vdb/baud/datas/",
            "status": 3,
            "color": "green",
            "ip": "172.17.0.5",
            "node_id": 4,
            "raft_status": {
              "ID": 7,
              "NodeID": 4,
              "Leader": 0,
              "Term": 2,
              "Index": 1,
              "Commit": 1,
              "Applied": 1,
              "Vote": 4,
              "PendQueue": 0,
              "RecvQueue": 0,
              "AppQueue": 0,
              "Stopped": false,
              "RestoringSnapshot": false,
              "State": "StateCandidate",
              "Replicas": {}
            },
            "index_status": 0
          },
          {
            "pid": 8,
            "size": 268435616,
            "replica_num": 3,
            "path": "/export/vdb/baud/datas/",
            "status": 3,
            "color": "green",
            "ip": "172.17.0.4",
            "node_id": 3,
            "raft_status": {
              "ID": 8,
              "NodeID": 3,
              "Leader": 0,
              "Term": 3,
              "Index": 1,
              "Commit": 1,
              "Applied": 1,
              "Vote": 3,
              "PendQueue": 0,
              "RecvQueue": 0,
              "AppQueue": 0,
              "Stopped": false,
              "RestoringSnapshot": false,
              "State": "StateCandidate",
              "Replicas": {}
            },
            "index_status": 0
          },
          {
            "pid": 9,
            "size": 268435616,
            "replica_num": 3,
            "path": "/export/vdb/baud/datas/",
            "status": 3,
            "color": "green",
            "ip": "172.17.0.5",
            "node_id": 4,
            "raft_status": {
              "ID": 9,
              "NodeID": 4,
              "Leader": 0,
              "Term": 3,
              "Index": 1,
              "Commit": 1,
              "Applied": 1,
              "Vote": 4,
              "PendQueue": 0,
              "RecvQueue": 0,
              "AppQueue": 0,
              "Stopped": false,
              "RestoringSnapshot": false,
              "State": "StateCandidate",
              "Replicas": {}
            },
            "index_status": 0
          }
        ],
        "status": "green",
        "name": "space",
        "partition_num": 3,
        "replica_num": 9,
        "doc_num": 0
      }
    ],
    "status": "green",
    "errors": null
  }
]

我这边按照你的配置和建表语句，重启集群后，集群正常

**Comment by guotf520** [comment]
集群虽然正常，但是你看一下每个分区的Leader是0，说明分区leader没有选出来，你试试数据能不能写入。

**Comment by wxingda** [comment]
https://github.com/vearch/vearch/pull/724
