### ISSUE TITLE
PS进程重启后，该节点上所有Leader分区都查不到数据。

### ISSUE THREAD

**Issue by guotf520** [vearch/vearch#705]
docker 3.2.7 版本，不论部署多少个ps节点，在关闭ps节点之前，数据可以正常查询，只要把ps节点关闭再启动，表中Leader分区只要在这个ps节点，用向量进行检索时都查不到数据。

集群配置：
[global]
    # the name will validate join cluster by same name
    name = "zycfc-vearch02"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    data = ["/data/vearch/data"]
    # log path , If you are in a production environment, You'd better set absolute paths
    log = "/data/vearch/logs"
    # default log type for any model
    level = "debug"
    # master <-> ps <-> router will use this key to send or receive data
    signkey = "vearch-ai"
    skip_auth = true
    # tell Vearch whether it should manage it's own instance of etcd or not
    # self_manage_etcd = false
    # automatically remove the failed node and recover when new nodes join
    # auto_recover_ps = false
    # support access etcd basic auth,depend on self_manage_etcd = true
    # support_etcd_auth = false
    # ensure leader-follow raft data synchronization is consistent
    raft_consistent = true

# if you are master, you'd better set all config for router、ps and router, ps use default config it so cool
[[masters]]
    # name machine name for cluster
    name = "m1"
    # ip or domain
    address = "10.94.100.2"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370
    pprof_port = 6062
    # monitor
    monitor_port = 8818

[router]
    # port for server
    port = 9001

[ps]
    # port for server
    rpc_port = 8082
    # raft config begin
    ps_heartbeat_timeout = 5 #seconds
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 2000 #ms
    raft_retain_logs = 200000000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1
    raft_truncate_count = 100000000
    #when behind leader this value,will stop the server for search
    raft_diff_count = 100000
    # engine config
    engine_dwpt_num = 8
    # max size byte
    # max_size = 50000000
    pprof_port = 6061
    # if set true , this ps only use in db meta config
    private = false
    # seconds
    flush_time_interval = 600
    flush_count_threshold = 10000

建表语句：
{"name": test_robot,  "partition_num": 1, "replica_num": 1,
                "engine": {
                    "name": "gamma",
                    "index_size": 20000,
                    "id_type": "Long",
                    "retrieval_type": "IVFPQ",
                    "retrieval_param": {
                        "metric_type": "InnerProduct",
                        "ncentroids": 512,
                        "nsubvector": 39
                    }
            },
            "properties": {
                "bot_id": {"type": "string", "index":True},
                "standard_id": {"type": "string"},
                "standard": {"type": "string"},
                "sentence": {"type": "string"},
                "sentence_feature": {"type": "vector", "dimension":312, "store_type": "RocksDB",
                    "store_param": {
                        "cache_size": 1024,
                        # "compress": {"rate":16}
                }}}
            }

查询语句：
{
            "query": {
                "sum": [{
                    "field": "sentence_feature",
                    "feature": feature,
                    "min_score": 0.1,
                    "boost": 1
                }]
                ,
                "filter":[{
                    "term":{
                        "bot_id":idno_list,
                        "operator":"or"
                    }
                }]
            },
            "retrieval_param": {
                "nprobe": 256
            },
            "fields": ["bot_id","standard"],
            "is_brute_search": 1,
            "online_log_level": "debug",
            "quick": False,
            "vector_value": False,
            "client_type": "random",
            "l2_sqrt": False,
            "size": 2
        }

所有日志：

[vearch-logs.zip](https://github.com/vearch/vearch/files/10349109/vearch-logs.zip)

**Comment by wxingda** [comment]
可以在重启后执行`curl -XPOST {{ROUTER}}/test_vector_db/vector_space/_flush`
