### ISSUE TITLE
单节点重启疑问

### ISSUE THREAD

**Issue by hanqiushi** [vearch/vearch#708]
我这边通过k8s创建单节点部署，使用 vearch:3.2.7 镜像，创建表后插入1w+条数据，手动重启pod，发现启动后约15min才能正常提供服务，异常log如下：

ERROR 2023-03-16 03:20:36,101 server.go:202 to register master error, nodeId:[1], err : master server all down
ERROR 2023-03-16 03:20:40,122 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]
ERROR 2023-03-16 03:20:40,122 partition_service.go:120 partition recovery get server info err: ps_notexists
ERROR 2023-03-16 03:26:58,798 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]
ERROR 2023-03-16 03:28:45,097 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]
ERROR 2023-03-16 03:28:48,877 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]
ERROR 2023-03-16 03:30:30,127 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]
ERROR 2023-03-16 03:32:34,677 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]
ERROR 2023-03-16 03:32:37,186 master.go:135 server can not find on master, maybe server is offline, nodeId:[1]

之后leader选举后恢复正常
INFO 2023-03-16 03:20:34,094 config.go:355 master's name:[master1] master's domain:[127.0.0.1] and local master's ip:[127.0.0.1]
INFO 2023-03-16 03:20:34,096 config.go:362 found local master successfully :master's name:[master1] master's ip:[127.0.0.1] and local master's name:[]
INFO 2023-03-16 03:20:34,097 config.go:112 vearch etcd address is 127.0.0.1:2370
INFO 2023-03-16 03:20:34,098 config.go:112 vearch etcd address is 127.0.0.1:2370
INFO 2023-03-16 03:20:34,098 meta.go:62 Server load meta from file is: /export/vdb/baud/datas/server_meta.txt
INFO 2023-03-16 03:20:34,099 server.go:199 to register master, nodeId:[1], times : 0
INFO 2023-03-16 03:20:34,099 master_cache.go:419 to start cache job beginINFO 2023-03-16 03:20:38,102 server.go:199 to register master, nodeId:[1], times : 1
INFO 2023-03-16 03:20:38,825 server.go:84 Server is ready!INFO 2023-03-16 03:20:38,825 config.go:112 vearch etcd address is 127.0.0.1:2370
INFO 2023-03-16 03:20:38,826 monitor_service.go:60 ***************** skip register monitoring
INFO 2023-03-16 03:20:38,835 master_cache.go:569 cache inited ok use time 4.736006362s
INFO 2023-03-16 03:20:38,835 signals.go:48 Wait Signals...
INFO 2023-03-16 03:20:40,105 server.go:213 register master ok, nodeId:[1]
INFO 2023-03-16 03:20:40,166 gamma.go:93 to create table for gamma by path:[/export/vdb/baud/datas/data/2]
INFO 2023-03-16 03:20:40,189 gamma.go:100 to create table for gamma finish by path:[/export/vdb/baud/datas/data/2]
INFO 2023-03-16 03:20:40,189 gamma.go:104 creat table: ts_space_1 cost time :22.737143
(此处略去部分log)......
INFO 2023-03-16 03:31:48,836 schedule_job.go:74 Complete Walking Spaces!INFO 2023-03-16 03:31:48,836 schedule_job.go:84 Start Walking Servers!
INFO 2023-03-16 03:31:48,836 schedule_job.go:99 Complete Walking Servers!INFO 2023-03-16 03:32:49,834 schedule_job.go:35 Start Walking Partitions!
INFO 2023-03-16 03:32:49,834 schedule_job.go:57 Complete Walking Partitions!
INFO 2023-03-16 03:32:49,835 schedule_job.go:62 Start Walking Spaces!
INFO 2023-03-16 03:32:49,836 schedule_job.go:74 Complete Walking Spaces!
INFO 2023-03-16 03:32:49,836 schedule_job.go:84 Start Walking Servers!
INFO 2023-03-16 03:32:49,836 schedule_job.go:99 Complete Walking Servers!
INFO 2023-03-16 03:33:44,090 store_raft_job.go:55 start truncate job! truncate count: 1000000000
INFO 2023-03-16 03:33:44,091 server.go:143 vearch server successful startup...
INFO 2023-03-16 03:33:44,095 store_raft_job.go:121 start flush job, flush time interval=600, count threshold=200000, min index num=0, max docid=19278
INFO 2023-03-16 03:33:47,606 raft_state_machine.go:220 partition[2] change leader to 1
INFO 2023-03-16 03:33:47,606 server.go:185 startChangeLeaderC() receive an change leader event, nodeId: 1, partitionId: 2
INFO 2023-03-16 03:33:47,608 cluster_service.go:78 rigister parttion:[2]INFO 2023-03-16 03:33:50,833 schedule_job.go:35 Start Walking Partitions!
INFO 2023-03-16 03:33:50,834 schedule_job.go:57 Complete Walking Partitions!INFO 2023-03-16 03:33:50,835 schedule_job.go:62 Start Walking Spaces!
INFO 2023-03-16 03:33:50,835 schedule_job.go:74 Complete Walking Spaces!
INFO 2023-03-16 03:33:50,836 schedule_job.go:84 Start Walking Servers!
INFO 2023-03-16 03:33:50,836 schedule_job.go:99 Complete Walking Servers!
INFO 2023-03-16 03:34:51,834 schedule_job.go:35 Start Walking Partitions!
INFO 2023-03-16 03:34:51,835 schedule_job.go:57 Complete Walking Partitions!
INFO 2023-03-16 03:34:51,836 schedule_job.go:62 Start Walking Spaces!
INFO 2023-03-16 03:34:51,836 schedule_job.go:74 Complete Walking Spaces!
INFO 2023-03-16 03:34:51,837 schedule_job.go:84 Start Walking Servers!
INFO 2023-03-16 03:34:51,837 schedule_job.go:99 Complete Walking Servers!
INFO 2023-03-16 03:35:41,023 rpc_client.go:35 instance client by rpc 127.0.0.1:8081
INFO 2023-03-16 03:35:41,023 rpc_client.go:49 to instance client for server:[[127.0.0.1:8081]]
INFO 2023-03-16 03:35:52,834 schedule_job.go:35 Start Walking Partitions!
INFO 2023-03-16 03:35:52,835 schedule_job.go:57 Complete Walking Partitions!
INFO 2023-03-16 03:35:52,835 schedule_job.go:62 Start Walking Spaces!INFO 2023-03-16 03:35:52,836 schedule_job.go:74 Complete Walking Spaces!INFO 2023-03-16 03:35:52,836 schedule_job.go:84 Start Walking Servers!
INFO 2023-03-16 03:35:52,837 schedule_job.go:99 Complete Walking Servers!

还请帮忙分析下这个问题，按理说单节点启动的时候不应该花费这么长时间进行选举

下面是我pod的启动参数，多谢

command:
            - /vearch/vearch
            - '-conf'
            - /vearch/config.toml
            - all

**Comment by hanqiushi** [comment]
打开debug log重启，发现是ps启动时间比较长

DEBUG 2023-03-17 03:41:46,480 master.go:447 master api Register success
DEBUG 2023-03-17 03:41:46,481 partition_service.go:248 starting recover partition[2]...
DEBUG 2023-03-17 03:41:46,612 gamma.go:124 gamma use memory is:[156635]
DEBUG 2023-03-17 03:41:52,467 startup.go:113 mem.Alloc:17714672 mem.TotalAlloc:24667824 mem.HeapAlloc:17714672 mem.HeapSys:64651264 routing :110
DEBUG 2023-03-17 03:41:56,614 gamma.go:124 gamma use memory is:[291259]
DEBUG 2023-03-17 03:42:02,468 startup.go:113 mem.Alloc:18642112 mem.TotalAlloc:25595264 mem.HeapAlloc:18642112 mem.HeapSys:64651264 routing :110
DEBUG 2023-03-17 03:42:06,615 gamma.go:124 gamma use memory is:[291259]
DEBUG 2023-03-17 03:42:12,469 startup.go:113 mem.Alloc:19870624 mem.TotalAlloc:26823776 mem.HeapAlloc:19870624 mem.HeapSys:64651264 routing :112
DEBUG 2023-03-17 03:42:16,616 gamma.go:124 gamma use memory is:[291259
]DEBUG 2023-03-17 03:42:22,470 startup.go:113 mem.Alloc:20801200 mem.TotalAlloc:27754352 mem.HeapAlloc:20801200 mem.HeapSys:64651264 routing :112
DEBUG 2023-03-17 03:42:26,617 gamma.go:124 gamma use memory is:[291259]
DEBUG 2023-03-17 03:42:32,471 startup.go:113 mem.Alloc:21729440 mem.TotalAlloc:28682592 mem.HeapAlloc:21729440 mem.HeapSys:64651264 routing :112
DEBUG 2023-03-17 03:42:35,463 partition_service.go:253 partition[2] recovered complete
DEBUG 2023-03-17 03:42:35,479 master_cache.go:713 get LOCK success,process fail server &{ID:1 RpcPort:8081 RaftHeartbeatPort:8898 RaftReplicatePort:8899 Ip:127.0.0.1 PartitionIds:[2] Size:0 Private:false Version:0xc00152ac00}
DEBUG 2023-03-17 03:42:35,481 master.go:658 Delete failserver is &{ID:1 TimeStamp:1679024505 Node:0xc0011cf770}success
.DEBUG 2023-03-17 03:42:36,469 schedule_job.go:77 PartitionIds not change, do nothing!
DEBUG 2023-03-17 03:42:36,618 gamma.go:124 gamma use memory is:[291259]
DEBUG 2023-03-17 03:42:37,197 schedule_job.go:131 Start clean task
DEBUG 2023-03-17 03:42:37,471 schedule_job.go:77 PartitionIds not change, do nothing!
DEBUG 2023-03-17 03:42:38,472 schedule_job.go:77 PartitionIds not change, do nothing!
DEBUG 2023-03-17 03:42:38,985 master.go:547 master api register partition response: {"code":200,"msg":"success"}
DEBUG 2023-03-17 03:42:39,473 schedule_job.go:77 PartitionIds not change, do nothing!

ps节点从 starting recover partition 到 partition[2] recovered complete 大约用了1min，但加载的数据量很小(只有1000+条数据)，建表参数如下：

{
    "name": "ts_space_1",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "retrieval_type": "FLAT",
        "retrieval_param": {
            "metric_type": "L2"
        }
    },
    "properties": {
        "feature": {
            "dimension": 256,
            "type": "vector"
        },
        "image_url": {
            "index": true,
            "type": "string"
        },
        "face": {
            "index": true,
            "type": "string"
        },
        "group": {
            "type": "string",
            "array": true,
            "index": true
        },
        "type": {
            "type": "string",
            "index": true
        }
    }
}

这个数据量对应这么长时间加载感觉不正常，想请教下可能是什么问题，多谢

**Comment by zcdb** [comment]
你试试分开master、router、ps部署呢？all的方式一般只建议简单测试功能使用

**Comment by hanqiushi** [comment]
> 你试试分开master、router、ps部署呢？all的方式一般只建议简单测试功能使用

效果跟all in one基本一样，也是加载一段时间才能使用

**Comment by hanqiushi** [comment]
@zcdb 我把建表语句中的index:true都去掉，加载时间为秒级
说明加载index时间过长？这又是正常的么

**Comment by gyd-a** [comment]
https://github.com/vearch/gamma/pull/111/commits/f6b2616dc7578b501eb34a1d04918e7d13a0b46c 修复gamma重启慢的问题，主要是因为重启是有更新的动作，更新时先删除数值索，删除这个动作比较慢

**Comment by hanqiushi** [comment]
> [vearch/gamma@f6b2616](https://github.com/vearch/gamma/commit/f6b2616dc7578b501eb34a1d04918e7d13a0b46c) 修复gamma重启慢的问题，主要是因为重启是有更新的动作，更新时先删除数值索，删除这个动作比较慢

多谢多谢，我试一下
