### ISSUE TITLE
basic_usage.py运行报错Segmentation fault

### ISSUE THREAD

**Issue by chloefresh** [vearch/vearch#736]
使用的包版本：
numpy       1.21.6
pip         23.3.1
setuptools  39.0.1
vearch      3.3.2

没有改代码，直接运行，显示Segmentation fault

gamma.ERROR.log内容如下：
concurrent_vector.h:125 ConcurrentVector[StrBlock_0], id[2162234] >= size[527]

**Comment by zcdb** [comment]
请问python 版本多少以及运行环境是？
