### ISSUE TITLE
查看表空间里面数据的size的命令是什么啊

### ISSUE THREAD

**Issue by chloefresh** [vearch/vearch#739]
想知道数据有没有灌进去，文档上没有翻到相关的命令。

**Comment by zcdb** [comment]
https://vearch.readthedocs.io/zh-cn/latest/use_op/cluster_status.html#id3 通过此接口获取

**Comment by chloefresh** [comment]
> https://vearch.readthedocs.io/zh-cn/latest/use_op/cluster_status.html#id3 通过此接口获取

是不是有微信群呀，可以拉我一下吗。我的vx：chloe3329 @zcdb
