### ISSUE TITLE
after update, how does the inferface change to the high level API?

### ISSUE THREAD

**Issue by LynnaPan** [vearch/vearch#74]
Hi, developer, i notice that vearch has a update recently, and many API inferfaces are changed. The high level API readme became blank as: https://github.com/vearch/vearch/blob/master/docs/APIVisualSearch.md
How does the inferface change to the high level API? is there any document update?

**Comment by gDreamcatcher** [comment]
Previously, we used high-level APIs to encapsulate low-level APIs. Later, we found that this would lead users to learn two sets of APIs, so in the new iteration, we combined the two APIs together. You can refer to low-level APIs, which will meet most of your needs。
