### ISSUE TITLE
编译vearch失败

### ISSUE THREAD

**Issue by ZhangIssac** [vearch/vearch#740]
**环境**

centos 7.9 
gcc 9.3.1
go 1.21.5

**启动报错**
![image](https://github.com/vearch/vearch/assets/58984599/db95cdd2-f390-4bc8-b825-fe4eed32958e)

**Comment by ZhangIssac** [comment]
@zcdb hello，如果可以，幸苦给点思路。使用单机模式，编译过程中无异常，启动报错了。感谢～

**Comment by zcdb** [comment]
看看你们的机器支持avx2吗

**Comment by ZhangIssac** [comment]
@zcdb 看起来是不支持，这个对cpu指令集有要求吗？
![image](https://github.com/vearch/vearch/assets/58984599/0b05fcd1-70e2-4156-a522-4f968f514934)

**Comment by zcdb** [comment]
默认需要avx2和sse4。可以修改编译指令，engine/CMakeLists.txt 里面去掉 -mavx2，重新构建。另外问一下你们这个是什么架构的机器？

**Comment by ZhangIssac** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            15
Model:                 6
Model name:            Common KVM processor
Stepping:              1
CPU MHz:               2194.842
BogoMIPS:              4389.68
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm

**Comment by ZhangIssac** [comment]
几个环境的机器配置有点差异，开发环境不支持avx2。

另外也想请教一下，没有在文档里找到如何去打包发布？难道需要每一台机器上编译一遍？

**Comment by zcdb** [comment]
打包发布我们是支持docker和k8s的。机器配置不一样的，建议还是使用统一的一套环境，不然你们也不好管理；或者统一去掉avx2和sse4的编译支持，取最低配置来编译，但是这个非常不建议，性能会下降很多
