### ISSUE TITLE
批量插入数据时，新插入的数据会把旧数据覆盖掉

### ISSUE THREAD

**Issue by chloefresh** [vearch/vearch#742]
写了一个for循环插入多个批次，会发现旧数据会被覆盖掉，表里存的是最新插入的批次数据
curl -H "content-type: application/json" -XPOST -d'
{"index": {"_id": "v1"}}\n
{"field1": "value", "field2": {"feature": []}}\n
{"index": {"_id": "v2"}}\n
{"field1": "value", "field2": {"feature": []}}\n
' http://router_server/$db_name/$space_name/_bulk

**Comment by chloefresh** [comment]
这个是正常的吗？

**Comment by zcdb** [comment]
这是正常的，如果指定的_id已存在，即为更新，否则为插入
