### ISSUE TITLE
"create table failed" for certain dimensions

### ISSUE THREAD

**Issue by jamjpan** [vearch/vearch#743]
In the Python API guide `vearch/engine/sdk/python/docs/APIPythonSDK.md`, under "A simple usage" step 2, change `dimension=128` to `dimension=100` in the below line and get `create table failed` error, -2 response code. How to make this work for any integer dimension?

`vector_field = GammaVectorInfo(name="feature", dimension=128)`

**Comment by zcdb** [comment]
set "nsubvector": 25 or 50 in engine_info. dimension needs to be able to divide nsubvector

**Comment by jamjpan** [comment]
Perfect, thank you!
