### ISSUE TITLE
vearch report Doc size reached upper size while total num of doc below max_size

### ISSUE THREAD

**Issue by zhyon404** [vearch/vearch#75]
https://github.com/vearch/vearch/blob/42acfcb03393ce1a8c40d6db896bece17017cfb0/engine/gamma/search/gamma_engine.cc#L644

current max_docid_ can only increase, deleted doc still count and stop new doc being added.
vearch becomes unavailable. Is some way to solve this problem?

**Comment by ljeagle** [comment]
The parameter of "max_size" denotes the maximum documents in each partition. It prevents the system which might be crashed by the exceeded memory, so we set this parameter. You can set an appropriate value according to your deployed machine. Later we may delete the parameter, extend the documents dynamically. However, the system would be definitely crashed without any protection when exceeding the maximum memory of the deployed machine, it should be cared by users.

**Comment by ljeagle** [comment]
The parameter of "max_size" denotes the maximum documents in each partition. It protects the system which might be crashed by the exceeded memory, so we set this parameter. You can set an appropriate value according to your deployed machine. Later we may delete the parameter, extend the documents dynamically. However, the system would be definitely crashed without any protection when exceeding the maximum memory of the deployed machine, it should be cared by users.

**Comment by ljeagle** [comment]
Now each operation of 'update' causes a new document added, this will let the "max_docid_" increase too quickly.  We plan to change the implementation of 'update',  just really update the existing document, not first delete, and then add a new document.

**Comment by zhyon404** [comment]
inplace update will be good, but if having a lot delete operation,  deleted docid still can't be reused?
can vearch add some compact operation trigger by timer or api?

**Comment by ljeagle** [comment]
Thanks for your good suggestion! We have thought to do compaction like leveldb. It would change the structure of index and storage, and may influence the searching performance when compacting.   So we would design and consider it carefully.

**Comment by zhyon404** [comment]
thanks a lot for your consideration, it would be really helpful for our use case. do you have same problem in production? any suggestions on this problem? i consider rebuilt space periodically. but without knowing the max_docid_ remaining, it is difficult to decide when to rebuild the space.

**Comment by zjsen668** [comment]
> However, the system would be definitely crashed without any protection when exceeding the maximum memory of the deployed machine, it should be cared by users.

Do vearch need to load all data into memory to work?
