### ISSUE TITLE
ncentroids

### ISSUE THREAD

**Issue by Dr1rD** [vearch/vearch#78]
Can we refer to faiss to set the value of Ncentroids?
[how-big-is-the-dataset](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#how-big-is-the-dataset)

**Comment by qiutianme** [comment]
I didn't found ncentroids in [how-big-is-the-dataset](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#how-big-is-the-dataset), but referring to faiss is a reasonable idea.

**Comment by Dr1rD** [comment]
In [how-big-is-the-dataset](https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index#how-big-is-the-dataset):
> **If below 1M vectors: "...,IVFx,..."**
> 
> Where x is 4*sqrt(N) to 16*sqrt(N), with N the size of the dataset. This just clusters the vectors with k-means. You will need between 30*x and 256*x vectors for training (the more the better).
> 
> Supported on GPU: yes

I think the "x" in "IVFx" is ncentroids. Is it?

**Comment by qiutianme** [comment]
@Dr1rD  Yes, The "x" in "IVFx" is ncentroids, I didn't notice this text.
