### ISSUE TITLE
请教一下正排原地更新的问题

### ISSUE THREAD

**Issue by littledoglily** [vearch/vearch#794]
从 [](url) https://github.com/vearch/vearch/wiki/Inplace-update%E5%92%8C%E7%B4%A2%E5%BC%95Compaction 这个链接看到对于正排定长字段是采用原地更新的方法，这不会导致更新时正在读该正排字段的请求读出来错误数据吗？ 好像memcpy并不是一个原子操作

**Comment by wxingda** [comment]
这块为了保证，并没有对读写加锁，更新时可能会读取到旧值，但是不会是错误数据

**Comment by littledoglily** [comment]
> 这块为了保证性能，并没有对读写加锁，更新时可能会读取到旧值，但是不会是错误数据

了解了，按我之前理解memcpy是按字节逐一copy的，感觉可能会读出一个非旧值和新值意外其他的值

**Comment by wxingda** [comment]
确实可能会读取到其他值，后续会加入读写锁或双缓存来避免这种情况

**Comment by littledoglily** [comment]
> 确实可能会读取到其他值，后续会加入读写锁或双缓存来避免这种情况

这个feature大概会在哪个版本上线？

**Comment by wxingda** [comment]
预计在v3.5.3上线

**Comment by littledoglily** [comment]
> 预计在v3.5.3上线

期待
