### ISSUE TITLE
重启vearch后doc的唯一标识ID会变化

### ISSUE THREAD

**Issue by lale314** [vearch/vearch#80]
插入数据时指定唯一标识ID，重启vearch后，根据ID来查询，有些ID查不到数据，观察发现重启后ID会变化

插入接口：
curl -XPOST -H "content-type: application/json"  -d'
{
    "field1": "value1",
    "field2": "value2",
    "field3": {
        "feature": [0.1, 0.2]
    }
}

' http://router_server/$db_name/$space_name/$id

id查询接口：
curl -XGET http://router_server/$db_name/$space_name/$id

**Comment by qiutianme** [comment]
@lale314  你是用的最新代码吗？麻烦给一下ID发生变化的具体案例，包括插入的文档和ID，通过ID去get的时候的结果

**Comment by lale314** [comment]
> @lale314 你是用的最新代码吗？麻烦给一下ID发生变化的具体案例，包括插入的文档和ID，通过ID去get的时候的结果

用的是最新的代码。
创建表空间：
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "test_space04",
    "partition_num": 1,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 10000000,
        "nprobe": 20,
        "metric_type": "L2",
        "ncentroids": 256,
        "nsubvector": 32
    },
    "properties": {
        "my_pk": {
            "type": "integer",
            "index": "true"
        },
        "text_vec": {
            "type": "vector",
            "dimension": 768
        }
    }
}
' http://127.0.0.1:8817/space/test_db01/_create

根据ID查询：
curl -XGET http://127.0.0.1:9001/test_db01/test_space04/19478052
返回结果，_id变了
{"_index":"test_db01","_type":"test_space04","_id":"19645781","found":true,"_version":1,"_source":{"my_pk":19478052}}

根据ID查询，无结果：
curl -XGET http://127.0.0.1:9001/test_db01/test_space04/19478040

{"_index":"test_db01","_type":"test_space04","_id":"19478040","found":false}

条件过滤，能返回结果：
curl -H "content-type: application/json" -XPOST -d'
{
"query": {
        "filter": [{
            "range": {
                "my_pk": {
                    "gte": 19478040,
                    "lte": 19478040
                }
            }
        }]
    },
    "direct_search_type": 0,
    "quick": false,
    "vector_value": true,
    "online_log_level": "debug",
    "size": 10
}
' http://127.0.0.1:9001/test_db01/test_space04/_search

{"took":4,"timed_out":false,"_shards":{"total":1,"failed":0,"successful":1},"hits":{"total":1,"max_score":0,"hits":[{"_index":"test_db01","_type":"test_space04","_id":"","_score":0,"_extra":{"vector_result":[]},"_version":0,"_source":{"my_pk":19478040,"text_vec":{"feature":[0.7823002,0.19404483,0.13025221 ......

**Comment by ansjsun** [comment]
@lale314 你访问下  http://127.0.0.1:9001/ 看看程序的git commit id。麻烦发出来

因为这个问题我们之前没有遇到过 怀疑版本很旧了

**Comment by lale314** [comment]
> @lale314 你访问下 http://127.0.0.1:9001/ 看看程序的git commit id。麻烦发出来
> 
> 因为这个问题我们之前没有遇到过 怀疑版本很旧了

{"tagline":"","name":"vearch001","cluster_name":"vearch001","cluster_uuid":"","version":{"build_version":"0.3","build_time":"2020-01-04 10:51.46","commit_id":"d2be0ec4c77cb7e699f6171efd4eb118fde551f7"}}
