### ISSUE TITLE
单机版本插入数据时ps节点异常退出

### ISSUE THREAD

**Issue by SplashCloud** [vearch/vearch#801]
# Summary 概要
运行单机版本的vearch，跑`/scripts/benchmark/`下的`restful.py`，ps节点经常异常退出。
# Platform 平台

操作系统: Ubuntu 20.04.4 LTS

CPU 信息: Intel(R) Xeon(R) Gold 5317 CPU @ 3.00GHz

Vearch 版本: d801ccb92b0f8fc2848825243ea67b0f2b0360a5

如何安装的: 源码编译 

# 依赖

```shell
$ ldd ../build/bin/vearch 
        linux-vdso.so.1 (0x00007ffc923ee000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f9fd7af9000)
        libgamma.so => /mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/build/gamma_build/libgamma.so (0x00007f9fd75f9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9fd75d6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9fd73e4000)
        libtcmalloc.so.4 => /lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007f9fd71eb000)
        libomp.so.5 => /lib/x86_64-linux-gnu/libomp.so.5 (0x00007f9fd70fa000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9fd6fab000)
        librocksdb.so.9.2 => /mnt/ssd/zhc/vector-db/libs/rocksdb-9.2.1/lib/librocksdb.so.9.2 (0x00007f9fd6496000)
        libtbb.so.12 => /mnt/ssd/zhc/vector-db/libs/tbb/lib/libtbb.so.12 (0x00007f9fd643d000)
        libzstd.so.1 => /mnt/ssd/zhc/vector-db/libs/zstd/lib/libzstd.so.1 (0x00007f9fd633f000)
        libprotobuf.so.32 => /mnt/ssd/zhc/vector-db/libs/protobuf-3.21.0/lib/libprotobuf.so.32 (0x00007f9fd606b000)
        libmkl_intel_lp64.so => /lib/x86_64-linux-gnu/libmkl_intel_lp64.so (0x00007f9fd54ff000)
        libmkl_intel_thread.so => /lib/x86_64-linux-gnu/libmkl_intel_thread.so (0x00007f9fd2f93000)
        libmkl_core.so => /lib/x86_64-linux-gnu/libmkl_core.so (0x00007f9fcec73000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9fcea91000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9fcea76000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9fd7b46000)
        libunwind.so.8 => /lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f9fcea57000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9fcea51000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9fcea47000)
        libsnappy.so.1 => /lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f9fcea3c000)
        libgflags.so.2.2 => /lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007f9fcea11000)
        libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f9fce9f3000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f9fce9de000)
        libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f9fce9d1000)
        libtbb.so.2 => /lib/x86_64-linux-gnu/libtbb.so.2 (0x00007f9fce98b000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f9fce962000)
```

# Reproduction instructions 复现步骤

 

## config配置
单机版本的vearch
```txt
[global]
    # the name will validate join cluster by same name
    name = "vearch"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    data = ["/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/deploy/datas/"]
    # log path , If you are in a production environment, You'd better set absolute paths
    log = "/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/deploy/logs/"
    # default log type for any model
    level = "info"
    # master <-> ps <-> router will use this key to send or receive data
    signkey = "vearch"
    skip_auth = true

# if you are master, you'd better set all config for router、ps and router, ps use default config it so cool
[[masters]]
    # name machine name for cluster
    name = "m1"
    # ip or domain
    address = "127.0.0.1"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370

[router]
    # port for server
    port = 9001

[ps]
    # port for server
    rpc_port = 8081
    # raft config begin
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 200 #ms
    raft_retain_logs = 10000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1
```
## 运行脚本
执行的是`/scripts/benchmark/restful.py`
```shell
python restful.py \
    --dataset sift \
    --index-type IVFFLAT \
    --task NORMAL \
    --output update-single

# index_params在代码里设置了，就是默认的参数
#        {
#            "metric_type": "L2",
#            "ncentroids": 2048
#        }
```

## 报错信息

程序经常会挂在`process_upsert_data`函数的`assert rs.json()["data"]["total"] == size`上

```shell
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/ssd/zhc/anaconda3/envs/vectordb/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd/zhc/anaconda3/envs/vectordb/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/scripts/benchmarks/restful.py", line 368, in process_upsert_data
    assert rs.json()["data"]["total"] == size
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/scripts/benchmarks/restful.py", line 782, in <module>
    run_task(args)
  File "/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/scripts/benchmarks/restful.py", line 759, in run_task
    run_normal(args)
  File "/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/scripts/benchmarks/restful.py", line 648, in run_normal
    upsert(args, xb)
  File "/mnt/ssd/zhc/vearch/go/src/github/vearch/vearch/scripts/benchmarks/restful.py", line 410, in upsert
    results = pool.map(process_upsert_data, total_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd/zhc/anaconda3/envs/vectordb/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd/zhc/anaconda3/envs/vectordb/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
AssertionError
```

# 日志信息

[vearch-ps-startup.log](https://github.com/user-attachments/files/16558391/vearch-ps-startup.log)
[gamma.INFO.log](https://github.com/user-attachments/files/16558393/gamma.INFO.log)
[ROUTER.ERROR.log](https://github.com/user-attachments/files/16558394/ROUTER.ERROR.log)
[MASTER.INFO.log](https://github.com/user-attachments/files/16558395/MASTER.INFO.log)
[ROUTER.INFO.log](https://github.com/user-attachments/files/16558396/ROUTER.INFO.log)
[PS.INFO.log](https://github.com/user-attachments/files/16558397/PS.INFO.log)

**Comment by zcdb** [comment]
d801ccb92b0f8fc2848825243ea67b0f2b0360a5 麻烦贴一下这个版本的链接

**Comment by SplashCloud** [comment]
> d801ccb92b0f8fc2848825243ea67b0f2b0360a5 麻烦贴一下这个版本的链接

我是直接clone源码的，d801ccb92b0f8fc2848825243ea67b0f2b0360a5是我clone的时候最新的commit。

这个是运行`build/build.sh`的版本信息：
```
version info: -X 'main.BuildVersion=v3.5.1' -X 'main.CommitID=d801ccb92b0f8fc2848825243ea67b0f2b0360a5' -X 'main.BuildTime=2024-08-09 23:10.24'
```

**Comment by zcdb** [comment]
1、这个版本的commit 我没找到，https://github.com/vearch/vearch/commits/d801ccb92b0f8fc2848825243ea67b0f2b0360a5

**Comment by SplashCloud** [comment]
> 1、这个版本的commit 我没找到，https://github.com/vearch/vearch/commits/d801ccb92b0f8fc2848825243ea67b0f2b0360a5 2、建议使用最新版本

抱歉，commit版本弄错了，应该是84d1fc76ca6e709a0cdf1a7f78e522597e86e571
好的，我先尝试下最新版本

**Comment by SplashCloud** [comment]
> 1、这个版本的commit 我没找到，https://github.com/vearch/vearch/commits/d801ccb92b0f8fc2848825243ea67b0f2b0360a5 2、建议使用最新版本

您好，我更换了最新的代码还是会出现上述问题，ps进程大部分情况下还是会在插入数据时异常退出，但是却没有PS.ERROR.log等日志，唯一显示异常信息的就是[vearch-ps-startup.log](https://github.com/user-attachments/files/16558391/vearch-ps-startup.log)；观察了插入过程中cpu和内存的使用情况，也没有异常。请问可以给出进一步的指导帮助分析下原因吗？非常感谢！

**Comment by zcdb** [comment]
现在看是插入的导致的崩溃，因为我这边现在没有ubuntu的系统，我centos运行是ok的，是否可以编译debug版本，就是：
sh build.sh -d
然后用gdb启动vearch ps 节点:     
gdb vearch
r -conf config.toml ps

**Comment by SplashCloud** [comment]
> 现在看是插入的导致的崩溃，因为我这边现在没有ubuntu的系统，我centos运行是ok的，是否可以编译debug版本，就是： sh build.sh -d 然后用gdb启动vearch ps 节点: gdb vearch r -conf config.toml ps

我用gdb启动ps节点之后，在插入数据异常退出时的函数调用栈如下，看着是在rocksdb里出现的异常。
[gdb.log](https://github.com/user-attachments/files/16621640/gdb.log)

**Comment by wxingda** [comment]
没找到Vearch 版本: d801ccb92b0f8fc2848825243ea67b0f2b0360a5，发个链接吧 @SplashCloud

**Comment by SplashCloud** [comment]
> 没找到Vearch 版本: d801ccb92b0f8fc2848825243ea67b0f2b0360a5，发个链接吧 @SplashCloud

现在已经使用最新的代码了：https://github.com/vearch/vearch/commits/19c5e41134628beb01906a435a4c4764db7b7399

**Comment by wxingda** [comment]
@SplashCloud 你安装了mkl吗

**Comment by SplashCloud** [comment]
> @SplashCloud 你安装了mkl吗

安装了的
![image](https://github.com/user-attachments/assets/7ebe37e6-7c5b-4b3b-9f6a-4b8ed4434da1)

**Comment by wxingda** [comment]
![image](https://github.com/user-attachments/assets/32a1225f-b6cf-4016-90e0-2eff072b0aa7)

@SplashCloud 你在编译的时候有没有遇到这个问题，我也装了mkl

**Comment by SplashCloud** [comment]
> ![image](https://private-user-images.githubusercontent.com/12606514/358231407-32a1225f-b6cf-4016-90e0-2eff072b0aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mjg0ODksIm5iZiI6MTcyMzcyODE4OSwicGF0aCI6Ii8xMjYwNjUxNC8zNTgyMzE0MDctMzJhMTIyNWYtYjZjZi00MDE2LTkwZTAtMmVmZjA3MmIwYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEzMjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTNjYTNjYzNjMjcyYmUyOGY3MTViZWZiYWI0MmZiYWFmMTBkODJmZjVjOGNlNzcyM2RiMTdmNWE5YjU2OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvLkMN_gmoBgKnik1f1oftiQxfr3Y8a8twYCTyW8Sj0)
> 
> @SplashCloud 你在编译的时候有没有遇到这个问题，我也装了mkl

有的，后面装了LAPACK解决的

**Comment by wxingda** [comment]
> > ![image](https://private-user-images.githubusercontent.com/12606514/358231407-32a1225f-b6cf-4016-90e0-2eff072b0aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mjg0ODksIm5iZiI6MTcyMzcyODE4OSwicGF0aCI6Ii8xMjYwNjUxNC8zNTgyMzE0MDctMzJhMTIyNWYtYjZjZi00MDE2LTkwZTAtMmVmZjA3MmIwYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEzMjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTNjYTNjYzNjMjcyYmUyOGY3MTViZWZiYWI0MmZiYWFmMTBkODJmZjVjOGNlNzcyM2RiMTdmNWE5YjU2OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvLkMN_gmoBgKnik1f1oftiQxfr3Y8a8twYCTyW8Sj0)
> > @SplashCloud 你在编译的时候有没有遇到这个问题，我也装了mkl
> 
> 有的，后面装了LAPACK解决的

是源码安装还是apt安装的？

**Comment by SplashCloud** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/12606514/358231407-32a1225f-b6cf-4016-90e0-2eff072b0aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mjg0ODksIm5iZiI6MTcyMzcyODE4OSwicGF0aCI6Ii8xMjYwNjUxNC8zNTgyMzE0MDctMzJhMTIyNWYtYjZjZi00MDE2LTkwZTAtMmVmZjA3MmIwYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDEzMjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTNjYTNjYzNjMjcyYmUyOGY3MTViZWZiYWI0MmZiYWFmMTBkODJmZjVjOGNlNzcyM2RiMTdmNWE5YjU2OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvLkMN_gmoBgKnik1f1oftiQxfr3Y8a8twYCTyW8Sj0)
> > > @SplashCloud 你在编译的时候有没有遇到这个问题，我也装了mkl
> > 
> > 
> > 有的，后面装了LAPACK解决的
> 
> 是源码安装还是apt安装的？

源码安装的，然后引进`internal/engine/CMakeLists.txt`里

**Comment by wxingda** [comment]
我这没有ubuntu系统，我用docker运行测试
宿主机操作系统: CentOS Linux release 8.5.2111

CPU 信息: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

启动docker容器，并进入容器
`docker run --name wxd-test --privileged -d ubuntu:20.04 sleep 9999d`
`docker exec -it wxd-test bash`

安装必要的软件
`apt install -y software-properties-common`
`add-apt-repository -y ppa:ubuntuhandbook1/apps`
`apt update && apt install -y  wget make automake git which libzstd1-dev libssl-dev libtbb2 libtbb-dev libboost-all-dev tar findutils g++ `
`wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0-linux-x86_64.sh`
`chmod 755 cmake-3.20.0-linux-x86_64.sh;./cmake-3.20.0-linux-x86_64.sh --skip-license --prefix=/usr/local`
`wget https://github.com/protocolbuffers/protobuf/releases/download/v21.0/protobuf-cpp-3.21.0.tar.gz && tar xf protobuf-cpp-3.21.0.tar.gz && cd protobuf-3.21.0/ && ./configure && make -j14 && make install`
`cd / && wget https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz && tar xf go1.22.5.linux-amd64.tar.gz && export GOROOT=/go && export PATH=$PATH:$GOROOT/bin`
安装mkl
`apt install intel-mkl`

把相关库硬编码到`internal/engine/CMakeLists.txt`里面
![image](https://github.com/user-attachments/assets/79615d1e-6b0e-45b4-ae73-c7a4ffb66beb)

编译成功后，由于是单机版，所以直接用all参数启动一个进程就可以
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/gamma_build`
`./bin/vearch -conf ../config/config.toml all`

使用/scripts/benchmark/restful.py运行了5次没有崩溃，你可以参考这个流程测一下

我看你ldd vearch，vearch链接了多个库，实际上这些库应该是libgamma.so链接的，vearch只需要链接到libgamma.so就可以
![image](https://github.com/user-attachments/assets/d82f95ab-fb29-4201-9eb7-14270704c095)

**Comment by SplashCloud** [comment]
非常感谢帮助，但是我按照你的流程在docker里启动vearch之后，运行测试时（在docker里）在创建space的时候返回：
```
2024-08-16 16:49:24,309 __main__:129 ERROR {"code":1,"msg":"internal_error:create partition err: call_rpcclient_failed:partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M "}
```
PS.*.log如下
```
ERROR 2024-08-16 16:49:24,081 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,116 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,215 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,215 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,215 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,249 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,260 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,317 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,340 handler_admin.go:118 partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
INFO 2024-08-16 16:35:14,162 startup.go:103 start server by version:[v3.5.2] commitID:[7c6857de3223ab7b98e3617ddd31563fdcd285c3]
INFO 2024-08-16 16:35:14,162 startup.go:104 The Config File Is: /vearch/build/config_single.toml
INFO 2024-08-16 16:35:14,162 startup.go:107 The cluster prefix is: /vearch
INFO 2024-08-16 16:35:14,162 startup.go:108 ResourceLimitRate: 0.850000
INFO 2024-08-16 16:35:14,162 config.go:115 vearch etcd address is 127.0.0.1:2370
INFO 2024-08-16 16:35:14,163 signals.go:49 Wait Signals...
INFO 2024-08-16 16:35:14,163 meta.go:54 Server create meta to file is: datas/server_meta.txt
INFO 2024-08-16 16:35:14,402 server.go:202 to register master, nodeId:[1], times : 0
INFO 2024-08-16 16:35:14,485 server.go:216 register master ok, nodeId:[1]
INFO 2024-08-16 16:35:14,485 server.go:146 vearch server successful startup...
INFO 2024-08-16 16:49:24,081 partition_service.go:236 delete partition:[3] success
INFO 2024-08-16 16:49:24,116 partition_service.go:236 delete partition:[1] success
INFO 2024-08-16 16:49:24,215 partition_service.go:236 delete partition:[2] success
INFO 2024-08-16 16:49:24,215 partition_service.go:236 delete partition:[3] success
INFO 2024-08-16 16:49:24,215 partition_service.go:236 delete partition:[1] success
INFO 2024-08-16 16:49:24,249 partition_service.go:236 delete partition:[2] success
INFO 2024-08-16 16:49:24,260 partition_service.go:236 delete partition:[3] success
INFO 2024-08-16 16:49:24,317 partition_service.go:236 delete partition:[1] success
INFO 2024-08-16 16:49:24,340 partition_service.go:236 delete partition:[2] success
INFO 2024-08-16 16:49:25,000 schedule_job.go:82 server.PartitionIds has changed, need to put server to topo again!, leaseId: [6509268653569652255]
```

MASTER.ERROR.log如下：
```
ERROR 2024-08-16 16:49:24,260 cluster_service.go:443 internal_error:create partition err: call_rpcclient_failed:partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,309 cluster_api.go:438 createSpaceService err: internal_error:create partition err: call_rpcclient_failed:partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
ERROR 2024-08-16 16:49:24,317 cluster_service.go:443 internal_error:create partition err: call_rpcclient_failed:partition_resource_exhausted:disk space not enough: total [560645]M, avail [70041]M
```

**Comment by wxingda** [comment]
这个原因是vearch在运行时对资源进行检测，防止oom或存储不足，日志里面显示disk总空间560645M，可用70041M，还剩12%，所以报错了，这个可以通过调整配置文件https://github.com/vearch/vearch/blob/7c6857de3223ab7b98e3617ddd31563fdcd285c3/config/config.toml#L25，把resource_limit_rate调整到0.95

**Comment by SplashCloud** [comment]
> 这个原因是vearch在运行时对资源进行检测，防止oom或存储不足，日志里面显示disk总空间560645M，可用70041M，还剩12%，所以报错了，这个可以通过调整配置文件
> 
> https://github.com/vearch/vearch/blob/7c6857de3223ab7b98e3617ddd31563fdcd285c3/config/config.toml#L25
> 
> 
> 把resource_limit_rate调整到0.95

测试可以成功运行了，非常感谢~
