### ISSUE TITLE
660W数据构建ivfflat索引性能查询耗时较高

### ISSUE THREAD

**Issue by littledoglily** [vearch/vearch#805]
cpu: Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
指令集只用avx2, 
索引类型：ivfflat
数据量：660W
向量维度：768
聚类之后日志：
<img width="1231" alt="企业微信截图_f9eed4ef-cf2d-4c59-b3fc-b6b86bbcdf88" src="https://github.com/user-attachments/assets/1be40409-0dee-4a8e-8e4c-c6d0afc55e74">

单个请求查询耗时在800ms左右 ，感觉不太正常，nprobe是并行的，每个nprobe里面的倒排链还能再进行并行吗？ 看代码好像不行；如果不行那单个链如果过长的话 ，感觉就很耗时了

**Comment by zcdb** [comment]
看聚类桶信息，分布很不均匀。建表语句设置的ncentroids和trainning_threshold的值是多少？

**Comment by littledoglily** [comment]
> trainning_threshold

ncent: 512
training_threshold: 1 （全部训练了

**Comment by zcdb** [comment]
training_threshold 设置为 [trainning_threshold * 39, trainning_threshold * 256]的值，ncentroids也可以适当调大一些

**Comment by littledoglily** [comment]
想了解下ivfflat 在train的时候用的quantizer = new faiss::IndexFlatL2(d); 一直是这个，这个东西不会根据metric是l2还是IP进行调整吗？

**Comment by zcdb** [comment]
如你所说，ivfflat train的是聚类中心，metric对应计算的是每个聚类中心放的向量数据，是两个独立的部分，聚类是kmeans算法，l2更有意义

**Comment by littledoglily** [comment]
你的意思是l2聚类效果比用inner更好？ 和在线的时候metric无关

**Comment by zcdb** [comment]
一般而言，kmeans l2会更好。是的，这是两个独立的部分
