### ISSUE TITLE
query failed  with  Partition not Exist Error

### ISSUE THREAD

**Issue by WeponX** [vearch/vearch#81]
http://10.31.103.50/vrouter/youtubeNet/user_vector3/_search
{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 9,
        "failed": 9,
        "successful": 0,
        "errors": {
            "internal error": {}
        }
    },
    "hits": {
        "total": 0,
        "max_score": 0
    }
} 
The PS.ERROR log:
```
E0109 11:46:36.099644       1 master.go:116] [ERROR] server can not find on master, maybe server is offline, nodeId:[351]
E0109 11:46:36.099747       1 partition_service.go:130] [ERROR] partition recovery get server info err: Partition Not Exists
```
The PS.DEBUG log:
```
D0109 11:42:20.100423       1 master_api.go:302] [DEBUG] master api register partition response:
D0109 11:42:20.100439       1 master_api.go:306] [DEBUG] master api register partition err: Query error, url: http://10.19.17.21:8817/register_partition, method: POST, resp body: {"code":550,"msg":"etcdserver: request timed out"}, req body: {"id":18,"space_id":2,"db_id":1,"partition_slot":3817748704,"leader_name":351,"replicas":[351,515,540]}
D0109 11:42:20.100463       1 master_api.go:300] [DEBUG] master api register partition url: http://10.19.17.2
```

**Comment by ansjsun** [comment]
1.check your master is crashed??

2.check you config.toml , how many master you set !

3.if you use local model , and master ps  router in one process, check your data dir , does it have old data.

**Comment by WeponX** [comment]
1. The return of  http://master IP/vmaster/_cluster/health is green 
2. vearch deployed in cluster model: 3 master, 3 router, 3 ps
3.  the data had been cleared before the operation
