### ISSUE TITLE
关于建立索引

### ISSUE THREAD

**Issue by paradoxtown** [vearch/vearch#84]
> index_size 指定每个分片的记录数量达到多少开始创建索引，不指定则不创建索引。

设置完阈值后，我将数据分批次插入数据库，想问一下这个建立索引的过程是在什么时候发生的？（是数据量一旦达到阈值就开始建立吗？那我怎么知道他是否建立了？或者说建立好了？）

**Comment by wxingda** [comment]
1.数据量达到阈值，自动创建索引
2.`curl -XGET {{MASTER}}/_cluster/health`，**index_status**为2时索引创建成功

**Comment by paradoxtown** [comment]
谢谢！
