### ISSUE TITLE
vearch可以动态增加、删除节点吗

### ISSUE THREAD

**Issue by zzypeak** [vearch/vearch#87]
我用vearch部署了3个节点，比如[10.10.10.16, 10.10.10.17, 10.10.10.18]进行试验，发现节点[10.10.10.17]机器负载较高，想用[10.10.10.19]进行替换，可是修改config.toml重新启动后，vearch并没有去连接19，仍在尝试连接17。想问下vearch支持这样的操作吗，若支持的话该如何操作呢？

**Comment by ansjsun** [comment]
可以增加删除节点。但是你这个情况 3个机器是2个是副本吧。因为默认查询只查询leader 导致的。你可以通过random参数进行随机查询，这样负载相对均衡。不好的一点是，在告诉插入的情况下副本可能存在一定不一致。 

http//xxx/db/space/_search?client_type=random  这样就是3个副本随机查询了

**Comment by zzypeak** [comment]
多谢指点，若我想扩展节点的话应该怎样操作呢，直接修改config.toml好像没启作用诶
