### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by Silocean** [vearch/vearch#89]
![image](https://user-images.githubusercontent.com/6680721/72715762-07d47800-3bac-11ea-9b3c-f317fe2108d4.png)
我的测试数据大概2.6G，约328万条64维向量，批量插入数据后内存占用达到了12G，

请问这个内存占用合理吗？

**Comment by qiutianme** [comment]
@Silocean 内存不太合理。你确认下是否有重复插入的情况，是否建了多个space。最后麻烦把你创建space的整个json参数发一下

**Comment by Silocean** [comment]
```
{
    "name": "test_space",
    "partition_num": 3,
    "replica_num": 1,
    "engine": {
        "name": "gamma",
        "index_size": 1000000,
        "max_size": 10000000,
        "nprobe": 32,
        "metric_type": "InnerProduct",
        "ncentroids": 4096,
        "nsubvector": 32
    },
    "properties": {
        "str": {
            "type": "keyword",
            "index": "true"
        },
        "num": {
            "type": "integer",
            "index": "true"
        },
        "score": {
            "type": "float",
            "index": "true"
        },
        "tags": {
            "type": "string",
            "array": true,
            "index": "true"
        },
        "nums": {
            "type": "integer",
            "array": false,
            "index": "true"
        },
        "vec": {
            "type": "vector",
            "dimension": 64,
            "store_type": "Mmap",
            "store_param": {
                "cache_size": 2000
            }
        }
    }
}
```
@qiutianme

**Comment by qiutianme** [comment]
@Silocean 我用我们的测试数据在最新的代码上测试了一下，同样是320万64维数据，占用的物理内存远小于12.7G。麻烦你提供下以下3点信息，方便我们做进一步的排查
1. 提供一下你使用的代码的commit id
2. 328万64维向量只有800M左右，而你说你的测试数据是2.6G，那说明其它正排字段占用空间也挺多的，能给一个添加到vearch的doc的完整例子吗
3. 是否有删除space，然后重建的操作

**Comment by rosickyyu** [comment]
@qiutianme 这个重建会有什么影响？我现在有400万数据，原始数据大小为27G，含有一个id列一个400维的向量列，插入后
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                              
35463 root      20   0  0.690t 0.020t  69044 S  20.0 16.3   5983:51 vearch  
我是2个节点，每个节点上一个master一个ps 路由在其中一个节点上 
curl -XPUT -H "content-type: application/json" -d'
{
    "name": "candidate_ht",
    "partition_num": 2,
    "replica_num": 2,
    "engine": {
        "name": "gamma",
        "index_size": 70000,
        "max_size": 3000000,
        "id_type": "String","retrieval_type": "IVFPQ",
        "retrieval_param": {
            "metric_type": "InnerProduct",
            "ncentroids":400,
            "nsubvector":64
        }
    },
    "properties": {
        "topic_id": {
            "type": "keyword",
                "index": true
        },
        "ht": {
            "type": "vector",
            "dimension": 400,
            "store_type": "Mmap"
        }
    }
}
' http://172.31.96.173:28818/space/user_ht_test/_create
这是建表语句，数据是有重复，但是插入后还是有407万数据
