### ISSUE TITLE
两台机器怎么配置master、router、ps？

### ISSUE THREAD

**Issue by xqtbox** [vearch/vearch#90]
两台机器怎么配置master、router、ps？

**Comment by zzypeak** [comment]
参考vearch/tools/deployment/demo/config.toml

**Comment by xqtbox** [comment]
> 参考vearch/tools/deployment/demo/config.toml

你好 ，请问 ：
1. 我有两台机器，这两台机器能同时都作为master、router、ps。组成几个集群吗？（就是2个master、2个router、2个ps）
2. 如果这两台机器组成一个集群，一台宕机，另外一台还能工作吗？

**Comment by ansjsun** [comment]
建议 1master。2 router。2ps

如果是创建表是两个副本 那么是不能工作的。




在2020年01月22日 09:49，QingTang 写道：

参考vearch/tools/deployment/demo/config.toml

你好 ，请问 ：

我有两台机器，这两台机器能同时都作为master、router、ps。组成几个集群吗？（就是2个master、2个router、2个ps）
如果这两台机器组成一个集群，一台宕机，另外一台还能工作吗？
