### ISSUE TITLE
Error on vearch v0.3 when start 

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#91]
Dear team 

I build successfully vearch v0.3 , when start it show error:

> E0121 16:31:24.310343   44274 master.go:199] [ERROR] unmarshl space err: json: cannot unmarshal number into Go struct field Space.engine of type string

What's wrong with it ?

**Comment by ansjsun** [comment]
0.3。index attr。is bool type not  string type . please。make “true” to true




On 01/21/2020 17:54, phamthanhtri wrote:

Dear team

I build successfully vearch v0.3 , when start it show error:

E0121 16:31:24.310343 44274 master.go:199] [ERROR] unmarshl space err: json: cannot unmarshal number into Go struct field Space.engine of type string

What's wrong with it ?

**Comment by phamthanhtri** [comment]
Thank you so much @ansjsun 

I am testing the search feature on GPU. When I search, it  has issues and show error log: 

> ERROR 2020-01-22 10:36:39,485 gamma_index_ivfpq_gpu.cc:351 gpu index not indexed!                                                                                                      
> goroutine 365967 [running]:                                                                                                                                                            
> runtime/debug.Stack(0xc00028a0a8, 0x1, 0x20)                                                                                                                                           
>         /usr/lib/golang/src/runtime/debug/stack.go:24 +0x9d                                                                                                                            
> github.com/vearch/vearch/util/vearchlog.LogErrAndReturn(0x17adba0, 0xc000a528f0, 0xc000fb9338, 0x1)                                                                                    
>         /GO_PATH/src/github.com/vearch/vearch/util/vearchlog/log_util.go:60 +0xcc                                                                                
> github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).singleSearchResult(0xc000ed84c8, 0xc000fb95a0, 0x0, 0xc000b1fb60)                                                             
>         /GO_PATH/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:213 +0x5a5                                                                             
> github.com/vearch/vearch/ps/engine/gammacb.(*readerImpl).Search(0xc000ed84c8, 0x17db940, 0xc000fca160, 0xc0013421e0, 0x0)
>         /GO_PATH/src/github.com/vearch/vearch/ps/engine/gammacb/reader.go:200 +0x361
> github.com/vearch/vearch/ps/storage/raftstore.(*Store).Search(0xc0013e7770, 0x17db940, 0xc000fca160, 0x1801100, 0xc0013421e0, 0xc00027a460, 0x43194a, 0xc0013421e0)
>         /GO_PATH/src/github.com/vearch/vearch/ps/storage/raftstore/store_read.go:53 +0xb2
> github.com/vearch/vearch/ps.(*SearchHandler).Execute(0xc000fcc208, 0xc000748e00, 0xc000748ec0, 0x0, 0x0)
>         /GO_PATH/src/github.com/vearch/vearch/ps/handler_document.go:363 +0xb6
> github.com/vearch/vearch/util/server/rpc/handler.(*Chain).Execute(0xc000a554c0, 0x17db940, 0xc000fca160, 0xc000748e00, 0xc000748ec0, 0x0, 0x0)
>         /GO_PATH/src/github.com/vearch/vearch/util/server/rpc/handler/chain.go:47 +0x127
> reflect.Value.call(0xc00020d100, 0xc000168570, 0x13, 0x155ce7b, 0x4, 0xc000fb9ac0, 0x4, 0x4, 0x14333c0, 0x95020, ...)
>         /usr/lib/golang/src/reflect/value.go:460 +0x5f6
> reflect.Value.Call(0xc00020d100, 0xc000168570, 0x13, 0xc000fb9ac0, 0x4, 0x4, 0xc000748ec0, 0xc000fb9a98, 0x4ba2e1)
>         /usr/lib/golang/src/reflect/value.go:321 +0xb4
> github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*service).call(0xc000f2d590, 0x17db940, 0xc000fca160, 0xc00020d180, 0x13b8f40, 0xc000748e00, 0x16, 0x12926a0, 0xc000748ec0, 0x16, ...)
>         /GO_PATH/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/service.go:361 +0x24a
> github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).handleRequest(0xc000802460, 0x17db940, 0xc000fca160, 0xc0010893e0, 0x0, 0x0, 0xc000249e30)
>         /GO_PATH/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:529 +0x980
> github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc000802460, 0xc0010893e0, 0x17f2740, 0xc00025cbd0, 0xc000fca160)
>         /GO_PATH/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:414 +0x1ff
> created by github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server.(*Server).serveConn
>         /GO_PATH/src/github.com/vearch/vearch/vendor/github.com/smallnest/rpcx/server/server.go:396 +0x723
