### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by cleomart** [vearch/vearch#94]
I am currently using Vearch with at least 1 million vector features and when I look at the memory consumption on the datas1 directory, it’s consuming 15G of memory. I would like to know why is it using too much memory even if I only have 1 replica of my data.

Thank you in advance!

**Comment by qiutianme** [comment]
@cleomart  I need to confirm the following information. 
1. "datas1 directory"  Does it means disk directory? Please use the top command to show the memory usage of the ps process of vearch. 
2. Please provide the json statement that you created the space
3. What is the exact number of vectors you add
