### ISSUE TITLE
gamma tests errors

### ISSUE THREAD

**Issue by Dr1rD** [vearch/vearch#95]
在engine/gamma/tests下cmake后再make，显示如下错误：

> Scanning dependencies of target test_files
[ 50%] Building CXX object CMakeFiles/test_files.dir/test_files.o
/home/dr/vearch/engine/gamma/tests/test_files.cc:15:10: fatal error: gamma_api_generated.h: No such file or directory
 #include "gamma_api_generated.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/test_files.dir/build.make:62: recipe for target 'CMakeFiles/test_files.dir/test_files.o' failed
make[2]: *** [CMakeFiles/test_files.dir/test_files.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_files.dir/all' failed
make[1]: *** [CMakeFiles/test_files.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

我把用到gamma_api_generated.h的两处注释后，再make还是有些问题：

> Scanning dependencies of target test_files
[ 50%] Building CXX object CMakeFiles/test_files.dir/test_files.o
In file included from /home/dr/vearch/engine/gamma/tests/test_files.cc:16:0:
/home/dr/vearch/engine/gamma/tests/test.h:23:10: fatal error: log.h: No such file or directory
 #include "log.h"
          ^~~~~~~
compilation terminated.
CMakeFiles/test_files.dir/build.make:62: recipe for target 'CMakeFiles/test_files.dir/test_files.o' failed
make[2]: *** [CMakeFiles/test_files.dir/test_files.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_files.dir/all' failed
make[1]: *** [CMakeFiles/test_files.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

请问我这是哪里搞错了？

**Comment by wxingda** [comment]
gamma_api_generated是动态生成的，如果想执行test程序，需要先将engine/gamma/CMakeLists.txt 中`option(BUILD_TOOLS "Build tools" off)`  修改为`option(BUILD_TOOLS "Build tools" on)`，然后参考https://github.com/vearch/vearch/blob/master/engine/gamma/README.md进行编译

**Comment by Dr1rD** [comment]
谢谢。
按照你说的，修改BUILD_TOOLS后，然后执行[https://github.com/vearch/vearch/blob/master/engine/gamma/README.md](https://github.com/vearch/vearch/blob/master/engine/gamma/README.md)中的cmake时，出现下面错误：

> [ 98%] Linking CXX executable flatsampletext
[100%] Built target flatsampletext
running cd "/home/dr/vearch/engine/gamma/third_party" && cp -r -p flatbuffers-1.11.0/include/flatbuffers .  2>&1
running cd "/home/dr/vearch/engine/gamma/idl" && sh build.sh flatbuffers-1.11.0 /home/dr/vearch/engine/gamma/idl/fbs-gen  2>&1
CMake Error at CMakeLists.txt:157 (add_subdirectory):
  add_subdirectory given source "/home/dr/vearch/engine/gamma/tools" which is
  not an existing directory.

是不是改BUILD_TEST？

我把BUILD_TEST改成on后，执行cmake成功，但是make失败了：

> [ 86%] Building CXX object CMakeFiles/gamma.dir/c_api/gamma_api.cc.o
/home/dr/vearch/engine/gamma/c_api/gamma_api.cc: In function ‘ResponseCode SetLogDictionary(ByteArray*)’:
/home/dr/vearch/engine/gamma/c_api/gamma_api.cc:300:31: error: ‘GIT_SHA1’ was not declared in this scope
   LOG(INFO) << "Version [" << GIT_SHA1 << "]";
                               ^~~~~~~~
/home/dr/vearch/engine/gamma/c_api/gamma_api.cc: In lambda function:
/home/dr/vearch/engine/gamma/c_api/gamma_api.cc:297:15: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
         system(ss.str().c_str());
         ~~~~~~^~~~~~~~~~~~~~~~~~
CMakeFiles/gamma.dir/build.make:494: recipe for target 'CMakeFiles/gamma.dir/c_api/gamma_api.cc.o' failed
make[2]: *** [CMakeFiles/gamma.dir/c_api/gamma_api.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gamma.dir/all' failed
make[1]: *** [CMakeFiles/gamma.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wxingda** [comment]
抱歉，写错了，确实应该是把BUILD_TEST设置成on，BUILD_TOOLS再改回off，清空build目录，然后再执行cmake试试

**Comment by Dr1rD** [comment]
改了后可以cmake，但是make错了，具体可以看下上一个回复。

**Comment by wxingda** [comment]
你的环境没有安装git吗？

**Comment by Dr1rD** [comment]
安装了啊

> ☁  ~  git --version 
git version 2.17.1

**Comment by wxingda** [comment]
这个问题已经修复
https://github.com/vearch/vearch/commit/f756e05372dec936b6b5ed517f2923650834922a
更新一下试试

**Comment by Dr1rD** [comment]
更新后可以了。感谢。

然后我在vearch/engine/gamma/build/tests下，按照[https://github.com/vearch/vearch/blob/master/engine/gamma/tests/README.md](https://github.com/vearch/vearch/blob/master/engine/gamma/tests/README.md) ，运行test_files时又有错误了:
![image](https://user-images.githubusercontent.com/32828866/73905017-e7f5c180-48d8-11ea-8116-5731cadfe65d.png)

**Comment by wxingda** [comment]
可以将test_files.cc:45 retrieval_type = "GPU"; 改为 retrieval_type = "IVFPQ";

**Comment by Dr1rD** [comment]
可以编译调试. 谢谢.
