### ISSUE TITLE
Memory occupied on GPU search ?

### ISSUE THREAD

**Issue by phamthanhtri** [vearch/vearch#96]
Hi team 

I am testing vearch v3 search on GPU . I current search successfully but  I  have a question.  When index on GPU , vearch occupied ~1800MB per gpu device (total 3 gpu)  regardless of the total number of docs available.  (total 100 000 docs  or  500 000  the gpu is the same)

How does the total number of  docs affect memory occupied  on gpu?

**Comment by wxingda** [comment]
Because GPU index datas are quantized with PQ, so there is little difference between small datasets.
You can try larger datasets like 100 000 and 5 000 000.

**Comment by phamthanhtri** [comment]
Thanks @wxingda  
I have one more question. When create space , I must define **_partition_num_**   corresponds to the number of partition servers available. Example  I define _partition_num_ = 2  , but  when I needed to expand the system by adding partition server . How do I change the _partition_num_ in config space so that it gets a new server ?

**Comment by ansjsun** [comment]
I am sorry  the partition num can not change .
