### ISSUE TITLE
vearch search时可以更新index吗

### ISSUE THREAD

**Issue by wuwenjunwwj** [vearch/vearch#98]
vearch search时可以修改index吗？是线程安全的吗

**Comment by ansjsun** [comment]
可以 安全




在2020年02月10日 21:21，wuwenjunwwj 写道：

vearch search时可以修改index吗？是线程安全的吗

**Comment by renyuxiang** [comment]
我在评测faiss的时候，id和向量都一样的数据 往faiss里插入2次，会有2条记录，请问vector是怎么保证不会往faiss里插入多次？
