### ISSUE TITLE
Memory usage estimation when rocksdb is used

### ISSUE THREAD

**Issue by cocodee** [vearch/vearch#99]
How could I estimate memory usage when Rocksdb is used?For example, a cluster with only one ps server is set up.And if 100 million vector,each vector 512  long are inserted.What is the memory requirement for the ps server?

**Comment by qiutianme** [comment]
@cocodee The memory usage depends on the "cache_size" you set, which is also the size of rocksdb's [block cache](https://github.com/facebook/rocksdb/wiki/Block-Cache). The higher the "cache_size", the better the reading performance from rocksdb.
